"""
Ansible - Easy batch, 50 questions total.
Distribution: 20 coding, 8 mcq, 8 fill-in-blank, 7 drag-and-drop, 7 dropdown-order.
(Moderately coding-weighted — more than the even Terraform/AWS split, less than the
heavily coding-weighted Python/Bash split.)

Schema matches python_easy_questions.py / terraform_easy_questions.py — see those files'
headers for full field notes. For "coding" questions here, correct_answer is a reference
YAML task/playbook snippet or ansible-playbook/ansible CLI command, graded leniently by
LLM against the prompt.
"""

ANSIBLE_EASY_QUESTIONS = [

    # ---------------- CODING (20) ----------------

    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the copy module to copy a local file 'app.conf' to '/etc/app.conf' on the remote host.",
        "correct_answer": "- name: Copy app config\n  copy:\n    src: app.conf\n    dest: /etc/app.conf",
        "explanation_correct": "Correct — the copy module's src and dest arguments correctly specify the local file and its destination path on the remote host.",
        "explanation_incorrect": "A correct solution must use the copy module with the correct src (local file) and dest (remote path) arguments.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the service module to ensure the nginx service is started and enabled at boot.",
        "correct_answer": "- name: Ensure nginx is running and enabled\n  service:\n    name: nginx\n    state: started\n    enabled: true",
        "explanation_correct": "Correct — state: started ensures the service is currently running, and enabled: true ensures it starts automatically on boot.",
        "explanation_incorrect": "A correct solution must both ensure the service is currently running (state: started) and set to start on boot (enabled: true).",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the package module to ensure the git package is installed.",
        "correct_answer": "- name: Install git\n  package:\n    name: git\n    state: present",
        "explanation_correct": "Correct — the package module with state: present installs the given package if it's not already installed.",
        "explanation_incorrect": "A correct solution must use the package module with name: git and state: present.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the file module to ensure a directory at /opt/myapp exists.",
        "correct_answer": "- name: Ensure /opt/myapp exists\n  file:\n    path: /opt/myapp\n    state: directory",
        "explanation_correct": "Correct — the file module with state: directory creates the directory if it doesn't already exist.",
        "explanation_incorrect": "A correct solution must use the file module with path set to /opt/myapp and state set to directory (not file).",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the user module to create a user named 'deploy'.",
        "correct_answer": "- name: Create deploy user\n  user:\n    name: deploy\n    state: present",
        "explanation_correct": "Correct — the user module with name: deploy and state: present creates the user if it doesn't already exist.",
        "explanation_incorrect": "A correct solution must use the user module with name set to deploy and state set to present.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the command module to run the command 'echo hello'.",
        "correct_answer": "- name: Run echo command\n  command: echo hello",
        "explanation_correct": "Correct — the command module runs the given command directly on the remote host.",
        "explanation_incorrect": "A correct solution must use the command module to run exactly 'echo hello'.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write a minimal Ansible playbook that targets the 'webservers' host group and includes a single task using the debug module to print 'Hello, Ansible!'.",
        "correct_answer": "- hosts: webservers\n  tasks:\n    - name: Print greeting\n      debug:\n        msg: \"Hello, Ansible!\"",
        "explanation_correct": "Correct — the play targets the webservers group, and the single task uses the debug module with a msg argument to print the given text.",
        "explanation_incorrect": "A correct solution must target the webservers group and include exactly one task that prints the given message using the debug module.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the template module to deploy a Jinja2 template 'nginx.conf.j2' to '/etc/nginx/nginx.conf'.",
        "correct_answer": "- name: Deploy nginx config\n  template:\n    src: nginx.conf.j2\n    dest: /etc/nginx/nginx.conf",
        "explanation_correct": "Correct — the template module renders the Jinja2 template and places the result at the specified destination path.",
        "explanation_incorrect": "A correct solution must use the template module (not copy, since it needs Jinja2 rendering) with the correct src and dest.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write the ansible-playbook command to run a playbook named site.yml.",
        "correct_answer": "ansible-playbook site.yml",
        "explanation_correct": "Correct — `ansible-playbook` followed by the playbook filename runs that playbook.",
        "explanation_incorrect": "A correct solution must run site.yml specifically using the ansible-playbook command.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task with a `when` conditional that only runs a debug message 'Production!' if the variable env equals 'production'.",
        "correct_answer": "- name: Show production message\n  debug:\n    msg: \"Production!\"\n  when: env == \"production\"",
        "explanation_correct": "Correct — the when clause correctly gates the task so it only runs when the env variable equals 'production'.",
        "explanation_incorrect": "A correct solution must include a when condition that compares the env variable to the string 'production', and only run the task if that's true.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using a loop to install the packages git, curl, and vim.",
        "correct_answer": "- name: Install packages\n  package:\n    name: \"{{ item }}\"\n    state: present\n  loop:\n    - git\n    - curl\n    - vim",
        "explanation_correct": "Correct — the loop iterates over all three package names, installing each one via the package module using {{ item }}.",
        "explanation_incorrect": "A correct solution must install all three packages using a loop construct (loop or with_items), not three separate hardcoded tasks.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible handler named 'restart nginx' that restarts the nginx service.",
        "correct_answer": "- name: restart nginx\n  service:\n    name: nginx\n    state: restarted",
        "explanation_correct": "Correct — this defines a handler (using the same structure as a task) that restarts the nginx service when notified.",
        "explanation_incorrect": "A correct solution must define a handler named 'restart nginx' that sets the nginx service's state to restarted.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task that copies a config file 'app.conf' to '/etc/app.conf' and notifies a handler named 'restart nginx' when the file changes.",
        "correct_answer": "- name: Copy app config\n  copy:\n    src: app.conf\n    dest: /etc/app.conf\n  notify: restart nginx",
        "explanation_correct": "Correct — the notify directive triggers the named handler whenever this task reports a change (e.g. the file content actually changed).",
        "explanation_incorrect": "A correct solution must include a notify directive referencing the 'restart nginx' handler by its exact name.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write a simple Ansible inventory file (INI format) defining a group 'webservers' containing two hosts: web1.example.com and web2.example.com.",
        "correct_answer": "[webservers]\nweb1.example.com\nweb2.example.com",
        "explanation_correct": "Correct — the [webservers] header defines the group, and each following line lists a host belonging to that group.",
        "explanation_incorrect": "A correct solution must define a group header named webservers followed by both hostnames, one per line.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task that uses become: true to install the nginx package with elevated privileges.",
        "correct_answer": "- name: Install nginx with elevated privileges\n  become: true\n  package:\n    name: nginx\n    state: present",
        "explanation_correct": "Correct — become: true escalates privileges for this task, and the package module installs nginx as usual.",
        "explanation_incorrect": "A correct solution must include become: true on the task in addition to correctly installing nginx via the package module.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task that sets a variable named app_port to 8080 using the set_fact module.",
        "correct_answer": "- name: Set app port\n  set_fact:\n    app_port: 8080",
        "explanation_correct": "Correct — set_fact defines app_port as a fact/variable with the value 8080, usable in later tasks.",
        "explanation_incorrect": "A correct solution must use the set_fact module to define app_port with the value 8080.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write the ansible-playbook command to run a playbook named site.yml, executing only tasks tagged 'deploy'.",
        "correct_answer": "ansible-playbook site.yml --tags deploy",
        "explanation_correct": "Correct — the --tags flag restricts execution to only the tasks (and their dependencies) tagged with 'deploy'.",
        "explanation_incorrect": "A correct solution must run site.yml with the --tags flag set to 'deploy' specifically.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write an Ansible task using the lineinfile module to ensure the line 'PermitRootLogin no' exists in '/etc/ssh/sshd_config'.",
        "correct_answer": "- name: Disable root login\n  lineinfile:\n    path: /etc/ssh/sshd_config\n    line: \"PermitRootLogin no\"",
        "explanation_correct": "Correct — the lineinfile module ensures the specified line is present in the file, without rewriting the entire file.",
        "explanation_incorrect": "A correct solution must use the lineinfile module (not copy or template) targeting the correct file path and line content.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write the ansible ad-hoc command to ping all hosts in the inventory to check connectivity.",
        "correct_answer": "ansible all -m ping",
        "explanation_correct": "Correct — `ansible all -m ping` runs the ping module against every host in the inventory, verifying connectivity.",
        "explanation_incorrect": "A correct solution must target all hosts and use the ping module specifically, via the ansible ad-hoc command (not ansible-playbook).",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "coding",
        "prompt": "Write a play header (the top-level 'hosts' entry, no tasks needed) that targets all hosts and disables fact gathering.",
        "correct_answer": "- hosts: all\n  gather_facts: false",
        "explanation_correct": "Correct — hosts: all targets every host, and gather_facts: false skips the fact-gathering step for this play.",
        "explanation_incorrect": "A correct solution must set hosts to all and explicitly set gather_facts to false.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "What format are Ansible playbooks written in?",
        "options": ["YAML", "JSON", "XML", "INI"],
        "correct_answer": "YAML",
        "explanation_correct": "Ansible playbooks are written in YAML, a human-readable data serialization format.",
        "explanation_incorrect": {
            "JSON": "Wrong — while Ansible can parse some JSON-compatible YAML, playbooks are conventionally written in YAML syntax.",
            "XML": "Wrong — Ansible playbooks don't use XML at all.",
            "INI": "Wrong — INI format is used for Ansible inventory files, not playbooks.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of an Ansible inventory file?",
        "options": [
            "Defines the hosts and groups of hosts that Ansible manages",
            "Defines the tasks Ansible should run",
            "Stores encrypted secrets used by playbooks",
            "Configures the SSH client's connection settings only",
        ],
        "correct_answer": "Defines the hosts and groups of hosts that Ansible manages",
        "explanation_correct": "The inventory lists the target hosts (and how they're grouped) that playbooks and ad-hoc commands run against.",
        "explanation_incorrect": {
            "Defines the tasks Ansible should run": "Wrong — tasks are defined in playbooks, not the inventory file.",
            "Stores encrypted secrets used by playbooks": "Wrong — that's the role of Ansible Vault, not the inventory.",
            "Configures the SSH client's connection settings only": "Wrong — while inventory can include some connection variables, its primary purpose is defining hosts/groups, not just SSH client config.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "What does the `become: true` directive do in an Ansible task?",
        "options": [
            "Escalates privileges (e.g. runs the task as root) for that task",
            "Converts the task into a handler",
            "Turns the task into a loop",
            "Enables verbose debug output for that task",
        ],
        "correct_answer": "Escalates privileges (e.g. runs the task as root) for that task",
        "explanation_correct": "become: true tells Ansible to run the task with elevated privileges, using the configured privilege escalation method (commonly sudo).",
        "explanation_incorrect": {
            "Converts the task into a handler": "Wrong — become is unrelated to handlers; it only affects privilege level.",
            "Turns the task into a loop": "Wrong — looping is controlled by the loop or with_items keyword, not become.",
            "Enables verbose debug output for that task": "Wrong — verbosity is controlled by CLI flags (like -v), not the become directive.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a handler in Ansible?",
        "options": [
            "A task that only runs when notified by another task, typically used for actions like restarting a service",
            "A task that always runs first in every playbook",
            "A special type of variable used for secrets",
            "A module specifically designed for error handling",
        ],
        "correct_answer": "A task that only runs when notified by another task, typically used for actions like restarting a service",
        "explanation_correct": "Handlers only execute when explicitly notified by a task (typically one that reports a change), commonly used to restart a service after its config file changes.",
        "explanation_incorrect": {
            "A task that always runs first in every playbook": "Wrong — handlers run at the end of a play (by default) and only if notified, not first.",
            "A special type of variable used for secrets": "Wrong — that describes a Vault-encrypted variable, unrelated to handlers.",
            "A module specifically designed for error handling": "Wrong — handlers aren't a module or an error-handling mechanism; they're a notification-triggered task type.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "Which module would you use to ensure a specific line exists in a file, without Ansible overwriting the entire file's contents?",
        "options": ["lineinfile", "copy", "template", "file"],
        "correct_answer": "lineinfile",
        "explanation_correct": "The lineinfile module adds, removes, or modifies a single line within an existing file, leaving the rest of its content untouched.",
        "explanation_incorrect": {
            "copy": "Wrong — copy replaces the entire destination file's contents with the source file, not just a single line.",
            "template": "Wrong — template renders and replaces the entire destination file's contents from a Jinja2 template, not just one line.",
            "file": "Wrong — the file module manages file/directory attributes (permissions, existence, type), not line-level content.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of the `when` keyword in an Ansible task?",
        "options": [
            "Conditionally runs the task only if the specified expression evaluates to true",
            "Schedules the task to run at a specific time of day",
            "Loops the task over a list of items",
            "Delays task execution by a fixed number of seconds",
        ],
        "correct_answer": "Conditionally runs the task only if the specified expression evaluates to true",
        "explanation_correct": "The when clause is evaluated before the task runs, and the task is skipped entirely if the condition evaluates to false.",
        "explanation_incorrect": {
            "Schedules the task to run at a specific time of day": "Wrong — Ansible doesn't have built-in time-of-day scheduling via when; that condition is purely a logical check.",
            "Loops the task over a list of items": "Wrong — that's the role of the loop or with_items keyword, not when.",
            "Delays task execution by a fixed number of seconds": "Wrong — that would be handled by a pause or wait mechanism, not when.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "What command is used to run an Ansible playbook?",
        "options": ["ansible-playbook", "ansible-run", "ansible-exec", "playbook-run"],
        "correct_answer": "ansible-playbook",
        "explanation_correct": "`ansible-playbook` is the dedicated command-line tool for executing playbook YAML files.",
        "explanation_incorrect": {
            "ansible-run": "Wrong — this is not a real Ansible command.",
            "ansible-exec": "Wrong — this is not a real Ansible command.",
            "playbook-run": "Wrong — this is not a real Ansible command.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of Ansible Vault?",
        "options": [
            "Encrypts sensitive data, like passwords, within playbooks or variable files",
            "Manages SSH key generation and distribution",
            "Stores logs of past playbook executions",
            "Compresses playbook files to save disk space",
        ],
        "correct_answer": "Encrypts sensitive data, like passwords, within playbooks or variable files",
        "explanation_correct": "Ansible Vault encrypts sensitive values (or entire files) so they can be safely stored in version control alongside the rest of the playbook code.",
        "explanation_incorrect": {
            "Manages SSH key generation and distribution": "Wrong — SSH key management isn't Vault's role; Vault is specifically about encrypting data at rest within Ansible content.",
            "Stores logs of past playbook executions": "Wrong — execution logging is a separate concern (e.g. via callback plugins), unrelated to Vault.",
            "Compresses playbook files to save disk space": "Wrong — Vault encrypts content; it doesn't provide compression as its purpose.",
        },
    },

    # ---------------- FILL-IN-BLANK (8) ----------------

    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Ansible playbooks are written in the ____ format.",
        "options": None,
        "correct_answer": "YAML",
        "explanation_correct": "YAML is the human-readable format used to define Ansible playbooks.",
        "explanation_incorrect": "The blank should be filled with the name of the format Ansible playbooks use: YAML.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ directive, when set to true on a task or play, escalates privileges to run as another user (commonly root).",
        "options": None,
        "correct_answer": "become",
        "explanation_correct": "become: true triggers Ansible's privilege escalation mechanism for the task or play.",
        "explanation_incorrect": "The blank should be filled with the directive used for privilege escalation: become.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A ____ is a task that only executes when notified by another task, commonly used to restart services after a config change.",
        "options": None,
        "correct_answer": "handler",
        "explanation_correct": "Handlers are notification-triggered tasks, commonly used for actions like service restarts.",
        "explanation_incorrect": "The blank should be filled with the term for this notification-triggered task type: handler.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ module ensures a specific line exists in a file, without overwriting the entire file's contents.",
        "options": None,
        "correct_answer": "lineinfile",
        "explanation_correct": "lineinfile adds, modifies, or removes a single line within an existing file.",
        "explanation_incorrect": "The blank should be filled with the name of this line-level file editing module: lineinfile.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ keyword adds a conditional to a task, so it only runs when the given expression evaluates to true.",
        "options": None,
        "correct_answer": "when",
        "explanation_correct": "The when clause gates task execution based on a conditional expression.",
        "explanation_incorrect": "The blank should be filled with the conditional keyword used on tasks: when.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The command used to execute an Ansible playbook is ansible-____.",
        "options": None,
        "correct_answer": "playbook",
        "explanation_correct": "ansible-playbook is the CLI tool used to run playbook files.",
        "explanation_incorrect": "The blank should be filled with the second half of the playbook-running command's name: playbook.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Ansible ____ encrypts sensitive data such as passwords, so it can be safely stored in version control.",
        "options": None,
        "correct_answer": "Vault",
        "explanation_correct": "Ansible Vault provides encryption for sensitive data within playbooks and variable files.",
        "explanation_incorrect": "The blank should be filled with the name of Ansible's encryption feature: Vault.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "An Ansible ____ file defines the hosts and groups of hosts that Ansible manages.",
        "options": None,
        "correct_answer": "inventory",
        "explanation_correct": "The inventory file lists managed hosts and how they're organized into groups.",
        "explanation_incorrect": "The blank should be filled with the term for this hosts-defining file: inventory.",
    },

    # ---------------- DRAG-AND-DROP (7) ----------------

    {
        "topic": "Ansible", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured minimal playbook that prints a message to the webservers group.",
        "options": ["    - name: Print message\n      debug:\n        msg: \"Hello, Ansible!\"", "- hosts: webservers", "  tasks:"],
        "correct_answer": '["- hosts: webservers", "  tasks:", "    - name: Print message\\n      debug:\\n        msg: \\"Hello, Ansible!\\""]',
        "explanation_correct": "Correct — the play must declare its target hosts first, followed by the tasks: key, followed by the actual task list nested under it.",
        "explanation_incorrect": "The hosts line must come first to define the play's target, followed by the tasks: key, with the individual task nested underneath it.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task that installs a package with elevated privileges.",
        "options": ["  package:\n    name: nginx\n    state: present", "- name: Install nginx", "  become: true"],
        "correct_answer": '["- name: Install nginx", "  become: true", "  package:\\n    name: nginx\\n    state: present"]',
        "explanation_correct": "Correct — the task's name comes first, followed by its directives (become) and the module invocation, all as sibling keys under the task.",
        "explanation_incorrect": "The task's name is conventionally listed first, with become and the module call as sibling keys beneath it — the module call shouldn't appear before the task's own name.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured inventory file defining a webservers group.",
        "options": ["web2.example.com", "[webservers]", "web1.example.com"],
        "correct_answer": '["[webservers]", "web1.example.com", "web2.example.com"]',
        "explanation_correct": "Correct — the group header must come before the hosts that belong to it, in INI-style inventory syntax.",
        "explanation_incorrect": "The group header ([webservers]) must appear before any hosts, since INI inventory syntax lists hosts under their group header.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task that loops over a list of packages to install.",
        "options": ["  loop:\n    - git\n    - curl\n    - vim", "- name: Install packages", "  package:\n    name: \"{{ item }}\"\n    state: present"],
        "correct_answer": '["- name: Install packages", "  package:\\n    name: \\"{{ item }}\\"\\n    state: present", "  loop:\\n    - git\\n    - curl\\n    - vim"]',
        "explanation_correct": "Correct — the task's name comes first, followed by the module call (referencing {{ item }}), followed by the loop list that supplies each item.",
        "explanation_incorrect": "The task name should come first, with the module call and its loop as sibling keys beneath it — conventionally the module block is listed before the loop that feeds it.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured conditional task that only runs when env equals 'production'.",
        "options": ["- name: Deploy production config", "  when: env == \"production\"", "  copy:\n    src: prod.conf\n    dest: /etc/app.conf"],
        "correct_answer": '["- name: Deploy production config", "  when: env == \\"production\\"", "  copy:\\n    src: prod.conf\\n    dest: /etc/app.conf"]',
        "explanation_correct": "Correct — the task's name comes first, with the when condition and the module call as sibling keys beneath it.",
        "explanation_incorrect": "The task name is listed first, with when and the module call as sibling keys beneath it, not before the task's own name.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for the overall workflow of running an Ansible playbook.",
        "options": ["Run ansible-playbook against the playbook and inventory", "Write the playbook YAML file", "Define the target hosts in an inventory file"],
        "correct_answer": '["Write the playbook YAML file", "Define the target hosts in an inventory file", "Run ansible-playbook against the playbook and inventory"]',
        "explanation_correct": "Correct — the playbook and inventory should both exist as inputs before ansible-playbook is run against them, though the order between writing the playbook and inventory is flexible; running the command always comes last.",
        "explanation_incorrect": "Both the playbook and the inventory need to exist before ansible-playbook can be run, since the command depends on both as inputs.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task that copies a config file and notifies a handler.",
        "options": ["  notify: restart nginx", "- name: Copy app config", "  copy:\n    src: app.conf\n    dest: /etc/app.conf"],
        "correct_answer": '["- name: Copy app config", "  copy:\\n    src: app.conf\\n    dest: /etc/app.conf", "  notify: restart nginx"]',
        "explanation_correct": "Correct — the task's name comes first, followed by the module call, followed by the notify directive that triggers the handler.",
        "explanation_incorrect": "The task name should come first, with the module call and notify directive as sibling keys beneath it, conventionally with notify following the module call.",
    },

    # ---------------- DROPDOWN-ORDER (7) ----------------

    {
        "topic": "Ansible", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these sections into a correctly structured play with a task that notifies a handler, and the handler itself.",
        "options": ["handlers:\n  - name: restart nginx\n    service:\n      name: nginx\n      state: restarted", "- hosts: webservers", "  tasks:\n    - name: Copy config\n      copy:\n        src: app.conf\n        dest: /etc/app.conf\n      notify: restart nginx"],
        "correct_answer": '["- hosts: webservers", "  tasks:\\n    - name: Copy config\\n      copy:\\n        src: app.conf\\n        dest: /etc/app.conf\\n      notify: restart nginx", "handlers:\\n  - name: restart nginx\\n    service:\\n      name: nginx\\n      state: restarted"]',
        "explanation_correct": "Correct — the hosts line must come first, and by convention the tasks: section is listed before the handlers: section within the same play.",
        "explanation_incorrect": "The play must declare its hosts first, and the tasks: section is conventionally listed before the handlers: section, even though the handler could technically be defined anywhere in the play.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using an ad-hoc ping command to verify connectivity.",
        "options": ["Verify each host returns a 'pong' response", "Ensure the inventory file lists the target hosts", "Run `ansible all -m ping`"],
        "correct_answer": '["Ensure the inventory file lists the target hosts", "Run `ansible all -m ping`", "Verify each host returns a \'pong\' response"]',
        "explanation_correct": "Correct — the inventory must list target hosts before the command has anything to run against, and verifying responses only makes sense after the command has actually run.",
        "explanation_incorrect": "The inventory must define target hosts before the ping command can target them, and checking for 'pong' responses only makes sense after the command has been run.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured lineinfile task.",
        "options": ["    path: /etc/ssh/sshd_config\n    line: \"PermitRootLogin no\"", "- name: Disable root login", "  lineinfile:"],
        "correct_answer": '["- name: Disable root login", "  lineinfile:", "    path: /etc/ssh/sshd_config\\n    line: \\"PermitRootLogin no\\""]',
        "explanation_correct": "Correct — the task name comes first, followed by the module name, followed by that module's arguments nested underneath it.",
        "explanation_incorrect": "The task name must come first, with the module name declared before its arguments, since the arguments are nested under the module key.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a basic role-based playbook workflow.",
        "options": ["Run the playbook, and Ansible executes the role's tasks", "Create a roles directory structure (e.g. roles/webserver/tasks/main.yml)", "Reference the role in a playbook using the roles: keyword"],
        "correct_answer": '["Create a roles directory structure (e.g. roles/webserver/tasks/main.yml)", "Reference the role in a playbook using the roles: keyword", "Run the playbook, and Ansible executes the role\'s tasks"]',
        "explanation_correct": "Correct — the role's files must exist before a playbook can reference it, and execution only happens once the playbook (with that reference) is actually run.",
        "explanation_incorrect": "The role directory structure must exist before it can be referenced by a playbook, and the role's tasks only execute once the playbook referencing it is run.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured play that disables fact gathering and includes one task.",
        "options": ["    - name: Simple task\n      debug:\n        msg: \"no facts needed\"", "- hosts: all\n  gather_facts: false", "  tasks:"],
        "correct_answer": '["- hosts: all\\n  gather_facts: false", "  tasks:", "    - name: Simple task\\n      debug:\\n        msg: \\"no facts needed\\""]',
        "explanation_correct": "Correct — the play header (hosts and gather_facts) must come first, followed by the tasks: key, followed by the actual task nested underneath.",
        "explanation_incorrect": "The play's top-level settings (hosts, gather_facts) must come before the tasks: key, and the individual task must be nested under tasks:, not listed before it.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured pair of tasks: one that sets a fact, and one that prints it.",
        "options": ["- name: Print port\n  debug:\n    msg: \"{{ app_port }}\"", "- name: Set app port", "  set_fact:\n    app_port: 8080"],
        "correct_answer": '["- name: Set app port", "  set_fact:\\n    app_port: 8080", "- name: Print port\\n  debug:\\n    msg: \\"{{ app_port }}\\""]',
        "explanation_correct": "Correct — the app_port fact must be set by the first task before a later task can reference it in a debug message.",
        "explanation_incorrect": "The variable must be set (via set_fact) in an earlier task before a subsequent task can reference its value.",
    },
    {
        "topic": "Ansible", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using tags to selectively run parts of a playbook.",
        "options": ["Only tasks matching that tag are executed", "Add tags: to relevant tasks in the playbook (e.g. tags: deploy)", "Run ansible-playbook with --tags deploy"],
        "correct_answer": '["Add tags: to relevant tasks in the playbook (e.g. tags: deploy)", "Run ansible-playbook with --tags deploy", "Only tasks matching that tag are executed"]',
        "explanation_correct": "Correct — tasks must be tagged before the --tags flag has anything meaningful to filter by, and the filtering effect only takes place once the command is actually run.",
        "explanation_incorrect": "Tasks must be tagged in the playbook before --tags has anything to select, and the filtered execution only happens once the command runs with that flag.",
    },
]
