"""
Ansible - Medium batch, 50 questions total.
Distribution: 20 coding, 8 mcq, 8 fill-in-blank, 7 drag-and-drop, 7 dropdown-order.

Schema matches ansible_easy_questions.py — see that file's header for full field notes.
Medium content covers register/block-rescue, delegate_to, run_once, retries/until,
ansible-vault, include_tasks/import_playbook, Jinja2 filters, tags, handlers with listen,
serial rolling updates, vars_files, changed_when, with_dict, role dependencies, and
ansible-galaxy.
"""

ANSIBLE_MEDIUM_QUESTIONS = [

    # ---------------- CODING (20) ----------------

    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write two Ansible tasks: the first registers the output of the command 'whoami' into a variable named result, and the second uses debug to print that variable.",
        "correct_answer": "- name: Run whoami\n  command: whoami\n  register: result\n\n- name: Show result\n  debug:\n    var: result",
        "explanation_correct": "Correct — the first task captures the command's output into the result variable, and the second task prints it using debug's var argument.",
        "explanation_incorrect": "A correct solution must register the command output into result in the first task, then reference that same variable in the second task's debug output.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible block that attempts to install a package named mypackage, and uses rescue to print an error message if the installation fails.",
        "correct_answer": "- block:\n    - name: Install package\n      package:\n        name: mypackage\n        state: present\n  rescue:\n    - name: Handle failure\n      debug:\n        msg: \"Installation failed\"",
        "explanation_correct": "Correct — the block groups the install task, and rescue provides a fallback task that runs only if something in the block fails.",
        "explanation_incorrect": "A correct solution must use a block/rescue structure, where the rescue section only runs if a task within the block fails.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that uses delegate_to: localhost to run a debug task on the control node instead of the remote host.",
        "correct_answer": "- name: Run on control node\n  debug:\n    msg: \"Running locally\"\n  delegate_to: localhost",
        "explanation_correct": "Correct — delegate_to: localhost redirects this task's execution to the Ansible control node rather than the remote target host.",
        "explanation_incorrect": "A correct solution must include delegate_to: localhost on the task specifically.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that uses run_once: true to ensure a debug task only executes once across all targeted hosts.",
        "correct_answer": "- name: Run once across all hosts\n  debug:\n    msg: \"Running only once\"\n  run_once: true",
        "explanation_correct": "Correct — run_once: true ensures the task executes on only the first host in the batch, rather than once per host.",
        "explanation_incorrect": "A correct solution must include run_once: true on the task, ensuring it executes just once regardless of how many hosts are targeted.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that runs the command check_status.sh, registers its result, and retries up to 5 times (waiting 10 seconds between attempts) until the return code is 0.",
        "correct_answer": "- name: Retry until success\n  command: check_status.sh\n  register: result\n  until: result.rc == 0\n  retries: 5\n  delay: 10",
        "explanation_correct": "Correct — until checks the condition against the registered result, retries caps the number of attempts at 5, and delay waits 10 seconds between each attempt.",
        "explanation_incorrect": "A correct solution must register the command's result, use until to check for a successful return code, and set retries to 5 and delay to 10.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write the ansible-vault command to encrypt a file named secrets.yml.",
        "correct_answer": "ansible-vault encrypt secrets.yml",
        "explanation_correct": "Correct — `ansible-vault encrypt` encrypts the given file in place, prompting for a vault password.",
        "explanation_incorrect": "A correct solution must encrypt secrets.yml specifically, using the ansible-vault encrypt subcommand.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that uses include_tasks to include a file named setup.yml.",
        "correct_answer": "- name: Include setup tasks\n  include_tasks: setup.yml",
        "explanation_correct": "Correct — include_tasks dynamically includes the tasks defined in the given file at this point in the play.",
        "explanation_incorrect": "A correct solution must use include_tasks specifically (not import_tasks or import_playbook) referencing setup.yml.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write a playbook entry that uses import_playbook to import another playbook named common.yml.",
        "correct_answer": "- import_playbook: common.yml",
        "explanation_correct": "Correct — import_playbook statically includes the entire contents of another playbook file at this point.",
        "explanation_incorrect": "A correct solution must use import_playbook specifically (not include_tasks) referencing common.yml.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task using debug that prints the value of variable username, falling back to 'guest' if username is undefined, using the Jinja2 default filter.",
        "correct_answer": "- name: Show username\n  debug:\n    msg: \"{{ username | default('guest') }}\"",
        "explanation_correct": "Correct — the default filter provides the fallback value 'guest' only when username is undefined, without raising an error.",
        "explanation_incorrect": "A correct solution must use the Jinja2 default filter on username, falling back to 'guest' specifically when it's undefined.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that installs the apache2 package, but only when ansible_facts['distribution'] equals 'Ubuntu'.",
        "correct_answer": "- name: Install apache2 on Ubuntu\n  package:\n    name: apache2\n    state: present\n  when: ansible_facts['distribution'] == \"Ubuntu\"",
        "explanation_correct": "Correct — the when condition checks the gathered distribution fact and only runs the install task when it equals 'Ubuntu'.",
        "explanation_incorrect": "A correct solution must gate the install task with a when condition checking ansible_facts['distribution'] against 'Ubuntu' specifically.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task with two tags, 'setup' and 'deploy', that prints a debug message 'Running'.",
        "correct_answer": "- name: Setup and deploy step\n  debug:\n    msg: \"Running\"\n  tags:\n    - setup\n    - deploy",
        "explanation_correct": "Correct — the tags list includes both 'setup' and 'deploy', letting this task be selected by either tag.",
        "explanation_incorrect": "A correct solution must include both tags (setup and deploy) as a list on the task.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible handler that listens for the notification 'restart web services' instead of using a fixed handler name, and restarts the apache2 service.",
        "correct_answer": "- name: Restart apache2\n  service:\n    name: apache2\n    state: restarted\n  listen: \"restart web services\"",
        "explanation_correct": "Correct — the listen directive lets this handler be triggered by any task that notifies 'restart web services', regardless of the handler's own name.",
        "explanation_incorrect": "A correct solution must include a listen directive with the exact topic 'restart web services', in addition to restarting the apache2 service.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write a play-level setting that performs a rolling update by processing hosts in batches of 2 at a time, targeting the webservers group.",
        "correct_answer": "- hosts: webservers\n  serial: 2",
        "explanation_correct": "Correct — serial: 2 processes the targeted hosts in batches of 2, completing all tasks for one batch before moving to the next.",
        "explanation_incorrect": "A correct solution must set serial to 2 at the play level, targeting the webservers group.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write a play-level vars_files entry that loads variables from a file located at vars/main.yml.",
        "correct_answer": "- hosts: webservers\n  vars_files:\n    - vars/main.yml",
        "explanation_correct": "Correct — vars_files loads the variables defined in the given file(s), making them available to the play.",
        "explanation_incorrect": "A correct solution must use vars_files (not vars or include_vars) referencing the exact path vars/main.yml.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task using the command module to run 'risky_script.sh', where the playbook should continue even if this task fails.",
        "correct_answer": "- name: Run risky script\n  command: risky_script.sh\n  ignore_errors: true",
        "explanation_correct": "Correct — ignore_errors: true prevents a failure in this task from halting the rest of the playbook.",
        "explanation_incorrect": "A correct solution must include ignore_errors: true on the task, so playbook execution continues even if the task fails.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that runs the command 'check_status.sh' but is never reported as 'changed', using changed_when.",
        "correct_answer": "- name: Check status\n  command: check_status.sh\n  changed_when: false",
        "explanation_correct": "Correct — changed_when: false overrides the command module's default changed-reporting behavior, always marking the task as unchanged.",
        "explanation_incorrect": "A correct solution must set changed_when to false on the task, specifically preventing it from being reported as changed.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that loops over a dictionary variable named mydict, printing each key and value, using dict2items.",
        "correct_answer": "- name: Print dict items\n  debug:\n    msg: \"{{ item.key }}: {{ item.value }}\"\n  loop: \"{{ mydict | dict2items }}\"",
        "explanation_correct": "Correct — the dict2items filter converts the dictionary into a list of key/value pairs that loop can iterate over, and item.key/item.value access each pair's parts.",
        "explanation_incorrect": "A correct solution must iterate over the dictionary's key-value pairs (via dict2items or with_dict) and print both the key and value for each entry.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write an Ansible task that uses debug to print a variable named myvar converted to a JSON string, using the to_json filter.",
        "correct_answer": "- name: Show JSON\n  debug:\n    msg: \"{{ myvar | to_json }}\"",
        "explanation_correct": "Correct — the to_json filter serializes myvar into its JSON string representation before it's printed.",
        "explanation_incorrect": "A correct solution must apply the to_json filter to myvar within the debug message.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write the contents of a roles/webserver/meta/main.yml file declaring a dependency on a role named 'common'.",
        "correct_answer": "---\ndependencies:\n  - role: common",
        "explanation_correct": "Correct — the dependencies list in meta/main.yml declares that the 'common' role must run before this role's own tasks.",
        "explanation_incorrect": "A correct solution must include a dependencies list containing an entry for the 'common' role.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "coding",
        "prompt": "Write the ansible-galaxy command to install the role 'geerlingguy.nginx' from Ansible Galaxy.",
        "correct_answer": "ansible-galaxy install geerlingguy.nginx",
        "explanation_correct": "Correct — `ansible-galaxy install` downloads and installs the specified role from the Galaxy registry.",
        "explanation_incorrect": "A correct solution must install the exact role name given, using the ansible-galaxy install subcommand.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `register` keyword do in an Ansible task?",
        "options": [
            "Stores the task's output/result into a variable for later use",
            "Registers the task with an external monitoring system",
            "Creates a new host entry in the inventory",
            "Encrypts the task's output automatically",
        ],
        "correct_answer": "Stores the task's output/result into a variable for later use",
        "explanation_correct": "register captures a task's result object (return code, stdout, changed status, etc.) into a named variable that later tasks can reference.",
        "explanation_incorrect": {
            "Registers the task with an external monitoring system": "Wrong — register is purely an internal Ansible variable-capture mechanism, unrelated to external monitoring.",
            "Creates a new host entry in the inventory": "Wrong — inventory management is separate from register, which only deals with task output.",
            "Encrypts the task's output automatically": "Wrong — encryption is Vault's role; register doesn't apply any encryption.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a `block` combined with `rescue` in Ansible?",
        "options": [
            "Groups tasks together and allows handling failures within the group, similar to a try/except construct",
            "Defines an entirely new play within the playbook",
            "Creates a loop over a group of hosts",
            "Registers multiple variables from a single task",
        ],
        "correct_answer": "Groups tasks together and allows handling failures within the group, similar to a try/except construct",
        "explanation_correct": "A block groups related tasks, and if any task in the block fails, execution jumps to the rescue section, closely mirroring try/except error handling.",
        "explanation_incorrect": {
            "Defines an entirely new play within the playbook": "Wrong — a block exists within a single play's task list, it doesn't define a separate play.",
            "Creates a loop over a group of hosts": "Wrong — looping over hosts is controlled by the play's hosts targeting, not block/rescue.",
            "Registers multiple variables from a single task": "Wrong — that's unrelated to block/rescue, which is about grouping and error handling, not variable registration.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `delegate_to: localhost` do on a task?",
        "options": [
            "Runs the task on the Ansible control node instead of the remote target host",
            "Deletes the local Ansible installation",
            "Disables the task entirely so it never runs",
            "Runs the task on all hosts simultaneously, ignoring targeting",
        ],
        "correct_answer": "Runs the task on the Ansible control node instead of the remote target host",
        "explanation_correct": "delegate_to redirects where a specific task executes — 'localhost' points it at the control node running Ansible itself, rather than the remote host being managed.",
        "explanation_incorrect": {
            "Deletes the local Ansible installation": "Wrong — delegate_to only affects where a task runs, it doesn't delete or modify any installation.",
            "Disables the task entirely so it never runs": "Wrong — the task still runs, just on a different host (the control node) than the play's normal target.",
            "Runs the task on all hosts simultaneously, ignoring targeting": "Wrong — delegate_to redirects execution to one specific host (localhost here), not to every host at once.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the effect of `run_once: true` on a task?",
        "options": [
            "The task executes only once across all targeted hosts, rather than once per host",
            "The task runs once per Ansible execution, regardless of what hosts other tasks target",
            "The task is permanently disabled after the first playbook run",
            "The task never runs again once triggered a single time, even in future playbook runs",
        ],
        "correct_answer": "The task executes only once across all targeted hosts, rather than once per host",
        "explanation_correct": "Without run_once, a task normally executes once per targeted host; run_once restricts it to executing on just the first host in the current batch.",
        "explanation_incorrect": {
            "The task runs once per Ansible execution, regardless of what hosts other tasks target": "Wrong — run_once applies to that specific task's execution against its own play's hosts, not globally across the whole run.",
            "The task is permanently disabled after the first playbook run": "Wrong — run_once affects a single play execution, not whether the task runs again on a future playbook run.",
            "The task never runs again once triggered a single time, even in future playbook runs": "Wrong — run_once has no memory across separate playbook executions; it only limits execution within the current run.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `serial` keyword control at the play level?",
        "options": [
            "How many hosts are processed in each batch during a rolling update",
            "How many times a failed task automatically retries",
            "The order in which tasks execute within a single host",
            "The maximum number of parallel SSH connections allowed globally",
        ],
        "correct_answer": "How many hosts are processed in each batch during a rolling update",
        "explanation_correct": "serial limits how many hosts go through the play's full task list at once, completing one batch before starting the next — useful for rolling deployments.",
        "explanation_incorrect": {
            "How many times a failed task automatically retries": "Wrong — that's the role of the retries keyword (with until), not serial.",
            "The order in which tasks execute within a single host": "Wrong — task execution order within a host is simply the order tasks are listed, unrelated to serial.",
            "The maximum number of parallel SSH connections allowed globally": "Wrong — that's controlled by the forks setting in ansible.cfg, a different concept from serial's batching behavior.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of `changed_when: false` on a task?",
        "options": [
            "Tells Ansible to never report this task as having made a change, regardless of its actual result",
            "Prevents the task from running at all",
            "Marks the task as failed unconditionally",
            "Disables idempotency checks for the entire playbook",
        ],
        "correct_answer": "Tells Ansible to never report this task as having made a change, regardless of its actual result",
        "explanation_correct": "changed_when overrides how a task's changed status is reported; setting it to false is common for read-only or status-check commands that shouldn't count as a 'change'.",
        "explanation_incorrect": {
            "Prevents the task from running at all": "Wrong — the task still runs normally; only its reported changed status is affected.",
            "Marks the task as failed unconditionally": "Wrong — changed_when affects the changed indicator, not failure status (that's failed_when).",
            "Disables idempotency checks for the entire playbook": "Wrong — changed_when applies only to the specific task it's set on, not globally to the whole playbook.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of the `default` Jinja2 filter in Ansible, as in `{{ username | default('guest') }}`?",
        "options": [
            "Provides a fallback value to use when the variable is undefined",
            "Permanently sets the variable's default value going forward",
            "Deletes the variable if its value is empty",
            "Converts the variable to its declared default type",
        ],
        "correct_answer": "Provides a fallback value to use when the variable is undefined",
        "explanation_correct": "The default filter substitutes the given fallback value only for this expression's evaluation when the referenced variable is undefined, without altering the variable itself.",
        "explanation_incorrect": {
            "Permanently sets the variable's default value going forward": "Wrong — the filter only affects that specific expression's output; it doesn't assign or persist a value to the variable.",
            "Deletes the variable if its value is empty": "Wrong — the filter never deletes anything; it just substitutes a fallback for display/use.",
            "Converts the variable to its declared default type": "Wrong — this isn't a type-conversion filter; it's about substituting a value when undefined.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `ansible-galaxy install` do?",
        "options": [
            "Downloads and installs a role (or collection) from Ansible Galaxy or another specified source",
            "Installs the Ansible package/tool itself onto the system",
            "Creates a brand-new Ansible Galaxy account",
            "Publishes a local role up to Ansible Galaxy",
        ],
        "correct_answer": "Downloads and installs a role (or collection) from Ansible Galaxy or another specified source",
        "explanation_correct": "ansible-galaxy install fetches a role or collection (from Galaxy by default, or another source if specified) and places it where Ansible can use it.",
        "explanation_incorrect": {
            "Installs the Ansible package/tool itself onto the system": "Wrong — installing Ansible itself is done via a package manager or pip, not ansible-galaxy (which assumes Ansible is already installed).",
            "Creates a brand-new Ansible Galaxy account": "Wrong — account creation happens on the Galaxy website, unrelated to this CLI subcommand.",
            "Publishes a local role up to Ansible Galaxy": "Wrong — that's closer to the role of `ansible-galaxy role import` or similar publishing commands, not install.",
        },
    },

    # ---------------- FILL-IN-BLANK (8) ----------------

    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ keyword stores a task's output into a variable that can be used by later tasks.",
        "options": None,
        "correct_answer": "register",
        "explanation_correct": "register captures a task's result object into a named variable.",
        "explanation_incorrect": "The blank should be filled with the keyword used to capture task output: register.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ groups a set of tasks together, and can be paired with rescue to handle failures similar to a try/except construct.",
        "options": None,
        "correct_answer": "block",
        "explanation_correct": "A block groups tasks and, combined with rescue, provides structured error handling.",
        "explanation_incorrect": "The blank should be filled with the keyword used to group tasks: block.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Setting ____: localhost on a task runs it on the Ansible control node instead of the remote target host.",
        "options": None,
        "correct_answer": "delegate_to",
        "explanation_correct": "delegate_to redirects a task's execution target, commonly to localhost for control-node actions.",
        "explanation_incorrect": "The blank should be filled with the keyword used to redirect task execution: delegate_to.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Setting ____: true on a task ensures it executes only once across all targeted hosts, rather than once per host.",
        "options": None,
        "correct_answer": "run_once",
        "explanation_correct": "run_once restricts a task to executing on just one host, even when the play targets many.",
        "explanation_incorrect": "The blank should be filled with the keyword used to limit a task to a single execution: run_once.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The play-level ____ keyword controls how many hosts are processed in each batch during a rolling update.",
        "options": None,
        "correct_answer": "serial",
        "explanation_correct": "serial limits how many hosts complete the play's tasks per batch, enabling rolling updates.",
        "explanation_incorrect": "The blank should be filled with the play-level batching keyword: serial.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Setting changed_when to ____ tells Ansible to never report a task as having made a change, regardless of its actual result.",
        "options": None,
        "correct_answer": "false",
        "explanation_correct": "changed_when: false overrides the task's reported changed status to always be false.",
        "explanation_incorrect": "The blank should be filled with the value that suppresses the changed status: false.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The Jinja2 ____ filter provides a fallback value when a variable is undefined, e.g. {{ username | default('guest') }}.",
        "options": None,
        "correct_answer": "default",
        "explanation_correct": "The default filter substitutes a fallback value for an undefined variable in that expression.",
        "explanation_incorrect": "The blank should be filled with the name of this fallback-providing filter: default.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command-line tool downloads and installs roles or collections from Ansible Galaxy.",
        "options": None,
        "correct_answer": "ansible-galaxy",
        "explanation_correct": "ansible-galaxy is the CLI tool for managing roles and collections from the Galaxy registry.",
        "explanation_incorrect": "The blank should be filled with the name of this CLI tool: ansible-galaxy.",
    },

    # ---------------- DRAG-AND-DROP (7) ----------------

    {
        "topic": "Ansible", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these tasks into the correct order for running a command, registering its output, and printing it.",
        "options": ["- name: Show result\n  debug:\n    var: result", "- name: Run whoami\n  command: whoami\n  register: result"],
        "correct_answer": '["- name: Run whoami\\n  command: whoami\\n  register: result", "- name: Show result\\n  debug:\\n    var: result"]',
        "explanation_correct": "Correct — the result variable must be registered by the first task before a later task can reference it in debug output.",
        "explanation_incorrect": "The variable must be registered before it can be referenced — the command task capturing 'result' must run before the debug task that prints it.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured block/rescue that installs a package and handles failure.",
        "options": ["  rescue:\n    - name: Handle failure\n      debug:\n        msg: \"Installation failed\"", "- block:\n    - name: Install package\n      package:\n        name: mypackage\n        state: present"],
        "correct_answer": '["- block:\\n    - name: Install package\\n      package:\\n        name: mypackage\\n        state: present", "  rescue:\\n    - name: Handle failure\\n      debug:\\n        msg: \\"Installation failed\\""]',
        "explanation_correct": "Correct — the block section (containing the risky task) must be defined before the rescue section that handles its potential failure.",
        "explanation_incorrect": "The block section must come first, since rescue is a fallback specifically for failures occurring within the block above it.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task using until/retries to retry a command.",
        "options": ["  until: result.rc == 0\n  retries: 5\n  delay: 10", "- name: Retry until success\n  command: check_status.sh", "  register: result"],
        "correct_answer": '["- name: Retry until success\\n  command: check_status.sh", "  register: result", "  until: result.rc == 0\\n  retries: 5\\n  delay: 10"]',
        "explanation_correct": "Correct — the command must run and register its result before until can check a condition against that result, with retries/delay controlling the retry behavior.",
        "explanation_incorrect": "The command must be defined and its output registered before the until condition can reference the result variable it depends on.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these playbook entries into the correct order: importing a common playbook, then defining a play that deploys an app.",
        "options": ["- hosts: webservers\n  tasks:\n    - name: Deploy app\n      debug:\n        msg: \"Deploying\"", "- import_playbook: common.yml"],
        "correct_answer": '["- import_playbook: common.yml", "- hosts: webservers\\n  tasks:\\n    - name: Deploy app\\n      debug:\\n        msg: \\"Deploying\\""]',
        "explanation_correct": "Correct — import_playbook is listed as a top-level entry before the subsequent play, so its contents run first in the overall playbook execution order.",
        "explanation_incorrect": "The import_playbook entry is placed before the deploy play, since playbook entries execute in the order they're listed.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured meta/main.yml file declaring a role dependency.",
        "options": ["  - role: common", "---", "dependencies:"],
        "correct_answer": '["---", "dependencies:", "  - role: common"]',
        "explanation_correct": "Correct — the YAML document start marker comes first, followed by the dependencies key, followed by the actual dependency entry nested underneath it.",
        "explanation_incorrect": "The document marker (---) conventionally comes first, the dependencies key must be declared before any entries can be nested under it.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured play that loads variables from a file and uses one in a task.",
        "options": ["  tasks:\n    - name: Use var\n      debug:\n        msg: \"{{ some_var }}\"", "- hosts: webservers", "  vars_files:\n    - vars/main.yml"],
        "correct_answer": '["- hosts: webservers", "  vars_files:\\n    - vars/main.yml", "  tasks:\\n    - name: Use var\\n      debug:\\n        msg: \\"{{ some_var }}\\""]',
        "explanation_correct": "Correct — the play's hosts must be declared first, followed by vars_files, with tasks (which use the loaded variables) listed after.",
        "explanation_incorrect": "The hosts line must come first, and while vars_files and tasks are technically independent keys, listing vars_files before tasks reflects that the variables should be available for the tasks to use.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured play performing a rolling update with a batch size of 2.",
        "options": ["  tasks:\n    - name: Deploy\n      debug:\n        msg: \"Deploying\"", "- hosts: webservers", "  serial: 2"],
        "correct_answer": '["- hosts: webservers", "  serial: 2", "  tasks:\\n    - name: Deploy\\n      debug:\\n        msg: \\"Deploying\\""]',
        "explanation_correct": "Correct — the hosts line must come first to define the play's target, with serial and tasks as sibling keys beneath it.",
        "explanation_incorrect": "The hosts line must come first, with serial and tasks declared beneath it as sibling keys of the play.",
    },

    # ---------------- DROPDOWN-ORDER (7) ----------------

    {
        "topic": "Ansible", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured task with two tags.",
        "options": ["  debug:\n    msg: \"Running\"", "- name: Setup and deploy step", "  tags:\n    - setup\n    - deploy"],
        "correct_answer": '["- name: Setup and deploy step", "  debug:\\n    msg: \\"Running\\"", "  tags:\\n    - setup\\n    - deploy"]',
        "explanation_correct": "Correct — the task's name comes first, with the module call and tags as sibling keys beneath it, conventionally with tags listed after the module.",
        "explanation_incorrect": "The task name should come first, and the module call and tags list are both sibling keys beneath it, with the module conventionally listed before tags.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these items into the correct order: a task that notifies a topic, followed by the handler listening for that topic.",
        "options": ["- name: Restart web service A\n  service:\n    name: apache2\n    state: restarted\n  listen: \"restart web services\"", "- name: Update config\n  template:\n    src: config.j2\n    dest: /etc/app/config\n  notify: \"restart web services\""],
        "correct_answer": '["- name: Update config\\n  template:\\n    src: config.j2\\n    dest: /etc/app/config\\n  notify: \\"restart web services\\"", "- name: Restart web service A\\n  service:\\n    name: apache2\\n    state: restarted\\n  listen: \\"restart web services\\""]',
        "explanation_correct": "Correct — by convention, tasks that notify handlers are listed in the tasks section before the handlers section, even though the handler only actually runs after all tasks complete.",
        "explanation_incorrect": "Conventionally the notifying task is defined in the tasks section, listed before the handler (in the handlers section) that listens for its notification, even though execution of the handler happens later.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured task that loops over a dictionary using dict2items.",
        "options": ["- name: Print dict items", "  loop: \"{{ mydict | dict2items }}\"", "  debug:\n    msg: \"{{ item.key }}: {{ item.value }}\""],
        "correct_answer": '["- name: Print dict items", "  debug:\\n    msg: \\"{{ item.key }}: {{ item.value }}\\"", "  loop: \\"{{ mydict | dict2items }}\\""]',
        "explanation_correct": "Correct — the task name comes first, with the module call and loop as sibling keys beneath it, conventionally with the module listed before the loop that feeds it.",
        "explanation_incorrect": "The task name is listed first, and while loop and the module call are sibling keys, conventionally the module block is listed before the loop supplying its items.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured task that prints a variable as JSON.",
        "options": ["    msg: \"{{ myvar | to_json }}\"", "- name: Show JSON", "  debug:"],
        "correct_answer": '["- name: Show JSON", "  debug:", "    msg: \\"{{ myvar | to_json }}\\""]',
        "explanation_correct": "Correct — the task name comes first, followed by the module name, followed by that module's nested msg argument.",
        "explanation_incorrect": "The task name must come first, with the module name declared before its arguments, since msg is nested under the debug key.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using check mode to preview changes before applying them.",
        "options": ["Run ansible-playbook without --check to apply the changes for real", "Run ansible-playbook with --check to preview changes without applying them", "Review the reported changes"],
        "correct_answer": '["Run ansible-playbook with --check to preview changes without applying them", "Review the reported changes", "Run ansible-playbook without --check to apply the changes for real"]',
        "explanation_correct": "Correct — the check-mode run must happen before there's anything to review, and the real run (applying changes) logically follows after reviewing the preview.",
        "explanation_incorrect": "The check-mode preview must run before its results can be reviewed, and actually applying the changes typically comes only after that review.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these tasks into the correct order for launching an async task and polling for its completion.",
        "options": ["- name: Check async task status\n  async_status:\n    jid: \"{{ async_result.ansible_job_id }}\"\n  register: job_result\n  until: job_result.finished\n  retries: 30\n  delay: 10", "- name: Run long task asynchronously\n  command: long_running_script.sh\n  async: 300\n  poll: 0\n  register: async_result"],
        "correct_answer": '["- name: Run long task asynchronously\\n  command: long_running_script.sh\\n  async: 300\\n  poll: 0\\n  register: async_result", "- name: Check async task status\\n  async_status:\\n    jid: \\"{{ async_result.ansible_job_id }}\\"\\n  register: job_result\\n  until: job_result.finished\\n  retries: 30\\n  delay: 10"]',
        "explanation_correct": "Correct — the async task must launch and register its job ID before a status-checking task can poll that job's completion.",
        "explanation_incorrect": "The async job must be started and its ID registered before async_status has anything to poll against.",
    },
    {
        "topic": "Ansible", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using group_vars with a playbook run.",
        "options": ["Ansible automatically loads and makes those variables available in tasks/templates", "Create a group_vars/webservers.yml file with variables for that group", "Run the playbook targeting the webservers group"],
        "correct_answer": '["Create a group_vars/webservers.yml file with variables for that group", "Run the playbook targeting the webservers group", "Ansible automatically loads and makes those variables available in tasks/templates"]',
        "explanation_correct": "Correct — the group_vars file must exist before it has anything to be loaded, and Ansible automatically applies those variables as part of running the playbook against that group.",
        "explanation_incorrect": "The group_vars file must exist before there's anything for Ansible to load, and variable availability is a result of running the playbook, not something that precedes it.",
    },
]
