"""
Ansible - Hard batch, 50 questions total.
Distribution: 20 coding, 8 mcq, 8 fill-in-blank, 7 drag-and-drop, 7 dropdown-order.

Schema matches ansible_easy_questions.py — see that file's header for full field notes.
Hard content covers FQCNs, loop_control, block/rescue/always, strategy plugins,
any_errors_fatal/force_handlers, delegate_facts, throttle, argument_specs, custom facts,
Jinja2 map/selectattr/regex_replace, variable precedence, Molecule, and ansible-lint.
"""

ANSIBLE_HARD_QUESTIONS = [

    # ---------------- CODING (20) ----------------

    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task using the fully qualified collection name (FQCN) ansible.builtin.copy to copy a local file 'app.conf' to '/etc/app.conf'.",
        "correct_answer": "- name: Copy app config\n  ansible.builtin.copy:\n    src: app.conf\n    dest: /etc/app.conf",
        "explanation_correct": "Correct — using the FQCN ansible.builtin.copy unambiguously references the built-in copy module, avoiding any naming collision with a same-named module from another collection.",
        "explanation_incorrect": "A correct solution must use the full FQCN form (ansible.builtin.copy), not the short form (copy), with the correct src and dest.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task that loops over a variable named packages to install each one, using loop_control to rename the loop variable from the default 'item' to 'pkg'.",
        "correct_answer": "- name: Install packages\n  package:\n    name: \"{{ pkg }}\"\n    state: present\n  loop: \"{{ packages }}\"\n  loop_control:\n    loop_var: pkg",
        "explanation_correct": "Correct — loop_control's loop_var setting renames the per-iteration variable to pkg, which is then correctly referenced inside the module call instead of the default item.",
        "explanation_incorrect": "A correct solution must use loop_control with loop_var set to pkg, and reference {{ pkg }} (not {{ item }}) inside the task.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible block that runs a risky command, uses rescue to handle failure, and uses always to run a cleanup task regardless of success or failure.",
        "correct_answer": "- block:\n    - name: Risky task\n      command: risky.sh\n  rescue:\n    - name: Handle failure\n      debug:\n        msg: \"Failed\"\n  always:\n    - name: Cleanup\n      debug:\n        msg: \"Cleaning up\"",
        "explanation_correct": "Correct — the block/rescue/always structure runs the risky task, falls back to rescue on failure, and always executes the cleanup task no matter what happened.",
        "explanation_incorrect": "A correct solution must include all three sections (block, rescue, always), with always guaranteed to run regardless of whether the block succeeded or the rescue was triggered.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write a play-level setting using strategy: free to allow each host to progress through the play's tasks independently, rather than in lockstep.",
        "correct_answer": "- hosts: webservers\n  strategy: free",
        "explanation_correct": "Correct — strategy: free lets each host move through the task list at its own pace, instead of waiting for every host to finish each task before any host proceeds to the next.",
        "explanation_incorrect": "A correct solution must set strategy to free specifically (not the default linear) at the play level.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write a play-level setting using any_errors_fatal: true to immediately abort the entire play if any host fails a task.",
        "correct_answer": "- hosts: webservers\n  any_errors_fatal: true",
        "explanation_correct": "Correct — any_errors_fatal: true stops the play across all hosts as soon as a single host encounters a failure, rather than letting other hosts continue.",
        "explanation_incorrect": "A correct solution must set any_errors_fatal to true at the play level.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task that loops over a list of dictionaries named users, and uses loop_control's label argument to display only each item's 'name' key in output, instead of the full dictionary.",
        "correct_answer": "- name: Process users\n  debug:\n    msg: \"Processing user\"\n  loop: \"{{ users }}\"\n  loop_control:\n    label: \"{{ item.name }}\"",
        "explanation_correct": "Correct — loop_control's label overrides what's shown in the task output for each iteration, displaying just item.name instead of the entire dictionary.",
        "explanation_incorrect": "A correct solution must use loop_control with a label set to {{ item.name }}, so output shows just the name rather than the full item.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task that gathers facts about a different host (otherhost) than the one currently being executed on, storing those facts against otherhost using delegate_facts.",
        "correct_answer": "- name: Gather facts about another host\n  setup:\n  delegate_to: otherhost\n  delegate_facts: true",
        "explanation_correct": "Correct — delegate_to redirects the setup module's execution to otherhost, and delegate_facts: true ensures the gathered facts are stored against otherhost rather than the current host.",
        "explanation_incorrect": "A correct solution must include both delegate_to (pointing to otherhost) and delegate_facts: true — without delegate_facts, gathered facts would be incorrectly attributed to the current host.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write the ansible-inventory command to display the inventory as a graph/tree structure.",
        "correct_answer": "ansible-inventory --graph",
        "explanation_correct": "Correct — `ansible-inventory --graph` renders the inventory's groups and hosts as a tree structure.",
        "explanation_incorrect": "A correct solution must use ansible-inventory with the --graph flag specifically.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task that uses debug to print the 'name' attribute of every dictionary in a list variable users where the 'active' attribute is true, using the selectattr and map filters.",
        "correct_answer": "- name: Get active user names\n  debug:\n    msg: \"{{ users | selectattr('active') | map(attribute='name') | list }}\"",
        "explanation_correct": "Correct — selectattr('active') filters the list down to dictionaries where 'active' is truthy, and map(attribute='name') extracts just the name from each of those.",
        "explanation_incorrect": "A correct solution must first filter the list to only active users (selectattr), then extract just the name attribute from each (map), rather than printing full dictionaries.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write two Ansible tasks: the first runs a command in a loop over the values 'a' and 'b', registering the results as loop_result, and the second uses debug to print loop_result.results.",
        "correct_answer": "- name: Run command on each item\n  command: \"echo {{ item }}\"\n  loop:\n    - a\n    - b\n  register: loop_result\n\n- name: Show all results\n  debug:\n    var: loop_result.results",
        "explanation_correct": "Correct — registering a looped task produces a result object with a .results list containing one entry per iteration, correctly accessed in the second task.",
        "explanation_incorrect": "A correct solution must register the looped task's output and access the individual per-iteration results via the .results attribute in a later task.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write the ansible-playbook command to run site.yml, limiting execution to hosts that are in both group1 and group2 (a host pattern intersection).",
        "correct_answer": "ansible-playbook site.yml --limit 'group1:&group2'",
        "explanation_correct": "Correct — the `:&` operator in a host pattern requires membership in both groups, correctly limiting execution to their intersection.",
        "explanation_incorrect": "A correct solution must use the intersection operator (:&) between the two group names in the --limit pattern, not a simple union (:) which would include hosts in either group.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write the ansible-vault command to encrypt a file named secrets.yml using a specific vault ID named 'prod'.",
        "correct_answer": "ansible-vault encrypt --vault-id prod@prompt secrets.yml",
        "explanation_correct": "Correct — the --vault-id flag with a named ID (prod) and a password source (@prompt) encrypts the file under that specific vault identity, supporting multiple distinct vault passwords in one project.",
        "explanation_incorrect": "A correct solution must specify the named vault ID 'prod' via --vault-id, not just a plain unnamed vault password.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write a minimal roles/webserver/meta/argument_specs.yml file defining a required string argument named 'app_name' for the role's main entry point.",
        "correct_answer": "---\nargument_specs:\n  main:\n    options:\n      app_name:\n        type: str\n        required: true",
        "explanation_correct": "Correct — the argument_specs file declares app_name as a required string option for the role's main entry point, which Ansible validates against when the role is called.",
        "explanation_incorrect": "A correct solution must define argument_specs with a main entry, declaring app_name with type str and required: true.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task using throttle: 2 to limit how many hosts run this specific debug task concurrently, to 2 at a time.",
        "correct_answer": "- name: Deploy carefully\n  debug:\n    msg: \"Deploying\"\n  throttle: 2",
        "explanation_correct": "Correct — throttle: 2 caps concurrent execution of this specific task at 2 hosts, independent of the play's overall forks/parallelism setting.",
        "explanation_incorrect": "A correct solution must include throttle: 2 on the task, specifically limiting its own concurrency rather than the whole play's.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write the ansible-galaxy command to install a collection named 'community.general'.",
        "correct_answer": "ansible-galaxy collection install community.general",
        "explanation_correct": "Correct — `ansible-galaxy collection install` downloads and installs the given collection (as opposed to `ansible-galaxy install`, which is used for roles).",
        "explanation_incorrect": "A correct solution must use the `collection install` subcommand specifically (not the role install form), targeting community.general.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task that copies a local custom facts file named custom.fact to /etc/ansible/facts.d/custom.fact on the remote host, so its contents become available as custom Ansible facts.",
        "correct_answer": "- name: Copy custom facts file\n  copy:\n    src: custom.fact\n    dest: /etc/ansible/facts.d/custom.fact",
        "explanation_correct": "Correct — placing an INI/JSON fact file in /etc/ansible/facts.d/ makes its contents automatically discoverable as ansible_local facts on subsequent fact gathering.",
        "explanation_incorrect": "A correct solution must copy the file to the exact facts.d path (/etc/ansible/facts.d/) for it to be automatically picked up as custom facts.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an ansible.cfg snippet that enables SSH pipelining under the [ssh_connection] section.",
        "correct_answer": "[ssh_connection]\npipelining = True",
        "explanation_correct": "Correct — enabling pipelining under [ssh_connection] reduces the number of SSH operations Ansible needs per task, often improving performance.",
        "explanation_incorrect": "A correct solution must set pipelining to True under the [ssh_connection] section header specifically.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write an Ansible task using debug that prints a variable raw_string with all digits removed, using the regex_replace Jinja2 filter.",
        "correct_answer": "- name: Strip digits\n  debug:\n    msg: \"{{ raw_string | regex_replace('[0-9]', '') }}\"",
        "explanation_correct": "Correct — the regex_replace filter with pattern [0-9] and an empty replacement removes every digit character from the string.",
        "explanation_incorrect": "A correct solution must use the regex_replace filter with a digit-matching pattern and an empty replacement string.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to run ansible-lint against a playbook file named site.yml.",
        "correct_answer": "ansible-lint site.yml",
        "explanation_correct": "Correct — `ansible-lint` analyzes the given playbook for style issues, deprecated syntax, and best-practice violations.",
        "explanation_incorrect": "A correct solution must run ansible-lint against site.yml specifically.",
        "options": None,
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "coding",
        "prompt": "Write a play-level setting using force_handlers: true to ensure notified handlers still run even if a later task in the play fails.",
        "correct_answer": "- hosts: webservers\n  force_handlers: true",
        "explanation_correct": "Correct — force_handlers: true overrides Ansible's default behavior of skipping pending handlers when a later task fails, ensuring they still run.",
        "explanation_incorrect": "A correct solution must set force_handlers to true at the play level.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the correct precedence order (highest to lowest) among extra vars (-e), role defaults, and host_vars?",
        "options": [
            "Extra vars (-e) > host_vars > role defaults",
            "Role defaults > host_vars > extra vars (-e)",
            "Host_vars > extra vars (-e) > role defaults",
            "They all have equal precedence",
        ],
        "correct_answer": "Extra vars (-e) > host_vars > role defaults",
        "explanation_correct": "Extra vars passed via -e on the command line have the highest precedence of nearly all variable sources in Ansible, followed by more specific sources like host_vars, with role defaults sitting at the lowest end of the precedence order.",
        "explanation_incorrect": {
            "Role defaults > host_vars > extra vars (-e)": "Wrong — this is essentially reversed; role defaults are actually the lowest-precedence source, not the highest.",
            "Host_vars > extra vars (-e) > role defaults": "Wrong — extra vars (-e) rank above host_vars in Ansible's precedence order, not below.",
            "They all have equal precedence": "Wrong — Ansible has a well-defined, non-equal precedence hierarchy across variable sources.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `strategy: free` do at the play level, compared to the default 'linear' strategy?",
        "options": [
            "Allows each host to proceed through the play's tasks independently, rather than waiting for all hosts to complete each task in lockstep",
            "Forces all hosts to run every task simultaneously with absolutely no exceptions",
            "Disables parallel execution entirely, running one host at a time",
            "Only affects the order in which handlers execute",
        ],
        "correct_answer": "Allows each host to proceed through the play's tasks independently, rather than waiting for all hosts to complete each task in lockstep",
        "explanation_correct": "With the default linear strategy, every host must finish a task before any host moves to the next; free strategy lets faster hosts race ahead without waiting for slower ones.",
        "explanation_incorrect": {
            "Forces all hosts to run every task simultaneously with absolutely no exceptions": "Wrong — free strategy actually removes the lockstep synchronization, allowing hosts to diverge in pace, not forcing strict simultaneity.",
            "Disables parallel execution entirely, running one host at a time": "Wrong — free strategy still runs hosts in parallel (up to the forks limit); it just removes the per-task synchronization barrier.",
            "Only affects the order in which handlers execute": "Wrong — strategy affects overall task execution flow across hosts, not just handler ordering specifically.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of `any_errors_fatal: true` at the play level?",
        "options": [
            "Immediately aborts the entire play across all hosts if any single host fails a task",
            "Ignores all errors that occur throughout the play",
            "Only marks the specific failed task itself as fatal, without affecting other hosts",
            "Disables error reporting entirely for the play",
        ],
        "correct_answer": "Immediately aborts the entire play across all hosts if any single host fails a task",
        "explanation_correct": "By default, a failure on one host doesn't stop other hosts from continuing; any_errors_fatal changes this so a single host's failure halts the play for every host.",
        "explanation_incorrect": {
            "Ignores all errors that occur throughout the play": "Wrong — this setting does the opposite; it makes errors more disruptive (halting the whole play), not less.",
            "Only marks the specific failed task itself as fatal, without affecting other hosts": "Wrong — the whole point of any_errors_fatal is that it affects the entire play across all hosts, not just the failing task/host in isolation.",
            "Disables error reporting entirely for the play": "Wrong — errors are still reported; this setting changes the play's response to a failure, not whether it's reported.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What is a Fully Qualified Collection Name (FQCN), such as ansible.builtin.copy?",
        "options": [
            "The full namespace.collection.module path used to unambiguously reference a specific module",
            "A special naming convention exclusively for variables",
            "A reserved inventory group name",
            "An identifier used specifically for vault encryption keys",
        ],
        "correct_answer": "The full namespace.collection.module path used to unambiguously reference a specific module",
        "explanation_correct": "FQCNs specify exactly which collection a module comes from, avoiding ambiguity when multiple installed collections might provide a module with the same short name.",
        "explanation_incorrect": {
            "A special naming convention exclusively for variables": "Wrong — FQCNs identify modules (and other plugins), not variables.",
            "A reserved inventory group name": "Wrong — FQCNs are unrelated to inventory groups; they're about module/plugin namespacing.",
            "An identifier used specifically for vault encryption keys": "Wrong — vault IDs are a separate concept from FQCNs, which are strictly about module/plugin references.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `force_handlers: true` do at the play level?",
        "options": [
            "Ensures notified handlers run even if a later task in the play fails",
            "Forces all handlers to run on every playbook execution, regardless of whether they were notified",
            "Disables handlers entirely for that play",
            "Runs handlers before tasks instead of after them",
        ],
        "correct_answer": "Ensures notified handlers run even if a later task in the play fails",
        "explanation_correct": "By default, if a task fails before the play finishes, any handlers that were notified but haven't run yet get skipped; force_handlers overrides that, letting them run anyway.",
        "explanation_incorrect": {
            "Forces all handlers to run on every playbook execution, regardless of whether they were notified": "Wrong — force_handlers still requires a handler to have been notified; it just changes whether a later failure prevents it from running.",
            "Disables handlers entirely for that play": "Wrong — this setting makes handlers more likely to run (despite failures), not disabled.",
            "Runs handlers before tasks instead of after them": "Wrong — handler execution timing (typically at the end of the play, or when explicitly flushed) is unrelated to force_handlers.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of Molecule in the Ansible ecosystem?",
        "options": [
            "A testing framework for developing and testing Ansible roles across multiple scenarios and platforms",
            "A templating engine used instead of Jinja2",
            "A tool for managing molecular/scientific data, unrelated to infrastructure",
            "A dynamic inventory plugin for cloud providers",
        ],
        "correct_answer": "A testing framework for developing and testing Ansible roles across multiple scenarios and platforms",
        "explanation_correct": "Molecule automates creating test instances, applying a role, and verifying the results across different platforms/scenarios, helping ensure roles work correctly and idempotently.",
        "explanation_incorrect": {
            "A templating engine used instead of Jinja2": "Wrong — Ansible still uses Jinja2 for templating; Molecule is a testing tool, not a templating replacement.",
            "A tool for managing molecular/scientific data, unrelated to infrastructure": "Wrong — despite the name, Molecule is squarely an Ansible role-testing tool, unrelated to scientific data.",
            "A dynamic inventory plugin for cloud providers": "Wrong — dynamic inventory plugins are a separate Ansible feature; Molecule's purpose is testing roles, not sourcing inventory.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What does the `throttle` keyword control when set on a task?",
        "options": [
            "Limits how many hosts can execute that specific task concurrently, independent of the play's overall forks setting",
            "Sets a fixed time delay before the task starts",
            "Limits the number of times a task automatically retries",
            "Controls the network bandwidth used by the task",
        ],
        "correct_answer": "Limits how many hosts can execute that specific task concurrently, independent of the play's overall forks setting",
        "explanation_correct": "throttle caps concurrency for just that one task (useful for a task that hits a rate-limited external service, for example), even if the play's overall forks setting would otherwise allow more parallelism.",
        "explanation_incorrect": {
            "Sets a fixed time delay before the task starts": "Wrong — that would be closer to a pause or wait_for construct, not throttle.",
            "Limits the number of times a task automatically retries": "Wrong — that's the role of the retries keyword (with until), not throttle.",
            "Controls the network bandwidth used by the task": "Wrong — throttle controls host-level concurrency, not network bandwidth.",
        },
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of `loop_control` with a `label` argument?",
        "options": [
            "Customizes what's displayed for each loop iteration in task output, instead of showing the full item",
            "Changes the variable name used to reference each loop item (that's loop_var instead)",
            "Limits the total number of loop iterations that will run",
            "Sorts the loop's items before iterating over them",
        ],
        "correct_answer": "Customizes what's displayed for each loop iteration in task output, instead of showing the full item",
        "explanation_correct": "label lets you show a concise, relevant piece of each item (like just its name) in the task's per-iteration output, instead of dumping the entire item's structure.",
        "explanation_incorrect": {
            "Changes the variable name used to reference each loop item (that's loop_var instead)": "Wrong — renaming the loop variable is the role of loop_control's loop_var option, a different setting from label.",
            "Limits the total number of loop iterations that will run": "Wrong — label only affects display output, it doesn't restrict how many iterations actually execute.",
            "Sorts the loop's items before iterating over them": "Wrong — loop_control doesn't provide sorting; label is purely a display/output customization.",
        },
    },

    # ---------------- FILL-IN-BLANK (8) ----------------

    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "In Ansible variable precedence, ____ vars (passed via -e on the command line) have the highest precedence of nearly all variable sources.",
        "options": None,
        "correct_answer": "extra",
        "explanation_correct": "Extra vars set with -e override nearly every other variable source in Ansible's precedence hierarchy.",
        "explanation_incorrect": "The blank should be filled with the term for these command-line variables: extra.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The play-level ____ strategy allows each host to proceed through tasks independently, rather than waiting for all hosts to complete each task in lockstep (the default 'linear' behavior).",
        "options": None,
        "correct_answer": "free",
        "explanation_correct": "The free strategy removes per-task synchronization across hosts, letting each proceed at its own pace.",
        "explanation_incorrect": "The blank should be filled with the name of this non-lockstep strategy: free.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Setting ____: true at the play level immediately aborts the entire play across all hosts if any single host fails a task.",
        "options": None,
        "correct_answer": "any_errors_fatal",
        "explanation_correct": "any_errors_fatal changes the default behavior so a single host's failure halts the play for all hosts.",
        "explanation_incorrect": "The blank should be filled with the setting used to make any failure fatal for the whole play: any_errors_fatal.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A Fully Qualified Collection Name, or ____, is the full namespace.collection.module path used to unambiguously reference a module.",
        "options": None,
        "correct_answer": "FQCN",
        "explanation_correct": "FQCN stands for Fully Qualified Collection Name, the full path form of a module reference.",
        "explanation_incorrect": "The blank should be filled with the acronym for this full module reference path: FQCN.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Setting ____: true at the play level ensures notified handlers still run even if a later task in the play fails.",
        "options": None,
        "correct_answer": "force_handlers",
        "explanation_correct": "force_handlers overrides the default behavior of skipping pending handlers after a later failure.",
        "explanation_incorrect": "The blank should be filled with the setting used to force handler execution despite failures: force_handlers.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ is a testing framework used to develop and test Ansible roles across multiple scenarios and platforms.",
        "options": None,
        "correct_answer": "Molecule",
        "explanation_correct": "Molecule automates role testing across defined scenarios and platforms.",
        "explanation_incorrect": "The blank should be filled with the name of this role-testing framework: Molecule.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ keyword on a task limits how many hosts can execute that specific task concurrently, independent of the play's overall parallelism setting.",
        "options": None,
        "correct_answer": "throttle",
        "explanation_correct": "throttle caps per-task concurrency, separate from the play's forks setting.",
        "explanation_incorrect": "The blank should be filled with the keyword used to limit per-task concurrency: throttle.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Using loop_control with a ____ argument customizes what's displayed for each loop iteration in output, instead of showing the full item.",
        "options": None,
        "correct_answer": "label",
        "explanation_correct": "loop_control's label option controls the per-iteration display text shown in task output.",
        "explanation_incorrect": "The blank should be filled with the loop_control argument used to customize iteration display: label.",
    },

    # ---------------- DRAG-AND-DROP (7) ----------------

    {
        "topic": "Ansible", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task using the FQCN form of the copy module.",
        "options": ["- name: Copy app config", "  ansible.builtin.copy:\n    src: app.conf\n    dest: /etc/app.conf"],
        "correct_answer": '["- name: Copy app config", "  ansible.builtin.copy:\\n    src: app.conf\\n    dest: /etc/app.conf"]',
        "explanation_correct": "Correct — the task's name comes first, with the FQCN module call and its arguments as a sibling key beneath it.",
        "explanation_incorrect": "The task name is conventionally listed first, with the module call (here in its FQCN form) beneath it.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured block/rescue/always sequence.",
        "options": ["  rescue:\n    - name: Handle failure\n      debug:\n        msg: \"Failed\"", "- block:\n    - name: Risky task\n      command: risky.sh", "  always:\n    - name: Cleanup\n      debug:\n        msg: \"Cleaning up\""],
        "correct_answer": '["- block:\\n    - name: Risky task\\n      command: risky.sh", "  rescue:\\n    - name: Handle failure\\n      debug:\\n        msg: \\"Failed\\"", "  always:\\n    - name: Cleanup\\n      debug:\\n        msg: \\"Cleaning up\\""]',
        "explanation_correct": "Correct — block must come first (containing the primary task), followed by rescue (the failure fallback), followed by always (which runs regardless of outcome).",
        "explanation_incorrect": "The conventional order is block, then rescue, then always — block contains the primary logic, rescue handles its failures, and always runs after either path completes.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task using loop_control to rename the loop variable to 'pkg'.",
        "options": ["- name: Install packages", "  package:\n    name: \"{{ pkg }}\"\n    state: present", "  loop: \"{{ packages }}\"\n  loop_control:\n    loop_var: pkg"],
        "correct_answer": '["- name: Install packages", "  package:\\n    name: \\"{{ pkg }}\\"\\n    state: present", "  loop: \\"{{ packages }}\\"\\n  loop_control:\\n    loop_var: pkg"]',
        "explanation_correct": "Correct — the task name comes first, followed by the module call referencing {{ pkg }}, followed by the loop and loop_control settings that define what pkg actually refers to.",
        "explanation_incorrect": "The task name comes first, with the module call and loop/loop_control settings as sibling keys beneath it, conventionally with the module block listed before the loop configuration.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task that gathers and stores facts about a different host using delegate_facts.",
        "options": ["  delegate_to: otherhost\n  delegate_facts: true", "- name: Gather facts about another host", "  setup:"],
        "correct_answer": '["- name: Gather facts about another host", "  setup:", "  delegate_to: otherhost\\n  delegate_facts: true"]',
        "explanation_correct": "Correct — the task name comes first, followed by the module call, followed by the delegate_to/delegate_facts directives that redirect execution and fact storage.",
        "explanation_incorrect": "The task name and module call are conventionally listed before the delegate_to/delegate_facts directives, which modify how and where the task's results are applied.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these tasks into the correct order for running a looped command and printing all of its registered results.",
        "options": ["- name: Show all results\n  debug:\n    var: loop_result.results", "- name: Run command on each item\n  command: \"echo {{ item }}\"\n  loop:\n    - a\n    - b\n  register: loop_result"],
        "correct_answer": '["- name: Run command on each item\\n  command: \\"echo {{ item }}\\"\\n  loop:\\n    - a\\n    - b\\n  register: loop_result", "- name: Show all results\\n  debug:\\n    var: loop_result.results"]',
        "explanation_correct": "Correct — the looped task must run and register its output before a later task can print its .results attribute.",
        "explanation_incorrect": "The looped, registered task must execute before its results are available for a later task to reference and print.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured meta/argument_specs.yml file for a role.",
        "options": ["---", "argument_specs:", "  main:\n    options:\n      app_name:\n        type: str\n        required: true"],
        "correct_answer": '["---", "argument_specs:", "  main:\\n    options:\\n      app_name:\\n        type: str\\n        required: true"]',
        "explanation_correct": "Correct — the document marker comes first, followed by the argument_specs key, followed by the main entry point's nested options.",
        "explanation_incorrect": "The document marker conventionally comes first, and argument_specs must be declared before its nested main/options content can appear beneath it.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured task using throttle to limit concurrency to 2 hosts.",
        "options": ["  throttle: 2", "- name: Deploy carefully", "  debug:\n    msg: \"Deploying\""],
        "correct_answer": '["- name: Deploy carefully", "  debug:\\n    msg: \\"Deploying\\"", "  throttle: 2"]',
        "explanation_correct": "Correct — the task name comes first, followed by the module call, with throttle as a sibling key controlling that task's concurrency.",
        "explanation_incorrect": "The task name is listed first, with the module call and throttle setting as sibling keys beneath it.",
    },

    # ---------------- DROPDOWN-ORDER (7) ----------------

    {
        "topic": "Ansible", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured task using map and selectattr filters.",
        "options": ["- name: Get active user names", "    msg: \"{{ users | selectattr('active') | map(attribute='name') | list }}\"", "  debug:"],
        "correct_answer": '["- name: Get active user names", "  debug:", "    msg: \\"{{ users | selectattr(\'active\') | map(attribute=\'name\') | list }}\\""]',
        "explanation_correct": "Correct — the task name comes first, followed by the module name, followed by the nested msg argument containing the filter chain.",
        "explanation_incorrect": "The task name must come first, with the module name declared before its nested msg argument.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using ansible-lint to review a playbook.",
        "options": ["Review and fix any reported style/best-practice issues", "Write or modify a playbook (e.g. site.yml)", "Run ansible-lint site.yml"],
        "correct_answer": '["Write or modify a playbook (e.g. site.yml)", "Run ansible-lint site.yml", "Review and fix any reported style/best-practice issues"]',
        "explanation_correct": "Correct — the playbook must exist before it can be linted, and issues can only be reviewed and fixed after the lint run has actually reported them.",
        "explanation_incorrect": "The playbook must be written before it can be linted, and reviewing/fixing issues only makes sense after ansible-lint has reported them.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured task using the regex_replace filter.",
        "options": ["  debug:", "    msg: \"{{ raw_string | regex_replace('[0-9]', '') }}\"", "- name: Strip digits"],
        "correct_answer": '["- name: Strip digits", "  debug:", "    msg: \\"{{ raw_string | regex_replace(\'[0-9]\', \'\') }}\\""]',
        "explanation_correct": "Correct — the task name comes first, followed by the module name, followed by the nested msg argument applying the filter.",
        "explanation_incorrect": "The task name must come first, with the module name declared before its nested msg argument.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for testing whether a playbook is idempotent.",
        "options": ["Confirm the second run reports no changes (idempotent)", "Run the playbook once and confirm it reports changes", "Run the playbook again immediately"],
        "correct_answer": '["Run the playbook once and confirm it reports changes", "Run the playbook again immediately", "Confirm the second run reports no changes (idempotent)"]',
        "explanation_correct": "Correct — the initial run (which should make changes) must happen first, the second run tests whether those changes are stable, and only then can idempotency be confirmed based on that second run's output.",
        "explanation_incorrect": "The first run must apply the initial changes before a second run can test for idempotency, and confirming 'no changes' only makes sense after that second run has actually completed.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these tasks into the correct order for setting up custom facts on a remote host.",
        "options": ["- name: Copy custom facts file\n  copy:\n    src: custom.fact\n    dest: /etc/ansible/facts.d/custom.fact", "- name: Ensure facts.d directory exists\n  file:\n    path: /etc/ansible/facts.d\n    state: directory"],
        "correct_answer": '["- name: Ensure facts.d directory exists\\n  file:\\n    path: /etc/ansible/facts.d\\n    state: directory", "- name: Copy custom facts file\\n  copy:\\n    src: custom.fact\\n    dest: /etc/ansible/facts.d/custom.fact"]',
        "explanation_correct": "Correct — the facts.d directory must exist before a fact file can be copied into it.",
        "explanation_incorrect": "The destination directory must exist before a file can be copied into it, so the directory-creation task must run first.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for installing and using an Ansible collection.",
        "options": ["Run the playbook, and Ansible resolves the module from the installed collection", "Run ansible-galaxy collection install community.general", "Reference a module from the collection using its FQCN in a playbook (e.g. community.general.xyz)"],
        "correct_answer": '["Run ansible-galaxy collection install community.general", "Reference a module from the collection using its FQCN in a playbook (e.g. community.general.xyz)", "Run the playbook, and Ansible resolves the module from the installed collection"]',
        "explanation_correct": "Correct — the collection must be installed before its modules can be referenced, and the playbook can only successfully resolve/run that module once both the installation and the reference are in place.",
        "explanation_incorrect": "The collection must be installed before a playbook can reference its modules, and successful resolution only happens once both the install and the reference exist.",
    },
    {
        "topic": "Ansible", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for the Molecule testing workflow.",
        "options": ["Molecule reports whether the role applied correctly and passed verification", "Define a Molecule scenario (molecule/default/molecule.yml) specifying the test platform", "Run `molecule test` to converge and verify the role"],
        "correct_answer": '["Define a Molecule scenario (molecule/default/molecule.yml) specifying the test platform", "Run `molecule test` to converge and verify the role", "Molecule reports whether the role applied correctly and passed verification"]',
        "explanation_correct": "Correct — the scenario must be defined before molecule test has anything to run against, and results are reported only after that test run completes.",
        "explanation_incorrect": "The Molecule scenario must be defined before running molecule test, and results can only be reported once that test run has actually finished.",
    },
]
