"""
AWS - Hard batch, 50 questions total.
Distribution: even split — 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.

Schema matches aws_easy_questions.py / aws_medium_questions.py — see those files' headers
for full field notes. Hard content covers IAM policy evaluation logic, Organizations SCPs,
DynamoDB GSI/streams/DAX, Lambda provisioned/reserved concurrency, PrivateLink, disaster
recovery strategies, KMS envelope encryption, blue/green deployments, Global Accelerator,
Aurora Global Database, X-Ray, GuardDuty, WAF, EventBridge, and CloudFormation custom
resources / drift detection.
"""

AWS_HARD_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write an IAM policy statement that explicitly denies the s3:DeleteObject action on all resources, ensuring it overrides any Allow statement elsewhere in the account.",
        "correct_answer": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Deny\",\n      \"Action\": \"s3:DeleteObject\",\n      \"Resource\": \"*\"\n    }\n  ]\n}",
        "explanation_correct": "Correct — an explicit Deny always overrides any Allow in IAM's policy evaluation logic, so this statement blocks s3:DeleteObject regardless of other permissive policies.",
        "explanation_incorrect": "A correct solution must use Effect: Deny (not Allow) on the s3:DeleteObject action across all resources, since only an explicit Deny is guaranteed to override an Allow elsewhere.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to add a Global Secondary Index on attribute 'CustomerId' (String type, partition key for the index) to an existing DynamoDB table named 'Orders'.",
        "correct_answer": "aws dynamodb update-table --table-name Orders --attribute-definitions AttributeName=CustomerId,AttributeType=S --global-secondary-index-updates \"[{\\\"Create\\\":{\\\"IndexName\\\":\\\"CustomerIdIndex\\\",\\\"KeySchema\\\":[{\\\"AttributeName\\\":\\\"CustomerId\\\",\\\"KeyType\\\":\\\"HASH\\\"}],\\\"Projection\\\":{\\\"ProjectionType\\\":\\\"ALL\\\"}}}]\"",
        "explanation_correct": "Correct — `aws dynamodb update-table` with a global-secondary-index-updates Create action adds a new GSI on CustomerId to the existing table.",
        "explanation_incorrect": "A correct solution must add a new Global Secondary Index (not a Local Secondary Index) on the CustomerId attribute to the existing table.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to set a governance-mode Object Lock retention of 30 days from now on the object 'file.txt' in bucket 'compliance-bucket'.",
        "correct_answer": "aws s3api put-object-retention --bucket compliance-bucket --key file.txt --retention Mode=GOVERNANCE,RetainUntilDate=2026-08-29T00:00:00Z",
        "explanation_correct": "Correct — `aws s3api put-object-retention` with Mode=GOVERNANCE and a RetainUntilDate roughly 30 days out correctly applies a governance-mode retention lock on the object.",
        "explanation_incorrect": "A correct solution must apply an Object Lock retention setting (mode GOVERNANCE) with a RetainUntilDate about 30 days in the future, to the specific object given.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write an IAM trust policy (assume-role policy document) that allows the AWS account with ID 987654321098 to assume the role.",
        "correct_answer": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"AWS\": \"arn:aws:iam::987654321098:root\"\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}",
        "explanation_correct": "Correct — the trust policy grants the specified account (referenced via its root ARN) permission to call sts:AssumeRole, which is what a trust policy is specifically for.",
        "explanation_incorrect": "A correct solution must be a trust policy (Principal referencing the given AWS account, Action sts:AssumeRole), not a regular permissions policy.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to create a Lambda function alias named 'prod' pointing to version 3 of a function named 'my-function'.",
        "correct_answer": "aws lambda create-alias --function-name my-function --name prod --function-version 3",
        "explanation_correct": "Correct — `aws lambda create-alias` creates a named alias pointing at the specified function version.",
        "explanation_incorrect": "A correct solution must create an alias named 'prod' pointing at version 3 specifically, of the given function.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to configure provisioned concurrency of 5 for the 'prod' alias of a Lambda function named 'my-function'.",
        "correct_answer": "aws lambda put-provisioned-concurrency-config --function-name my-function --qualifier prod --provisioned-concurrent-executions 5",
        "explanation_correct": "Correct — `aws lambda put-provisioned-concurrency-config` with the alias as --qualifier and a count of 5 keeps 5 execution environments pre-initialized for that alias.",
        "explanation_incorrect": "A correct solution must configure provisioned concurrency specifically for the 'prod' alias (via --qualifier), with a count of 5.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to create an AWS Organizations Service Control Policy named 'DenyRootActions' from a local JSON policy file named scp.json.",
        "correct_answer": "aws organizations create-policy --name DenyRootActions --type SERVICE_CONTROL_POLICY --content file://scp.json --description \"Denies root user actions\"",
        "explanation_correct": "Correct — `aws organizations create-policy` with --type SERVICE_CONTROL_POLICY and the given content file creates a new SCP with the specified name.",
        "explanation_incorrect": "A correct solution must create a policy of type SERVICE_CONTROL_POLICY (not a regular IAM policy), using the content of the local scp.json file.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to enable VPC Flow Logs for a VPC with ID vpc-0123456789abcdef0, sending logs to a CloudWatch Logs group named 'vpc-flow-logs'.",
        "correct_answer": "aws ec2 create-flow-logs --resource-type VPC --resource-ids vpc-0123456789abcdef0 --traffic-type ALL --log-destination-type cloud-watch-logs --log-group-name vpc-flow-logs --deliver-logs-permission-arn arn:aws:iam::123456789012:role/flow-logs-role",
        "explanation_correct": "Correct — `aws ec2 create-flow-logs` with the VPC resource ID, traffic type, and CloudWatch Logs destination correctly enables flow logging for that VPC.",
        "explanation_incorrect": "A correct solution must enable flow logs for the specified VPC, directed to a CloudWatch Logs destination with the given log group name.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to create a composite CloudWatch alarm named 'combined-alarm' that fires only when both existing alarms 'alarm1' and 'alarm2' are in ALARM state.",
        "correct_answer": "aws cloudwatch put-composite-alarm --alarm-name combined-alarm --alarm-rule \"ALARM(alarm1) AND ALARM(alarm2)\"",
        "explanation_correct": "Correct — `aws cloudwatch put-composite-alarm` with an --alarm-rule combining both underlying alarms with AND correctly requires both to be in ALARM state before the composite alarm fires.",
        "explanation_incorrect": "A correct solution must combine both underlying alarms with an AND condition in the alarm rule, not just reference one or use OR.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "coding",
        "prompt": "Write the AWS CLI command to create an Aurora Global Database named 'my-global-db' based on an existing primary Aurora cluster named 'my-aurora-cluster'.",
        "correct_answer": "aws rds create-global-cluster --global-cluster-identifier my-global-db --source-db-cluster-identifier my-aurora-cluster",
        "explanation_correct": "Correct — `aws rds create-global-cluster` with --source-db-cluster-identifier converts the existing Aurora cluster into the primary of a new global database.",
        "explanation_incorrect": "A correct solution must create a global cluster based on the specified existing Aurora cluster as its source.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "In IAM policy evaluation, what happens when there's both an explicit Allow and an explicit Deny for the same action on the same resource?",
        "options": [
            "The explicit Deny always wins",
            "The explicit Allow always wins",
            "Whichever policy was created most recently takes precedence",
            "The request results in an undefined/random outcome",
        ],
        "correct_answer": "The explicit Deny always wins",
        "explanation_correct": "AWS's policy evaluation logic gives explicit Deny statements the highest precedence — they override any Allow, regardless of which policy (identity-based, resource-based, SCP, etc.) it comes from.",
        "explanation_incorrect": {
            "The explicit Allow always wins": "Wrong — this is backwards; an explicit Deny always overrides an Allow, not the other way around.",
            "Whichever policy was created most recently takes precedence": "Wrong — IAM evaluation isn't based on policy creation time at all; it's based on the Allow/Deny logic itself.",
            "The request results in an undefined/random outcome": "Wrong — IAM's evaluation logic is deterministic; explicit Deny consistently overrides Allow.",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the primary purpose of AWS Organizations Service Control Policies (SCPs)?",
        "options": [
            "Define the maximum permissions boundary for accounts within an organization, without granting any permissions themselves",
            "Grant permissions directly to individual IAM users",
            "Completely replace the need for IAM policies",
            "Apply only to the organization's management (root) account",
        ],
        "correct_answer": "Define the maximum permissions boundary for accounts within an organization, without granting any permissions themselves",
        "explanation_correct": "SCPs set the outer limit on what actions are possible in an account, but they never grant permissions on their own — IAM policies within the account still need to explicitly allow actions within that boundary.",
        "explanation_incorrect": {
            "Grant permissions directly to individual IAM users": "Wrong — SCPs never grant permissions by themselves; only IAM policies do that (within whatever boundary the SCP allows).",
            "Completely replace the need for IAM policies": "Wrong — SCPs work alongside IAM policies as a boundary, not a replacement for them.",
            "Apply only to the organization's management (root) account": "Wrong — SCPs typically apply to member accounts within organizational units; the management account itself is actually unaffected by SCPs.",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the difference between a DynamoDB Global Secondary Index (GSI) and a Local Secondary Index (LSI)?",
        "options": [
            "A GSI can have a different partition key than the base table, while an LSI shares the base table's partition key but uses a different sort key",
            "They are functionally identical, just named differently",
            "An LSI can be added after table creation, while a GSI cannot",
            "A GSI is always faster to query than an LSI",
        ],
        "correct_answer": "A GSI can have a different partition key than the base table, while an LSI shares the base table's partition key but uses a different sort key",
        "explanation_correct": "GSIs offer flexibility to query on entirely different partition keys, while LSIs are tied to the base table's partition key and only vary the sort key — and importantly, LSIs must be defined at table creation time.",
        "explanation_incorrect": {
            "They are functionally identical, just named differently": "Wrong — their key structures and creation-time requirements differ meaningfully.",
            "An LSI can be added after table creation, while a GSI cannot": "Wrong — this is backwards; GSIs can be added after table creation, while LSIs must be defined when the table is created.",
            "A GSI is always faster to query than an LSI": "Wrong — query performance depends on the specific access pattern, not an inherent GSI-vs-LSI speed advantage.",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What is provisioned concurrency in Lambda used for?",
        "options": [
            "Keeping a specified number of execution environments initialized and ready to respond immediately",
            "Reducing the amount of memory allocated to a function",
            "Increasing a function's maximum allowed timeout",
            "Eliminating cold starts entirely with no additional cost",
        ],
        "correct_answer": "Keeping a specified number of execution environments initialized and ready to respond immediately",
        "explanation_correct": "Provisioned concurrency pre-warms a set number of execution environments, so invocations against them skip the cold-start initialization delay.",
        "explanation_incorrect": {
            "Reducing the amount of memory allocated to a function": "Wrong — memory allocation is a separate function configuration setting, unrelated to provisioned concurrency.",
            "Increasing a function's maximum allowed timeout": "Wrong — timeout is a separate setting; provisioned concurrency doesn't affect it.",
            "Eliminating cold starts entirely with no additional cost": "Wrong — provisioned concurrency reduces cold starts for the provisioned capacity specifically, but it does have an additional cost (you pay for the pre-warmed environments even when idle).",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What distinguishes a VPC interface endpoint (built on AWS PrivateLink) from a gateway endpoint?",
        "options": [
            "Interface endpoints use an ENI with a private IP and support a broader range of services, including many third-party ones, while gateway endpoints are limited to S3 and DynamoDB",
            "They are functionally identical in every respect",
            "Gateway endpoints support a broader range of services than interface endpoints",
            "PrivateLink is exclusively used for VPN connections",
        ],
        "correct_answer": "Interface endpoints use an ENI with a private IP and support a broader range of services, including many third-party ones, while gateway endpoints are limited to S3 and DynamoDB",
        "explanation_correct": "Interface endpoints (PrivateLink) place an elastic network interface with a private IP in your subnet and can reach many AWS and third-party services, while gateway endpoints are a routing-table-based mechanism limited specifically to S3 and DynamoDB.",
        "explanation_incorrect": {
            "They are functionally identical in every respect": "Wrong — their underlying mechanisms (ENI-based vs route-table-based) and supported service scopes differ significantly.",
            "Gateway endpoints support a broader range of services than interface endpoints": "Wrong — this is backwards; gateway endpoints are limited to just S3 and DynamoDB, while interface endpoints support many more services.",
            "PrivateLink is exclusively used for VPN connections": "Wrong — PrivateLink is about private service connectivity within AWS's network, unrelated to VPN tunnels to on-premises networks.",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the 'pilot light' disaster recovery strategy?",
        "options": [
            "A minimal version of critical infrastructure is always running in a secondary region, ready to be scaled up during a disaster",
            "No infrastructure exists in the secondary region until a disaster actually occurs",
            "Full production infrastructure runs simultaneously and identically in both regions at all times",
            "Backups are taken regularly but never restored or tested",
        ],
        "correct_answer": "A minimal version of critical infrastructure is always running in a secondary region, ready to be scaled up during a disaster",
        "explanation_correct": "Pilot light keeps just the core, hard-to-quickly-recreate components (like a replicated database) running in the DR region, with the rest scaled up only when a disaster actually triggers failover.",
        "explanation_incorrect": {
            "No infrastructure exists in the secondary region until a disaster actually occurs": "Wrong — that describes a 'backup and restore' strategy, a slower/cheaper approach than pilot light, which does keep something minimal running continuously.",
            "Full production infrastructure runs simultaneously and identically in both regions at all times": "Wrong — that describes a 'multi-site active/active' strategy, a more expensive approach than pilot light.",
            "Backups are taken regularly but never restored or tested": "Wrong — untested backups aren't a defined DR strategy at all, and pilot light specifically involves running (not just backed-up) minimal infrastructure.",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What does AWS KMS envelope encryption involve?",
        "options": [
            "Encrypting data with a data key, then encrypting that data key itself with a KMS master key",
            "Encrypting data twice in a row using the exact same key",
            "Storing encryption keys in plaintext for faster access",
            "A technique that applies only to S3 object encryption",
        ],
        "correct_answer": "Encrypting data with a data key, then encrypting that data key itself with a KMS master key",
        "explanation_correct": "Envelope encryption uses a locally generated data key to encrypt the actual data (efficient for large payloads), then protects that data key by encrypting it with a KMS master key, so only the small encrypted data key needs to be sent to KMS.",
        "explanation_incorrect": {
            "Encrypting data twice in a row using the exact same key": "Wrong — envelope encryption uses two distinct keys (a data key and a master key), not the same key applied twice.",
            "Storing encryption keys in plaintext for faster access": "Wrong — the entire point of envelope encryption is to avoid ever storing the data key in plaintext at rest.",
            "A technique that applies only to S3 object encryption": "Wrong — envelope encryption is a general KMS pattern used across many services and custom applications, not limited to S3.",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of a Lambda function's reserved concurrency setting?",
        "options": [
            "Guarantees a specific number of concurrent executions are available for that function while also capping its maximum, preventing it from consuming the account's entire concurrency pool",
            "Increases the memory allocation available to the function",
            "Automatically enables provisioned concurrency for the function",
            "Disables the function from being invoked",
        ],
        "correct_answer": "Guarantees a specific number of concurrent executions are available for that function while also capping its maximum, preventing it from consuming the account's entire concurrency pool",
        "explanation_correct": "Reserved concurrency sets aside a portion of the account-wide concurrency limit exclusively for that function, both guaranteeing it capacity and preventing it from scaling beyond that reserved amount.",
        "explanation_incorrect": {
            "Increases the memory allocation available to the function": "Wrong — memory is a separate configuration setting, unrelated to reserved concurrency.",
            "Automatically enables provisioned concurrency for the function": "Wrong — reserved and provisioned concurrency are related but distinct features; reserving concurrency doesn't automatically pre-warm environments.",
            "Disables the function from being invoked": "Wrong — reserved concurrency limits and guarantees capacity, it doesn't disable invocation (unless set to zero, which is a specific edge case, not the general purpose).",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "In a blue/green deployment with CodeDeploy, what typically happens to the original (blue) environment after a successful deployment to the new (green) environment?",
        "options": [
            "It's typically kept running briefly (for potential rollback) before being terminated or deregistered",
            "It's immediately and permanently deleted with no rollback option at all",
            "It continues serving all production traffic indefinitely, alongside green",
            "It's automatically merged together with the green environment",
        ],
        "correct_answer": "It's typically kept running briefly (for potential rollback) before being terminated or deregistered",
        "explanation_correct": "A common blue/green pattern keeps the old (blue) environment available for a defined period after cutover, so traffic can be quickly reverted if the new (green) environment has problems, before eventually decommissioning it.",
        "explanation_incorrect": {
            "It's immediately and permanently deleted with no rollback option at all": "Wrong — immediate, irreversible deletion would defeat one of the main safety benefits of blue/green deployment (a quick rollback path).",
            "It continues serving all production traffic indefinitely, alongside green": "Wrong — after cutover, traffic is shifted to green; blue typically isn't left serving production traffic indefinitely alongside it.",
            "It's automatically merged together with the green environment": "Wrong — blue and green are kept as separate, distinct environments; they aren't merged into one.",
        },
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of AWS Global Accelerator?",
        "options": [
            "Improves availability and performance for global applications using the AWS global network and static anycast IP addresses",
            "Provides a content delivery network for caching static assets",
            "Manages DNS failover exclusively, with no networking-layer improvements",
            "Encrypts traffic automatically as it moves between AWS regions",
        ],
        "correct_answer": "Improves availability and performance for global applications using the AWS global network and static anycast IP addresses",
        "explanation_correct": "Global Accelerator routes user traffic onto AWS's global network backbone as early as possible via static anycast IPs, improving performance and enabling fast failover across regions/endpoints.",
        "explanation_incorrect": {
            "Provides a content delivery network for caching static assets": "Wrong — that's the role of CloudFront; Global Accelerator focuses on network path optimization and endpoint failover, not content caching.",
            "Manages DNS failover exclusively, with no networking-layer improvements": "Wrong — Global Accelerator operates at the network layer using anycast IPs, going beyond what DNS-based failover (like Route 53) alone provides.",
            "Encrypts traffic automatically as it moves between AWS regions": "Wrong — encryption isn't Global Accelerator's core purpose; it's focused on routing performance and availability.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "In IAM policy evaluation, an explicit ____ always overrides any Allow statement, regardless of which policy it comes from.",
        "options": None,
        "correct_answer": "Deny",
        "explanation_correct": "An explicit Deny takes precedence over any Allow in AWS's IAM policy evaluation logic.",
        "explanation_incorrect": "The blank should be filled with the statement effect that always wins: Deny.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "AWS Organizations policies that define the maximum permission boundary for accounts, without granting permissions themselves, are commonly known by their acronym, ____.",
        "options": None,
        "correct_answer": "SCP",
        "explanation_correct": "SCPs (Service Control Policies) set the outer permissions boundary for accounts within an organization.",
        "explanation_incorrect": "The blank should be filled with the acronym for these organization-wide boundary policies: SCP.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A DynamoDB ____ Secondary Index can use a different partition key than the base table, unlike a Local Secondary Index, which shares the base table's partition key.",
        "options": None,
        "correct_answer": "Global",
        "explanation_correct": "A Global Secondary Index (GSI) can be defined with its own partition key, independent of the base table's.",
        "explanation_incorrect": "The blank should be filled with the type of index that allows a different partition key: Global.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ concurrency in Lambda keeps a specified number of execution environments initialized and ready to respond immediately, avoiding cold starts.",
        "options": None,
        "correct_answer": "Provisioned",
        "explanation_correct": "Provisioned concurrency pre-warms execution environments so invocations skip cold-start initialization.",
        "explanation_incorrect": "The blank should be filled with the name of this Lambda concurrency feature: Provisioned.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The disaster recovery strategy where a minimal version of critical infrastructure runs continuously in a secondary region, ready to scale up during a disaster, is called ____ light.",
        "options": None,
        "correct_answer": "pilot",
        "explanation_correct": "Pilot light DR keeps only the essential, hard-to-quickly-recreate components running continuously in the DR region.",
        "explanation_incorrect": "The blank should be filled with the first word of this DR strategy's name: pilot.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "KMS ____ encryption involves encrypting data with a data key, then encrypting that data key itself with a KMS master key.",
        "options": None,
        "correct_answer": "envelope",
        "explanation_correct": "Envelope encryption uses a data key for the bulk data and a master key to protect that data key.",
        "explanation_incorrect": "The blank should be filled with the term for this two-layer encryption pattern: envelope.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Lambda ____ concurrency guarantees a specific number of concurrent executions are available for a function while also capping its maximum.",
        "options": None,
        "correct_answer": "reserved",
        "explanation_correct": "Reserved concurrency sets aside part of the account's concurrency pool exclusively for a given function, and caps that function's maximum concurrency.",
        "explanation_incorrect": "The blank should be filled with the name of this Lambda concurrency feature: reserved.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "AWS ____ Accelerator improves availability and performance for global applications using the AWS global network and static anycast IP addresses.",
        "options": None,
        "correct_answer": "Global",
        "explanation_correct": "Global Accelerator routes traffic over AWS's backbone network using static anycast IPs for improved performance and failover.",
        "explanation_incorrect": "The blank should be filled with the name of this AWS networking service: Global.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "VPC interface endpoints are built on AWS ____, which uses an ENI with a private IP to connect to a broad range of supported services, including many third-party ones.",
        "options": None,
        "correct_answer": "PrivateLink",
        "explanation_correct": "PrivateLink is the underlying technology behind interface endpoints, providing private connectivity to supported services.",
        "explanation_incorrect": "The blank should be filled with the name of this underlying AWS technology: PrivateLink.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Aurora ____ Database allows a primary cluster in one region to replicate to secondary clusters in other regions with low latency, for disaster recovery and read scaling.",
        "options": None,
        "correct_answer": "Global",
        "explanation_correct": "Aurora Global Database replicates data across regions with low latency, supporting fast disaster recovery and cross-region read scaling.",
        "explanation_incorrect": "The blank should be filled with the name of this Aurora feature: Global.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up cross-account IAM role assumption.",
        "options": ["The source account principal assumes the role to gain access in the target account", "In the target account, create a role with a trust policy allowing the source account", "In the source account, grant a user/role permission to call sts:AssumeRole on that target role's ARN"],
        "correct_answer": '["In the target account, create a role with a trust policy allowing the source account", "In the source account, grant a user/role permission to call sts:AssumeRole on that target role\'s ARN", "The source account principal assumes the role to gain access in the target account"]',
        "explanation_correct": "Correct — the target role and its trust policy must exist before source-account permissions can reference it, and both sides must be configured before assumption can actually succeed.",
        "explanation_incorrect": "The target role must exist (with its trust policy) before the source account can be granted permission to assume it, and both configurations must be in place before assumption can succeed.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for connecting multiple VPCs using a Transit Gateway.",
        "options": ["Update each VPC's route tables to route inter-VPC traffic through the Transit Gateway", "Create a Transit Gateway", "Attach each VPC to the Transit Gateway"],
        "correct_answer": '["Create a Transit Gateway", "Attach each VPC to the Transit Gateway", "Update each VPC\'s route tables to route inter-VPC traffic through the Transit Gateway"]',
        "explanation_correct": "Correct — the Transit Gateway must exist before VPCs can attach to it, and attachments must exist before route tables can meaningfully route traffic through them.",
        "explanation_incorrect": "The Transit Gateway must be created before VPCs can attach to it, and attachments must exist before route tables can be updated to use them.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order describing a pilot light disaster recovery response.",
        "options": ["Redirect traffic (e.g. via DNS) to the now-scaled secondary region", "Maintain a minimal set of critical infrastructure running in the secondary region", "When a disaster occurs in the primary region, scale up the secondary region's infrastructure"],
        "correct_answer": '["Maintain a minimal set of critical infrastructure running in the secondary region", "When a disaster occurs in the primary region, scale up the secondary region\'s infrastructure", "Redirect traffic (e.g. via DNS) to the now-scaled secondary region"]',
        "explanation_correct": "Correct — the minimal infrastructure must be running continuously beforehand, scaling up happens only in response to a disaster, and traffic redirection follows once the secondary region is ready.",
        "explanation_incorrect": "The minimal pilot-light infrastructure runs continuously before any disaster, scaling occurs specifically in response to a detected disaster, and traffic is redirected only once the region is scaled and ready.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up Lambda provisioned concurrency.",
        "options": ["Lambda pre-initializes the specified number of execution environments", "Publish a specific version or alias of the function", "Configure provisioned concurrency for that version/alias"],
        "correct_answer": '["Publish a specific version or alias of the function", "Configure provisioned concurrency for that version/alias", "Lambda pre-initializes the specified number of execution environments"]',
        "explanation_correct": "Correct — a version/alias must exist before provisioned concurrency can be configured for it, and pre-initialization happens as a result of that configuration.",
        "explanation_incorrect": "A published version or alias must exist before provisioned concurrency can target it, and environment pre-initialization occurs only after that configuration is applied.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for a CodeDeploy blue/green deployment.",
        "options": ["Shift traffic from blue to green, then terminate or retain blue for rollback", "Deploy the new application version to a separate (green) environment", "Run validation/health checks against the green environment"],
        "correct_answer": '["Deploy the new application version to a separate (green) environment", "Run validation/health checks against the green environment", "Shift traffic from blue to green, then terminate or retain blue for rollback"]',
        "explanation_correct": "Correct — the green environment must be deployed before it can be validated, and traffic is only shifted after validation confirms it's healthy.",
        "explanation_incorrect": "The green environment must be deployed before it can be health-checked, and traffic shifting (the riskiest step) should only happen after validation succeeds.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up DynamoDB Streams with a Lambda trigger.",
        "options": ["Configure the stream as an event source for the Lambda function", "Enable DynamoDB Streams on the table", "Create a Lambda function to process stream records"],
        "correct_answer": '["Enable DynamoDB Streams on the table", "Create a Lambda function to process stream records", "Configure the stream as an event source for the Lambda function"]',
        "explanation_correct": "Correct — the stream must exist before it can be used as an event source, and the Lambda function must exist before it can be wired up to consume that stream.",
        "explanation_incorrect": "Streams must be enabled before there's anything to trigger from, and the Lambda function must exist before the event source mapping can be configured to invoke it.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order describing KMS envelope encryption of a large object.",
        "options": ["Store the encrypted data key alongside the encrypted data (discarding the plaintext data key)", "Request a data key from KMS", "Use the data key to encrypt the actual data locally"],
        "correct_answer": '["Request a data key from KMS", "Use the data key to encrypt the actual data locally", "Store the encrypted data key alongside the encrypted data (discarding the plaintext data key)"]',
        "explanation_correct": "Correct — the data key must be obtained before it can be used to encrypt data, and storing the encrypted key alongside the encrypted data happens after both are produced.",
        "explanation_incorrect": "A data key must be requested before it can be used for local encryption, and storage of the encrypted key happens only after the encryption itself has taken place.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up cross-account S3 replication.",
        "options": ["Configure a replication rule on the source bucket referencing the destination bucket and role", "Create an IAM role in the source account with permission to replicate to the destination bucket", "Add a bucket policy on the destination bucket granting the source account replication permissions"],
        "correct_answer": '["Create an IAM role in the source account with permission to replicate to the destination bucket", "Add a bucket policy on the destination bucket granting the source account replication permissions", "Configure a replication rule on the source bucket referencing the destination bucket and role"]',
        "explanation_correct": "Correct — the IAM role and destination bucket policy must both be in place before the replication rule (which relies on both) can be configured.",
        "explanation_incorrect": "The IAM role and destination bucket permissions must exist before a replication rule referencing them can be configured on the source bucket.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order describing Auto Scaling lifecycle hook usage.",
        "options": ["A custom action (e.g. running configuration scripts) completes, then the hook is completed to let the instance proceed", "Define a lifecycle hook on the Auto Scaling group (e.g. for instance launch)", "An instance enters a wait state during launch/termination"],
        "correct_answer": '["Define a lifecycle hook on the Auto Scaling group (e.g. for instance launch)", "An instance enters a wait state during launch/termination", "A custom action (e.g. running configuration scripts) completes, then the hook is completed to let the instance proceed"]',
        "explanation_correct": "Correct — the hook must be defined before it can pause any instance, the wait state occurs as a result of that hook triggering, and completion of the custom action is what releases the instance from the wait state.",
        "explanation_incorrect": "The lifecycle hook must be defined before it can cause an instance to enter a wait state, and the custom action must run and complete before the hook is marked complete to release the instance.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for deploying CloudFormation nested stacks.",
        "options": ["Deploy the parent stack, which provisions all nested child stacks", "Create child stack templates for reusable components", "Reference the child templates from a parent stack using AWS::CloudFormation::Stack resources"],
        "correct_answer": '["Create child stack templates for reusable components", "Reference the child templates from a parent stack using AWS::CloudFormation::Stack resources", "Deploy the parent stack, which provisions all nested child stacks"]',
        "explanation_correct": "Correct — the child templates must exist before the parent template can reference them, and deployment (which triggers provisioning of the nested stacks) happens last.",
        "explanation_incorrect": "Child templates must exist before a parent stack can reference them as nested stacks, and deployment of the parent (which provisions the children) happens only after that reference is in place.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up Route 53 failover routing.",
        "options": ["Associate a health check with the primary record so Route 53 can detect failures and fail over", "Create a primary record set pointing to the primary resource", "Create a secondary record set pointing to the backup resource, marked as failover"],
        "correct_answer": '["Create a primary record set pointing to the primary resource", "Create a secondary record set pointing to the backup resource, marked as failover", "Associate a health check with the primary record so Route 53 can detect failures and fail over"]',
        "explanation_correct": "Correct — both record sets should exist before the health check ties them together for failover behavior, since the health check is what determines when to switch between them.",
        "explanation_incorrect": "Both the primary and secondary records should be defined before a health check is attached to coordinate failover between them.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up X-Ray tracing.",
        "options": ["View the service map and trace details in the X-Ray console", "Instrument the application with the X-Ray SDK", "The application sends trace segments to the X-Ray daemon/service"],
        "correct_answer": '["Instrument the application with the X-Ray SDK", "The application sends trace segments to the X-Ray daemon/service", "View the service map and trace details in the X-Ray console"]',
        "explanation_correct": "Correct — the application must be instrumented before it can generate trace data, and trace data must be sent to X-Ray before it can be viewed in the console.",
        "explanation_incorrect": "Instrumentation must happen before any trace segments can be generated, and those segments must reach X-Ray before there's anything to view in the console.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up GuardDuty threat detection.",
        "options": ["Review and respond to findings in the GuardDuty console", "Enable GuardDuty for the account/organization", "GuardDuty analyzes VPC Flow Logs, DNS logs, and CloudTrail events for threats"],
        "correct_answer": '["Enable GuardDuty for the account/organization", "GuardDuty analyzes VPC Flow Logs, DNS logs, and CloudTrail events for threats", "Review and respond to findings in the GuardDuty console"]',
        "explanation_correct": "Correct — GuardDuty must be enabled before it starts analyzing data sources, and findings can only be reviewed once analysis has actually produced results.",
        "explanation_incorrect": "GuardDuty must be enabled before it begins analyzing any logs, and findings only exist to review after that analysis has run.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up WAF protection for an application.",
        "options": ["Associate the Web ACL with a CloudFront distribution or Application Load Balancer", "Create a Web ACL", "Add rules to the Web ACL (e.g. rate limiting, SQL injection protection)"],
        "correct_answer": '["Create a Web ACL", "Add rules to the Web ACL (e.g. rate limiting, SQL injection protection)", "Associate the Web ACL with a CloudFront distribution or Application Load Balancer"]',
        "explanation_correct": "Correct — the Web ACL must exist before rules can be added to it, and it's typically configured with rules before being associated with the resource it protects.",
        "explanation_incorrect": "The Web ACL must be created before rules can be added to it, and it should be configured with rules before (or as part of) being associated with the protected resource.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for triggering a Lambda function from an EventBridge rule.",
        "options": ["Matching events automatically invoke the target Lambda function", "Create an EventBridge rule defining a matching event pattern", "Set a Lambda function as the rule's target"],
        "correct_answer": '["Create an EventBridge rule defining a matching event pattern", "Set a Lambda function as the rule\'s target", "Matching events automatically invoke the target Lambda function"]',
        "explanation_correct": "Correct — the rule must exist before a target can be assigned to it, and invocation only happens once both the rule and its target are configured.",
        "explanation_incorrect": "The EventBridge rule must exist before a target can be set for it, and automatic invocation only occurs after both the rule and target are fully configured.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up an Aurora Global Database.",
        "options": ["Data is replicated from the primary to secondary regions with low latency", "Create an Aurora cluster in the primary region", "Add one or more secondary regions to create a global database"],
        "correct_answer": '["Create an Aurora cluster in the primary region", "Add one or more secondary regions to create a global database", "Data is replicated from the primary to secondary regions with low latency"]',
        "explanation_correct": "Correct — the primary cluster must exist before secondary regions can be added to it, and replication only occurs once the global database configuration is in place.",
        "explanation_incorrect": "The primary Aurora cluster must exist before secondary regions can be added, and cross-region replication only begins once the global database is configured.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for accelerating DynamoDB reads with DAX.",
        "options": ["Read requests are served from the DAX cache when possible, falling back to DynamoDB on a cache miss", "Create a DAX cluster in front of the DynamoDB table", "Update the application to use the DAX client instead of calling DynamoDB directly"],
        "correct_answer": '["Create a DAX cluster in front of the DynamoDB table", "Update the application to use the DAX client instead of calling DynamoDB directly", "Read requests are served from the DAX cache when possible, falling back to DynamoDB on a cache miss"]',
        "explanation_correct": "Correct — the DAX cluster must exist before the application can be pointed at it, and cache-serving behavior only takes effect once the application is actually using the DAX client.",
        "explanation_incorrect": "The DAX cluster must be created before the application can be configured to use it, and cache behavior only applies once the application is routed through DAX.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up a CloudFormation custom resource.",
        "options": ["CloudFormation invokes the Lambda function during stack operations to manage the custom resource", "Write a Lambda function to handle Create/Update/Delete lifecycle events", "Define a custom resource in the CloudFormation template referencing that Lambda function"],
        "correct_answer": '["Write a Lambda function to handle Create/Update/Delete lifecycle events", "Define a custom resource in the CloudFormation template referencing that Lambda function", "CloudFormation invokes the Lambda function during stack operations to manage the custom resource"]',
        "explanation_correct": "Correct — the Lambda function must exist before the template can reference it, and CloudFormation only invokes it once the custom resource is defined against it.",
        "explanation_incorrect": "The Lambda function must exist before it can be referenced by a custom resource, and invocation only happens once that custom resource is defined in the template.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for detecting CloudFormation stack drift.",
        "options": ["Review the drift detection results to identify manually modified resources", "Run a drift detection operation on the stack", "CloudFormation compares actual resource configurations to the stack's template"],
        "correct_answer": '["Run a drift detection operation on the stack", "CloudFormation compares actual resource configurations to the stack\'s template", "Review the drift detection results to identify manually modified resources"]',
        "explanation_correct": "Correct — drift detection must be initiated before the comparison happens, and results can only be reviewed once that comparison has completed.",
        "explanation_incorrect": "Drift detection must be started before CloudFormation performs the comparison, and reviewing results only makes sense after that comparison has finished.",
    },
    {
        "topic": "AWS", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up AWS Direct Connect for a hybrid network.",
        "options": ["Traffic between the on-premises network and AWS flows over the dedicated connection", "Provision a Direct Connect connection at a supported location", "Create a virtual interface (VIF) associating the connection with a VPC or AWS service"],
        "correct_answer": '["Provision a Direct Connect connection at a supported location", "Create a virtual interface (VIF) associating the connection with a VPC or AWS service", "Traffic between the on-premises network and AWS flows over the dedicated connection"]',
        "explanation_correct": "Correct — the physical connection must be provisioned before a virtual interface can be created on it, and traffic only flows once that virtual interface is configured.",
        "explanation_incorrect": "The Direct Connect connection must be provisioned before a virtual interface can be layered on top of it, and traffic only begins flowing once that VIF is configured.",
    },
]
