"""
AWS - Medium batch, 50 questions total.
Distribution: even split — 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.

Schema matches aws_easy_questions.py — see that file's header for full field notes.
Medium content covers VPC networking (NAT gateways, peering, VPC endpoints), IAM policy
documents, DynamoDB, Secrets Manager/Parameter Store, ECS/Fargate, CloudFormation, STS,
API Gateway + Lambda, RDS Multi-AZ, and ECR.
"""

AWS_MEDIUM_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to create a DynamoDB table named 'Users' with a partition key 'UserId' of type String, using on-demand (pay-per-request) billing.",
        "correct_answer": "aws dynamodb create-table --table-name Users --attribute-definitions AttributeName=UserId,AttributeType=S --key-schema AttributeName=UserId,KeyType=HASH --billing-mode PAY_PER_REQUEST",
        "explanation_correct": "Correct — this defines UserId as a String partition key (HASH) and sets billing-mode to PAY_PER_REQUEST for on-demand capacity.",
        "explanation_incorrect": "A correct solution must create the Users table with UserId as its partition key of type String, using on-demand billing mode.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to store a value 'secret123' as a SecureString parameter named '/app/db_password' in Systems Manager Parameter Store.",
        "correct_answer": "aws ssm put-parameter --name \"/app/db_password\" --value \"secret123\" --type SecureString",
        "explanation_correct": "Correct — `aws ssm put-parameter` with --type SecureString stores the value encrypted at the given parameter name.",
        "explanation_incorrect": "A correct solution must store the value as a SecureString (encrypted) type specifically, not a plain String parameter, at the given name.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to create a CloudFormation stack named 'my-stack' using a local template file named template.yaml.",
        "correct_answer": "aws cloudformation create-stack --stack-name my-stack --template-body file://template.yaml",
        "explanation_correct": "Correct — `aws cloudformation create-stack` with --template-body file:// reads the local template file and creates a stack from it.",
        "explanation_incorrect": "A correct solution must create a stack with the given name, using the local template.yaml file as its template.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to assume the IAM role with ARN arn:aws:iam::123456789012:role/MyRole, using session name 'my-session'.",
        "correct_answer": "aws sts assume-role --role-arn arn:aws:iam::123456789012:role/MyRole --role-session-name my-session",
        "explanation_correct": "Correct — `aws sts assume-role` with the role ARN and a session name returns temporary credentials for that role.",
        "explanation_incorrect": "A correct solution must call sts assume-role with the exact role ARN and session name given.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write an IAM policy JSON document that allows the s3:GetObject action on all objects in a bucket named 'my-bucket'.",
        "correct_answer": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": \"s3:GetObject\",\n      \"Resource\": \"arn:aws:s3:::my-bucket/*\"\n    }\n  ]\n}",
        "explanation_correct": "Correct — the Allow statement grants s3:GetObject specifically on the object-level ARN pattern (bucket/*), which correctly covers all objects within the bucket.",
        "explanation_incorrect": "A correct solution must use a valid IAM policy document structure (Version, Statement, Effect, Action, Resource) and target the object ARN pattern (bucket/*), not just the bucket ARN itself.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to apply an S3 bucket lifecycle configuration (already defined in a local file named lifecycle.json) to a bucket named 'my-bucket'.",
        "correct_answer": "aws s3api put-bucket-lifecycle-configuration --bucket my-bucket --lifecycle-configuration file://lifecycle.json",
        "explanation_correct": "Correct — `aws s3api put-bucket-lifecycle-configuration` applies the given lifecycle rules to the specified bucket.",
        "explanation_incorrect": "A correct solution must apply the lifecycle configuration from the local file to the specified bucket, typically using put-bucket-lifecycle-configuration.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to update the environment variables of a Lambda function named 'my-function', setting ENV to 'production'.",
        "correct_answer": "aws lambda update-function-configuration --function-name my-function --environment \"Variables={ENV=production}\"",
        "explanation_correct": "Correct — `aws lambda update-function-configuration` with the --environment flag updates the function's environment variables.",
        "explanation_incorrect": "A correct solution must update the specified function's environment variables to include ENV=production.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to create an SQS queue named 'my-queue' that includes a redrive policy attribute (assume you have a JSON string for the redrive policy ready to pass via --attributes).",
        "correct_answer": "aws sqs create-queue --queue-name my-queue --attributes RedrivePolicy='{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:123456789012:my-dlq\",\"maxReceiveCount\":\"5\"}'",
        "explanation_correct": "Correct — `aws sqs create-queue` with a RedrivePolicy attribute configures the queue to forward failed messages to the specified dead-letter queue after maxReceiveCount attempts.",
        "explanation_incorrect": "A correct solution must create the queue and configure a RedrivePolicy attribute pointing to a dead-letter queue ARN with a maxReceiveCount.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to register a new ECS task definition from a local JSON file named task-def.json.",
        "correct_answer": "aws ecs register-task-definition --cli-input-json file://task-def.json",
        "explanation_correct": "Correct — `aws ecs register-task-definition` with --cli-input-json reads the task definition from the given local file.",
        "explanation_incorrect": "A correct solution must register a new task definition using the contents of the local task-def.json file.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "coding",
        "prompt": "Write the AWS CLI command to create a read replica named 'mydb-replica' of an existing RDS instance named 'mydb'.",
        "correct_answer": "aws rds create-db-instance-read-replica --db-instance-identifier mydb-replica --source-db-instance-identifier mydb",
        "explanation_correct": "Correct — `aws rds create-db-instance-read-replica` creates a new read replica from the specified source instance.",
        "explanation_incorrect": "A correct solution must create a read replica with the given name, sourced from the specified existing RDS instance.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a NAT Gateway in a VPC?",
        "options": [
            "Allows instances in a private subnet to initiate outbound internet connections while remaining unreachable from the internet",
            "Provides load balancing across EC2 instances",
            "Encrypts traffic passing between subnets",
            "Manages DNS resolution within a VPC",
        ],
        "correct_answer": "Allows instances in a private subnet to initiate outbound internet connections while remaining unreachable from the internet",
        "explanation_correct": "A NAT Gateway sits in a public subnet and translates outbound traffic from private-subnet instances, letting them reach the internet without exposing them to inbound connections.",
        "explanation_incorrect": {
            "Provides load balancing across EC2 instances": "Wrong — that's the role of an ELB, unrelated to NAT Gateway's purpose.",
            "Encrypts traffic passing between subnets": "Wrong — NAT Gateways handle address translation for internet access, not encryption.",
            "Manages DNS resolution within a VPC": "Wrong — that's the role of Route 53 Resolver, unrelated to NAT Gateway.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What is a key difference between a Security Group and a Network ACL (NACL)?",
        "options": [
            "Security groups are stateful and operate at the instance level; NACLs are stateless and operate at the subnet level",
            "They are functionally identical, just with different names",
            "NACLs operate at the instance level and security groups at the subnet level",
            "Security groups only control outbound traffic, never inbound",
        ],
        "correct_answer": "Security groups are stateful and operate at the instance level; NACLs are stateless and operate at the subnet level",
        "explanation_correct": "Security groups automatically allow return traffic for an established connection (stateful) and attach to instances/ENIs, while NACLs require explicit rules for both directions (stateless) and apply to entire subnets.",
        "explanation_incorrect": {
            "They are functionally identical, just with different names": "Wrong — their statefulness and scope (instance vs subnet) are meaningfully different.",
            "NACLs operate at the instance level and security groups at the subnet level": "Wrong — this reverses the actual scopes; security groups are instance-level and NACLs are subnet-level.",
            "Security groups only control outbound traffic, never inbound": "Wrong — security groups control both inbound and outbound traffic via separate rule sets.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What does a target tracking scaling policy do in Auto Scaling?",
        "options": [
            "Automatically adjusts capacity to keep a specified metric (like average CPU utilization) near a target value",
            "Manually scales resources according to a fixed schedule with no automation",
            "Only allows scaling down, never scaling up",
            "Requires manual approval before every scaling action",
        ],
        "correct_answer": "Automatically adjusts capacity to keep a specified metric (like average CPU utilization) near a target value",
        "explanation_correct": "Target tracking policies work like a thermostat — Auto Scaling continuously adjusts the number of instances to keep the chosen metric close to the target you set.",
        "explanation_incorrect": {
            "Manually scales resources according to a fixed schedule with no automation": "Wrong — that describes scheduled scaling, a different Auto Scaling feature, not target tracking.",
            "Only allows scaling down, never scaling up": "Wrong — target tracking scales in both directions as needed to maintain the target.",
            "Requires manual approval before every scaling action": "Wrong — target tracking scaling is fully automated, with no manual approval step by default.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What is a primary benefit of using DynamoDB over RDS for certain workloads?",
        "options": [
            "DynamoDB offers seamless horizontal scaling and single-digit millisecond latency for key-value/document workloads",
            "DynamoDB is always cheaper than RDS regardless of workload",
            "DynamoDB natively supports complex multi-table SQL joins",
            "DynamoDB requires no data modeling at all",
        ],
        "correct_answer": "DynamoDB offers seamless horizontal scaling and single-digit millisecond latency for key-value/document workloads",
        "explanation_correct": "DynamoDB is a managed NoSQL database designed to scale horizontally with consistently low latency, well suited to key-value and document access patterns.",
        "explanation_incorrect": {
            "DynamoDB is always cheaper than RDS regardless of workload": "Wrong — cost depends heavily on the specific workload and access patterns; it isn't universally cheaper.",
            "DynamoDB natively supports complex multi-table SQL joins": "Wrong — DynamoDB is a NoSQL database and doesn't support relational joins the way RDS does.",
            "DynamoDB requires no data modeling at all": "Wrong — DynamoDB actually requires careful upfront data modeling (especially around access patterns and key design), often more deliberate than a relational schema.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What does AWS KMS provide?",
        "options": [
            "Managed creation and control of encryption keys used to protect data",
            "A content delivery network for static assets",
            "A container orchestration service",
            "A database schema migration tool",
        ],
        "correct_answer": "Managed creation and control of encryption keys used to protect data",
        "explanation_correct": "KMS (Key Management Service) lets you create, manage, and control access to encryption keys used across many AWS services and your own applications.",
        "explanation_incorrect": {
            "A content delivery network for static assets": "Wrong — that's the role of CloudFront, unrelated to KMS.",
            "A container orchestration service": "Wrong — that's the role of ECS/EKS, unrelated to KMS.",
            "A database schema migration tool": "Wrong — that's closer to the role of the Database Migration Service (DMS), unrelated to KMS.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a target group in an Application Load Balancer?",
        "options": [
            "Defines a set of targets (like EC2 instances) that receive traffic, along with their health check settings",
            "Defines IAM permissions for the load balancer itself",
            "Stores SSL/TLS certificates used by the load balancer",
            "Configures DNS routing for the load balancer's domain",
        ],
        "correct_answer": "Defines a set of targets (like EC2 instances) that receive traffic, along with their health check settings",
        "explanation_correct": "A target group groups together the backend resources (EC2 instances, IPs, or Lambda functions) that a load balancer routes traffic to, and defines how their health is checked.",
        "explanation_incorrect": {
            "Defines IAM permissions for the load balancer itself": "Wrong — IAM permissions are managed separately via IAM roles/policies, not target groups.",
            "Stores SSL/TLS certificates used by the load balancer": "Wrong — certificates are managed via listeners and ACM, not target groups.",
            "Configures DNS routing for the load balancer's domain": "Wrong — that's the role of Route 53, unrelated to target groups.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What is Amazon CloudFront primarily used for?",
        "options": [
            "A content delivery network (CDN) that caches and delivers content from edge locations closer to users",
            "A managed relational database service",
            "A container image registry",
            "An identity provider for federated login",
        ],
        "correct_answer": "A content delivery network (CDN) that caches and delivers content from edge locations closer to users",
        "explanation_correct": "CloudFront caches content at globally distributed edge locations, reducing latency by serving users from a location near them rather than the origin server directly.",
        "explanation_incorrect": {
            "A managed relational database service": "Wrong — that's the role of RDS, unrelated to CloudFront.",
            "A container image registry": "Wrong — that's the role of ECR, unrelated to CloudFront.",
            "An identity provider for federated login": "Wrong — that's closer to the role of Cognito, unrelated to CloudFront.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of an SQS dead-letter queue?",
        "options": [
            "Captures messages that repeatedly fail to be processed successfully, for later inspection",
            "Automatically and permanently deletes failed messages",
            "Encrypts messages at rest in the primary queue",
            "Increases the overall throughput of the primary queue",
        ],
        "correct_answer": "Captures messages that repeatedly fail to be processed successfully, for later inspection",
        "explanation_correct": "A dead-letter queue receives messages that exceed a defined number of processing attempts, preventing them from being retried indefinitely while preserving them for debugging.",
        "explanation_incorrect": {
            "Automatically and permanently deletes failed messages": "Wrong — the whole point of a DLQ is to preserve failed messages, not delete them outright.",
            "Encrypts messages at rest in the primary queue": "Wrong — encryption is a separate SQS configuration (via KMS), unrelated to dead-letter queues.",
            "Increases the overall throughput of the primary queue": "Wrong — a DLQ doesn't affect the primary queue's throughput; it's a destination for problem messages.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What does AWS Secrets Manager provide beyond what Systems Manager Parameter Store offers?",
        "options": [
            "Automatic secret rotation capabilities, in addition to secure storage",
            "It's functionally identical to Parameter Store, just under a different name",
            "Free, unlimited storage for any number of secrets",
            "It can only be used to store database passwords, nothing else",
        ],
        "correct_answer": "Automatic secret rotation capabilities, in addition to secure storage",
        "explanation_correct": "Secrets Manager includes built-in support for automatically rotating credentials (like database passwords) on a schedule, a feature Parameter Store doesn't provide natively.",
        "explanation_incorrect": {
            "It's functionally identical to Parameter Store, just under a different name": "Wrong — Secrets Manager includes rotation and other secret-specific features that meaningfully differentiate it.",
            "Free, unlimited storage for any number of secrets": "Wrong — Secrets Manager actually costs more per secret than Parameter Store's standard tier; it isn't free or unlimited.",
            "It can only be used to store database passwords, nothing else": "Wrong — Secrets Manager can store any kind of secret (API keys, tokens, etc.), not just database credentials.",
        },
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a VPC endpoint?",
        "options": [
            "Allows private connectivity between a VPC and supported AWS services without traversing the public internet",
            "Provides public internet access to instances inside a VPC",
            "Load balances traffic between two separate VPCs",
            "Encrypts all traffic within a VPC by default",
        ],
        "correct_answer": "Allows private connectivity between a VPC and supported AWS services without traversing the public internet",
        "explanation_correct": "VPC endpoints let resources in a VPC reach services like S3 or DynamoDB privately, keeping traffic on the AWS network instead of going out over the public internet.",
        "explanation_incorrect": {
            "Provides public internet access to instances inside a VPC": "Wrong — that's closer to the role of an internet gateway or NAT gateway, not a VPC endpoint.",
            "Load balances traffic between two separate VPCs": "Wrong — VPC endpoints are about private service access, not load balancing between VPCs.",
            "Encrypts all traffic within a VPC by default": "Wrong — VPC endpoints are about network path/routing, not automatic encryption of all VPC traffic.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ Gateway allows instances in a private subnet to initiate outbound internet connections while remaining unreachable directly from the internet.",
        "options": None,
        "correct_answer": "NAT",
        "explanation_correct": "A NAT (Network Address Translation) Gateway sits in a public subnet and forwards private-subnet instances' outbound traffic.",
        "explanation_incorrect": "The blank should be filled with the name of this gateway type: NAT.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Stateless firewall rules that operate at the subnet level, evaluated in numbered order, are commonly known by their acronym, ____.",
        "options": None,
        "correct_answer": "NACL",
        "explanation_correct": "NACLs (Network Access Control Lists) provide subnet-level, stateless traffic filtering.",
        "explanation_incorrect": "The blank should be filled with the acronym for subnet-level stateless firewall rules: NACL.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ tracking scaling policy in Auto Scaling automatically adjusts capacity to keep a chosen metric near a target value.",
        "options": None,
        "correct_answer": "target",
        "explanation_correct": "Target tracking policies automatically scale resources to maintain a specified metric near a set target.",
        "explanation_incorrect": "The blank should be filled with the name of this Auto Scaling policy type: target.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The AWS service used to create and manage encryption keys is commonly known by its acronym, ____.",
        "options": None,
        "correct_answer": "KMS",
        "explanation_correct": "KMS (Key Management Service) manages encryption keys used to protect data across AWS.",
        "explanation_incorrect": "The blank should be filled with the acronym for AWS's key management service: KMS.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "In an Application Load Balancer, a ____ group defines the set of targets that receive traffic and their associated health check settings.",
        "options": None,
        "correct_answer": "target",
        "explanation_correct": "A target group defines the backend resources a load balancer routes traffic to, along with their health checks.",
        "explanation_incorrect": "The blank should be filled with the term for this backend grouping: target.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Amazon ____ is a content delivery network (CDN) that caches content at edge locations closer to users.",
        "options": None,
        "correct_answer": "CloudFront",
        "explanation_correct": "CloudFront is AWS's CDN service, distributing cached content from edge locations worldwide.",
        "explanation_incorrect": "The blank should be filled with the name of AWS's CDN service: CloudFront.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "An SQS ____ letter queue captures messages that repeatedly fail processing, for later inspection.",
        "options": None,
        "correct_answer": "dead",
        "explanation_correct": "A dead-letter queue holds messages that have exceeded their allowed processing attempts.",
        "explanation_incorrect": "The blank should be filled with the first word of this queue type's name: dead.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "AWS ____ Manager provides secure storage and automatic rotation capabilities for credentials like database passwords.",
        "options": None,
        "correct_answer": "Secrets",
        "explanation_correct": "Secrets Manager stores sensitive credentials securely and can automatically rotate them on a schedule.",
        "explanation_incorrect": "The blank should be filled with the name of this AWS service: Secrets.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A VPC ____ allows private connectivity between a VPC and supported AWS services without traversing the public internet.",
        "options": None,
        "correct_answer": "endpoint",
        "explanation_correct": "A VPC endpoint provides a private network path from a VPC to a supported AWS service.",
        "explanation_incorrect": "The blank should be filled with the term for this private connectivity feature: endpoint.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The AWS service used to request temporary, limited-privilege credentials, such as when assuming an IAM role, is commonly known by its acronym, ____.",
        "options": None,
        "correct_answer": "STS",
        "explanation_correct": "STS (Security Token Service) issues temporary credentials, commonly used when assuming an IAM role.",
        "explanation_incorrect": "The blank should be filled with the acronym for AWS's temporary credentials service: STS.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up VPC peering between two VPCs.",
        "options": ["Update route tables in both VPCs to route traffic through the peering connection", "Create a VPC peering connection request", "Accept the peering connection from the other VPC's owner"],
        "correct_answer": '["Create a VPC peering connection request", "Accept the peering connection from the other VPC\'s owner", "Update route tables in both VPCs to route traffic through the peering connection"]',
        "explanation_correct": "Correct — the peering request must be created before it can be accepted, and route tables can only meaningfully route through the connection once it's active (accepted).",
        "explanation_incorrect": "The peering request must exist before it can be accepted, and route tables should be updated only after the connection is active.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a NAT Gateway.",
        "options": ["Update the private subnet's route table to send outbound traffic through the NAT Gateway", "Allocate an Elastic IP address", "Create the NAT Gateway in a public subnet using that Elastic IP"],
        "correct_answer": '["Allocate an Elastic IP address", "Create the NAT Gateway in a public subnet using that Elastic IP", "Update the private subnet\'s route table to send outbound traffic through the NAT Gateway"]',
        "explanation_correct": "Correct — the Elastic IP must exist before the NAT Gateway can be created with it, and the NAT Gateway must exist before route tables can point to it.",
        "explanation_incorrect": "The Elastic IP must be allocated before the NAT Gateway can use it, and the NAT Gateway must be created before a route table can reference it.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for deploying resources with CloudFormation.",
        "options": ["CloudFormation provisions the resources defined in the template", "Write a CloudFormation template defining the desired resources", "Create a stack from the template"],
        "correct_answer": '["Write a CloudFormation template defining the desired resources", "Create a stack from the template", "CloudFormation provisions the resources defined in the template"]',
        "explanation_correct": "Correct — the template must be written before a stack can be created from it, and provisioning happens as a result of stack creation.",
        "explanation_incorrect": "The template must exist before a stack can be created from it, and resource provisioning is the outcome of stack creation, not something that happens before it.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up cross-region S3 replication.",
        "options": ["New/updated objects in the source bucket are automatically replicated to the destination", "Enable versioning on both source and destination buckets", "Create a replication rule specifying the source and destination buckets"],
        "correct_answer": '["Enable versioning on both source and destination buckets", "Create a replication rule specifying the source and destination buckets", "New/updated objects in the source bucket are automatically replicated to the destination"]',
        "explanation_correct": "Correct — versioning is a prerequisite that must be enabled before a replication rule can be created, and replication only begins happening once the rule is in place.",
        "explanation_incorrect": "Versioning must be enabled on both buckets before replication can be configured, and objects only start replicating after the rule is actually created.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for deploying a service on ECS Fargate.",
        "options": ["ECS launches and manages Fargate tasks according to the service's desired count", "Register a task definition specifying container image and resource requirements", "Create an ECS service referencing the task definition"],
        "correct_answer": '["Register a task definition specifying container image and resource requirements", "Create an ECS service referencing the task definition", "ECS launches and manages Fargate tasks according to the service\'s desired count"]',
        "explanation_correct": "Correct — the task definition must exist before a service can reference it, and task launching happens as a result of the service being created.",
        "explanation_incorrect": "The task definition must be registered before a service can reference it, and ECS only begins launching tasks after the service exists.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order describing the process of assuming an IAM role via STS.",
        "options": ["Use the temporary credentials to make AWS API calls with the role's permissions", "Call sts:AssumeRole with the target role's ARN", "STS returns temporary security credentials"],
        "correct_answer": '["Call sts:AssumeRole with the target role\'s ARN", "STS returns temporary security credentials", "Use the temporary credentials to make AWS API calls with the role\'s permissions"]',
        "explanation_correct": "Correct — the AssumeRole call must be made before STS can return credentials, and those credentials must be received before they can be used to make API calls.",
        "explanation_incorrect": "The AssumeRole request must be made before STS has anything to respond with, and the returned credentials must exist before they can be used for API calls.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for integrating API Gateway with a Lambda function.",
        "options": ["Configure a Lambda integration so API requests invoke the function", "Create a Lambda function", "Create an API Gateway REST or HTTP API"],
        "correct_answer": '["Create a Lambda function", "Create an API Gateway REST or HTTP API", "Configure a Lambda integration so API requests invoke the function"]',
        "explanation_correct": "Correct — the Lambda function and the API must both exist before an integration can be configured connecting the two.",
        "explanation_incorrect": "Both the Lambda function and the API Gateway resource must exist before an integration linking them can be configured.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order describing an RDS Multi-AZ failover event.",
        "options": ["The database endpoint DNS is updated to point to the new primary", "RDS detects a failure in the primary instance", "RDS automatically fails over to the standby instance in another Availability Zone"],
        "correct_answer": '["RDS detects a failure in the primary instance", "RDS automatically fails over to the standby instance in another Availability Zone", "The database endpoint DNS is updated to point to the new primary"]',
        "explanation_correct": "Correct — the failure must be detected before failover can be triggered, and the DNS update to the new primary happens as part of completing that failover.",
        "explanation_incorrect": "A failure must be detected before RDS initiates failover, and the DNS endpoint update happens as the final step of completing the failover.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up an Auto Scaling target tracking policy.",
        "options": ["Auto Scaling automatically adjusts capacity to maintain that target", "Create or identify an Auto Scaling group", "Define a target tracking policy specifying a metric and target value"],
        "correct_answer": '["Create or identify an Auto Scaling group", "Define a target tracking policy specifying a metric and target value", "Auto Scaling automatically adjusts capacity to maintain that target"]',
        "explanation_correct": "Correct — the Auto Scaling group must exist before a policy can be attached to it, and automated adjustment only happens once the policy is defined.",
        "explanation_incorrect": "The Auto Scaling group must exist before a scaling policy can be attached to it, and automatic capacity adjustment only begins after the policy is defined.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for pushing a Docker image to Amazon ECR.",
        "options": ["Push the image to the ECR repository", "Authenticate Docker to the ECR registry", "Tag the local image with the ECR repository URI"],
        "correct_answer": '["Authenticate Docker to the ECR registry", "Tag the local image with the ECR repository URI", "Push the image to the ECR repository"]',
        "explanation_correct": "Correct — Docker must authenticate to the registry before pushing is allowed, and the image must be tagged with the correct repository URI before it can be pushed there.",
        "explanation_incorrect": "Authentication must happen before Docker can push to the registry, and the image must be tagged with the target repository URI before the push command will send it there.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for querying logs with CloudWatch Logs Insights.",
        "options": ["Write and run a query to analyze log data", "Navigate to CloudWatch Logs Insights", "Select the log group to query"],
        "correct_answer": '["Navigate to CloudWatch Logs Insights", "Select the log group to query", "Write and run a query to analyze log data"]',
        "explanation_correct": "Correct — you must be in the Logs Insights interface before selecting a log group, and a log group must be selected before a query can run against it.",
        "explanation_incorrect": "You need to be in the Logs Insights tool before choosing a log group to query, and a log group must be selected before a query can be run against it.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for creating and using a Lambda layer.",
        "options": ["Attach the layer to one or more Lambda functions", "Package shared code/dependencies into a layer archive", "Publish the layer to Lambda"],
        "correct_answer": '["Package shared code/dependencies into a layer archive", "Publish the layer to Lambda", "Attach the layer to one or more Lambda functions"]',
        "explanation_correct": "Correct — the layer archive must be packaged before it can be published, and it must be published before it can be attached to a function.",
        "explanation_incorrect": "The layer content must be packaged before it can be published to Lambda, and it must exist as a published layer before it can be attached to any function.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up an SQS dead-letter queue.",
        "options": ["Messages that fail processing beyond maxReceiveCount are moved to the dead-letter queue", "Create a dead-letter queue", "Configure the source queue's redrive policy to point to the dead-letter queue and set maxReceiveCount"],
        "correct_answer": '["Create a dead-letter queue", "Configure the source queue\'s redrive policy to point to the dead-letter queue and set maxReceiveCount", "Messages that fail processing beyond maxReceiveCount are moved to the dead-letter queue"]',
        "explanation_correct": "Correct — the dead-letter queue must exist before the source queue's redrive policy can reference it, and messages only get moved there once that configuration is in place.",
        "explanation_incorrect": "The dead-letter queue must exist before it can be referenced in a redrive policy, and messages only move there after that policy is configured.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for executing a Step Functions state machine.",
        "options": ["The state machine transitions through its defined states until completion", "Define a state machine using Amazon States Language (JSON)", "Start an execution of the state machine"],
        "correct_answer": '["Define a state machine using Amazon States Language (JSON)", "Start an execution of the state machine", "The state machine transitions through its defined states until completion"]',
        "explanation_correct": "Correct — the state machine definition must exist before an execution can start, and state transitions happen only after execution begins.",
        "explanation_incorrect": "The state machine must be defined before it can be executed, and state transitions only occur once an execution has actually started.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up an EFS file system shared across EC2 instances.",
        "options": ["Mount the file system on EC2 instances using the EFS mount helper", "Create an EFS file system", "Create mount targets in the relevant subnets/Availability Zones"],
        "correct_answer": '["Create an EFS file system", "Create mount targets in the relevant subnets/Availability Zones", "Mount the file system on EC2 instances using the EFS mount helper"]',
        "explanation_correct": "Correct — the file system must exist before mount targets can be created for it, and mount targets must exist before instances can actually mount the file system.",
        "explanation_incorrect": "The EFS file system must be created before mount targets can be set up for it, and mount targets must exist before instances in those subnets can mount it.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for cost monitoring with AWS Budgets.",
        "options": ["An alert is triggered when spend approaches or exceeds the threshold", "Create a budget specifying a cost or usage threshold", "AWS tracks actual spend against that budget"],
        "correct_answer": '["Create a budget specifying a cost or usage threshold", "AWS tracks actual spend against that budget", "An alert is triggered when spend approaches or exceeds the threshold"]',
        "explanation_correct": "Correct — the budget and its threshold must be defined before AWS can track spend against it, and alerts only fire once tracked spend meets the alert conditions.",
        "explanation_incorrect": "A budget must be created before spend can be tracked against it, and an alert only fires once tracking shows the threshold has been reached.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for launching a Spot Instance.",
        "options": ["AWS launches the instance if capacity is available at or below the specified price", "Specify a maximum price (or use the default Spot price) and instance requirements", "Request a Spot Instance"],
        "correct_answer": '["Specify a maximum price (or use the default Spot price) and instance requirements", "Request a Spot Instance", "AWS launches the instance if capacity is available at or below the specified price"]',
        "explanation_correct": "Correct — pricing and requirements must be specified before the request is made, and AWS only launches the instance after evaluating that request against available capacity.",
        "explanation_incorrect": "The price and requirements must be specified before submitting the request, and launch only happens after AWS evaluates that request.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for deploying an application with Elastic Beanstalk.",
        "options": ["Elastic Beanstalk provisions and configures the underlying infrastructure automatically", "Package the application code", "Upload the package to Elastic Beanstalk"],
        "correct_answer": '["Package the application code", "Upload the package to Elastic Beanstalk", "Elastic Beanstalk provisions and configures the underlying infrastructure automatically"]',
        "explanation_correct": "Correct — the code must be packaged before it can be uploaded, and infrastructure provisioning happens as a result of that upload.",
        "explanation_incorrect": "The application must be packaged before it can be uploaded, and Elastic Beanstalk only provisions infrastructure after receiving that uploaded package.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up Route 53 weighted routing.",
        "options": ["Route 53 distributes traffic across the resources according to the assigned weights", "Create multiple record sets for the same domain name pointing to different resources", "Assign a weight to each record set"],
        "correct_answer": '["Create multiple record sets for the same domain name pointing to different resources", "Assign a weight to each record set", "Route 53 distributes traffic across the resources according to the assigned weights"]',
        "explanation_correct": "Correct — the record sets must exist before weights can be assigned to them, and traffic distribution only happens once those weights are configured.",
        "explanation_incorrect": "Multiple record sets must exist before weights can be assigned to each one, and weighted distribution only takes effect after those weights are configured.",
    },
    {
        "topic": "AWS", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using AWS Config to track resource compliance.",
        "options": ["Config evaluates resources against the rule and flags non-compliant ones", "Enable AWS Config to record resource configurations", "Define a Config rule specifying a desired configuration state"],
        "correct_answer": '["Enable AWS Config to record resource configurations", "Define a Config rule specifying a desired configuration state", "Config evaluates resources against the rule and flags non-compliant ones"]',
        "explanation_correct": "Correct — Config must be enabled and recording before a rule can be evaluated against tracked resources, and evaluation only happens once a rule is defined.",
        "explanation_incorrect": "Config must be enabled before it has any recorded configuration data to evaluate, and a rule must be defined before Config can evaluate resources against it.",
    },
]
