"""
AWS - Easy batch, 50 questions total.
Distribution: even split — 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.
(Following the same even-mix pattern as Terraform, since AWS content is more about
services/CLI/concepts than algorithmic problem-solving, similar to Terraform.)

Schema matches python_easy_questions.py / terraform_easy_questions.py — see those files'
headers for full field notes. For "coding" questions here, correct_answer is a reference
AWS CLI command, graded leniently by LLM against the prompt.
"""

AWS_EASY_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to list all S3 buckets in your account.",
        "correct_answer": "aws s3 ls",
        "explanation_correct": "Correct — `aws s3 ls` with no bucket argument lists all buckets owned by the account.",
        "explanation_incorrect": "A correct solution must list all S3 buckets in the account, typically using `aws s3 ls`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to create a new S3 bucket named 'my-example-bucket' in the us-east-1 region.",
        "correct_answer": "aws s3 mb s3://my-example-bucket --region us-east-1",
        "explanation_correct": "Correct — `aws s3 mb` (make bucket) creates a new bucket with the given name in the specified region.",
        "explanation_incorrect": "A correct solution must create a new bucket with the exact name given, in the specified region, typically using `aws s3 mb`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to list all EC2 instances in your account.",
        "correct_answer": "aws ec2 describe-instances",
        "explanation_correct": "Correct — `aws ec2 describe-instances` returns details for all EC2 instances in the account (in the configured region).",
        "explanation_incorrect": "A correct solution must list EC2 instance information, typically using `aws ec2 describe-instances`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to stop an EC2 instance with instance ID i-0123456789abcdef0.",
        "correct_answer": "aws ec2 stop-instances --instance-ids i-0123456789abcdef0",
        "explanation_correct": "Correct — `aws ec2 stop-instances` with the --instance-ids flag stops the specified instance.",
        "explanation_incorrect": "A correct solution must stop the specific instance ID given, typically using `aws ec2 stop-instances --instance-ids`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to show details of an IAM user named 'jdoe'.",
        "correct_answer": "aws iam get-user --user-name jdoe",
        "explanation_correct": "Correct — `aws iam get-user` with --user-name returns details about the specified IAM user.",
        "explanation_incorrect": "A correct solution must retrieve details for the specific IAM user 'jdoe', typically using `aws iam get-user --user-name`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to upload a local file named 'report.txt' to an S3 bucket named 'my-bucket'.",
        "correct_answer": "aws s3 cp report.txt s3://my-bucket/",
        "explanation_correct": "Correct — `aws s3 cp` copies the local file into the specified S3 bucket.",
        "explanation_incorrect": "A correct solution must upload the local file to the specified S3 bucket, typically using `aws s3 cp`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to create a new IAM user named 'newuser'.",
        "correct_answer": "aws iam create-user --user-name newuser",
        "explanation_correct": "Correct — `aws iam create-user` with --user-name creates a new IAM user with the given name.",
        "explanation_incorrect": "A correct solution must create a new IAM user with the exact name 'newuser', typically using `aws iam create-user --user-name`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to list all objects in an S3 bucket named 'my-bucket'.",
        "correct_answer": "aws s3 ls s3://my-bucket",
        "explanation_correct": "Correct — `aws s3 ls` with a bucket path lists the objects (and prefixes) inside that bucket.",
        "explanation_incorrect": "A correct solution must list the objects inside the specified bucket, not just all buckets, typically using `aws s3 ls s3://<bucket>`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to create a new security group named 'web-sg' with the description 'Web server security group' in the default VPC.",
        "correct_answer": "aws ec2 create-security-group --group-name web-sg --description \"Web server security group\"",
        "explanation_correct": "Correct — `aws ec2 create-security-group` with --group-name and --description creates the security group as specified (using the default VPC when none is given).",
        "explanation_incorrect": "A correct solution must create a security group with the exact name and description given, typically using `aws ec2 create-security-group`.",
        "options": None,
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "coding",
        "prompt": "Write the AWS CLI command to terminate an EC2 instance with instance ID i-0123456789abcdef0.",
        "correct_answer": "aws ec2 terminate-instances --instance-ids i-0123456789abcdef0",
        "explanation_correct": "Correct — `aws ec2 terminate-instances` with --instance-ids permanently terminates the specified instance.",
        "explanation_incorrect": "A correct solution must terminate the specific instance ID given, typically using `aws ec2 terminate-instances --instance-ids`.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What does EC2 stand for?",
        "options": ["Elastic Compute Cloud", "Elastic Container Cloud", "Enterprise Compute Cloud", "Elastic Compute Container"],
        "correct_answer": "Elastic Compute Cloud",
        "explanation_correct": "EC2 (Elastic Compute Cloud) is AWS's service for provisioning resizable virtual server instances.",
        "explanation_incorrect": {
            "Elastic Container Cloud": "Wrong — 'container' is not part of the EC2 acronym; container services are handled by ECS/EKS instead.",
            "Enterprise Compute Cloud": "Wrong — the 'E' stands for Elastic, referring to resizable capacity, not Enterprise.",
            "Elastic Compute Container": "Wrong — this mixes up EC2 with ECS (Elastic Container Service), a different AWS service.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is Amazon S3 primarily used for?",
        "options": ["Object storage", "Relational database hosting", "Virtual server hosting", "DNS management"],
        "correct_answer": "Object storage",
        "explanation_correct": "S3 (Simple Storage Service) stores and retrieves data as objects, commonly used for files, backups, and static website assets.",
        "explanation_incorrect": {
            "Relational database hosting": "Wrong — that's the role of RDS, a separate AWS service.",
            "Virtual server hosting": "Wrong — that's the role of EC2, not S3.",
            "DNS management": "Wrong — that's the role of Route 53, not S3.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of an IAM role?",
        "options": [
            "It grants temporary permissions to AWS resources or services without long-term credentials",
            "It stores files in the cloud",
            "It manages DNS records for a domain",
            "It monitors application performance metrics",
        ],
        "correct_answer": "It grants temporary permissions to AWS resources or services without long-term credentials",
        "explanation_correct": "IAM roles are assumed temporarily by users, applications, or AWS services to gain a defined set of permissions, without embedding long-lived access keys.",
        "explanation_incorrect": {
            "It stores files in the cloud": "Wrong — that's the role of a storage service like S3, unrelated to IAM roles.",
            "It manages DNS records for a domain": "Wrong — that's the role of Route 53, unrelated to IAM.",
            "It monitors application performance metrics": "Wrong — that's the role of CloudWatch, unrelated to IAM roles.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is a Security Group in AWS?",
        "options": [
            "A virtual firewall that controls inbound and outbound traffic for resources like EC2 instances",
            "A group of IAM users with shared permissions",
            "A type of S3 bucket access policy",
            "A load balancer configuration",
        ],
        "correct_answer": "A virtual firewall that controls inbound and outbound traffic for resources like EC2 instances",
        "explanation_correct": "Security groups act as stateful virtual firewalls, defining which traffic is allowed in and out of the resources they're attached to.",
        "explanation_incorrect": {
            "A group of IAM users with shared permissions": "Wrong — that describes an IAM group, a completely different concept from a security group.",
            "A type of S3 bucket access policy": "Wrong — S3 access is controlled by bucket policies and ACLs, not security groups (which apply to networked resources like EC2).",
            "A load balancer configuration": "Wrong — a security group is a firewall construct, not a load balancer setting.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is an Availability Zone?",
        "options": [
            "An isolated location within an AWS Region with independent power, cooling, and networking",
            "A single physical server within a data center",
            "A type of EBS storage volume",
            "A billing category for cost allocation",
        ],
        "correct_answer": "An isolated location within an AWS Region with independent power, cooling, and networking",
        "explanation_correct": "Availability Zones are physically separate data centers within a Region, designed so that a failure in one doesn't take down the others.",
        "explanation_incorrect": {
            "A single physical server within a data center": "Wrong — an Availability Zone is made up of one or more entire data centers, not a single server.",
            "A type of EBS storage volume": "Wrong — EBS volume types (like gp3, io2) are unrelated to Availability Zones as a concept.",
            "A billing category for cost allocation": "Wrong — Availability Zones are a physical/infrastructure concept, not a billing construct.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What does RDS stand for, and what is it used for?",
        "options": [
            "Relational Database Service — used to run managed relational databases",
            "Remote Data Storage — used for general file storage",
            "Regional Distribution Service — used as a content delivery network",
            "Resource Deployment System — used for provisioning infrastructure",
        ],
        "correct_answer": "Relational Database Service — used to run managed relational databases",
        "explanation_correct": "RDS provisions and manages relational databases (like MySQL, PostgreSQL, or SQL Server) while handling tasks like backups and patching.",
        "explanation_incorrect": {
            "Remote Data Storage — used for general file storage": "Wrong — general file storage is the role of S3 or EBS, not RDS.",
            "Regional Distribution Service — used as a content delivery network": "Wrong — CDN functionality is provided by CloudFront, a different service.",
            "Resource Deployment System — used for provisioning infrastructure": "Wrong — infrastructure provisioning is handled by tools like CloudFormation, not RDS.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is AWS Lambda used for?",
        "options": [
            "Running code without provisioning or managing servers (serverless compute)",
            "Hosting static websites exclusively",
            "Managing DNS records",
            "Storing large files long-term",
        ],
        "correct_answer": "Running code without provisioning or managing servers (serverless compute)",
        "explanation_correct": "Lambda runs your code in response to events or requests, automatically managing the underlying compute infrastructure so you don't have to provision servers.",
        "explanation_incorrect": {
            "Hosting static websites exclusively": "Wrong — static website hosting is more directly associated with S3; Lambda can support dynamic behavior but isn't limited to or defined by static hosting.",
            "Managing DNS records": "Wrong — that's the role of Route 53, unrelated to Lambda.",
            "Storing large files long-term": "Wrong — that's the role of S3 or Glacier, not Lambda, which is a compute service.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of an Elastic Load Balancer (ELB)?",
        "options": [
            "It distributes incoming traffic across multiple targets, such as EC2 instances",
            "It stores application log files",
            "It manages user authentication for applications",
            "It encrypts data at rest in S3",
        ],
        "correct_answer": "It distributes incoming traffic across multiple targets, such as EC2 instances",
        "explanation_correct": "An ELB spreads incoming requests across healthy targets, improving availability and fault tolerance for an application.",
        "explanation_incorrect": {
            "It stores application log files": "Wrong — log storage is the role of services like CloudWatch Logs or S3, not the ELB itself.",
            "It manages user authentication for applications": "Wrong — authentication is handled by services like Cognito or IAM, not the load balancer.",
            "It encrypts data at rest in S3": "Wrong — S3 encryption is a separate S3 feature, unrelated to the load balancer's role.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is a key pair used for in EC2?",
        "options": [
            "Securely connecting to an EC2 instance (e.g. via SSH) using public/private key authentication",
            "Encrypting objects stored in S3",
            "Tagging resources for cost allocation",
            "Balancing traffic across instances",
        ],
        "correct_answer": "Securely connecting to an EC2 instance (e.g. via SSH) using public/private key authentication",
        "explanation_correct": "A key pair consists of a public key (installed on the instance) and a private key (kept by you), used to securely authenticate SSH (or RDP) connections instead of a password.",
        "explanation_incorrect": {
            "Encrypting objects stored in S3": "Wrong — S3 encryption uses separate mechanisms (like KMS keys), unrelated to EC2 key pairs.",
            "Tagging resources for cost allocation": "Wrong — that's the role of resource tags, a completely different concept from a key pair.",
            "Balancing traffic across instances": "Wrong — that's the role of a load balancer, unrelated to key pairs.",
        },
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the maximum object size that can be uploaded to S3 in a single PUT request?",
        "options": ["5GB", "1GB", "100MB", "There is no limit"],
        "correct_answer": "5GB",
        "explanation_correct": "A single S3 PUT operation can upload an object up to 5GB; larger objects require multipart upload.",
        "explanation_incorrect": {
            "1GB": "Wrong — the single-PUT limit is higher than this; 5GB is the actual cap.",
            "100MB": "Wrong — this is far below the actual single-PUT limit of 5GB.",
            "There is no limit": "Wrong — while S3 supports very large objects overall (via multipart upload, up to 5TB total), a single PUT request specifically is capped at 5GB.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Amazon's official command-line tool for interacting with AWS services is called the AWS ____.",
        "options": None,
        "correct_answer": "CLI",
        "explanation_correct": "The AWS CLI (Command Line Interface) lets you manage AWS services from a terminal.",
        "explanation_incorrect": "The blank should be filled with the name of the command-line tool: CLI.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "An AWS ____ is a geographic area containing multiple isolated Availability Zones.",
        "options": None,
        "correct_answer": "region",
        "explanation_correct": "AWS Regions are separate geographic areas, each made up of multiple Availability Zones.",
        "explanation_incorrect": "The blank should be filled with the term for a broad geographic AWS grouping: region.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ service provides scalable object storage for files, backups, and static website hosting.",
        "options": None,
        "correct_answer": "S3",
        "explanation_correct": "S3 (Simple Storage Service) is AWS's core object storage service.",
        "explanation_incorrect": "The blank should be filled with the name of AWS's object storage service: S3.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The AWS service used to manage users, groups, roles, and permissions is commonly known by its acronym, ____.",
        "options": None,
        "correct_answer": "IAM",
        "explanation_correct": "IAM (Identity and Access Management) is AWS's service for controlling who can do what across your account.",
        "explanation_incorrect": "The blank should be filled with the acronym for AWS's identity/permissions service: IAM.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "An EC2 ____ is a virtual server running in AWS's cloud.",
        "options": None,
        "correct_answer": "instance",
        "explanation_correct": "An EC2 instance is a single virtual server provisioned through the EC2 service.",
        "explanation_incorrect": "The blank should be filled with the term for a single virtual EC2 server: instance.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ service lets you run code without provisioning or managing servers, commonly described as serverless computing.",
        "options": None,
        "correct_answer": "Lambda",
        "explanation_correct": "AWS Lambda runs your code in response to triggers, automatically managing the underlying compute.",
        "explanation_incorrect": "The blank should be filled with the name of AWS's serverless compute service: Lambda.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "____ Groups act as virtual firewalls that control inbound and outbound traffic to EC2 instances.",
        "options": None,
        "correct_answer": "Security",
        "explanation_correct": "Security Groups are the stateful virtual firewalls attached to EC2 instances and other networked resources.",
        "explanation_incorrect": "The blank should be filled with the term describing this type of firewall grouping: Security.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "AWS ____ is the monitoring service used to collect metrics and logs and set alarms for AWS resources.",
        "options": None,
        "correct_answer": "CloudWatch",
        "explanation_correct": "CloudWatch collects metrics and logs across AWS services and can trigger alarms based on defined thresholds.",
        "explanation_incorrect": "The blank should be filled with the name of AWS's monitoring service: CloudWatch.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Amazon EBS provides persistent block storage for EC2 instances; EBS stands for Elastic Block ____.",
        "options": None,
        "correct_answer": "Store",
        "explanation_correct": "EBS stands for Elastic Block Store, providing durable, attachable block storage volumes for EC2 instances.",
        "explanation_incorrect": "The blank should be filled with the final word of the EBS acronym: Store.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Key-value labels attached to AWS resources for organization and cost tracking are called ____.",
        "options": None,
        "correct_answer": "tags",
        "explanation_correct": "Tags let you attach custom key-value metadata to AWS resources, useful for organization, automation, and cost allocation.",
        "explanation_incorrect": "The blank should be filled with the term for these key-value resource labels: tags.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the typical order for launching a new EC2 instance via the console.",
        "options": ["Launch the instance", "Choose an AMI (Amazon Machine Image)", "Select an instance type", "Configure security group and key pair"],
        "correct_answer": '["Choose an AMI (Amazon Machine Image)", "Select an instance type", "Configure security group and key pair", "Launch the instance"]',
        "explanation_correct": "Correct — you choose the base image first, then the hardware profile (instance type), then networking/access settings, before finally launching.",
        "explanation_incorrect": "The AMI selection comes first since it defines the OS/base image, sizing and security configuration follow, and launching is the final step once everything is configured.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for uploading a file to S3 and making it publicly accessible.",
        "options": ["Set the object's permissions or bucket policy to allow public read access", "Create an S3 bucket", "Upload the file to the bucket"],
        "correct_answer": '["Create an S3 bucket", "Upload the file to the bucket", "Set the object\'s permissions or bucket policy to allow public read access"]',
        "explanation_correct": "Correct — the bucket must exist before a file can be uploaded to it, and a file must exist in the bucket before its access permissions can be set.",
        "explanation_incorrect": "The bucket must be created before anything can be uploaded to it, and the file must be uploaded before its individual access permissions can be configured.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for creating an IAM user with programmatic access.",
        "options": ["Generate access keys for programmatic access", "Create the IAM user", "Attach a policy granting the needed permissions"],
        "correct_answer": '["Create the IAM user", "Attach a policy granting the needed permissions", "Generate access keys for programmatic access"]',
        "explanation_correct": "Correct — the user must exist before a policy can be attached to it, and generating access keys for that user comes after the user and its permissions are set up.",
        "explanation_incorrect": "The IAM user must be created before permissions can be attached to it, and access keys are generated for a user that already exists with its intended permissions.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a new RDS database.",
        "options": ["Launch the RDS instance", "Choose a database engine (e.g. MySQL, PostgreSQL)", "Configure instance size and storage"],
        "correct_answer": '["Choose a database engine (e.g. MySQL, PostgreSQL)", "Configure instance size and storage", "Launch the RDS instance"]',
        "explanation_correct": "Correct — the database engine choice shapes the available configuration options, which must be set before the instance can actually be launched.",
        "explanation_incorrect": "The engine must be chosen first since it determines available options, sizing/storage configuration follows, and launching is the final step.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up an EC2 Auto Scaling group.",
        "options": ["Define scaling policies (min/max/desired capacity)", "Create a launch template", "Create the Auto Scaling group referencing the launch template"],
        "correct_answer": '["Create a launch template", "Create the Auto Scaling group referencing the launch template", "Define scaling policies (min/max/desired capacity)"]',
        "explanation_correct": "Correct — the launch template must exist before an Auto Scaling group can reference it, and scaling policies are configured on the group once it exists.",
        "explanation_incorrect": "The launch template must be created before the Auto Scaling group can reference it, and scaling policies apply to a group that already exists.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order describing how a request flows through an Elastic Load Balancer.",
        "options": ["Target processes the request and returns a response", "Client sends a request to the load balancer's DNS name", "Load balancer forwards the request to a healthy target (e.g. an EC2 instance)"],
        "correct_answer": '["Client sends a request to the load balancer\'s DNS name", "Load balancer forwards the request to a healthy target (e.g. an EC2 instance)", "Target processes the request and returns a response"]',
        "explanation_correct": "Correct — the client's request must reach the load balancer first, which then routes it to a healthy backend target, which finally processes and responds to it.",
        "explanation_incorrect": "The request must first arrive at the load balancer before it can be routed anywhere, and a target can only respond after receiving the forwarded request.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for attaching an EBS volume to a running EC2 instance.",
        "options": ["Mount the volume's filesystem inside the instance's OS", "Create the EBS volume in the same Availability Zone as the instance", "Attach the volume to the instance"],
        "correct_answer": '["Create the EBS volume in the same Availability Zone as the instance", "Attach the volume to the instance", "Mount the volume\'s filesystem inside the instance\'s OS"]',
        "explanation_correct": "Correct — the volume must exist before it can be attached, and it must be attached to the instance before the OS can mount its filesystem.",
        "explanation_incorrect": "The volume must be created before it can be attached, and attachment must happen before the instance's operating system can mount it.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a basic CloudWatch alarm.",
        "options": ["Configure an action (e.g. send an SNS notification) when the threshold is breached", "Choose a metric to monitor (e.g. CPUUtilization)", "Set a threshold for the alarm"],
        "correct_answer": '["Choose a metric to monitor (e.g. CPUUtilization)", "Set a threshold for the alarm", "Configure an action (e.g. send an SNS notification) when the threshold is breached"]',
        "explanation_correct": "Correct — the metric to watch must be selected first, a threshold is defined against that metric, and an action is configured for when that threshold is breached.",
        "explanation_incorrect": "The metric must be chosen before a threshold can be set against it, and the response action is configured last, based on that threshold being breached.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for creating and using a security group.",
        "options": ["Attach the security group to an EC2 instance", "Create a new security group", "Add inbound/outbound rules specifying allowed traffic"],
        "correct_answer": '["Create a new security group", "Add inbound/outbound rules specifying allowed traffic", "Attach the security group to an EC2 instance"]',
        "explanation_correct": "Correct — the security group must exist before rules can be added to it, and it must exist (with its rules) before it can be attached to an instance.",
        "explanation_incorrect": "The security group must be created before rules can be added to it, and it should be configured with rules before (or as part of) being attached to an instance.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these items into AWS's basic resource hierarchy, from broadest to narrowest.",
        "options": ["EC2 Instance", "AWS Region", "Availability Zone"],
        "correct_answer": '["AWS Region", "Availability Zone", "EC2 Instance"]',
        "explanation_correct": "Correct — a Region contains multiple Availability Zones, and an EC2 instance runs within a single Availability Zone, making this the broadest-to-narrowest order.",
        "explanation_incorrect": "A Region is the broadest grouping, containing multiple Availability Zones, and an individual EC2 instance is the most specific, running within just one of those zones.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for creating an S3 bucket, enabling versioning, and uploading a file.",
        "options": ["Upload objects to the bucket", "Create the S3 bucket", "Enable versioning on the bucket"],
        "correct_answer": '["Create the S3 bucket", "Enable versioning on the bucket", "Upload objects to the bucket"]',
        "explanation_correct": "Correct — the bucket must exist before versioning can be enabled on it, and enabling versioning before uploads ensures every subsequent upload is versioned.",
        "explanation_incorrect": "The bucket must be created before any of its settings (like versioning) can be configured, and versioning is typically enabled before uploading content you want versioned.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order describing the IAM policy attachment flow.",
        "options": ["The principal now has the granted permissions", "Create an IAM policy document defining permissions", "Attach the policy to a user, group, or role"],
        "correct_answer": '["Create an IAM policy document defining permissions", "Attach the policy to a user, group, or role", "The principal now has the granted permissions"]',
        "explanation_correct": "Correct — the policy must be defined before it can be attached to anything, and the principal only gains the permissions once the attachment has been made.",
        "explanation_incorrect": "The policy document must exist before it can be attached to a principal, and the principal only gains those permissions after the attachment takes effect.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for launching and connecting to an EC2 instance via SSH.",
        "options": ["Connect via SSH using the private key file", "Launch the EC2 instance with a key pair", "Wait for the instance to enter the running state"],
        "correct_answer": '["Launch the EC2 instance with a key pair", "Wait for the instance to enter the running state", "Connect via SSH using the private key file"]',
        "explanation_correct": "Correct — the instance must be launched before it can start running, and it must be running before an SSH connection can succeed.",
        "explanation_incorrect": "The instance must be launched before it can reach a running state, and it needs to be running before SSH access will work.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for backing up an EBS volume.",
        "options": ["The snapshot is stored durably in S3-backed storage", "Select the EBS volume", "Create a snapshot of the volume"],
        "correct_answer": '["Select the EBS volume", "Create a snapshot of the volume", "The snapshot is stored durably in S3-backed storage"]',
        "explanation_correct": "Correct — the volume must be selected before a snapshot of it can be taken, and durable storage of that snapshot happens after it's created.",
        "explanation_incorrect": "A volume must be identified before a snapshot can be taken of it, and storage of the resulting snapshot happens after the snapshot process completes.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for routing traffic to a domain using Route 53.",
        "options": ["Add DNS records pointing to your resources", "Register or configure a domain", "Create a hosted zone in Route 53"],
        "correct_answer": '["Register or configure a domain", "Create a hosted zone in Route 53", "Add DNS records pointing to your resources"]',
        "explanation_correct": "Correct — a domain must exist before a hosted zone can manage it, and the hosted zone must exist before DNS records can be added within it.",
        "explanation_incorrect": "The domain must exist before a hosted zone is created for it, and the hosted zone must exist before records can be added to it.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for deploying a basic Lambda function.",
        "options": ["Configure a trigger (e.g. API Gateway or S3 event) to invoke it", "Write the function code", "Package and upload the code to Lambda"],
        "correct_answer": '["Write the function code", "Package and upload the code to Lambda", "Configure a trigger (e.g. API Gateway or S3 event) to invoke it"]',
        "explanation_correct": "Correct — code must be written before it can be uploaded, and the function must exist in Lambda before a trigger can be configured to invoke it.",
        "explanation_incorrect": "The code must be written before it can be packaged and uploaded, and the Lambda function must exist before a trigger can be wired up to it.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up SNS notifications.",
        "options": ["Publish a message to the topic to notify subscribers", "Create an SNS topic", "Subscribe an endpoint (e.g. email or SQS queue) to the topic"],
        "correct_answer": '["Create an SNS topic", "Subscribe an endpoint (e.g. email or SQS queue) to the topic", "Publish a message to the topic to notify subscribers"]',
        "explanation_correct": "Correct — the topic must exist before anything can subscribe to it, and subscribers must be in place before publishing a message would notify anyone.",
        "explanation_incorrect": "The SNS topic must be created before subscriptions can be added to it, and subscriptions must exist before a published message has anywhere to be delivered.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for restoring an EC2 instance from a snapshot.",
        "options": ["Verify the restored instance is functioning correctly", "Create an AMI or volume from the snapshot", "Launch a new EC2 instance using that AMI/volume"],
        "correct_answer": '["Create an AMI or volume from the snapshot", "Launch a new EC2 instance using that AMI/volume", "Verify the restored instance is functioning correctly"]',
        "explanation_correct": "Correct — an AMI/volume must be created from the snapshot before a new instance can be launched from it, and verification naturally happens after the instance is running.",
        "explanation_incorrect": "The AMI or volume must be created from the snapshot before it can be used to launch an instance, and verification comes only after that instance actually exists.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for configuring a VPC with a public subnet.",
        "options": ["Attach an internet gateway and update the route table for public access", "Create a VPC", "Create a subnet within the VPC"],
        "correct_answer": '["Create a VPC", "Create a subnet within the VPC", "Attach an internet gateway and update the route table for public access"]',
        "explanation_correct": "Correct — the VPC must exist before a subnet can be created within it, and the subnet must exist before it can be made public via the internet gateway and route table.",
        "explanation_incorrect": "The VPC must be created before a subnet can exist inside it, and the subnet must exist before its route table can be updated for public internet access.",
    },
    {
        "topic": "AWS", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for basic CloudTrail setup and use.",
        "options": ["Review logged events in the CloudTrail console or an S3 bucket", "Enable CloudTrail for the account", "AWS API calls are logged as events"],
        "correct_answer": '["Enable CloudTrail for the account", "AWS API calls are logged as events", "Review logged events in the CloudTrail console or an S3 bucket"]',
        "explanation_correct": "Correct — CloudTrail must be enabled before it starts logging events, and events must be logged before there's anything to review.",
        "explanation_incorrect": "CloudTrail must be enabled before any API activity is logged, and logging must happen before there's anything available to review.",
    },
]
