"""
Bash - Hard batch, 50 questions total.
Distribution: 30 coding, 8 mcq, 6 fill-in-blank, 3 drag-and-drop, 3 dropdown-order.

Schema matches python_easy_questions.py / bash_easy_questions.py — see those files'
headers for full field notes. Hard content covers process substitution, named pipes,
flock, namerefs, mapfile, coprocesses, retry/backoff patterns, trap-based cleanup,
parallel execution, and version comparison.
"""

BASH_HARD_QUESTIONS = [

    # ---------------- CODING (30) ----------------

    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a single bash command that enables strict mode: exit immediately on any error, treat unset variables as an error, and make a pipeline fail if any command within it fails.",
        "correct_answer": "set -euo pipefail",
        "explanation_correct": "Correct — -e exits on error, -u errors on unset variables, and -o pipefail makes the whole pipeline's exit status reflect any failing stage, together giving stricter default error handling.",
        "explanation_incorrect": "A correct solution must combine all three behaviors (exit on error, error on unset variables, and pipeline failure propagation) in a single set command.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner using process substitution to diff the sorted output of two commands, cmd1 and cmd2, without creating any temporary files.",
        "correct_answer": "diff <(cmd1 | sort) <(cmd2 | sort)",
        "explanation_correct": "Correct — process substitution presents each command's output as a file-like path that diff can read directly, avoiding the need for real temporary files.",
        "explanation_incorrect": "A correct solution must use process substitution (<(...)) to feed each command's sorted output directly into diff, not intermediate temp files.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash command that creates a named pipe (FIFO) called mypipe.",
        "correct_answer": "mkfifo mypipe",
        "explanation_correct": "Correct — `mkfifo` creates a special FIFO file that processes can use to communicate by writing to and reading from it in order.",
        "explanation_incorrect": "A correct solution must create a named pipe specifically (not a regular file), using mkfifo.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that uses flock to ensure only one instance of the command do_work runs at a time, using a lock file at /tmp/mylock.lock (non-blocking — skip if already locked).",
        "correct_answer": "flock -n /tmp/mylock.lock do_work",
        "explanation_correct": "Correct — flock -n attempts to acquire the lock without blocking, running do_work only if the lock is free, and failing immediately if another instance already holds it.",
        "explanation_incorrect": "A correct solution must use flock with the given lock file path to prevent concurrent execution of do_work, using the non-blocking flag.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner using a here-string to pass the value of variable data directly to the standard input of `wc -l`.",
        "correct_answer": "wc -l <<< \"$data\"",
        "explanation_correct": "Correct — the <<< here-string operator feeds the given string directly to the command's standard input without needing echo or a pipe.",
        "explanation_incorrect": "A correct solution must use the <<< here-string syntax specifically to pass the variable's value to wc -l.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that converts the value of variable s to all uppercase using bash's built-in case-conversion parameter expansion (not tr or awk).",
        "correct_answer": "echo \"${s^^}\"",
        "explanation_correct": "Correct — the ${var^^} expansion converts every character in the variable's value to uppercase, using only bash built-ins.",
        "explanation_incorrect": "A correct solution must use bash's built-in ${var^^} syntax specifically, not an external command like tr.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that uses declare -n to create a nameref variable ref pointing at a variable named target, then modifies target's value through ref and prints the result.",
        "correct_answer": "target=\"original\"\ndeclare -n ref=target\nref=\"modified\"\necho \"$target\"",
        "explanation_correct": "Correct — declare -n makes ref an alias for target, so assigning to ref actually updates target itself, which the final echo confirms.",
        "explanation_incorrect": "A correct solution must use declare -n to create a true alias (nameref) such that modifying ref actually changes target's value, not just a copy.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that reads all lines of a file named data.txt into an array named lines, using mapfile.",
        "correct_answer": "mapfile -t lines < data.txt",
        "explanation_correct": "Correct — mapfile -t reads each line of the file into successive array elements, stripping the trailing newline from each.",
        "explanation_incorrect": "A correct solution must populate the lines array with one element per line of the file, typically using mapfile (or readarray) with the -t flag.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that merges two already-declared associative arrays, a and b, into a new associative array named merged, where values from b take precedence over a on key conflicts.",
        "correct_answer": "declare -A merged=()\nfor k in \"${!a[@]}\"; do\n  merged[$k]=${a[$k]}\ndone\nfor k in \"${!b[@]}\"; do\n  merged[$k]=${b[$k]}\ndone",
        "explanation_correct": "Correct — copying all of a's entries first, then overwriting/adding b's entries afterward, correctly gives b's values precedence on any overlapping keys.",
        "explanation_incorrect": "A correct solution must copy all keys from both arrays into merged, ensuring that when a key exists in both, b's value is the one that ends up in merged.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that retries the command my_command up to 3 times with exponential backoff (sleeping 1s, then 2s, then 4s between attempts), exiting 0 on the first success or exiting 1 if all attempts fail.",
        "correct_answer": "for i in 1 2 3; do\n  my_command && exit 0\n  sleep $((2 ** (i - 1)))\ndone\nexit 1",
        "explanation_correct": "Correct — the loop attempts the command up to 3 times, exits immediately on success, and doubles the sleep duration each time it fails (1, 2, 4 seconds), exiting with failure only after all attempts are exhausted.",
        "explanation_incorrect": "A correct solution must retry up to 3 times, use exponentially increasing sleep durations between attempts, exit successfully on the first success, and exit with failure only if every attempt fails.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that runs long_running_task with a 5-second timeout, killing it if it hasn't finished by then.",
        "correct_answer": "timeout 5 long_running_task",
        "explanation_correct": "Correct — the `timeout` command runs the given command and terminates it if it exceeds the specified duration.",
        "explanation_incorrect": "A correct solution must enforce a 5-second time limit on the command's execution, typically using the timeout command.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that determines the absolute path of the directory containing the currently running script ($0), regardless of the current working directory.",
        "correct_answer": "dir=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
        "explanation_correct": "Correct — dirname extracts the script's containing directory (which may be relative), and cd-ing into it before running pwd resolves it to an absolute path.",
        "explanation_incorrect": "A correct solution must resolve the script's directory to an absolute path even if the script was invoked with a relative path — just using dirname \"$0\" alone would leave a relative path in some cases.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that checks whether it's being run as the root user, printing an error message and exiting with status 1 if it's not.",
        "correct_answer": "if [ \"$(id -u)\" -ne 0 ]; then\n  echo \"This script must be run as root\"\n  exit 1\nfi",
        "explanation_correct": "Correct — `id -u` returns 0 for the root user, so checking that it's not equal to 0 correctly detects a non-root invocation and exits accordingly.",
        "explanation_incorrect": "A correct solution must check the effective user ID (typically via id -u) and only print the error and exit non-zero when it's not root (UID 0).",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner using jq that extracts the value of the 'name' key from a JSON string stored in variable json_data.",
        "correct_answer": "echo \"$json_data\" | jq -r '.name'",
        "explanation_correct": "Correct — piping the JSON string into jq with the '.name' filter extracts that field, and -r outputs it as raw text without surrounding quotes.",
        "explanation_incorrect": "A correct solution must extract specifically the 'name' field's value from the JSON, typically using jq with a '.name' filter.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner using curl that requests the URL stored in variable url, fails (returns nonzero exit status) if the HTTP response is 4xx or 5xx, and discards the response body.",
        "correct_answer": "curl -sf -o /dev/null \"$url\"",
        "explanation_correct": "Correct — the -f flag makes curl fail silently (and return a nonzero exit code) on HTTP error responses, -s suppresses progress output, and -o /dev/null discards the response body.",
        "explanation_incorrect": "A correct solution must make curl itself report failure on HTTP error status codes (via -f), rather than treating a 404/500 response as a successful request.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that starts two background commands, cmd1 and cmd2, tracks their PIDs in an array, and waits for whichever one finishes first using `wait -n`.",
        "correct_answer": "pids=()\ncmd1 &\npids+=($!)\ncmd2 &\npids+=($!)\nwait -n \"${pids[@]}\"",
        "explanation_correct": "Correct — capturing $! immediately after backgrounding each command records its PID, and `wait -n` with the PID list returns as soon as the first of them completes.",
        "explanation_incorrect": "A correct solution must track both background jobs' PIDs and use wait -n (not plain wait, which would wait for all of them) to return after the first one finishes.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that creates a temporary file, then uses trap on EXIT to guarantee that file is removed even if the script exits early due to an error.",
        "correct_answer": "tmpfile=$(mktemp)\ntrap 'rm -f \"$tmpfile\"' EXIT",
        "explanation_correct": "Correct — registering the cleanup command on the EXIT trap ensures it runs no matter how the script terminates, whether it completes normally or exits early due to an error.",
        "explanation_incorrect": "A correct solution must guarantee cleanup happens regardless of how the script exits, using a trap registered on EXIT (not just cleanup code at the end of the script, which wouldn't run if the script exits early).",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that safely creates a uniquely-named temporary file and stores its path in a variable named tmpfile.",
        "correct_answer": "tmpfile=$(mktemp)",
        "explanation_correct": "Correct — `mktemp` creates a new, uniquely named temporary file and prints its path, which is captured into the variable.",
        "explanation_incorrect": "A correct solution must create an actual temporary file with a guaranteed-unique name (not a hardcoded name that could collide), typically using mktemp.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that prints the text 'Error!' in red using ANSI escape codes, resetting the terminal color afterward.",
        "correct_answer": "echo -e \"\\033[31mError!\\033[0m\"",
        "explanation_correct": "Correct — \\033[31m sets the foreground color to red, and \\033[0m resets all formatting back to default afterward.",
        "explanation_incorrect": "A correct solution must both set the text color to red before the message and reset formatting afterward, so subsequent output isn't also colored.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that validates the first command-line argument ($1) against a regex to check it looks like a valid email address, printing 'Invalid email' and exiting 1 if it doesn't match.",
        "correct_answer": "if [[ ! \"$1\" =~ ^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$ ]]; then\n  echo \"Invalid email\"\n  exit 1\nfi",
        "explanation_correct": "Correct — the regex requires non-space, non-@ characters, an @ symbol, more non-space characters, a dot, and a final segment — a reasonable basic email shape check — and the negated match correctly triggers on non-matching input.",
        "explanation_incorrect": "A correct solution must check the argument against a reasonable email-shaped pattern (containing an @ and a domain with a dot) and only print the error/exit when it doesn't match.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that splits a comma-separated string stored in variable csv (e.g. 'a,b,c') into an array named parts.",
        "correct_answer": "IFS=',' read -r -a parts <<< \"$csv\"",
        "explanation_correct": "Correct — setting IFS to a comma for this single command and reading into an array with -a correctly splits the string on commas into separate array elements.",
        "explanation_incorrect": "A correct solution must split the string on commas specifically (not whitespace) into an array, typically using IFS combined with read -a.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that extracts a slice of an already-defined array arr, starting at index 2 and taking 3 elements.",
        "correct_answer": "echo \"${arr[@]:2:3}\"",
        "explanation_correct": "Correct — the ${array[@]:offset:length} syntax extracts a slice of the array starting at the given offset for the given number of elements.",
        "explanation_incorrect": "A correct solution must extract exactly 3 elements starting at index 2 (the third element), using array slicing syntax.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that processes each element of an already-defined array items in parallel (up to 4 at a time) by calling a function process_item on each, using xargs.",
        "correct_answer": "printf '%s\\n' \"${items[@]}\" | xargs -P 4 -I {} bash -c 'process_item \"$@\"' _ {}",
        "explanation_correct": "Correct — printing each array item on its own line feeds xargs one item per invocation, -P 4 runs up to 4 in parallel, and wrapping the call in bash -c allows invoking the shell function process_item for each item.",
        "explanation_incorrect": "A correct solution must run process_item on each item with true parallelism (up to 4 concurrent invocations), typically using xargs -P.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that compares two version strings v1 and v2 (in X.Y.Z form) and prints 'less', 'equal', or 'greater' describing how v1 relates to v2, using sort -V for the comparison.",
        "correct_answer": "if [ \"$v1\" = \"$v2\" ]; then\n  echo \"equal\"\nelif [ \"$(printf '%s\\n%s' \"$v1\" \"$v2\" | sort -V | head -n1)\" = \"$v1\" ]; then\n  echo \"less\"\nelse\n  echo \"greater\"\nfi",
        "explanation_correct": "Correct — checking for exact equality first, then using version-aware sort -V to determine which version sorts first, correctly classifies the relationship even for multi-part version numbers.",
        "explanation_incorrect": "A correct solution must correctly compare version strings component-wise (not as plain strings, which would misorder something like '2.10' vs '2.9'), typically using sort -V.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash script that uses a coprocess to run the command mycmd, then reads a single line from its output.",
        "correct_answer": "coproc mycmd\nread -u \"${COPROC[0]}\" line\necho \"$line\"",
        "explanation_correct": "Correct — `coproc` runs mycmd asynchronously with pipes connected via the COPROC array, and reading from COPROC[0] (its output file descriptor) retrieves a line of its output.",
        "explanation_incorrect": "A correct solution must use the `coproc` builtin to run the command and read from its output file descriptor (via the COPROC array), not just background it with &.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that converts the value of variable s to all lowercase using bash's built-in case-conversion parameter expansion.",
        "correct_answer": "echo \"${s,,}\"",
        "explanation_correct": "Correct — the ${var,,} expansion converts every character in the variable's value to lowercase using only bash built-ins.",
        "explanation_incorrect": "A correct solution must use bash's built-in ${var,,} syntax specifically, not an external command like tr.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner that uses indirect variable reference to print the value of the variable whose name is stored in another variable called ref_name.",
        "correct_answer": "echo \"${!ref_name}\"",
        "explanation_correct": "Correct — the ${!varname} syntax performs indirect expansion, looking up the variable whose name is stored in varname and returning its value.",
        "explanation_incorrect": "A correct solution must use indirect expansion (${!ref_name}) to look up the value of the variable named by ref_name's contents, not ref_name's own literal value.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash command that limits the maximum number of open file descriptors for the current shell session to 256.",
        "correct_answer": "ulimit -n 256",
        "explanation_correct": "Correct — `ulimit -n` sets the soft limit on the number of open file descriptors for the current shell and its child processes.",
        "explanation_incorrect": "A correct solution must set the open-file-descriptor limit specifically (not memory, processes, or another resource), typically using ulimit -n.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash one-liner using grep -P (Perl-compatible regex) that extracts all sequences of digits from the string stored in variable s.",
        "correct_answer": "echo \"$s\" | grep -oP '\\d+'",
        "explanation_correct": "Correct — the -o flag outputs only the matched portions (not whole lines), and -P with \\d+ matches one or more consecutive digits using PCRE syntax.",
        "explanation_incorrect": "A correct solution must extract only the digit sequences themselves (not full lines), typically using grep -oP with a \\d+ pattern.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "coding",
        "prompt": "Write a bash command, placed inside a running script, that redirects all of the script's own subsequent output (both stdout and stderr) to a file named logfile.txt for the remainder of its execution.",
        "correct_answer": "exec > logfile.txt 2>&1",
        "explanation_correct": "Correct — using exec with redirection but no command reassigns the shell's own output streams, so every subsequent command in the script writes to logfile.txt instead of the terminal.",
        "explanation_incorrect": "A correct solution must redirect the script's own file descriptors going forward (using exec with redirection and no command), not just a single command's output.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `set -o pipefail` change about a pipeline's exit status?",
        "options": [
            "The pipeline's exit status reflects the last command in it that failed, rather than always the final command",
            "It disables the use of pipes entirely",
            "It makes all commands in the pipeline run in parallel",
            "It suppresses all errors within a pipeline",
        ],
        "correct_answer": "The pipeline's exit status reflects the last command in it that failed, rather than always the final command",
        "explanation_correct": "Without pipefail, a pipeline's exit status is just that of its last command, even if an earlier stage failed; pipefail makes the overall status reflect the rightmost non-zero exit code in the pipeline.",
        "explanation_incorrect": {
            "It disables the use of pipes entirely": "Wrong — pipes still work normally; pipefail only changes how the overall exit status is determined.",
            "It makes all commands in the pipeline run in parallel": "Wrong — commands in a pipeline already run concurrently by default (connected via pipes); pipefail is unrelated to that.",
            "It suppresses all errors within a pipeline": "Wrong — pipefail actually surfaces errors that would otherwise be hidden by a successful final command, the opposite of suppression.",
        },
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the key difference between `wait` (no arguments) and `wait -n`?",
        "options": [
            "wait -n returns as soon as any one specified background job finishes, rather than waiting for all of them",
            "wait -n waits for a fixed number of seconds before returning",
            "wait -n cancels all background jobs immediately",
            "There is no functional difference between them",
        ],
        "correct_answer": "wait -n returns as soon as any one specified background job finishes, rather than waiting for all of them",
        "explanation_correct": "Plain `wait` blocks until all background jobs complete; `wait -n` returns as soon as the next (first) one finishes, useful for reacting to whichever job completes first.",
        "explanation_incorrect": {
            "wait -n waits for a fixed number of seconds before returning": "Wrong — wait -n is about job completion, not a timer; sleep handles fixed-duration waits.",
            "wait -n cancels all background jobs immediately": "Wrong — wait -n only waits for a job to finish naturally; it doesn't terminate any jobs.",
            "There is no functional difference between them": "Wrong — the 'wait for one vs wait for all' distinction is a meaningful and commonly used difference.",
        },
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What does process substitution (e.g. `<(command)`) provide?",
        "options": [
            "A temporary, file-like input source backed by a command's output, without creating a real file on disk",
            "A way to run a command exclusively in a subshell with no other effect",
            "A way to redirect a command's standard error specifically",
            "A way to run a command in the background",
        ],
        "correct_answer": "A temporary, file-like input source backed by a command's output, without creating a real file on disk",
        "explanation_correct": "Process substitution presents a command's output (or input) as something that looks like a file path to other commands, letting tools like diff or comm treat command output as if it were a file, without an actual temp file.",
        "explanation_incorrect": {
            "A way to run a command exclusively in a subshell with no other effect": "Wrong — while it may involve a subshell internally, its purpose is specifically providing file-like access to that output, not subshell isolation alone.",
            "A way to redirect a command's standard error specifically": "Wrong — that's what 2> or 2>&1 handle; process substitution is about treating command output/input as a file.",
            "A way to run a command in the background": "Wrong — that's what & does; process substitution is unrelated to backgrounding.",
        },
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `declare -n ref=target` create?",
        "options": [
            "A nameref, where ref acts as an alias for the variable target",
            "A read-only copy of target's current value",
            "A new, empty variable unrelated to target",
            "An array containing target's value",
        ],
        "correct_answer": "A nameref, where ref acts as an alias for the variable target",
        "explanation_correct": "A nameref makes ref behave as a direct reference to target — reading or writing ref actually reads or writes target itself, not a separate copy.",
        "explanation_incorrect": {
            "A read-only copy of target's current value": "Wrong — a nameref is a live alias, not a static snapshot; changes to target are reflected through ref, and vice versa.",
            "A new, empty variable unrelated to target": "Wrong — the whole purpose of -n is to link ref to target, not create an independent variable.",
            "An array containing target's value": "Wrong — declare -n doesn't create an array; it creates a name-reference to a single variable.",
        },
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of `mkfifo`?",
        "options": [
            "Creates a named pipe (FIFO) that separate processes can use to communicate",
            "Creates a temporary regular file",
            "Creates a symbolic link between two files",
            "Creates a compressed archive of files",
        ],
        "correct_answer": "Creates a named pipe (FIFO) that separate processes can use to communicate",
        "explanation_correct": "A FIFO created with mkfifo behaves like a pipe with a filesystem name — one process can write to it while another reads, without either needing to know about a shared parent shell.",
        "explanation_incorrect": {
            "Creates a temporary regular file": "Wrong — that would be mktemp; a FIFO is a special pipe file, not a regular data file.",
            "Creates a symbolic link between two files": "Wrong — that's the role of `ln -s`, unrelated to FIFOs.",
            "Creates a compressed archive of files": "Wrong — archiving/compression is handled by tools like tar or gzip.",
        },
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `flock` primarily provide in a shell script?",
        "options": [
            "File-based locking to prevent multiple instances of a script (or section) from running concurrently",
            "Faster disk I/O for large files",
            "Automatic retries when a command fails",
            "Fine-grained control over process scheduling priority",
        ],
        "correct_answer": "File-based locking to prevent multiple instances of a script (or section) from running concurrently",
        "explanation_correct": "flock acquires a lock on a file, letting only one process hold it at a time — commonly used to prevent overlapping runs of a cron job or script.",
        "explanation_incorrect": {
            "Faster disk I/O for large files": "Wrong — flock is about coordination/locking, not I/O performance.",
            "Automatic retries when a command fails": "Wrong — retry logic must be implemented separately (e.g. with a loop); flock only manages locking.",
            "Fine-grained control over process scheduling priority": "Wrong — that's the role of tools like nice/renice, unrelated to flock.",
        },
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the effect of `${var^^}` in bash parameter expansion?",
        "options": [
            "Converts the value of var to all uppercase",
            "Converts the value of var to all lowercase",
            "Capitalizes only the first letter of var",
            "Reverses the characters of var",
        ],
        "correct_answer": "Converts the value of var to all uppercase",
        "explanation_correct": "The `^^` case-conversion operator uppercases every matching character in the variable's value.",
        "explanation_incorrect": {
            "Converts the value of var to all lowercase": "Wrong — that's ${var,,}, the lowercase equivalent, not ${var^^}.",
            "Capitalizes only the first letter of var": "Wrong — a single ^ (${var^}) capitalizes only the first character; the doubled ^^ applies to the whole string.",
            "Reverses the characters of var": "Wrong — bash parameter expansion doesn't have a built-in string-reversal operator at all; case conversion and reversal are unrelated operations.",
        },
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `exec > logfile.txt 2>&1` do when run inside a script, with no command following exec?",
        "options": [
            "Redirects all subsequent output (stdout and stderr) of the script itself to logfile.txt for the rest of its execution",
            "Replaces the current script with logfile.txt as a new program",
            "Only redirects the output of the single next command",
            "Has no effect, since exec requires a command argument",
        ],
        "correct_answer": "Redirects all subsequent output (stdout and stderr) of the script itself to logfile.txt for the rest of its execution",
        "explanation_correct": "When exec is given redirections but no command, it applies those redirections to the current shell process itself, affecting every command that follows for the rest of the script.",
        "explanation_incorrect": {
            "Replaces the current script with logfile.txt as a new program": "Wrong — that describes exec's other use (replacing the process image with a new command), which doesn't apply here since no command is given, only redirections.",
            "Only redirects the output of the single next command": "Wrong — the redirection persists for the shell's remaining lifetime, not just one command.",
            "Has no effect, since exec requires a command argument": "Wrong — exec with only redirections (and no command) is valid and commonly used specifically for this persistent-redirection purpose.",
        },
    },

    # ---------------- FILL-IN-BLANK (6) ----------------

    {
        "topic": "Bash", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ command creates a named pipe (FIFO) that separate processes can use to communicate.",
        "options": None,
        "correct_answer": "mkfifo",
        "explanation_correct": "mkfifo creates a special FIFO file usable for inter-process communication.",
        "explanation_incorrect": "The blank should be filled with the command used to create a named pipe: mkfifo.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ command provides file-based locking, commonly used to prevent multiple instances of a script from running concurrently.",
        "options": None,
        "correct_answer": "flock",
        "explanation_correct": "flock manages an exclusive (or shared) lock on a file, letting only one process hold it at a time.",
        "explanation_incorrect": "The blank should be filled with the command used for file-based locking: flock.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The `${var^^}` parameter expansion converts the value of var to all ____case.",
        "options": None,
        "correct_answer": "upper",
        "explanation_correct": "The doubled caret (^^) applies uppercase conversion to every character in the variable's value.",
        "explanation_incorrect": "The blank should describe the case conversion performed by ^^: upper.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The `${var,,}` parameter expansion converts the value of var to all ____case.",
        "options": None,
        "correct_answer": "lower",
        "explanation_correct": "The doubled comma (,,) applies lowercase conversion to every character in the variable's value.",
        "explanation_incorrect": "The blank should describe the case conversion performed by ,,: lower.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ command safely creates a uniquely named temporary file or directory.",
        "options": None,
        "correct_answer": "mktemp",
        "explanation_correct": "mktemp generates a temporary path guaranteed not to collide with existing files, avoiding common security/race pitfalls of hand-rolled temp file names.",
        "explanation_incorrect": "The blank should be filled with the command used to create temporary files/directories safely: mktemp.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Declaring a variable with `declare -____` creates a nameref, letting one variable act as a live alias for another.",
        "options": None,
        "correct_answer": "n",
        "explanation_correct": "The -n flag on declare creates a nameref, linking the declared variable to another variable by name.",
        "explanation_incorrect": "The blank should be filled with the declare flag used to create a nameref: n.",
    },

    # ---------------- DRAG-AND-DROP (3) ----------------

    {
        "topic": "Bash", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly ordered script that creates a temp file, guarantees its cleanup on exit, and writes to it.",
        "options": ["echo \"hello\" > \"$tmpfile\"", "tmpfile=$(mktemp)", "trap 'rm -f \"$tmpfile\"' EXIT"],
        "correct_answer": '["tmpfile=$(mktemp)", "trap \'rm -f \\"$tmpfile\\"\' EXIT", "echo \\"hello\\" > \\"$tmpfile\\""]',
        "explanation_correct": "Correct — the temp file must be created before the trap can meaningfully reference it, the cleanup trap should be registered early (before any risk of an error), and using the file comes last.",
        "explanation_incorrect": "The temp file must exist before the cleanup trap references its path, and registering the trap early (before further commands that could fail) is the safer, conventional ordering.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a sensible strict-mode script header.",
        "options": ["trap 'echo \"Error occurred\"' ERR", "set -euo pipefail", "IFS=$'\\n\\t'"],
        "correct_answer": '["set -euo pipefail", "IFS=$\'\\\\n\\\\t\'", "trap \'echo \\"Error occurred\\"\' ERR"]',
        "explanation_correct": "Correct — strict mode is conventionally enabled first, followed by a safer IFS setting, followed by an error trap — all near the top of the script before any real logic runs.",
        "explanation_incorrect": "While bash doesn't strictly require this exact order, the conventional layout enables strict mode first, then adjusts IFS, then registers error handling, all before the script's main logic.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly ordered script that runs two background jobs, tracks their PIDs, and waits for the first to finish.",
        "options": ["cmd2 &\npids+=($!)", "wait -n \"${pids[@]}\"", "pids=()", "cmd1 &\npids+=($!)"],
        "correct_answer": '["pids=()", "cmd1 &\\npids+=($!)", "cmd2 &\\npids+=($!)", "wait -n \\"${pids[@]}\\""]',
        "explanation_correct": "Correct — the array must be initialized before PIDs are appended to it, both jobs must be started and their PIDs captured before waiting, and wait -n must come last to block for the first completion.",
        "explanation_incorrect": "The pids array must exist before anything is appended to it, both background jobs must be launched (and their PIDs recorded) before wait -n has anything to wait on.",
    },

    # ---------------- DROPDOWN-ORDER (3) ----------------

    {
        "topic": "Bash", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly ordered script using a coprocess to read one line of output from a command.",
        "options": ["echo \"$line\"", "coproc mycmd", "read -u \"${COPROC[0]}\" line"],
        "correct_answer": '["coproc mycmd", "read -u \\"${COPROC[0]}\\" line", "echo \\"$line\\""]',
        "explanation_correct": "Correct — the coprocess must be started before its output file descriptor exists to read from, and the line must be read into the variable before it can be printed.",
        "explanation_incorrect": "The coprocess must be started before COPROC[0] is available to read from, and the read must complete before the line variable has anything to print.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured retry loop with exponential backoff.",
        "options": ["for i in 1 2 3; do", "  my_command && exit 0\n  sleep $((2 ** (i - 1)))", "done\nexit 1"],
        "correct_answer": '["for i in 1 2 3; do", "  my_command && exit 0\\n  sleep $((2 ** (i - 1)))", "done\\nexit 1"]',
        "explanation_correct": "Correct — the loop must be opened before its body (the attempt and backoff sleep) runs, and the final exit 1 must come after the loop, reached only if every attempt failed.",
        "explanation_incorrect": "The loop header must come first to open the iteration, its body runs each attempt and sleep, and the final failure exit must come only after the loop has exhausted all attempts.",
    },
    {
        "topic": "Bash", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured root-check script.",
        "options": ["fi", "  echo \"This script must be run as root\"\n  exit 1", "if [ \"$(id -u)\" -ne 0 ]; then"],
        "correct_answer": '["if [ \\"$(id -u)\\" -ne 0 ]; then", "  echo \\"This script must be run as root\\"\\n  exit 1", "fi"]',
        "explanation_correct": "Correct — the if line opens the conditional check, the error message and exit form its body, and fi closes the block.",
        "explanation_incorrect": "The if line must come first to open the conditional, its body (message and exit) comes next, and fi must be last to properly close the block.",
    },
]
