"""
Bash - Easy batch, 50 questions total.
Distribution: 32 coding, 8 mcq, 6 fill-in-blank, 2 drag-and-drop, 2 dropdown-order.
(Weighted heavily toward coding, matching the Python easy batches.)

Schema matches python_easy_questions.py — see that file's header for full field notes.
For "coding" questions here, correct_answer is a reference bash script/one-liner,
graded leniently by LLM against the prompt.
"""

BASH_EASY_QUESTIONS = [

    # ---------------- CODING (32) ----------------

    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash command that prints 'Hello, World!' to the console.",
        "correct_answer": "echo \"Hello, World!\"",
        "explanation_correct": "Correct — `echo` prints its arguments to standard output.",
        "explanation_incorrect": "A correct solution must print the exact text 'Hello, World!' using echo or an equivalent output command.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash command that prints the value of the HOME environment variable.",
        "correct_answer": "echo \"$HOME\"",
        "explanation_correct": "Correct — referencing $HOME and printing it with echo displays the value of that environment variable.",
        "explanation_incorrect": "A correct solution must reference the HOME environment variable (using $HOME) and print its value.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that checks if a variable x (already set to 5) is equal to 5, printing 'yes' if so.",
        "correct_answer": "x=5\nif [ \"$x\" -eq 5 ]; then\n  echo \"yes\"\nfi",
        "explanation_correct": "Correct — using the -eq numeric comparison inside an if/test correctly checks whether x equals 5 and prints 'yes' when true.",
        "explanation_incorrect": "A correct solution must use a conditional test (like [ \"$x\" -eq 5 ]) and print 'yes' only when the condition is true.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash for loop that prints the numbers 1 through 5, each on its own line.",
        "correct_answer": "for i in 1 2 3 4 5; do\n  echo \"$i\"\ndone",
        "explanation_correct": "Correct — the for loop iterates over the numbers 1 through 5 and echoes each one on its own line.",
        "explanation_incorrect": "A correct solution must print each number from 1 to 5 on its own line, using a for loop (a range-based construct like {1..5} is also acceptable).",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that reads a filename from the user and prints whether it exists.",
        "correct_answer": "read -p \"Enter filename: \" filename\nif [ -f \"$filename\" ]; then\n  echo \"File exists\"\nelse\n  echo \"File does not exist\"\nfi",
        "explanation_correct": "Correct — reading the filename with `read`, then testing it with -f, correctly determines and reports whether the file exists.",
        "explanation_incorrect": "A correct solution must read a filename from the user (via read) and use a file test (like -f) to check for its existence.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that prints the number of lines in a file named data.txt.",
        "correct_answer": "wc -l < data.txt",
        "explanation_correct": "Correct — `wc -l` counts the number of newline characters in the input, effectively counting lines.",
        "explanation_incorrect": "A correct solution must count and print the number of lines in data.txt, typically using wc -l.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash function named greet that takes one argument (a name) and prints 'Hello, <name>'.",
        "correct_answer": "greet() {\n  echo \"Hello, $1\"\n}",
        "explanation_correct": "Correct — the function accepts its first positional parameter ($1) and includes it in the greeting message.",
        "explanation_incorrect": "A correct solution must define a function named greet that uses its first argument ($1) in the printed greeting.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash command that lists all files in the current directory, including hidden files.",
        "correct_answer": "ls -a",
        "explanation_correct": "Correct — the -a flag tells ls to include entries starting with a dot (hidden files).",
        "explanation_incorrect": "A correct solution must list files including hidden ones — plain `ls` without a flag would omit dotfiles.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that prints the current working directory.",
        "correct_answer": "pwd",
        "explanation_correct": "Correct — `pwd` prints the full path of the current working directory.",
        "explanation_incorrect": "A correct solution must print the current working directory, typically using the pwd command.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that checks if a directory named 'backup' exists, and creates it if it doesn't.",
        "correct_answer": "if [ ! -d \"backup\" ]; then\n  mkdir backup\nfi",
        "explanation_correct": "Correct — testing with -d and negating it (! -d) correctly detects a missing directory, and mkdir creates it in that case.",
        "explanation_incorrect": "A correct solution must check whether the 'backup' directory exists (using a -d test) and only create it if it's missing.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that counts the number of files in the current directory (not including subdirectories).",
        "correct_answer": "ls -p | grep -v / | wc -l",
        "explanation_correct": "Correct — listing entries, filtering out anything ls marks as a directory (trailing slash from -p), and counting the remainder gives the file count.",
        "explanation_incorrect": "A correct solution must count only files (excluding directories) in the current directory.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that loops through the elements of an array named fruits (already defined) and prints each one.",
        "correct_answer": "for fruit in \"${fruits[@]}\"; do\n  echo \"$fruit\"\ndone",
        "explanation_correct": "Correct — iterating over \"${fruits[@]}\" correctly expands each array element (safely, even with spaces) and prints it.",
        "explanation_incorrect": "A correct solution must iterate over every element of the fruits array and print each one, typically using \"${fruits[@]}\".",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that prints the exit status of the last executed command.",
        "correct_answer": "echo $?",
        "explanation_correct": "Correct — the $? variable holds the exit status of the most recently executed command.",
        "explanation_incorrect": "A correct solution must print the value of $?, which holds the previous command's exit status.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that reverses a string stored in a variable named s and prints the result.",
        "correct_answer": "s=\"hello\"\necho \"$s\" | rev",
        "explanation_correct": "Correct — piping the string into `rev` reverses the order of its characters.",
        "explanation_incorrect": "A correct solution must print the characters of the string in reverse order, e.g. using the rev command.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash while loop that prints the numbers 1 through 5, each on its own line.",
        "correct_answer": "i=1\nwhile [ $i -le 5 ]; do\n  echo \"$i\"\n  i=$((i + 1))\ndone",
        "explanation_correct": "Correct — the loop increments i each iteration and continues while i is less than or equal to 5, printing each value.",
        "explanation_incorrect": "A correct solution must use a while loop (not a for loop) to print each number from 1 to 5, incrementing a counter variable manually.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that lists all .txt files in the current directory.",
        "correct_answer": "ls *.txt",
        "explanation_correct": "Correct — the *.txt glob pattern matches all files in the current directory ending in .txt.",
        "explanation_incorrect": "A correct solution must list only files ending in .txt in the current directory.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that takes two numbers as command-line arguments and prints their sum.",
        "correct_answer": "echo $(($1 + $2))",
        "explanation_correct": "Correct — using arithmetic expansion $(( )) on the first two positional parameters correctly computes and prints their sum.",
        "explanation_incorrect": "A correct solution must add the two numbers passed as command-line arguments ($1 and $2) and print the result.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that converts the string 'hello' to uppercase and prints it.",
        "correct_answer": "echo \"hello\" | tr 'a-z' 'A-Z'",
        "explanation_correct": "Correct — piping the string through `tr 'a-z' 'A-Z'` translates every lowercase letter to its uppercase equivalent.",
        "explanation_incorrect": "A correct solution must convert the string to all uppercase and print the result, e.g. using tr or bash's ${var^^} syntax.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that checks if a variable named name is empty, printing 'name is empty' if so.",
        "correct_answer": "if [ -z \"$name\" ]; then\n  echo \"name is empty\"\nfi",
        "explanation_correct": "Correct — the -z test checks whether the string is empty (zero length), correctly detecting an unset or empty variable.",
        "explanation_incorrect": "A correct solution must use a test like -z to check whether the variable is empty, and print the message only in that case.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that counts the number of words in the string 'the quick brown fox'.",
        "correct_answer": "echo \"the quick brown fox\" | wc -w",
        "explanation_correct": "Correct — `wc -w` counts whitespace-separated words in its input.",
        "explanation_incorrect": "A correct solution must count and print the number of words in the given string, typically using wc -w.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that appends the line 'new entry' to a file named log.txt.",
        "correct_answer": "echo \"new entry\" >> log.txt",
        "explanation_correct": "Correct — the >> operator appends output to the end of a file rather than overwriting it.",
        "explanation_incorrect": "A correct solution must add the text as a new line at the end of log.txt without erasing its existing contents (using >>, not a single >).",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that prints the first 5 lines of a file named data.txt.",
        "correct_answer": "head -n 5 data.txt",
        "explanation_correct": "Correct — `head -n 5` prints the first 5 lines of the given file.",
        "explanation_incorrect": "A correct solution must print exactly the first 5 lines of data.txt, typically using head -n 5.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script using a case statement that prints 'weekday' if a variable day is 'Saturday' or 'Sunday' the opposite — print 'weekend' for those two, and 'weekday' for any other value.",
        "correct_answer": "case \"$day\" in\n  Saturday|Sunday)\n    echo \"weekend\"\n    ;;\n  *)\n    echo \"weekday\"\n    ;;\nesac",
        "explanation_correct": "Correct — the case statement matches Saturday or Sunday to print 'weekend', and falls through to the wildcard pattern for every other value, printing 'weekday'.",
        "explanation_incorrect": "A correct solution must use a case statement with a pattern matching Saturday or Sunday (printing 'weekend') and a default wildcard case for everything else (printing 'weekday').",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that removes all .tmp files in the current directory.",
        "correct_answer": "rm -f *.tmp",
        "explanation_correct": "Correct — the *.tmp glob expands to all matching files, and rm removes them.",
        "explanation_incorrect": "A correct solution must remove every file ending in .tmp in the current directory.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that checks whether at least one command-line argument was provided, printing 'Usage: script.sh <arg>' if not.",
        "correct_answer": "if [ $# -eq 0 ]; then\n  echo \"Usage: script.sh <arg>\"\nfi",
        "explanation_correct": "Correct — $# holds the number of arguments passed to the script, and checking it against 0 correctly detects a missing argument.",
        "explanation_incorrect": "A correct solution must check the argument count (using $#) and print the usage message only when no arguments were provided.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that displays the disk usage of the current directory in human-readable form.",
        "correct_answer": "du -sh .",
        "explanation_correct": "Correct — `du -sh .` summarizes the total disk usage of the current directory in a human-readable format (e.g. '4.0K', '2.1M').",
        "explanation_incorrect": "A correct solution must display the disk usage of the current directory in a human-readable format, typically using du -sh.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that copies a file named source.txt to dest.txt, printing 'Copy successful' if the copy succeeds.",
        "correct_answer": "cp source.txt dest.txt && echo \"Copy successful\"",
        "explanation_correct": "Correct — using && ensures the success message only prints if the cp command completed without error.",
        "explanation_incorrect": "A correct solution must copy the file and only print the success message if the copy actually succeeded (e.g. using && or checking $?).",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that searches for the string 'error' in a file named log.txt.",
        "correct_answer": "grep \"error\" log.txt",
        "explanation_correct": "Correct — `grep` searches for lines matching the given pattern within the specified file.",
        "explanation_incorrect": "A correct solution must search log.txt for lines containing 'error', typically using grep.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that calculates and prints the factorial of a number stored in a variable n (already set), using a loop.",
        "correct_answer": "result=1\nfor ((i=1; i<=n; i++)); do\n  result=$((result * i))\ndone\necho \"$result\"",
        "explanation_correct": "Correct — multiplying result by each integer from 1 up to n via the loop correctly accumulates the factorial.",
        "explanation_incorrect": "A correct solution must compute the product of all integers from 1 to n using a loop, and print the final result.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that prints the number of arguments passed to the script.",
        "correct_answer": "echo $#",
        "explanation_correct": "Correct — $# expands to the number of positional parameters passed to the script.",
        "explanation_incorrect": "A correct solution must print the count of arguments passed to the script, using $#.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash script that checks whether a number stored in a variable n (already set) is even or odd, printing 'even' or 'odd' accordingly.",
        "correct_answer": "if [ $((n % 2)) -eq 0 ]; then\n  echo \"even\"\nelse\n  echo \"odd\"\nfi",
        "explanation_correct": "Correct — using the modulo operator to check the remainder when dividing by 2 correctly determines even or odd.",
        "explanation_incorrect": "A correct solution must correctly determine whether n is even or odd (e.g. by checking n % 2) and print the matching result.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "coding",
        "prompt": "Write a bash one-liner that sorts the lines of a file named names.txt alphabetically and prints the result.",
        "correct_answer": "sort names.txt",
        "explanation_correct": "Correct — `sort` reorders the lines of the given file alphabetically by default and prints them.",
        "explanation_incorrect": "A correct solution must print the lines of names.txt in alphabetical order, typically using the sort command.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "Which symbol is used to run a command in the background in bash?",
        "options": ["&", "|", "&&", ";"],
        "correct_answer": "&",
        "explanation_correct": "Appending `&` to a command runs it as a background job, returning control to the shell immediately.",
        "explanation_incorrect": {
            "|": "Wrong — the pipe connects the output of one command to the input of another; it doesn't background anything.",
            "&&": "Wrong — this runs a second command only if the first succeeds; it doesn't background either command.",
            ";": "Wrong — this simply separates sequential commands run one after another, not in the background.",
        },
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "What does the $? variable hold immediately after a command runs?",
        "options": ["The exit status of the last command", "The process ID of the shell", "The current working directory", "The number of arguments passed to the script"],
        "correct_answer": "The exit status of the last command",
        "explanation_correct": "$? always reflects the exit code of the most recently executed command, with 0 typically meaning success.",
        "explanation_incorrect": {
            "The process ID of the shell": "Wrong — that's $$, not $?.",
            "The current working directory": "Wrong — that's obtained via pwd or $PWD, not $?.",
            "The number of arguments passed to the script": "Wrong — that's $#, not $?.",
        },
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "Which command is used to display the contents of a file?",
        "options": ["cat", "ls", "cd", "mkdir"],
        "correct_answer": "cat",
        "explanation_correct": "`cat` concatenates and prints the contents of one or more files to standard output.",
        "explanation_incorrect": {
            "ls": "Wrong — ls lists directory contents (filenames), it doesn't print a file's contents.",
            "cd": "Wrong — cd changes the current directory; it doesn't display file contents.",
            "mkdir": "Wrong — mkdir creates a new directory; it has nothing to do with viewing files.",
        },
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "What does the shebang line `#!/bin/bash` at the top of a script do?",
        "options": [
            "Tells the operating system which interpreter to use to run the script",
            "Comments out the rest of the file",
            "Imports the bash standard library",
            "Sets the file's permissions to executable",
        ],
        "correct_answer": "Tells the operating system which interpreter to use to run the script",
        "explanation_correct": "The shebang line tells the OS which program (in this case, /bin/bash) should interpret and execute the rest of the file.",
        "explanation_incorrect": {
            "Comments out the rest of the file": "Wrong — only the shebang line itself is treated specially; the rest of the script still runs normally.",
            "Imports the bash standard library": "Wrong — bash doesn't have an 'import' concept triggered by the shebang; it simply specifies the interpreter.",
            "Sets the file's permissions to executable": "Wrong — execute permission is set separately with chmod +x, unrelated to the shebang line's content.",
        },
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "Which operator checks numeric equality inside a bash `[ ]` test, e.g. `[ \"$x\" -eq 5 ]`?",
        "options": ["-eq", "==", "=", "-equal"],
        "correct_answer": "-eq",
        "explanation_correct": "`-eq` is the standard test operator for comparing two integers for equality inside `[ ]`.",
        "explanation_incorrect": {
            "==": "Wrong — == is a string comparison operator (and a bash extension inside [[ ]]), not the standard numeric equality test for [ ].",
            "=": "Wrong — = compares strings, not numbers, inside a [ ] test.",
            "-equal": "Wrong — this is not a real bash test operator.",
        },
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "What does `chmod +x script.sh` do?",
        "options": ["Makes the script executable", "Changes the file's owner", "Compresses the file", "Deletes the file"],
        "correct_answer": "Makes the script executable",
        "explanation_correct": "`chmod +x` adds execute permission to the file, allowing it to be run directly (e.g. ./script.sh).",
        "explanation_incorrect": {
            "Changes the file's owner": "Wrong — changing ownership is done with chown, not chmod.",
            "Compresses the file": "Wrong — chmod only affects permissions, not file size or compression.",
            "Deletes the file": "Wrong — chmod never removes files; that's the role of rm.",
        },
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "Which command displays the current working directory?",
        "options": ["pwd", "ls", "cd", "whoami"],
        "correct_answer": "pwd",
        "explanation_correct": "`pwd` (print working directory) outputs the absolute path of the directory the shell is currently in.",
        "explanation_incorrect": {
            "ls": "Wrong — ls lists the contents of a directory, it doesn't print the current directory's own path.",
            "cd": "Wrong — cd changes directories; it doesn't display the current one without arguments.",
            "whoami": "Wrong — whoami prints the current logged-in username, not the working directory.",
        },
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "mcq",
        "prompt": "What does the $0 variable represent inside a bash script?",
        "options": ["The name of the script itself", "The first argument passed to the script", "The exit status of the last command", "The process ID of the script"],
        "correct_answer": "The name of the script itself",
        "explanation_correct": "$0 holds the name (or path) used to invoke the script, distinct from $1, $2, etc. which are the actual arguments.",
        "explanation_incorrect": {
            "The first argument passed to the script": "Wrong — that's $1; $0 refers to the script's own name.",
            "The exit status of the last command": "Wrong — that's $?, not $0.",
            "The process ID of the script": "Wrong — that's $$, not $0.",
        },
    },

    # ---------------- FILL-IN-BLANK (6) ----------------

    {
        "topic": "Bash", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command changes the shell's current working directory.",
        "options": None,
        "correct_answer": "cd",
        "explanation_correct": "`cd` changes the current directory to the one specified as its argument.",
        "explanation_incorrect": "The blank should be filled with the command used to change directories: cd.",
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The command `chmod ____ script.sh` (symbolic mode) makes a script executable.",
        "options": None,
        "correct_answer": "+x",
        "explanation_correct": "`chmod +x` adds execute permission to a file.",
        "explanation_incorrect": "The blank should be filled with the symbolic mode flag that adds execute permission: +x.",
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "In bash, a variable's value is accessed by prefixing its name with the ____ character, e.g. $name.",
        "options": None,
        "correct_answer": "$",
        "explanation_correct": "The dollar sign triggers variable expansion in bash, e.g. $name or ${name}.",
        "explanation_incorrect": "The blank should be filled with the character used to reference a variable's value: $.",
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ loop is used to iterate over a list of items in bash, as in: for item in list; do ... done.",
        "options": None,
        "correct_answer": "for",
        "explanation_correct": "The `for` loop iterates over each item in a given list or range.",
        "explanation_incorrect": "The blank should be filled with the loop keyword used for iterating over a list: for.",
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ symbol redirects a command's standard output to overwrite a file, e.g. echo hi ____ out.txt.",
        "options": None,
        "correct_answer": ">",
        "explanation_correct": "A single `>` redirects output to a file, overwriting any existing content.",
        "explanation_incorrect": "The blank should be filled with the redirection symbol that overwrites a file: >.",
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "To read a line of input from the user into a variable named name, use the ____ command, e.g. ____ name.",
        "options": None,
        "correct_answer": "read",
        "explanation_correct": "`read` captures a line of input from standard input into one or more variables.",
        "explanation_incorrect": "The blank should be filled with the command used to read user input: read.",
    },

    # ---------------- DRAG-AND-DROP (2) ----------------

    {
        "topic": "Bash", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured bash script that prints 'Hello, World!'.",
        "options": ["echo \"Hello, World!\"", "#!/bin/bash"],
        "correct_answer": '["#!/bin/bash", "echo \\"Hello, World!\\""]',
        "explanation_correct": "Correct — the shebang line must be the very first line of a script, before any commands.",
        "explanation_incorrect": "The shebang line must come first, at the very top of the file, before any executable commands.",
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured if statement that checks whether file.txt exists.",
        "options": ["fi", "  echo \"File exists\"", "if [ -f \"file.txt\" ]; then"],
        "correct_answer": '["if [ -f \\"file.txt\\" ]; then", "  echo \\"File exists\\"", "fi"]',
        "explanation_correct": "Correct — the if/then line opens the conditional block, the echo statement is the body that runs when true, and fi closes the block.",
        "explanation_incorrect": "The if line must come first to open the conditional, its body must come next, and fi must be last to properly close the block.",
    },

    # ---------------- DROPDOWN-ORDER (2) ----------------

    {
        "topic": "Bash", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to read the user's name and print a greeting.",
        "options": ["echo \"Hello, $name\"", "read -p \"Enter your name: \" name"],
        "correct_answer": '["read -p \\"Enter your name: \\" name", "echo \\"Hello, $name\\""]',
        "explanation_correct": "Correct — the name must be read into the variable before it can be referenced in the greeting message.",
        "explanation_incorrect": "The read command must run first to populate the name variable before it can be used in the echo statement.",
    },
    {
        "topic": "Bash", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to sum the numbers 1 through 5 in a loop and print the result.",
        "options": ["echo \"$sum\"", "sum=0", "for i in 1 2 3 4 5; do\n  sum=$((sum + i))\ndone"],
        "correct_answer": '["sum=0", "for i in 1 2 3 4 5; do\\n  sum=$((sum + i))\\ndone", "echo \\"$sum\\""]',
        "explanation_correct": "Correct — sum must be initialized before the loop accumulates into it, and the final value can only be printed after the loop finishes.",
        "explanation_incorrect": "The sum variable must be initialized before the loop runs, and printing the result must come after the loop has finished accumulating.",
    },
]
