"""
Bash - Medium batch, 50 questions total.
Distribution: 30 coding, 8 mcq, 6 fill-in-blank, 3 drag-and-drop, 3 dropdown-order.

Schema matches python_easy_questions.py / bash_easy_questions.py — see those files'
headers for full field notes.
"""

BASH_MEDIUM_QUESTIONS = [

    # ---------------- CODING (30) ----------------

    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash script that declares an associative array mapping fruit names to colors (including banana -> yellow), then prints the color of banana.",
        "correct_answer": "declare -A colors\ncolors[banana]=\"yellow\"\necho \"${colors[banana]}\"",
        "explanation_correct": "Correct — declare -A creates an associative array, and indexing it with the key 'banana' correctly retrieves its associated value.",
        "explanation_incorrect": "A correct solution must use `declare -A` to create an associative array with a banana key mapped to yellow, and print that value.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash function called sum_args that returns (via echo) the sum of all arguments passed to it.",
        "correct_answer": "sum_args() {\n  total=0\n  for n in \"$@\"; do\n    total=$((total + n))\n  done\n  echo \"$total\"\n}",
        "explanation_correct": "Correct — iterating over \"$@\" (all arguments) and accumulating them into total, then echoing the result, correctly sums an arbitrary number of arguments.",
        "explanation_incorrect": "A correct solution must sum every argument passed to the function (not just a fixed number of them) and echo the total.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner using parameter expansion that prints the value of variable user, or 'guest' if user is unset or empty, without modifying user itself.",
        "correct_answer": "echo \"${user:-guest}\"",
        "explanation_correct": "Correct — the ${var:-default} expansion returns the fallback value when the variable is unset or empty, without altering the variable's actual value.",
        "explanation_incorrect": "A correct solution must use the ${var:-default} form specifically, since ${var:=default} would also assign the default to the variable, which the prompt says not to do.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that extracts and prints the file extension from a filename stored in variable filename (e.g. 'archive.tar.gz' -> 'gz').",
        "correct_answer": "echo \"${filename##*.}\"",
        "explanation_correct": "Correct — the ${var##*.} expansion strips everything up to and including the last dot, leaving only the final extension.",
        "explanation_incorrect": "A correct solution must return only the portion of the filename after the final dot, correctly handling filenames with multiple dots.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash script that uses getopts to parse a -n flag with a required argument, and prints the value passed to -n.",
        "correct_answer": "while getopts \"n:\" opt; do\n  case $opt in\n    n) name=\"$OPTARG\" ;;\n  esac\ndone\necho \"$name\"",
        "explanation_correct": "Correct — the getopts loop with 'n:' correctly declares -n as taking a required argument, captured via $OPTARG and printed at the end.",
        "explanation_incorrect": "A correct solution must use getopts to parse the -n flag (with the colon indicating it takes an argument), capture the value via $OPTARG, and print it.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that finds all files in the current directory larger than 1MB.",
        "correct_answer": "find . -maxdepth 1 -type f -size +1M",
        "explanation_correct": "Correct — find with -type f, -size +1M, and -maxdepth 1 correctly limits the search to files in the current directory that exceed 1MB.",
        "explanation_incorrect": "A correct solution must locate files (not directories) larger than 1MB, typically using find with a -size +1M filter.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner using sed that replaces all occurrences of 'foo' with 'bar' in a file named data.txt, editing the file in place.",
        "correct_answer": "sed -i 's/foo/bar/g' data.txt",
        "explanation_correct": "Correct — the -i flag edits the file in place, and 's/foo/bar/g' substitutes every occurrence of 'foo' with 'bar' on each line.",
        "explanation_incorrect": "A correct solution must replace every occurrence of 'foo' with 'bar' (using the global flag) and modify the file itself, not just print the result.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner using awk that prints the second column of a space-separated file named data.txt.",
        "correct_answer": "awk '{print $2}' data.txt",
        "explanation_correct": "Correct — awk splits each line into fields by whitespace by default, and $2 refers to the second field.",
        "explanation_incorrect": "A correct solution must print only the second whitespace-separated field of each line in data.txt, typically using awk.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash script that traps the SIGINT signal (Ctrl+C) and prints 'Interrupted!' before exiting.",
        "correct_answer": "trap 'echo \"Interrupted!\"; exit' SIGINT\nwhile true; do\n  sleep 1\ndone",
        "explanation_correct": "Correct — the trap command registers a handler for SIGINT that prints the message and exits, overriding the default behavior of immediately terminating.",
        "explanation_incorrect": "A correct solution must use `trap` to register a handler for SIGINT that prints the message before the script exits.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that prints the count of unique lines in a file named data.txt.",
        "correct_answer": "sort data.txt | uniq | wc -l",
        "explanation_correct": "Correct — sorting the lines groups duplicates together, uniq collapses them to one occurrence each, and wc -l counts the result.",
        "explanation_incorrect": "A correct solution must count only distinct lines (not total lines), typically by combining sort, uniq, and wc -l.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash function is_integer that takes one argument and returns exit status 0 if it's a valid integer, or 1 otherwise (using return, not echo), using a regex match.",
        "correct_answer": "is_integer() {\n  if [[ \"$1\" =~ ^-?[0-9]+$ ]]; then\n    return 0\n  else\n    return 1\n  fi\n}",
        "explanation_correct": "Correct — the regex ^-?[0-9]+$ matches an optional leading minus sign followed by one or more digits, and the function returns the appropriate exit status based on the match.",
        "explanation_incorrect": "A correct solution must use `return` (not echo) to signal success/failure, and correctly identify valid integers (including negative ones) via a regex or equivalent check.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that uses xargs to delete every file whose name is listed (one per line) in a file named files_to_delete.txt.",
        "correct_answer": "xargs rm < files_to_delete.txt",
        "explanation_correct": "Correct — xargs reads each line from standard input as an argument to rm, deleting each listed file.",
        "explanation_incorrect": "A correct solution must read filenames from files_to_delete.txt and pass each one as an argument to rm, typically via xargs.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash script using an until loop that prints the numbers 1 through 5, each on its own line.",
        "correct_answer": "i=1\nuntil [ $i -gt 5 ]; do\n  echo \"$i\"\n  i=$((i + 1))\ndone",
        "explanation_correct": "Correct — the until loop continues running while its condition is false, so it correctly prints 1 through 5 and stops once i exceeds 5.",
        "explanation_incorrect": "A correct solution must use an until loop specifically (which runs while its condition is false) to print 1 through 5.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that prints the length of a string stored in variable s, using parameter expansion.",
        "correct_answer": "echo \"${#s}\"",
        "explanation_correct": "Correct — the ${#var} expansion returns the length of the string stored in var.",
        "explanation_incorrect": "A correct solution must use the ${#var} parameter expansion syntax to get the string's length, not an external command like wc unless clearly equivalent.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that runs two commands (task1 and task2, assume they exist) in the background and waits for both to finish before continuing.",
        "correct_answer": "task1 &\ntask2 &\nwait",
        "explanation_correct": "Correct — appending & backgrounds each command, and `wait` with no arguments blocks until all backgrounded jobs of the current shell have completed.",
        "explanation_incorrect": "A correct solution must background both commands (using &) and then use `wait` to block until they've both finished.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that redirects both standard output and standard error of a command (assume the command is `mycommand`) to a file named output.log.",
        "correct_answer": "mycommand > output.log 2>&1",
        "explanation_correct": "Correct — redirecting stdout to the file first, then redirecting stderr (2) to wherever stdout (1) now points, sends both streams to the same file.",
        "explanation_incorrect": "A correct solution must send both stdout and stderr into output.log, with the redirections in the correct order (stdout redirected before stderr is pointed at it).",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that runs a command (assume `mycommand`) and uses tee to both display its output on the terminal and save it to a file named output.log.",
        "correct_answer": "mycommand | tee output.log",
        "explanation_correct": "Correct — `tee` reads from standard input, writes it to the given file, and also passes it through to standard output, achieving both goals at once.",
        "explanation_incorrect": "A correct solution must both display the command's output and save it to a file simultaneously, typically using tee.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that prints the current date formatted as YYYY-MM-DD.",
        "correct_answer": "date +%Y-%m-%d",
        "explanation_correct": "Correct — the date command's +%Y-%m-%d format string produces a four-digit year, two-digit month, and two-digit day separated by hyphens.",
        "explanation_incorrect": "A correct solution must print today's date in exactly YYYY-MM-DD format, typically using the date command with a format string.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that finds and prints the 3 largest files in the current directory (by size).",
        "correct_answer": "du -a . | sort -rn | head -n 3",
        "explanation_correct": "Correct — listing files with sizes, sorting numerically in reverse (largest first), and taking the top 3 lines correctly identifies the largest files.",
        "explanation_incorrect": "A correct solution must identify and print the 3 largest files by size, typically combining du, sort, and head.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash script that reads a file named data.txt line by line, printing each line prefixed with its line number.",
        "correct_answer": "line_num=1\nwhile IFS= read -r line; do\n  echo \"$line_num: $line\"\n  line_num=$((line_num + 1))\ndone < data.txt",
        "explanation_correct": "Correct — reading line by line with `while read`, tracking a counter, and printing both the counter and the line correctly numbers each output line.",
        "explanation_incorrect": "A correct solution must read the file line by line (not word by word) and prefix each printed line with an incrementing line number.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a recursive bash function factorial that computes and echoes the factorial of its single numeric argument.",
        "correct_answer": "factorial() {\n  if [ \"$1\" -le 1 ]; then\n    echo 1\n  else\n    echo $(( $1 * $(factorial $(( $1 - 1 ))) ))\n  fi\n}",
        "explanation_correct": "Correct — the function calls itself with a decremented argument until it hits the base case (n <= 1 returns 1), then multiplies results back up the call chain.",
        "explanation_incorrect": "A correct solution must be recursive (the function calling itself) with a proper base case, correctly computing the product of all integers from 1 to n.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that removes duplicate lines from a file named data.txt, preserving the original order of first occurrences.",
        "correct_answer": "awk '!seen[$0]++' data.txt",
        "explanation_correct": "Correct — this awk idiom tracks each line seen in an associative array and only prints a line the first time it's encountered, preserving original order (unlike sort | uniq, which reorders lines).",
        "explanation_incorrect": "A correct solution must remove duplicate lines while keeping the first occurrence in its original position — plain `sort | uniq` would reorder the lines, which doesn't satisfy this requirement.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner using cut that extracts the first colon-separated field from the string 'user:x:1000:1000'.",
        "correct_answer": "echo \"user:x:1000:1000\" | cut -d: -f1",
        "explanation_correct": "Correct — specifying ':' as the delimiter and selecting field 1 correctly extracts the first colon-separated value.",
        "explanation_incorrect": "A correct solution must extract only the first colon-delimited field ('user'), typically using cut with -d: and -f1.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash function that declares a local variable named temp inside it (so it doesn't leak into the global scope), sets it to 'inside', and echoes it.",
        "correct_answer": "my_func() {\n  local temp=\"inside\"\n  echo \"$temp\"\n}",
        "explanation_correct": "Correct — using `local` scopes the temp variable to the function only, preventing it from overwriting or persisting as a global variable after the function returns.",
        "explanation_incorrect": "A correct solution must use the `local` keyword when declaring the variable inside the function, not a plain assignment which would create a global variable.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner using printf that formats the number 3.14159 to exactly two decimal places.",
        "correct_answer": "printf \"%.2f\\n\" 3.14159",
        "explanation_correct": "Correct — the %.2f format specifier rounds and displays a floating-point number to exactly two decimal places.",
        "explanation_incorrect": "A correct solution must print the number rounded/truncated to exactly two decimal places, typically using printf with a %.2f format specifier.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash script using a here-doc that writes the two lines 'line one' and 'line two' to a file named notes.txt.",
        "correct_answer": "cat << EOF > notes.txt\nline one\nline two\nEOF",
        "explanation_correct": "Correct — the here-doc syntax (cat << EOF ... EOF) feeds the enclosed lines to cat, and redirecting to notes.txt writes them to the file.",
        "explanation_incorrect": "A correct solution must use a here-doc (<<) construct to supply the multi-line text, redirected into notes.txt.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that checks if a command named 'docker' exists on the system, printing 'found' if it does.",
        "correct_answer": "command -v docker && echo \"found\"",
        "explanation_correct": "Correct — `command -v` checks whether a command exists in the shell's known commands/PATH, and && only runs the echo if that check succeeds.",
        "explanation_incorrect": "A correct solution must check for the existence of the docker command (typically via command -v or which) and only print 'found' if it exists.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that replaces every space in a string stored in variable s with an underscore, printing the result.",
        "correct_answer": "echo \"${s// /_}\"",
        "explanation_correct": "Correct — the ${var// /_} parameter expansion performs a global search-and-replace of spaces with underscores within the string.",
        "explanation_incorrect": "A correct solution must replace every space (not just the first) in the string with an underscore.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash script that iterates over the keys and values of an already-declared associative array named config, printing each key-value pair.",
        "correct_answer": "for key in \"${!config[@]}\"; do\n  echo \"$key: ${config[$key]}\"\ndone",
        "explanation_correct": "Correct — \"${!config[@]}\" expands to all the array's keys, and indexing config with each key inside the loop retrieves the corresponding value.",
        "explanation_incorrect": "A correct solution must iterate over both the keys and their corresponding values of the associative array, typically using \"${!array[@]}\" to get the keys.",
        "options": None,
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "coding",
        "prompt": "Write a bash one-liner that finds and kills all running processes matching the name 'myapp'.",
        "correct_answer": "pkill -f myapp",
        "explanation_correct": "Correct — `pkill -f` searches the full command line for a matching pattern and sends a termination signal to every matching process.",
        "explanation_incorrect": "A correct solution must locate and terminate every process matching 'myapp', typically using pkill (or an equivalent ps | grep | kill combination).",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the correct syntax to declare an associative array named arr in bash?",
        "options": ["declare -A arr", "declare -a arr", "array arr", "dict arr"],
        "correct_answer": "declare -A arr",
        "explanation_correct": "The uppercase -A flag with declare creates an associative (key-value) array in bash.",
        "explanation_incorrect": {
            "declare -a arr": "Wrong — lowercase -a declares a regular indexed array, not an associative one.",
            "array arr": "Wrong — `array` is not a valid bash declaration keyword.",
            "dict arr": "Wrong — `dict` is not a bash keyword; that syntax comes from other languages like Python.",
        },
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the bash parameter expansion `${var:-default}` do?",
        "options": [
            "Returns var's value if set and non-empty, otherwise 'default', without modifying var itself",
            "Assigns 'default' to var permanently if var is unset",
            "Raises an error if var is unset",
            "Deletes var if it's empty",
        ],
        "correct_answer": "Returns var's value if set and non-empty, otherwise 'default', without modifying var itself",
        "explanation_correct": "The `:-` form substitutes the default only for the current expansion — it doesn't change what var itself is set to. (The `:=` form is the one that would actually assign the default to var.)",
        "explanation_incorrect": {
            "Assigns 'default' to var permanently if var is unset": "Wrong — that describes ${var:=default}, a different expansion, not ${var:-default}.",
            "Raises an error if var is unset": "Wrong — that describes ${var:?message}, not ${var:-default}.",
            "Deletes var if it's empty": "Wrong — this expansion never deletes or unsets a variable.",
        },
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "Which built-in bash command is used to parse command-line options/flags within a script?",
        "options": ["getopts", "getopt2", "parseargs", "optparse"],
        "correct_answer": "getopts",
        "explanation_correct": "`getopts` is bash's built-in for parsing short-form command-line options inside a loop, one flag at a time.",
        "explanation_incorrect": {
            "getopt2": "Wrong — this isn't a real bash command.",
            "parseargs": "Wrong — this isn't a real bash builtin.",
            "optparse": "Wrong — optparse is a Python module, not a bash command.",
        },
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `trap` command do in a bash script?",
        "options": [
            "Executes a specified command when the script receives a given signal",
            "Pauses script execution indefinitely",
            "Automatically deletes temporary files when the script exits",
            "Restarts the script from the beginning",
        ],
        "correct_answer": "Executes a specified command when the script receives a given signal",
        "explanation_correct": "trap registers a handler that runs in response to a signal (like SIGINT) or a special event (like EXIT), allowing custom cleanup or messaging.",
        "explanation_incorrect": {
            "Pauses script execution indefinitely": "Wrong — trap doesn't pause anything by itself; it registers a response to a future event.",
            "Automatically deletes temporary files when the script exits": "Wrong — that behavior would have to be explicitly coded inside a trap handler (e.g. trap 'rm tmpfile' EXIT); trap itself doesn't do this automatically.",
            "Restarts the script from the beginning": "Wrong — trap doesn't restart execution; it runs a specified command in response to a signal.",
        },
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of the `xargs` command?",
        "options": [
            "Builds and executes commands using arguments read from standard input",
            "Compresses files into an archive",
            "Monitors currently running processes",
            "Schedules recurring cron jobs",
        ],
        "correct_answer": "Builds and executes commands using arguments read from standard input",
        "explanation_correct": "xargs takes items from standard input (often piped from another command) and uses them as arguments to build and run a specified command.",
        "explanation_incorrect": {
            "Compresses files into an archive": "Wrong — that's the role of tools like tar or gzip, not xargs.",
            "Monitors currently running processes": "Wrong — that's the role of tools like top or ps, not xargs.",
            "Schedules recurring cron jobs": "Wrong — cron jobs are configured via crontab, unrelated to xargs.",
        },
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `2>&1` do when added to the end of a command?",
        "options": [
            "Redirects standard error to wherever standard output is currently going",
            "Redirects standard output to standard error",
            "Runs the command twice",
            "Discards all output entirely",
        ],
        "correct_answer": "Redirects standard error to wherever standard output is currently going",
        "explanation_correct": "File descriptor 2 (stderr) is redirected to the current destination of file descriptor 1 (stdout), commonly used to merge both streams into the same file or pipe.",
        "explanation_incorrect": {
            "Redirects standard output to standard error": "Wrong — that would be `1>&2`, the reverse direction.",
            "Runs the command twice": "Wrong — this syntax is purely about stream redirection, not repeated execution.",
            "Discards all output entirely": "Wrong — discarding output would involve redirecting to /dev/null, not merging streams with 2>&1.",
        },
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the key difference between using `local` and a regular assignment for a variable inside a bash function?",
        "options": [
            "local scopes the variable to the function, while a regular assignment creates or modifies a global variable",
            "local makes the variable read-only",
            "Variables declared with local persist and remain accessible after the function returns",
            "There is no functional difference between the two",
        ],
        "correct_answer": "local scopes the variable to the function, while a regular assignment creates or modifies a global variable",
        "explanation_correct": "Without `local`, a variable assigned inside a function is global by default in bash, meaning it can overwrite an existing variable of the same name or persist after the function ends.",
        "explanation_incorrect": {
            "local makes the variable read-only": "Wrong — local controls scope, not mutability; a separate `readonly` keyword handles immutability.",
            "Variables declared with local persist and remain accessible after the function returns": "Wrong — that's backwards; local variables specifically go out of scope once the function returns.",
            "There is no functional difference between the two": "Wrong — scope is a real and significant difference, especially in scripts with multiple functions sharing variable names.",
        },
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `wait` command do in bash?",
        "options": [
            "Pauses the script until specified (or all) background jobs complete",
            "Pauses the script for a fixed number of seconds",
            "Cancels all currently running background jobs",
            "Restarts a background job that has failed",
        ],
        "correct_answer": "Pauses the script until specified (or all) background jobs complete",
        "explanation_correct": "`wait` blocks the shell until the given background job(s) (or all of them, if none are specified) finish executing.",
        "explanation_incorrect": {
            "Pauses the script for a fixed number of seconds": "Wrong — that describes the `sleep` command, not `wait`.",
            "Cancels all currently running background jobs": "Wrong — wait doesn't cancel jobs; it waits for them, and cancellation would require something like `kill`.",
            "Restarts a background job that has failed": "Wrong — wait doesn't restart or manage job failures, only waits for completion.",
        },
    },

    # ---------------- FILL-IN-BLANK (6) ----------------

    {
        "topic": "Bash", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "To declare an associative array in bash, use ____ -A arr_name.",
        "options": None,
        "correct_answer": "declare",
        "explanation_correct": "`declare -A` creates an associative array; without -A, declare creates a regular scalar or indexed array variable.",
        "explanation_incorrect": "The blank should be filled with the command used to declare variables/arrays with specific attributes: declare.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command parses command-line flags and their arguments inside a bash script, typically used inside a while loop.",
        "options": None,
        "correct_answer": "getopts",
        "explanation_correct": "getopts is bash's built-in option parser, processing one flag per loop iteration.",
        "explanation_incorrect": "The blank should be filled with the built-in command used to parse flags: getopts.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command executes a specified action when a script receives a given signal, such as SIGINT.",
        "options": None,
        "correct_answer": "trap",
        "explanation_correct": "trap registers a handler that runs in response to a received signal or shell event.",
        "explanation_incorrect": "The blank should be filled with the command used to register signal handlers: trap.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Declaring a variable with the ____ keyword inside a function scopes it to that function instead of the global shell environment.",
        "options": None,
        "correct_answer": "local",
        "explanation_correct": "`local` restricts a variable's visibility and lifetime to the function it's declared in.",
        "explanation_incorrect": "The blank should be filled with the keyword used to scope a variable to a function: local.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command builds and runs commands using input read from standard input, one item at a time (or in batches).",
        "options": None,
        "correct_answer": "xargs",
        "explanation_correct": "xargs converts input (often piped from another command) into arguments for building and executing a specified command.",
        "explanation_incorrect": "The blank should be filled with the command used to build commands from piped input: xargs.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command formats and prints text using a format string similar to C's printf, useful for precise number and text formatting.",
        "options": None,
        "correct_answer": "printf",
        "explanation_correct": "`printf` formats output according to a specified format string, offering more control than plain echo.",
        "explanation_incorrect": "The blank should be filled with the command used for formatted output: printf.",
    },

    # ---------------- DRAG-AND-DROP (3) ----------------

    {
        "topic": "Bash", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly ordered script that declares an associative array, sets a value, and prints it.",
        "options": ["echo \"${colors[banana]}\"", "declare -A colors", "colors[banana]=\"yellow\""],
        "correct_answer": '["declare -A colors", "colors[banana]=\\"yellow\\"", "echo \\"${colors[banana]}\\""]',
        "explanation_correct": "Correct — the array must be declared before a key can be assigned to it, and a value must be assigned before it can be printed.",
        "explanation_incorrect": "The array must be declared before any key can be set on it, and the key must be set before its value can be printed.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured until loop that prints numbers 1 through 5.",
        "options": ["i=1", "  echo \"$i\"\n  i=$((i + 1))\ndone", "until [ $i -gt 5 ]; do"],
        "correct_answer": '["i=1", "until [ $i -gt 5 ]; do", "  echo \\"$i\\"\\n  i=$((i + 1))\\ndone"]',
        "explanation_correct": "Correct — i must be initialized before the loop condition can check it, and the loop header must come before its body.",
        "explanation_incorrect": "The counter must be initialized before the until condition tests it, and the loop must be opened before its body can run.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured getopts loop that parses a -n flag and stores its value.",
        "options": ["done", "while getopts \"n:\" opt; do", "  case $opt in\n    n) name=\"$OPTARG\" ;;\n  esac"],
        "correct_answer": '["while getopts \\"n:\\" opt; do", "  case $opt in\\n    n) name=\\"$OPTARG\\" ;;\\n  esac", "done"]',
        "explanation_correct": "Correct — the while/getopts line opens the parsing loop, the case statement handles each recognized flag, and done closes the loop.",
        "explanation_incorrect": "The loop must be opened before the case statement handling each flag, and done must come last to close the loop.",
    },

    # ---------------- DROPDOWN-ORDER (3) ----------------

    {
        "topic": "Bash", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to write two lines of text to a file using a here-doc.",
        "options": ["EOF", "cat << EOF > notes.txt", "line one\nline two"],
        "correct_answer": '["cat << EOF > notes.txt", "line one\\nline two", "EOF"]',
        "explanation_correct": "Correct — the here-doc must be opened with the cat/redirect line, followed by the content, and closed with the matching EOF delimiter.",
        "explanation_incorrect": "The here-doc's opening line must come first, its content next, and the closing delimiter (EOF) must be the final line to properly terminate it.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to run two commands in the background and wait for both to finish.",
        "options": ["task2 &", "wait", "task1 &"],
        "correct_answer": '["task1 &", "task2 &", "wait"]',
        "explanation_correct": "Correct — both commands must be launched in the background before wait can be used to block until they've finished.",
        "explanation_incorrect": "Both background jobs must be started before wait is called, or there would be nothing running yet for wait to block on.",
    },
    {
        "topic": "Bash", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured recursive factorial function.",
        "options": ["factorial() {", "  if [ \"$1\" -le 1 ]; then\n    echo 1\n  else\n    echo $(( $1 * $(factorial $(( $1 - 1 ))) ))\n  fi", "}"],
        "correct_answer": '["factorial() {", "  if [ \\"$1\\" -le 1 ]; then\\n    echo 1\\n  else\\n    echo $(( $1 * $(factorial $(( $1 - 1 ))) ))\\n  fi", "}"]',
        "explanation_correct": "Correct — the function must be opened before its body (the base case check and recursive call) is defined, and closed only after.",
        "explanation_incorrect": "The function definition must be opened before its body can be declared inside it, and closed only after the logic is complete.",
    },
]
