"""
Kubernetes - Medium batch, 50 questions total.
Distribution: 15 coding, 9 mcq, 9 fill-in-blank, 9 drag-and-drop, 8 dropdown-order.
(Same weighting as kubernetes_easy_questions.py -- see that file's header for full field notes.)

Medium content covers Secrets, kubectl top/rollout/label/cp, Jobs/CronJobs, PVCs, Ingress,
HPA, kubectl explain/patch/diff, probes, init containers, StatefulSets, DaemonSets, taints/
tolerations, resource requests/limits, and imagePullPolicy.
"""

KUBERNETES_MEDIUM_QUESTIONS = [

    # ---------------- CODING (15) ----------------

    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to create a generic Secret named 'db-secret' with a literal key-value pair username=admin.",
        "correct_answer": "kubectl create secret generic db-secret --from-literal=username=admin",
        "explanation_correct": "Correct -- `kubectl create secret generic` with --from-literal creates a Secret containing the given key-value pair.",
        "explanation_incorrect": "A correct solution must create a generic Secret named db-secret with the username=admin literal, using kubectl create secret generic.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to view resource usage (CPU/memory) for all pods in the current namespace.",
        "correct_answer": "kubectl top pods",
        "explanation_correct": "Correct -- `kubectl top pods` shows current CPU and memory usage for pods in the current namespace, sourced from the metrics server.",
        "explanation_incorrect": "A correct solution must display pod resource usage, typically using kubectl top pods.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to view resource usage (CPU/memory) for all nodes in the cluster.",
        "correct_answer": "kubectl top nodes",
        "explanation_correct": "Correct -- `kubectl top nodes` shows current CPU and memory usage for each node in the cluster.",
        "explanation_incorrect": "A correct solution must display node resource usage, typically using kubectl top nodes.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to roll back a Deployment named 'web-deployment' to its previous revision.",
        "correct_answer": "kubectl rollout undo deployment web-deployment",
        "explanation_correct": "Correct -- `kubectl rollout undo` reverts the specified Deployment to its previous revision.",
        "explanation_incorrect": "A correct solution must roll back web-deployment specifically, using kubectl rollout undo.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to view the rollout history of a Deployment named 'web-deployment'.",
        "correct_answer": "kubectl rollout history deployment web-deployment",
        "explanation_correct": "Correct -- `kubectl rollout history` lists the revision history for the specified Deployment.",
        "explanation_incorrect": "A correct solution must show the rollout history for web-deployment specifically, using kubectl rollout history.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to add a label env=prod to a pod named 'web-pod'.",
        "correct_answer": "kubectl label pod web-pod env=prod",
        "explanation_correct": "Correct -- `kubectl label` attaches the given key-value label to the specified resource.",
        "explanation_incorrect": "A correct solution must add the env=prod label to web-pod specifically, using kubectl label pod.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to copy a local file app.log into a pod named 'web-pod' at path /tmp/app.log.",
        "correct_answer": "kubectl cp app.log web-pod:/tmp/app.log",
        "explanation_correct": "Correct -- `kubectl cp` copies files between the local filesystem and a container, using the pod:path syntax for the destination.",
        "explanation_incorrect": "A correct solution must copy app.log into web-pod at exactly /tmp/app.log, using kubectl cp.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to list all Jobs in the current namespace.",
        "correct_answer": "kubectl get jobs",
        "explanation_correct": "Correct -- `kubectl get jobs` lists all Job resources in the current namespace.",
        "explanation_incorrect": "A correct solution must list Jobs specifically, using kubectl get jobs.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to list all CronJobs in the current namespace.",
        "correct_answer": "kubectl get cronjobs",
        "explanation_correct": "Correct -- `kubectl get cronjobs` lists all CronJob resources in the current namespace.",
        "explanation_incorrect": "A correct solution must list CronJobs specifically, using kubectl get cronjobs.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to list all PersistentVolumeClaims in the current namespace.",
        "correct_answer": "kubectl get pvc",
        "explanation_correct": "Correct -- `kubectl get pvc` lists all PersistentVolumeClaim resources in the current namespace.",
        "explanation_incorrect": "A correct solution must list PersistentVolumeClaims specifically, using kubectl get pvc.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to list all Ingress resources in the current namespace.",
        "correct_answer": "kubectl get ingress",
        "explanation_correct": "Correct -- `kubectl get ingress` lists all Ingress resources in the current namespace.",
        "explanation_incorrect": "A correct solution must list Ingress resources specifically, using kubectl get ingress.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to create a HorizontalPodAutoscaler for a Deployment named 'web-deployment', targeting 50% CPU utilization, with a minimum of 2 and a maximum of 10 replicas.",
        "correct_answer": "kubectl autoscale deployment web-deployment --cpu-percent=50 --min=2 --max=10",
        "explanation_correct": "Correct -- `kubectl autoscale` creates an HPA targeting the given CPU utilization percentage, with the specified min/max replica bounds.",
        "explanation_incorrect": "A correct solution must create an HPA with exactly 50% CPU target, min 2, and max 10 replicas, using kubectl autoscale deployment.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to display documentation for the Pod resource's spec.containers field.",
        "correct_answer": "kubectl explain pod.spec.containers",
        "explanation_correct": "Correct -- `kubectl explain` shows the documentation and type information for the specified resource field, sourced from the cluster's API schema.",
        "explanation_incorrect": "A correct solution must show documentation for pod.spec.containers specifically, using kubectl explain.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to patch a Deployment named 'web-deployment', setting its replica count to 3, using a strategic merge patch.",
        "correct_answer": "kubectl patch deployment web-deployment -p '{\"spec\":{\"replicas\":3}}'",
        "explanation_correct": "Correct -- `kubectl patch` with a JSON merge patch body updates just the specified field (replicas) without needing to reapply the entire manifest.",
        "explanation_incorrect": "A correct solution must patch web-deployment's replicas field to 3 specifically, using kubectl patch with a merge patch body.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "coding",
        "prompt": "Write the kubectl command to view the diff between a local manifest file deployment.yaml and the live cluster state.",
        "correct_answer": "kubectl diff -f deployment.yaml",
        "explanation_correct": "Correct -- `kubectl diff -f` compares the given manifest against what's currently applied in the cluster, without actually applying any changes.",
        "explanation_incorrect": "A correct solution must diff deployment.yaml against the live cluster state specifically, using kubectl diff -f.",
        "options": None,
    },

    # ---------------- MCQ (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a liveness probe?",
        "options": [
            "Determines whether a container is still running correctly; if it fails, Kubernetes restarts the container",
            "Determines whether a pod is ready to receive traffic",
            "Checks the health of the node the pod is running on",
            "Validates a container image's cryptographic signature",
        ],
        "correct_answer": "Determines whether a container is still running correctly; if it fails, Kubernetes restarts the container",
        "explanation_correct": "A liveness probe periodically checks whether a container is still functioning; a failure triggers a restart, helping recover from hung or deadlocked processes.",
        "explanation_incorrect": {
            "Determines whether a pod is ready to receive traffic": "Wrong — that's the role of a readiness probe, a distinct mechanism from liveness.",
            "Checks the health of the node the pod is running on": "Wrong — node health is monitored separately by the kubelet/node controller, not by a container's liveness probe.",
            "Validates a container image's cryptographic signature": "Wrong — image signature verification is a separate concern (e.g. via admission controllers), unrelated to liveness probes.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a readiness probe?",
        "options": [
            "Determines whether a pod is ready to receive traffic; if it fails, the pod is removed from service endpoints",
            "Automatically restarts a failed container",
            "Checks available disk space on the node",
            "Validates RBAC permissions for the pod",
        ],
        "correct_answer": "Determines whether a pod is ready to receive traffic; if it fails, the pod is removed from service endpoints",
        "explanation_correct": "A readiness probe controls whether a pod is included in a Service's load-balancing rotation, preventing traffic from reaching a pod that isn't actually ready to handle it.",
        "explanation_incorrect": {
            "Automatically restarts a failed container": "Wrong — that's the role of a liveness probe, a distinct mechanism from readiness.",
            "Checks available disk space on the node": "Wrong — readiness probes check application-level readiness, not node disk space.",
            "Validates RBAC permissions for the pod": "Wrong — RBAC is a separate authorization mechanism, unrelated to readiness probes.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of an init container?",
        "options": [
            "Runs and completes before the main application containers start, useful for setup tasks",
            "Runs alongside the main container for the pod's entire lifetime",
            "Replaces the main container if it fails",
            "Is only used for collecting logs",
        ],
        "correct_answer": "Runs and completes before the main application containers start, useful for setup tasks",
        "explanation_correct": "Init containers run sequentially to completion before any main containers start, commonly used for setup tasks like waiting for a dependency or preparing files.",
        "explanation_incorrect": {
            "Runs alongside the main container for the pod's entire lifetime": "Wrong — that describes a sidecar container pattern, not an init container, which finishes before the main containers even start.",
            "Replaces the main container if it fails": "Wrong — init containers aren't a failover mechanism for the main container; they run once, upfront, before it.",
            "Is only used for collecting logs": "Wrong — log collection is one possible sidecar use case, but init containers are specifically about pre-start setup, not an ongoing logging role.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is a StatefulSet used for, as opposed to a Deployment?",
        "options": [
            "Managing stateful applications that need stable, unique network identities and persistent storage per pod",
            "Managing purely stateless applications only",
            "Automatically scheduling exactly one pod per node",
            "Managing ConfigMaps across the cluster",
        ],
        "correct_answer": "Managing stateful applications that need stable, unique network identities and persistent storage per pod",
        "explanation_correct": "Unlike a Deployment's interchangeable pods, a StatefulSet gives each pod a stable, unique identity and (optionally) its own persistent storage, well suited for databases and similar stateful workloads.",
        "explanation_incorrect": {
            "Managing purely stateless applications only": "Wrong — that's better suited to a Deployment; StatefulSets exist specifically for the stateful case.",
            "Automatically scheduling exactly one pod per node": "Wrong — that describes a DaemonSet's behavior, not a StatefulSet.",
            "Managing ConfigMaps across the cluster": "Wrong — ConfigMap management is unrelated to StatefulSets, which manage pod identity and storage.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is a DaemonSet used for?",
        "options": [
            "Ensures a copy of a pod runs on every (or selected) node in the cluster, typically for node-level agents",
            "Manages a fixed number of replicas regardless of how many nodes exist",
            "Runs one-time batch jobs only",
            "Manages persistent storage allocation cluster-wide",
        ],
        "correct_answer": "Ensures a copy of a pod runs on every (or selected) node in the cluster, typically for node-level agents",
        "explanation_correct": "DaemonSets automatically place one pod instance on every node (or a selected subset), commonly used for things like log collectors, monitoring agents, or networking components.",
        "explanation_incorrect": {
            "Manages a fixed number of replicas regardless of how many nodes exist": "Wrong — that describes a Deployment/ReplicaSet's behavior; a DaemonSet's replica count scales with the number of matching nodes, not a fixed number.",
            "Runs one-time batch jobs only": "Wrong — that's the role of a Job, a completely different resource from a DaemonSet.",
            "Manages persistent storage allocation cluster-wide": "Wrong — storage allocation is handled by PersistentVolumes/Claims and storage classes, unrelated to DaemonSets.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of resource requests and limits on a container?",
        "options": [
            "Requests specify the minimum resources guaranteed, and limits specify the maximum allowed — helping the scheduler and preventing resource exhaustion",
            "They are purely informational and have no effect on scheduling",
            "Requests and limits must always be set to the same value",
            "Only limits can be set on a container, never requests",
        ],
        "correct_answer": "Requests specify the minimum resources guaranteed, and limits specify the maximum allowed — helping the scheduler and preventing resource exhaustion",
        "explanation_correct": "Requests inform the scheduler how much of a resource a container needs to be placed on a node, while limits cap how much it can actually consume, protecting other workloads from resource exhaustion.",
        "explanation_incorrect": {
            "They are purely informational and have no effect on scheduling": "Wrong — requests directly influence scheduling decisions, and limits are actively enforced at runtime; neither is merely informational.",
            "Requests and limits must always be set to the same value": "Wrong — they can differ (and often do); setting them equal is a specific choice (Guaranteed QoS), not a requirement.",
            "Only limits can be set on a container, never requests": "Wrong — both requests and limits can be independently specified on a container.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is a Kubernetes Job used for?",
        "options": [
            "Runs a pod to completion for a given task, retrying on failure, rather than running indefinitely",
            "Running a long-lived web server that should always be up",
            "Exposing a pod's network endpoint to other pods",
            "Storing configuration data for other resources",
        ],
        "correct_answer": "Runs a pod to completion for a given task, retrying on failure, rather than running indefinitely",
        "explanation_correct": "A Job creates pods to perform a task and tracks their successful completion, retrying failed attempts up to a configured limit, unlike a Deployment which keeps pods running indefinitely.",
        "explanation_incorrect": {
            "Running a long-lived web server that should always be up": "Wrong — that's the use case for a Deployment, not a Job, which is designed for finite, completing tasks.",
            "Exposing a pod's network endpoint to other pods": "Wrong — that's the role of a Service, unrelated to a Job's purpose.",
            "Storing configuration data for other resources": "Wrong — that's the role of a ConfigMap, unrelated to a Job.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of taints and tolerations?",
        "options": [
            "Taints on nodes repel pods unless the pod has a matching toleration, allowing control over which pods can be scheduled where",
            "Taints encrypt traffic between nodes",
            "Tolerations define a pod's resource limits",
            "Taints are a type of network policy restricting pod communication",
        ],
        "correct_answer": "Taints on nodes repel pods unless the pod has a matching toleration, allowing control over which pods can be scheduled where",
        "explanation_correct": "A taint marks a node as generally unsuitable for pods, and only pods with a matching toleration are allowed to be scheduled there, giving fine-grained control over pod placement (e.g. reserving nodes for specific workloads).",
        "explanation_incorrect": {
            "Taints encrypt traffic between nodes": "Wrong — taints are about scheduling eligibility, not encryption, which is an unrelated concern.",
            "Tolerations define a pod's resource limits": "Wrong — resource limits are set separately via the container's resources field, unrelated to tolerations.",
            "Taints are a type of network policy restricting pod communication": "Wrong — taints affect scheduling placement, not network-level traffic rules, which are the role of NetworkPolicy.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `imagePullPolicy: Always` on a container specify?",
        "options": [
            "The kubelet always pulls the image from the registry before starting the container, even if a local copy already exists",
            "The image is pulled only once, ever, per cluster",
            "Images are never pulled and must be pre-loaded onto every node",
            "The policy only applies to init containers, not regular containers",
        ],
        "correct_answer": "The kubelet always pulls the image from the registry before starting the container, even if a local copy already exists",
        "explanation_correct": "With Always, the kubelet checks the registry and pulls the image every time the container starts, ensuring the latest version at that tag is used rather than relying on a potentially stale cached copy.",
        "explanation_incorrect": {
            "The image is pulled only once, ever, per cluster": "Wrong — that behavior is closer to IfNotPresent (per node, not per cluster), the opposite of what Always does.",
            "Images are never pulled and must be pre-loaded onto every node": "Wrong — that describes a Never policy, which requires the image to already exist locally, the opposite of Always.",
            "The policy only applies to init containers, not regular containers": "Wrong — imagePullPolicy applies to any container (init or regular) it's set on; it isn't restricted to init containers.",
        },
    },

    # ---------------- FILL-IN-BLANK (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ probe determines whether a container is still running correctly; if it fails, Kubernetes restarts the container.",
        "options": None,
        "correct_answer": "liveness",
        "explanation_correct": "A liveness probe triggers a container restart if it detects the container is no longer functioning correctly.",
        "explanation_incorrect": "The blank should be filled with the name of this probe type: liveness.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ probe determines whether a pod is ready to receive traffic; if it fails, the pod is removed from service endpoints.",
        "options": None,
        "correct_answer": "readiness",
        "explanation_correct": "A readiness probe controls whether a pod is included in a Service's active endpoint list.",
        "explanation_incorrect": "The blank should be filled with the name of this probe type: readiness.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "An ____ container runs and completes before the main application containers in a pod start, useful for setup tasks.",
        "options": None,
        "correct_answer": "init",
        "explanation_correct": "Init containers run sequentially to completion before any main containers start.",
        "explanation_incorrect": "The blank should be filled with the name of this container type: init.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ is used for managing stateful applications that need stable, unique network identities and persistent storage per pod.",
        "options": None,
        "correct_answer": "StatefulSet",
        "explanation_correct": "StatefulSets give each pod a stable identity and optional dedicated persistent storage.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: StatefulSet.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ ensures a copy of a pod runs on every (or selected) node in the cluster, typically used for node-level agents.",
        "options": None,
        "correct_answer": "DaemonSet",
        "explanation_correct": "DaemonSets place one pod instance per matching node, common for monitoring or logging agents.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: DaemonSet.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A Kubernetes ____ runs a pod to completion for a given task, retrying on failure, rather than running indefinitely.",
        "options": None,
        "correct_answer": "Job",
        "explanation_correct": "A Job manages pods that run a finite task to completion.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: Job.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ is a Job that runs on a repeating schedule, similar to a cron entry.",
        "options": None,
        "correct_answer": "CronJob",
        "explanation_correct": "CronJobs create Jobs on a defined recurring schedule.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: CronJob.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "____ on nodes repel pods unless the pod has a matching toleration, allowing control over which pods can be scheduled where.",
        "options": None,
        "correct_answer": "Taints",
        "explanation_correct": "Taints mark nodes as unsuitable for pods that lack a matching toleration.",
        "explanation_incorrect": "The blank should be filled with the term for this node-level scheduling restriction: Taints.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A Horizontal Pod ____ automatically adjusts the number of pod replicas based on observed metrics like CPU utilization.",
        "options": None,
        "correct_answer": "Autoscaler",
        "explanation_correct": "The Horizontal Pod Autoscaler (HPA) scales replica counts up or down based on observed metrics.",
        "explanation_incorrect": "The blank should be filled with the second word of this resource's name: Autoscaler.",
    },

    # ---------------- DRAG-AND-DROP (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a Horizontal Pod Autoscaler for a Deployment.",
        "options": ["Monitor `kubectl get hpa` to observe scaling behavior under load", "Ensure the Deployment has resource requests defined (required for CPU-based scaling)", "Run `kubectl autoscale deployment web-deployment --cpu-percent=50 --min=2 --max=10`"],
        "correct_answer": '["Ensure the Deployment has resource requests defined (required for CPU-based scaling)", "Run `kubectl autoscale deployment web-deployment --cpu-percent=50 --min=2 --max=10`", "Monitor `kubectl get hpa` to observe scaling behavior under load"]',
        "explanation_correct": "Correct -- resource requests must be set before CPU-based autoscaling can function, the HPA must be created before scaling behavior can be observed, and monitoring is the final step.",
        "explanation_incorrect": "Resource requests are a prerequisite for CPU-based HPA to work at all, the autoscaler must be created before there's anything to monitor, and monitoring naturally comes last.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for rolling back a bad Deployment update.",
        "options": ["Confirm pods return to a healthy state", "Notice the new rollout is causing issues (e.g. failing health checks)", "Run `kubectl rollout undo deployment web-deployment` to revert to the previous revision"],
        "correct_answer": '["Notice the new rollout is causing issues (e.g. failing health checks)", "Run `kubectl rollout undo deployment web-deployment` to revert to the previous revision", "Confirm pods return to a healthy state"]',
        "explanation_correct": "Correct -- the problem must be noticed before a rollback is initiated, and confirming recovery is the final step once the rollback has been applied.",
        "explanation_incorrect": "The issue must be identified before triggering a rollback, and confirming that pods recovered is the natural final verification step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for using a Secret as a pod environment variable.",
        "options": ["Deploy the pod, which reads the secret value at runtime", "Create the Secret with `kubectl create secret generic db-secret --from-literal=username=admin`", "Reference the Secret in the pod's manifest as an environment variable source"],
        "correct_answer": '["Create the Secret with `kubectl create secret generic db-secret --from-literal=username=admin`", "Reference the Secret in the pod\'s manifest as an environment variable source", "Deploy the pod, which reads the secret value at runtime"]',
        "explanation_correct": "Correct -- the Secret must exist before a pod manifest can reference it, and the pod must be deployed before it can actually read the referenced value.",
        "explanation_incorrect": "The Secret must be created before it can be referenced in a pod manifest, and the pod must be deployed before it can consume that value at runtime.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a Job to run a batch task.",
        "options": ["Run `kubectl get jobs` to monitor completion status", "Write a Job manifest specifying the container and command to run", "Run `kubectl apply -f job.yaml` to create it"],
        "correct_answer": '["Write a Job manifest specifying the container and command to run", "Run `kubectl apply -f job.yaml` to create it", "Run `kubectl get jobs` to monitor completion status"]',
        "explanation_correct": "Correct -- the manifest must exist before it can be applied, and monitoring status only makes sense once the Job actually exists in the cluster.",
        "explanation_incorrect": "The Job manifest must be written before it can be applied, and monitoring completion is the natural final step once the Job is running.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing a pod stuck in Pending state due to taints.",
        "options": ["Add a matching toleration to the pod spec if the taint is intentional", "Run `kubectl describe pod <name>` and review the events for scheduling failures", "Check node taints with `kubectl describe node <name>`"],
        "correct_answer": '["Run `kubectl describe pod <name>` and review the events for scheduling failures", "Check node taints with `kubectl describe node <name>`", "Add a matching toleration to the pod spec if the taint is intentional"]',
        "explanation_correct": "Correct -- the pod's scheduling failure events must be observed before investigating node taints as a cause, and adding a toleration is the resolution step once the taint is confirmed as the reason.",
        "explanation_incorrect": "The pod's own events should be checked first to spot a scheduling issue, then node taints investigated as a likely cause, with adding a toleration as the final fix.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up persistent storage for a StatefulSet.",
        "options": ["Verify each pod has its own persistent volume with `kubectl get pvc`", "Define a PersistentVolumeClaim template within the StatefulSet manifest", "Apply the StatefulSet, which provisions a unique PVC per replica"],
        "correct_answer": '["Define a PersistentVolumeClaim template within the StatefulSet manifest", "Apply the StatefulSet, which provisions a unique PVC per replica", "Verify each pod has its own persistent volume with `kubectl get pvc`"]',
        "explanation_correct": "Correct -- the PVC template must be defined before applying the StatefulSet, and verification only makes sense after the StatefulSet has actually provisioned the claims.",
        "explanation_incorrect": "The PVC template must be part of the manifest before applying it, and checking the resulting PVCs is the natural final verification step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for exposing an application externally via Ingress.",
        "options": ["Apply the Ingress and verify external access through the configured host/path", "Create a Service exposing the application internally", "Write an Ingress resource routing external traffic to that Service"],
        "correct_answer": '["Create a Service exposing the application internally", "Write an Ingress resource routing external traffic to that Service", "Apply the Ingress and verify external access through the configured host/path"]',
        "explanation_correct": "Correct -- the Service must exist before an Ingress can route to it, and applying/verifying the Ingress is the final step once both are in place.",
        "explanation_incorrect": "The internal Service must exist before an Ingress resource can reference it, and applying and verifying the Ingress is the final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for using kubectl patch to make a quick live change.",
        "options": ["Run `kubectl get deployment web-deployment -o yaml` to confirm the patch applied", "Identify the resource and field that needs to change", "Run `kubectl patch deployment web-deployment -p '{...}'` with the desired change"],
        "correct_answer": '["Identify the resource and field that needs to change", "Run `kubectl patch deployment web-deployment -p \'{...}\'` with the desired change", "Run `kubectl get deployment web-deployment -o yaml` to confirm the patch applied"]',
        "explanation_correct": "Correct -- the target field must be identified before a patch can be written for it, and confirming the change is the final verification step after patching.",
        "explanation_incorrect": "The specific field to change must be identified before writing the patch command, and verifying the result is the natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for previewing changes before applying a manifest update.",
        "options": ["Run `kubectl apply -f deployment.yaml` once satisfied with the diff", "Modify the local manifest file", "Run `kubectl diff -f deployment.yaml` to preview the changes"],
        "correct_answer": '["Modify the local manifest file", "Run `kubectl diff -f deployment.yaml` to preview the changes", "Run `kubectl apply -f deployment.yaml` once satisfied with the diff"]',
        "explanation_correct": "Correct -- the manifest must be modified before there's anything new to diff, and the actual apply should follow only after reviewing that diff.",
        "explanation_incorrect": "The manifest must be changed before diff has anything meaningful to show, and applying the change should come only after reviewing the diff.",
    },

    # ---------------- DROPDOWN-ORDER (8) ----------------

    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up an init container for a setup task.",
        "options": ["The main application container starts once all init containers have succeeded", "Define an initContainers section in the pod spec with the setup task", "The init container runs and completes before the main container starts"],
        "correct_answer": '["Define an initContainers section in the pod spec with the setup task", "The init container runs and completes before the main container starts", "The main application container starts once all init containers have succeeded"]',
        "explanation_correct": "Correct -- the init container must be defined before it can run, and the main container only starts after the defined init containers have completed successfully.",
        "explanation_incorrect": "The init container must be defined in the spec before it can execute, and the main container only starts once that init container has finished.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for configuring liveness and readiness probes on a pod.",
        "options": ["Deploy the pod and monitor its status via `kubectl get pods`", "Define a readinessProbe so the pod isn't sent traffic until it's ready", "Define a livenessProbe so Kubernetes can detect and restart a hung container"],
        "correct_answer": '["Define a readinessProbe so the pod isn\'t sent traffic until it\'s ready", "Define a livenessProbe so Kubernetes can detect and restart a hung container", "Deploy the pod and monitor its status via `kubectl get pods`"]',
        "explanation_correct": "Correct -- both probes should be defined in the manifest before deployment, and monitoring the resulting pod status is the final step once it's actually running.",
        "explanation_incorrect": "Both probes need to be defined in the pod spec before deployment, and checking pod status is the natural final step after deploying.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using kubectl explain to understand a resource field.",
        "options": ["Use that understanding to correctly write the manifest field", "Run `kubectl explain pod.spec.containers` to see field documentation", "Review the field's type and description"],
        "correct_answer": '["Run `kubectl explain pod.spec.containers` to see field documentation", "Review the field\'s type and description", "Use that understanding to correctly write the manifest field"]',
        "explanation_correct": "Correct -- the documentation must be retrieved before it can be reviewed, and writing the manifest field correctly follows from that understanding.",
        "explanation_incorrect": "The explain output must be retrieved before it can be reviewed, and applying that understanding to the manifest is the natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for creating and using a ServiceAccount with limited permissions.",
        "options": ["Assign the ServiceAccount to a pod via its manifest", "Create a ServiceAccount", "Create a Role and RoleBinding granting it specific permissions"],
        "correct_answer": '["Create a ServiceAccount", "Create a Role and RoleBinding granting it specific permissions", "Assign the ServiceAccount to a pod via its manifest"]',
        "explanation_correct": "Correct -- the ServiceAccount must exist before permissions can be bound to it, and it must have its permissions configured before being assigned meaningfully to a pod.",
        "explanation_incorrect": "The ServiceAccount must exist before a RoleBinding can reference it, and assigning it to a pod is the final step once its permissions are configured.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for troubleshooting a CrashLoopBackOff pod.",
        "options": ["Identify and fix the underlying application error causing the crash", "Run `kubectl get pods` and notice the CrashLoopBackOff status", "Run `kubectl logs <pod> --previous` to see logs from the crashed container"],
        "correct_answer": '["Run `kubectl get pods` and notice the CrashLoopBackOff status", "Run `kubectl logs <pod> --previous` to see logs from the crashed container", "Identify and fix the underlying application error causing the crash"]',
        "explanation_correct": "Correct -- the crash status must be noticed before investigating logs, and fixing the root cause follows once the logs reveal what went wrong.",
        "explanation_incorrect": "The CrashLoopBackOff status must be observed before digging into the crashed container's logs, and fixing the issue follows once the cause is understood from those logs.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting resource requests and limits on a container.",
        "options": ["Add both to the container spec and apply the updated manifest", "Determine appropriate CPU/memory requests based on expected usage", "Determine appropriate CPU/memory limits to cap resource consumption"],
        "correct_answer": '["Determine appropriate CPU/memory requests based on expected usage", "Determine appropriate CPU/memory limits to cap resource consumption", "Add both to the container spec and apply the updated manifest"]',
        "explanation_correct": "Correct -- appropriate request and limit values should be determined before they're written into the manifest and applied.",
        "explanation_incorrect": "Sizing decisions for requests and limits should be made before adding them to the manifest, with applying the change as the final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a rolling update with tuned maxSurge/maxUnavailable settings.",
        "options": ["Observe pods being replaced gradually according to the configured strategy", "Configure the Deployment's rolling update strategy with maxSurge and maxUnavailable values", "Trigger an update by changing the pod template (e.g. new image)"],
        "correct_answer": '["Configure the Deployment\'s rolling update strategy with maxSurge and maxUnavailable values", "Trigger an update by changing the pod template (e.g. new image)", "Observe pods being replaced gradually according to the configured strategy"]',
        "explanation_correct": "Correct -- the strategy must be configured before an update is triggered, and observing the replacement behavior is the final step once the update is underway.",
        "explanation_incorrect": "The rolling update strategy must be configured before triggering the actual update, and observing the resulting behavior is the natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for verifying RBAC permissions for a ServiceAccount.",
        "options": ["Adjust the Role/RoleBinding if the permission is missing or incorrect", "Run `kubectl auth can-i <verb> <resource> --as=system:serviceaccount:<namespace>:<name>` to check a specific permission", "Review the result to confirm whether the action is allowed"],
        "correct_answer": '["Run `kubectl auth can-i <verb> <resource> --as=system:serviceaccount:<namespace>:<name>` to check a specific permission", "Review the result to confirm whether the action is allowed", "Adjust the Role/RoleBinding if the permission is missing or incorrect"]',
        "explanation_correct": "Correct -- the permission check must run before its result can be reviewed, and adjusting the RBAC configuration only happens once a gap has been identified.",
        "explanation_incorrect": "The can-i check must run before its yes/no result can be reviewed, and adjusting the Role/RoleBinding follows only if that review reveals a missing permission.",
    },
]
