"""
Kubernetes - Hard batch, 50 questions total.
Distribution: 15 coding, 9 mcq, 9 fill-in-blank, 9 drag-and-drop, 8 dropdown-order.
(Same weighting as kubernetes_easy_questions.py -- see that file's header for full field notes.)

Hard content covers admission controllers/webhooks, CRDs, the Operator pattern,
PodDisruptionBudgets, anti-affinity, RBAC ClusterRoles, owner references/garbage
collection, static pods, topology spread constraints, ephemeral debug containers,
ResourceQuotas/LimitRanges, PriorityClasses, CSI drivers, Helm, kustomize, and
workload identity.
"""

KUBERNETES_HARD_QUESTIONS = [

    # ---------------- CODING (15) ----------------

    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to attach an interactive ephemeral debug container (using image busybox) to a running pod named 'web-pod'.",
        "correct_answer": "kubectl debug web-pod -it --image=busybox",
        "explanation_correct": "Correct -- `kubectl debug` with -it and --image attaches an interactive ephemeral container to the running pod for troubleshooting, without restarting it.",
        "explanation_incorrect": "A correct solution must attach an interactive debug container using the busybox image to web-pod specifically, using kubectl debug.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to list all events in the current namespace, sorted by creation timestamp.",
        "correct_answer": "kubectl get events --sort-by=.metadata.creationTimestamp",
        "explanation_correct": "Correct -- `kubectl get events` with --sort-by=.metadata.creationTimestamp lists namespace events in chronological order.",
        "explanation_incorrect": "A correct solution must list events sorted by creation timestamp specifically, using kubectl get events --sort-by.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to create a ClusterRole named 'pod-reader' that allows get and list verbs on pods, cluster-wide.",
        "correct_answer": "kubectl create clusterrole pod-reader --verb=get,list --resource=pods",
        "explanation_correct": "Correct -- `kubectl create clusterrole` with the given verbs and resource creates a cluster-scoped RBAC role permitting get/list on pods.",
        "explanation_incorrect": "A correct solution must create a ClusterRole named pod-reader with exactly get and list verbs on pods.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to bind the ClusterRole 'pod-reader' to a user named 'jane' via a ClusterRoleBinding.",
        "correct_answer": "kubectl create clusterrolebinding pod-reader-binding --clusterrole=pod-reader --user=jane",
        "explanation_correct": "Correct -- `kubectl create clusterrolebinding` associates the specified ClusterRole with the given user, granting them its permissions cluster-wide.",
        "explanation_incorrect": "A correct solution must bind the pod-reader ClusterRole to user jane specifically, using kubectl create clusterrolebinding.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view all Custom Resource Definitions (CRDs) installed in the cluster.",
        "correct_answer": "kubectl get crds",
        "explanation_correct": "Correct -- `kubectl get crds` lists every CustomResourceDefinition registered with the cluster's API server.",
        "explanation_incorrect": "A correct solution must list CRDs specifically, using kubectl get crds.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view the current ResourceQuota objects in the current namespace.",
        "correct_answer": "kubectl get resourcequota",
        "explanation_correct": "Correct -- `kubectl get resourcequota` lists ResourceQuota objects in the current namespace.",
        "explanation_incorrect": "A correct solution must list ResourceQuota objects specifically, using kubectl get resourcequota.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view the current LimitRange objects in the current namespace.",
        "correct_answer": "kubectl get limitrange",
        "explanation_correct": "Correct -- `kubectl get limitrange` lists LimitRange objects in the current namespace.",
        "explanation_incorrect": "A correct solution must list LimitRange objects specifically, using kubectl get limitrange.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view all PriorityClasses defined in the cluster.",
        "correct_answer": "kubectl get priorityclasses",
        "explanation_correct": "Correct -- `kubectl get priorityclasses` lists all cluster-scoped PriorityClass objects.",
        "explanation_incorrect": "A correct solution must list PriorityClasses specifically, using kubectl get priorityclasses.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view the current PodDisruptionBudgets in the current namespace.",
        "correct_answer": "kubectl get pdb",
        "explanation_correct": "Correct -- `kubectl get pdb` lists PodDisruptionBudget objects in the current namespace.",
        "explanation_incorrect": "A correct solution must list PodDisruptionBudgets specifically, using kubectl get pdb.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view all NetworkPolicies in the current namespace.",
        "correct_answer": "kubectl get networkpolicies",
        "explanation_correct": "Correct -- `kubectl get networkpolicies` lists NetworkPolicy objects in the current namespace.",
        "explanation_incorrect": "A correct solution must list NetworkPolicies specifically, using kubectl get networkpolicies.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to list all pods (across all namespaces) running on a specific node named 'node-1'.",
        "correct_answer": "kubectl get pods --field-selector spec.nodeName=node-1 --all-namespaces",
        "explanation_correct": "Correct -- the field-selector filters pods to only those scheduled on node-1, and --all-namespaces expands the query beyond the current namespace.",
        "explanation_incorrect": "A correct solution must filter pods to those running specifically on node-1, across all namespaces, typically using --field-selector spec.nodeName.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view the full YAML definition of a CustomResourceDefinition named 'widgets.example.com'.",
        "correct_answer": "kubectl get crd widgets.example.com -o yaml",
        "explanation_correct": "Correct -- specifying -o yaml on the get command outputs the CRD's complete definition in YAML format.",
        "explanation_incorrect": "A correct solution must show the full YAML for widgets.example.com specifically, using kubectl get crd -o yaml.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to force-delete a pod named 'stuck-pod' that is stuck terminating, bypassing graceful termination.",
        "correct_answer": "kubectl delete pod stuck-pod --grace-period=0 --force",
        "explanation_correct": "Correct -- setting --grace-period=0 together with --force immediately removes the pod object from the API server, bypassing the normal graceful termination wait.",
        "explanation_incorrect": "A correct solution must force-delete stuck-pod specifically, bypassing graceful termination, using --grace-period=0 --force.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view the current ServiceAccounts in the current namespace.",
        "correct_answer": "kubectl get serviceaccounts",
        "explanation_correct": "Correct -- `kubectl get serviceaccounts` lists ServiceAccount objects in the current namespace.",
        "explanation_incorrect": "A correct solution must list ServiceAccounts specifically, using kubectl get serviceaccounts.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "coding",
        "prompt": "Write the kubectl command to view all API resource types the cluster's API server supports.",
        "correct_answer": "kubectl api-resources",
        "explanation_correct": "Correct -- `kubectl api-resources` lists every resource type (built-in and custom) that the API server currently exposes.",
        "explanation_incorrect": "A correct solution must list all available API resource types, typically using kubectl api-resources.",
        "options": None,
    },

    # ---------------- MCQ (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of an admission controller in Kubernetes?",
        "options": [
            "Intercepts API requests after authentication/authorization but before persistence, to validate or mutate objects",
            "Authenticates users making requests to the API server",
            "Schedules pods onto specific nodes",
            "Manages network routing between pods",
        ],
        "correct_answer": "Intercepts API requests after authentication/authorization but before persistence, to validate or mutate objects",
        "explanation_correct": "Admission controllers run as the last step before an object is persisted to etcd, letting them validate (reject invalid objects) or mutate (modify) requests as needed.",
        "explanation_incorrect": {
            "Authenticates users making requests to the API server": "Wrong — that's the role of authentication plugins, which run earlier in the request pipeline, before admission control.",
            "Schedules pods onto specific nodes": "Wrong — that's the role of the scheduler, a completely separate component from admission controllers.",
            "Manages network routing between pods": "Wrong — that's the role of the CNI plugin/kube-proxy, unrelated to admission control.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is a Custom Resource Definition (CRD)?",
        "options": [
            "Extends the Kubernetes API with a new, custom resource type, defined by the user",
            "A built-in resource specifically for defining container images",
            "A type of RBAC policy",
            "A network configuration object",
        ],
        "correct_answer": "Extends the Kubernetes API with a new, custom resource type, defined by the user",
        "explanation_correct": "A CRD registers a new resource kind with the API server, letting users define and manage custom objects using the same declarative model as built-in resources like Pods or Deployments.",
        "explanation_incorrect": {
            "A built-in resource specifically for defining container images": "Wrong — image management isn't what CRDs are for; they're a general extension mechanism for any custom resource type.",
            "A type of RBAC policy": "Wrong — RBAC policies (Roles, RoleBindings, etc.) are unrelated to CRDs, which are about extending the API schema.",
            "A network configuration object": "Wrong — CRDs are a general API extension mechanism, not specifically tied to networking.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the Operator pattern in Kubernetes?",
        "options": [
            "Uses a custom controller with domain-specific logic (often paired with a CRD) to automate management of a complex application",
            "A manual process of applying YAML manifests by hand",
            "A built-in Kubernetes scheduling algorithm",
            "A type of Ingress controller",
        ],
        "correct_answer": "Uses a custom controller with domain-specific logic (often paired with a CRD) to automate management of a complex application",
        "explanation_correct": "Operators encode operational knowledge (like how to safely upgrade or back up a specific application) into a controller that watches a custom resource and automates day-2 operations that would otherwise require manual intervention.",
        "explanation_incorrect": {
            "A manual process of applying YAML manifests by hand": "Wrong — the whole point of the Operator pattern is to automate what would otherwise be manual operational work.",
            "A built-in Kubernetes scheduling algorithm": "Wrong — scheduling is handled by kube-scheduler, unrelated to the Operator pattern's application-management focus.",
            "A type of Ingress controller": "Wrong — while an Ingress controller could theoretically be implemented as an Operator, the Operator pattern itself is a general automation concept, not specifically about ingress.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of a PodDisruptionBudget?",
        "options": [
            "Limits how many pods of a given application can be voluntarily disrupted at once, such as during node drains",
            "Prevents any pod from ever being deleted",
            "Defines CPU/memory resource limits for pods",
            "Schedules pods evenly across availability zones",
        ],
        "correct_answer": "Limits how many pods of a given application can be voluntarily disrupted at once, such as during node drains",
        "explanation_correct": "A PodDisruptionBudget caps how many of an application's pods can be voluntarily taken down simultaneously (e.g. during a node drain or cluster upgrade), protecting overall availability.",
        "explanation_incorrect": {
            "Prevents any pod from ever being deleted": "Wrong — it limits voluntary disruption to a bounded number of pods at once, it doesn't prevent deletion entirely; pods can still be evicted respecting the budget.",
            "Defines CPU/memory resource limits for pods": "Wrong — that's the role of resource requests/limits on the container spec, unrelated to PodDisruptionBudgets.",
            "Schedules pods evenly across availability zones": "Wrong — that's the role of topology spread constraints or affinity rules, a different mechanism from PodDisruptionBudgets.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of pod anti-affinity?",
        "options": [
            "Discourages or prevents scheduling pods onto the same node (or topology domain) as other specified pods, for spreading replicas",
            "Forces all pods of an application onto a single node",
            "Encrypts pod-to-pod traffic",
            "Defines resource limits for a pod",
        ],
        "correct_answer": "Discourages or prevents scheduling pods onto the same node (or topology domain) as other specified pods, for spreading replicas",
        "explanation_correct": "Anti-affinity rules keep specified pods apart (e.g. across different nodes or zones), commonly used to spread an application's replicas for better fault tolerance.",
        "explanation_incorrect": {
            "Forces all pods of an application onto a single node": "Wrong — that describes the opposite behavior (co-location), which is closer to what affinity, not anti-affinity, would achieve.",
            "Encrypts pod-to-pod traffic": "Wrong — anti-affinity is purely a scheduling constraint; encryption is an unrelated concern.",
            "Defines resource limits for a pod": "Wrong — that's the role of the container's resources field, unrelated to anti-affinity.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the key difference between a ClusterRole and a Role in Kubernetes RBAC?",
        "options": [
            "A ClusterRole can apply cluster-wide or be bound within a specific namespace, while a Role is always scoped to a single namespace",
            "They are functionally identical in every respect",
            "A Role applies cluster-wide, while a ClusterRole is namespace-scoped",
            "ClusterRoles cannot be used to grant permissions on namespaced resources",
        ],
        "correct_answer": "A ClusterRole can apply cluster-wide or be bound within a specific namespace, while a Role is always scoped to a single namespace",
        "explanation_correct": "A ClusterRole is more flexible — it can be bound cluster-wide via a ClusterRoleBinding, or bound to just one namespace via a RoleBinding — while a plain Role can only ever apply within the namespace it's created in.",
        "explanation_incorrect": {
            "They are functionally identical in every respect": "Wrong — their scoping flexibility differs meaningfully, as described above.",
            "A Role applies cluster-wide, while a ClusterRole is namespace-scoped": "Wrong — this is backwards; a Role is namespace-scoped, and a ClusterRole is the one with cluster-wide reach (or namespace-bindable) flexibility.",
            "ClusterRoles cannot be used to grant permissions on namespaced resources": "Wrong — ClusterRoles absolutely can grant permissions on namespaced resources (e.g. when bound via a RoleBinding within a specific namespace).",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of owner references and garbage collection in Kubernetes?",
        "options": [
            "Automatically deletes dependent objects when their owner object is deleted, preventing orphaned resources",
            "Manually tracks disk usage per object",
            "Defines RBAC ownership of a namespace",
            "Schedules cleanup jobs to run on a timer",
        ],
        "correct_answer": "Automatically deletes dependent objects when their owner object is deleted, preventing orphaned resources",
        "explanation_correct": "Owner references link dependent objects (like a ReplicaSet's pods) to their controlling owner, and Kubernetes' garbage collector automatically cleans up those dependents when the owner is deleted.",
        "explanation_incorrect": {
            "Manually tracks disk usage per object": "Wrong — owner references are about object lifecycle relationships, unrelated to disk usage tracking.",
            "Defines RBAC ownership of a namespace": "Wrong — RBAC permissions are a separate concept from owner references, which are about object lifecycle, not access control.",
            "Schedules cleanup jobs to run on a timer": "Wrong — garbage collection triggers reactively when an owner is deleted, not on a fixed timer schedule.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is a static pod in Kubernetes?",
        "options": [
            "A pod managed directly by the kubelet on a specific node from a local manifest file, rather than through the API server",
            "A pod that never restarts under any circumstances",
            "A pod that is guaranteed a fixed, unchanging IP address",
            "A pod that cannot ever be deleted",
        ],
        "correct_answer": "A pod managed directly by the kubelet on a specific node from a local manifest file, rather than through the API server",
        "explanation_correct": "Static pods are defined by manifest files that the kubelet watches directly on a node's filesystem, bypassing the normal API-server-driven scheduling — commonly used to run core control plane components.",
        "explanation_incorrect": {
            "A pod that never restarts under any circumstances": "Wrong — static pods can still be restarted by the kubelet according to their restart policy, like any other pod.",
            "A pod that is guaranteed a fixed, unchanging IP address": "Wrong — static pods don't have any special guarantee about IP stability beyond normal pod networking behavior.",
            "A pod that cannot ever be deleted": "Wrong — static pods can be removed by deleting their manifest file from the node, they aren't permanently undeletable.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of topology spread constraints?",
        "options": [
            "Control how pods are distributed across failure domains like zones or nodes, to improve availability",
            "Define which container image registry to pull images from",
            "Set CPU/memory limits per topology zone",
            "Completely replace the need for affinity rules",
        ],
        "correct_answer": "Control how pods are distributed across failure domains like zones or nodes, to improve availability",
        "explanation_correct": "Topology spread constraints let you specify how evenly pods should be spread across topology domains (like zones or nodes), reducing the risk that a single failure domain going down takes out too many replicas at once.",
        "explanation_incorrect": {
            "Define which container image registry to pull images from": "Wrong — that's controlled separately via the image field and imagePullSecrets, unrelated to topology spread constraints.",
            "Set CPU/memory limits per topology zone": "Wrong — resource limits are set per-container, not scoped by topology zone.",
            "Completely replace the need for affinity rules": "Wrong — topology spread constraints and affinity/anti-affinity rules are complementary tools, not a full replacement for one another.",
        },
    },

    # ---------------- FILL-IN-BLANK (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "An ____ controller intercepts API requests after authentication/authorization but before persistence, to validate or mutate objects.",
        "options": None,
        "correct_answer": "admission",
        "explanation_correct": "Admission controllers run as the final step before an object is written to etcd.",
        "explanation_incorrect": "The blank should be filled with the name of this controller type: admission.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A Custom Resource ____ (CRD) extends the Kubernetes API with a new, custom resource type defined by the user.",
        "options": None,
        "correct_answer": "Definition",
        "explanation_correct": "CustomResourceDefinition registers a new resource kind with the API server.",
        "explanation_incorrect": "The blank should be filled with the final word of the CRD acronym: Definition.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ pattern uses a custom controller with domain-specific logic, often paired with a CRD, to automate management of a complex application.",
        "options": None,
        "correct_answer": "Operator",
        "explanation_correct": "The Operator pattern encodes operational knowledge into an automated controller.",
        "explanation_incorrect": "The blank should be filled with the name of this pattern: Operator.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A Pod ____ Budget limits how many pods of a given application can be voluntarily disrupted at once, such as during node drains.",
        "options": None,
        "correct_answer": "Disruption",
        "explanation_correct": "A PodDisruptionBudget caps voluntary disruption of an application's pods.",
        "explanation_incorrect": "The blank should be filled with the middle word of this resource's name: Disruption.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Pod ____-affinity discourages or prevents scheduling pods onto the same node or topology domain as other specified pods.",
        "options": None,
        "correct_answer": "anti",
        "explanation_correct": "Anti-affinity rules keep specified pods apart across nodes or topology domains.",
        "explanation_incorrect": "The blank should be filled with the prefix for this affinity variant: anti.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A ____ in Kubernetes RBAC can apply cluster-wide or be bound within a specific namespace, unlike a Role, which is always scoped to a single namespace.",
        "options": None,
        "correct_answer": "ClusterRole",
        "explanation_correct": "A ClusterRole offers more flexible scoping than a plain namespace-bound Role.",
        "explanation_incorrect": "The blank should be filled with the name of this RBAC resource type: ClusterRole.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ references allow Kubernetes to automatically delete dependent objects when their owner object is deleted, preventing orphaned resources.",
        "options": None,
        "correct_answer": "Owner",
        "explanation_correct": "Owner references link dependent objects to their controlling owner for garbage collection.",
        "explanation_incorrect": "The blank should be filled with the term for this ownership-linking mechanism: Owner.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A ____ pod is managed directly by the kubelet on a specific node from a local manifest file, rather than through the API server.",
        "options": None,
        "correct_answer": "static",
        "explanation_correct": "Static pods bypass normal API-server-driven scheduling, watched directly by the kubelet.",
        "explanation_incorrect": "The blank should be filled with the name of this pod type: static.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Topology ____ constraints control how pods are distributed across failure domains like zones or nodes, to improve availability.",
        "options": None,
        "correct_answer": "spread",
        "explanation_correct": "Topology spread constraints control pod distribution across specified topology domains.",
        "explanation_incorrect": "The blank should be filled with the term for this distribution mechanism: spread.",
    },

    # ---------------- DRAG-AND-DROP (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a validating admission webhook.",
        "options": ["The API server calls the webhook to validate matching requests before persisting them", "Deploy a webhook server implementing the admission review API", "Create a ValidatingWebhookConfiguration pointing to that webhook service"],
        "correct_answer": '["Deploy a webhook server implementing the admission review API", "Create a ValidatingWebhookConfiguration pointing to that webhook service", "The API server calls the webhook to validate matching requests before persisting them"]',
        "explanation_correct": "Correct -- the webhook server must exist before configuration can point to it, and the API server only calls it once that configuration registers the webhook for matching requests.",
        "explanation_incorrect": "The webhook server must be running before it can be referenced in a webhook configuration, and calls to it only happen once that registration is in place.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for building and deploying a basic Operator.",
        "options": ["Deploy the controller into the cluster so it begins managing instances of the custom resource", "Define a CRD representing the custom resource the Operator will manage", "Write a controller that watches for changes to that custom resource and reconciles cluster state accordingly"],
        "correct_answer": '["Define a CRD representing the custom resource the Operator will manage", "Write a controller that watches for changes to that custom resource and reconciles cluster state accordingly", "Deploy the controller into the cluster so it begins managing instances of the custom resource"]',
        "explanation_correct": "Correct -- the CRD must exist before a controller can watch it, and deploying that controller is the final step that actually activates the automation.",
        "explanation_incorrect": "The CRD must be defined before a controller can watch and react to its instances, and deployment is the final step that puts the whole system into action.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a PodDisruptionBudget before a planned node drain.",
        "options": ["Run `kubectl drain <node>`, which respects the budget by not evicting pods that would violate it", "Define a PodDisruptionBudget specifying the minimum available replicas for the application", "Apply the PodDisruptionBudget"],
        "correct_answer": '["Define a PodDisruptionBudget specifying the minimum available replicas for the application", "Apply the PodDisruptionBudget", "Run `kubectl drain <node>`, which respects the budget by not evicting pods that would violate it"]',
        "explanation_correct": "Correct -- the PDB must be defined before it can be applied, and it must be active in the cluster before a drain operation can respect it.",
        "explanation_incorrect": "The PodDisruptionBudget must be defined before it can be applied to the cluster, and it must already be in effect for a subsequent drain to honor it.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing a garbage collection issue with orphaned resources.",
        "options": ["Manually clean up the orphaned resources if owner references were missing or misconfigured", "Notice resources still exist after their expected owner was deleted", "Check the resource's ownerReferences field to see if it's set correctly"],
        "correct_answer": '["Notice resources still exist after their expected owner was deleted", "Check the resource\'s ownerReferences field to see if it\'s set correctly", "Manually clean up the orphaned resources if owner references were missing or misconfigured"]',
        "explanation_correct": "Correct -- the orphaned resources must be noticed before investigating their ownerReferences, and manual cleanup is the resolution step once a misconfiguration is confirmed.",
        "explanation_incorrect": "The unexpected persistence of resources must be noticed before their owner reference configuration is checked, and manual cleanup follows once that check reveals the misconfiguration.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up cluster-wide read access via RBAC.",
        "options": ["Verify access with `kubectl auth can-i`", "Create a ClusterRole defining the allowed verbs and resources", "Create a ClusterRoleBinding associating the ClusterRole with a user or group"],
        "correct_answer": '["Create a ClusterRole defining the allowed verbs and resources", "Create a ClusterRoleBinding associating the ClusterRole with a user or group", "Verify access with `kubectl auth can-i`"]',
        "explanation_correct": "Correct -- the ClusterRole must exist before it can be bound, and verification is the final step confirming the whole setup grants the intended access.",
        "explanation_incorrect": "The ClusterRole must be defined before it can be bound to a user, and verifying the resulting access is a sensible final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for troubleshooting a pod that won't schedule due to anti-affinity rules.",
        "options": ["Adjust the anti-affinity rule or add more nodes if the constraint can't currently be satisfied", "Run `kubectl describe pod <name>` and review scheduling failure events", "Check the pod's anti-affinity rules and the labels of pods already running on candidate nodes"],
        "correct_answer": '["Run `kubectl describe pod <name>` and review scheduling failure events", "Check the pod\'s anti-affinity rules and the labels of pods already running on candidate nodes", "Adjust the anti-affinity rule or add more nodes if the constraint can\'t currently be satisfied"]',
        "explanation_correct": "Correct -- the scheduling failure must be observed before investigating anti-affinity as a cause, and adjusting the rule (or adding capacity) is the resolution step.",
        "explanation_incorrect": "The scheduling failure events should be reviewed first, then anti-affinity rules and node labels examined as a likely cause, with adjustments as the final resolution step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for using an ephemeral debug container to troubleshoot a running pod.",
        "options": ["Exit the debug session once troubleshooting is complete", "Run `kubectl debug <pod> -it --image=busybox` to attach a debug container", "Use the debug container's tools to inspect the target container's environment"],
        "correct_answer": '["Run `kubectl debug <pod> -it --image=busybox` to attach a debug container", "Use the debug container\'s tools to inspect the target container\'s environment", "Exit the debug session once troubleshooting is complete"]',
        "explanation_correct": "Correct -- the debug container must be attached before it can be used for inspection, and exiting is the final step once troubleshooting has wrapped up.",
        "explanation_incorrect": "The ephemeral debug container must be attached before it can be used to inspect anything, and exiting the session is the natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up topology spread constraints for high availability.",
        "options": ["Verify pods are distributed across the specified topology domains with `kubectl get pods -o wide`", "Define topologySpreadConstraints in the pod template specifying the topology key (e.g. zone) and max skew", "Apply the Deployment with this configuration"],
        "correct_answer": '["Define topologySpreadConstraints in the pod template specifying the topology key (e.g. zone) and max skew", "Apply the Deployment with this configuration", "Verify pods are distributed across the specified topology domains with `kubectl get pods -o wide`"]',
        "explanation_correct": "Correct -- the constraint must be defined before applying the Deployment, and verification only makes sense once pods have actually been scheduled under that configuration.",
        "explanation_incorrect": "The topology spread constraint must be defined in the manifest before applying it, and verifying pod distribution is the natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for installing an application with Helm.",
        "options": ["Verify the release with `helm list` and `kubectl get pods`", "Add the relevant Helm chart repository", "Run `helm install <release-name> <chart>` with any needed value overrides"],
        "correct_answer": '["Add the relevant Helm chart repository", "Run `helm install <release-name> <chart>` with any needed value overrides", "Verify the release with `helm list` and `kubectl get pods`"]',
        "explanation_correct": "Correct -- the chart repository must be added before a chart from it can be installed, and verification is the final step confirming the release deployed successfully.",
        "explanation_incorrect": "The chart repository must be registered before the chart can be installed from it, and verifying the resulting release is the natural final step.",
    },

    # ---------------- DROPDOWN-ORDER (8) ----------------

    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up a mutating webhook that injects a sidecar container.",
        "options": ["New matching pods automatically have the sidecar injected before creation", "Deploy the mutating webhook server with the sidecar injection logic", "Create a MutatingWebhookConfiguration pointing to that service"],
        "correct_answer": '["Deploy the mutating webhook server with the sidecar injection logic", "Create a MutatingWebhookConfiguration pointing to that service", "New matching pods automatically have the sidecar injected before creation"]',
        "explanation_correct": "Correct -- the webhook server must be running before configuration can point to it, and sidecar injection only happens once that registration is in place for matching pods.",
        "explanation_incorrect": "The webhook server must exist before it can be referenced in a webhook configuration, and injection behavior only kicks in once that configuration is registered.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for diagnosing etcd-related cluster issues.",
        "options": ["Investigate disk I/O or resource constraints on the etcd node, since etcd is sensitive to latency", "Check control plane component health, including etcd, via `kubectl get componentstatuses` or equivalent", "Review etcd logs for errors (e.g. via the control plane node directly)"],
        "correct_answer": '["Check control plane component health, including etcd, via `kubectl get componentstatuses` or equivalent", "Review etcd logs for errors (e.g. via the control plane node directly)", "Investigate disk I/O or resource constraints on the etcd node, since etcd is sensitive to latency"]',
        "explanation_correct": "Correct -- a high-level health check is a reasonable starting point, reviewing logs for specifics comes next, and investigating underlying resource constraints is the deepest, final diagnostic step.",
        "explanation_incorrect": "Checking overall component health is a sensible first step, reviewing detailed logs narrows the cause, and investigating underlying resource constraints is the deepest level of diagnosis.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting a ResourceQuota and observing its enforcement.",
        "options": ["Attempt to create a resource exceeding the quota and observe the request being rejected", "Define a ResourceQuota limiting total CPU/memory or object counts in a namespace", "Apply the ResourceQuota to the namespace"],
        "correct_answer": '["Define a ResourceQuota limiting total CPU/memory or object counts in a namespace", "Apply the ResourceQuota to the namespace", "Attempt to create a resource exceeding the quota and observe the request being rejected"]',
        "explanation_correct": "Correct -- the quota must be defined before it can be applied, and testing enforcement only makes sense once the quota is actually active in the namespace.",
        "explanation_incorrect": "The ResourceQuota must be defined before applying it to a namespace, and testing enforcement is the natural final step once it's active.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for configuring priority-based pod preemption.",
        "options": ["Under resource pressure, lower-priority pods may be preempted to make room for the higher-priority pod", "Define a PriorityClass with a specific priority value", "Assign the PriorityClass to a critical pod's spec"],
        "correct_answer": '["Define a PriorityClass with a specific priority value", "Assign the PriorityClass to a critical pod\'s spec", "Under resource pressure, lower-priority pods may be preempted to make room for the higher-priority pod"]',
        "explanation_correct": "Correct -- the PriorityClass must be defined before it can be assigned to a pod, and preemption only occurs once that assignment is actually in place and resources become scarce.",
        "explanation_incorrect": "The PriorityClass must be defined before it can be assigned to a pod's spec, and preemption behavior is a consequence of that assignment under resource pressure, not something that precedes it.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up a CSI driver for a new storage backend.",
        "options": ["Create a PersistentVolumeClaim using that StorageClass to dynamically provision storage", "Install the CSI driver components into the cluster", "Create a StorageClass referencing the CSI provisioner"],
        "correct_answer": '["Install the CSI driver components into the cluster", "Create a StorageClass referencing the CSI provisioner", "Create a PersistentVolumeClaim using that StorageClass to dynamically provision storage"]',
        "explanation_correct": "Correct -- the CSI driver must be installed before a StorageClass can reference its provisioner, and a StorageClass must exist before a PVC can use it to provision storage.",
        "explanation_incorrect": "The CSI driver must be installed before a StorageClass can reference it, and the StorageClass must exist before a PersistentVolumeClaim can request storage through it.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using kustomize to manage environment-specific overlays.",
        "options": ["Run `kubectl apply -k overlays/staging` to apply the customized manifests", "Define a base set of manifests", "Create an overlay directory with environment-specific patches (e.g. for staging)"],
        "correct_answer": '["Define a base set of manifests", "Create an overlay directory with environment-specific patches (e.g. for staging)", "Run `kubectl apply -k overlays/staging` to apply the customized manifests"]',
        "explanation_correct": "Correct -- the base manifests must exist before an overlay can patch them, and applying the overlay is the final step once both are defined.",
        "explanation_incorrect": "The base manifests must exist before an overlay can be built on top of them, and applying the overlay is the final step that brings both together.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for investigating kubelet-level issues on a node.",
        "options": ["Restart the kubelet service if it's found to be in a bad state", "SSH into the node and check the kubelet service status (e.g. `systemctl status kubelet`)", "Review kubelet logs for errors related to pod management"],
        "correct_answer": '["SSH into the node and check the kubelet service status (e.g. `systemctl status kubelet`)", "Review kubelet logs for errors related to pod management", "Restart the kubelet service if it\'s found to be in a bad state"]',
        "explanation_correct": "Correct -- checking service status is a reasonable starting point, reviewing logs narrows down the cause, and restarting is the corrective action taken once a bad state is confirmed.",
        "explanation_incorrect": "Checking the kubelet's service status is a sensible first step, reviewing logs for specific errors follows, and restarting the service is the corrective action taken based on those findings.",
    },
    {
        "topic": "Kubernetes", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up workload identity so a pod can access external cloud resources without static credentials.",
        "options": ["Assign the ServiceAccount to the pod, which then assumes the cloud identity's permissions at runtime", "Configure a trust relationship between the Kubernetes ServiceAccount and the cloud IAM identity", "Annotate the Kubernetes ServiceAccount to reference that cloud identity"],
        "correct_answer": '["Configure a trust relationship between the Kubernetes ServiceAccount and the cloud IAM identity", "Annotate the Kubernetes ServiceAccount to reference that cloud identity", "Assign the ServiceAccount to the pod, which then assumes the cloud identity\'s permissions at runtime"]',
        "explanation_correct": "Correct -- the trust relationship must be configured before the ServiceAccount can be annotated to use it, and assigning the ServiceAccount to a pod is the final step that activates the workload identity.",
        "explanation_incorrect": "The trust relationship between the ServiceAccount and cloud identity must be established before the ServiceAccount is annotated to reference it, and assigning it to a pod is the final activating step.",
    },
]
