"""
Kubernetes - Easy batch, 50 questions total.
Distribution: 15 coding, 9 mcq, 9 fill-in-blank, 9 drag-and-drop, 8 dropdown-order.
(Coding-weighted higher than the even Terraform/AWS split, but lighter than Ansible.)

Focused on core kubectl admin commands and foundational Kubernetes concepts (Pods,
Deployments, Services, Namespaces, ConfigMaps, labels).

Schema matches ansible_easy_questions.py -- see that file's header for full field notes.
For "coding" questions here, correct_answer is a reference kubectl command, graded
leniently by LLM against the prompt.
"""

KUBERNETES_EASY_QUESTIONS = [

    # ---------------- CODING (15) ----------------

    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to list all pods in the current namespace.",
        "correct_answer": "kubectl get pods",
        "explanation_correct": "Correct -- `kubectl get pods` lists all pods in the currently active namespace.",
        "explanation_incorrect": "A correct solution must list the pods in the current namespace, typically using kubectl get pods.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to list all pods across all namespaces.",
        "correct_answer": "kubectl get pods --all-namespaces",
        "explanation_correct": "Correct -- the --all-namespaces flag (or -A) expands the query to every namespace in the cluster, not just the current one.",
        "explanation_incorrect": "A correct solution must list pods from every namespace, not just the current one, typically using kubectl get pods --all-namespaces.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to describe a pod named 'web-pod', showing detailed status and events.",
        "correct_answer": "kubectl describe pod web-pod",
        "explanation_correct": "Correct -- `kubectl describe pod` shows detailed information about the pod, including its status, containers, and recent events.",
        "explanation_incorrect": "A correct solution must describe the pod named web-pod specifically, using kubectl describe pod.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to view the logs from a pod named 'web-pod'.",
        "correct_answer": "kubectl logs web-pod",
        "explanation_correct": "Correct -- `kubectl logs` retrieves the container logs from the specified pod.",
        "explanation_incorrect": "A correct solution must show the logs for web-pod specifically, using kubectl logs.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to delete a pod named 'web-pod'.",
        "correct_answer": "kubectl delete pod web-pod",
        "explanation_correct": "Correct -- `kubectl delete pod` removes the specified pod from the cluster.",
        "explanation_incorrect": "A correct solution must delete the pod named web-pod specifically, using kubectl delete pod.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to apply a manifest file named deployment.yaml, creating or updating the resources it defines.",
        "correct_answer": "kubectl apply -f deployment.yaml",
        "explanation_correct": "Correct -- `kubectl apply -f` creates or updates cluster resources to match the state defined in the given manifest file.",
        "explanation_incorrect": "A correct solution must apply the deployment.yaml file specifically, using kubectl apply -f.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to list all Deployments in the current namespace.",
        "correct_answer": "kubectl get deployments",
        "explanation_correct": "Correct -- `kubectl get deployments` lists all Deployment resources in the current namespace.",
        "explanation_incorrect": "A correct solution must list Deployments specifically, using kubectl get deployments.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to scale a Deployment named 'web-deployment' to 5 replicas.",
        "correct_answer": "kubectl scale deployment web-deployment --replicas=5",
        "explanation_correct": "Correct -- `kubectl scale` with --replicas=5 adjusts the specified Deployment's desired replica count to 5.",
        "explanation_incorrect": "A correct solution must scale web-deployment to exactly 5 replicas, using kubectl scale deployment.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to list all Services in the current namespace.",
        "correct_answer": "kubectl get services",
        "explanation_correct": "Correct -- `kubectl get services` lists all Service resources in the current namespace.",
        "explanation_incorrect": "A correct solution must list Services specifically, using kubectl get services.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to list all nodes in the cluster.",
        "correct_answer": "kubectl get nodes",
        "explanation_correct": "Correct -- `kubectl get nodes` lists every node registered with the cluster, along with their status.",
        "explanation_incorrect": "A correct solution must list cluster nodes specifically, using kubectl get nodes.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to open an interactive bash shell inside a pod named 'web-pod'.",
        "correct_answer": "kubectl exec -it web-pod -- /bin/bash",
        "explanation_correct": "Correct -- the -it flags allocate an interactive TTY, and -- /bin/bash specifies the shell to run inside the pod's container.",
        "explanation_incorrect": "A correct solution must open an interactive shell inside web-pod specifically, using kubectl exec -it with a shell command.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to create a namespace named 'staging'.",
        "correct_answer": "kubectl create namespace staging",
        "explanation_correct": "Correct -- `kubectl create namespace` creates a new namespace with the given name.",
        "explanation_incorrect": "A correct solution must create a namespace named staging specifically, using kubectl create namespace.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to list all namespaces in the cluster.",
        "correct_answer": "kubectl get namespaces",
        "explanation_correct": "Correct -- `kubectl get namespaces` lists every namespace that exists in the cluster.",
        "explanation_incorrect": "A correct solution must list all namespaces, using kubectl get namespaces.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to forward local port 8080 to port 80 on a pod named 'web-pod'.",
        "correct_answer": "kubectl port-forward web-pod 8080:80",
        "explanation_correct": "Correct -- `kubectl port-forward` maps the local port (8080) to the pod's port (80), letting you access the pod as if it were local.",
        "explanation_incorrect": "A correct solution must forward local port 8080 to port 80 on web-pod specifically, using kubectl port-forward.",
        "options": None,
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "coding",
        "prompt": "Write the kubectl command to display the current cluster context and connection information.",
        "correct_answer": "kubectl cluster-info",
        "explanation_correct": "Correct -- `kubectl cluster-info` displays the addresses of the cluster's control plane and core services.",
        "explanation_incorrect": "A correct solution must display current cluster connectivity information, using kubectl cluster-info.",
        "options": None,
    },

    # ---------------- MCQ (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What is a Pod in Kubernetes?",
        "options": [
            "The smallest deployable unit, typically containing one or more tightly coupled containers",
            "A physical server in the cluster",
            "A type of network policy",
            "A persistent storage volume",
        ],
        "correct_answer": "The smallest deployable unit, typically containing one or more tightly coupled containers",
        "explanation_correct": "A Pod is Kubernetes' smallest deployable unit, wrapping one or more containers that share networking and storage.",
        "explanation_incorrect": {
            "A physical server in the cluster": "Wrong — that's a Node, a distinct concept from a Pod.",
            "A type of network policy": "Wrong — NetworkPolicy is a separate Kubernetes resource, unrelated to what a Pod is.",
            "A persistent storage volume": "Wrong — that's a PersistentVolume, a different resource type from a Pod.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a Kubernetes Service?",
        "options": [
            "Provides a stable network endpoint to access a set of pods, even as individual pods are created or destroyed",
            "Stores application configuration data",
            "Schedules pods onto specific nodes",
            "Manages persistent storage allocation",
        ],
        "correct_answer": "Provides a stable network endpoint to access a set of pods, even as individual pods are created or destroyed",
        "explanation_correct": "Since pods are ephemeral and their IPs can change, a Service provides a consistent address and load-balances traffic across whichever pods currently match its selector.",
        "explanation_incorrect": {
            "Stores application configuration data": "Wrong — that's the role of a ConfigMap (or Secret), not a Service.",
            "Schedules pods onto specific nodes": "Wrong — pod scheduling is handled by the scheduler component, unrelated to Services.",
            "Manages persistent storage allocation": "Wrong — that's the role of PersistentVolumes/PersistentVolumeClaims, not Services.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a Deployment in Kubernetes?",
        "options": [
            "Manages the desired state and lifecycle of a set of replica pods, including rolling updates",
            "Stores encrypted secret data",
            "Defines network policies for pod traffic",
            "Allocates persistent storage volumes",
        ],
        "correct_answer": "Manages the desired state and lifecycle of a set of replica pods, including rolling updates",
        "explanation_correct": "A Deployment declaratively manages a set of identical pods (via an underlying ReplicaSet), handling scaling and rolling updates to reach and maintain the desired state.",
        "explanation_incorrect": {
            "Stores encrypted secret data": "Wrong — that's the role of a Secret, a different resource from a Deployment.",
            "Defines network policies for pod traffic": "Wrong — that's the role of a NetworkPolicy resource, unrelated to Deployments.",
            "Allocates persistent storage volumes": "Wrong — that's the role of PersistentVolumes/Claims, not Deployments.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a Namespace in Kubernetes?",
        "options": [
            "Provides a way to divide cluster resources into logically isolated groups",
            "Defines a physical network boundary between servers",
            "Stores container images for the cluster",
            "Schedules pods onto nodes",
        ],
        "correct_answer": "Provides a way to divide cluster resources into logically isolated groups",
        "explanation_correct": "Namespaces let you partition a single cluster's resources into separate logical groups, useful for multi-team or multi-environment (dev/staging/prod) organization.",
        "explanation_incorrect": {
            "Defines a physical network boundary between servers": "Wrong — namespaces are a logical/API-level grouping, not a physical network boundary.",
            "Stores container images for the cluster": "Wrong — that's the role of a container registry, unrelated to namespaces.",
            "Schedules pods onto nodes": "Wrong — pod scheduling is handled by the scheduler component, unrelated to namespaces.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What does `kubectl apply` do?",
        "options": [
            "Creates or updates resources in the cluster to match the state defined in a manifest file",
            "Deletes resources defined in a manifest file",
            "Only creates new resources, and errors if they already exist",
            "Lists all resources currently in the cluster",
        ],
        "correct_answer": "Creates or updates resources in the cluster to match the state defined in a manifest file",
        "explanation_correct": "apply is declarative — it reconciles the cluster's actual state toward whatever is described in the manifest, creating resources that don't exist and updating ones that do.",
        "explanation_incorrect": {
            "Deletes resources defined in a manifest file": "Wrong — that's the role of kubectl delete -f, not apply.",
            "Only creates new resources, and errors if they already exist": "Wrong — that describes kubectl create, a more limited command; apply handles both creation and updates gracefully.",
            "Lists all resources currently in the cluster": "Wrong — that's the role of kubectl get, unrelated to apply's purpose.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What is a ReplicaSet responsible for?",
        "options": [
            "Ensuring a specified number of identical pod replicas are running at all times",
            "Storing configuration data for pods",
            "Exposing pods via a stable network endpoint",
            "Managing persistent storage volumes",
        ],
        "correct_answer": "Ensuring a specified number of identical pod replicas are running at all times",
        "explanation_correct": "A ReplicaSet continuously monitors and maintains the desired count of matching pods, creating new ones if any are lost.",
        "explanation_incorrect": {
            "Storing configuration data for pods": "Wrong — that's the role of a ConfigMap, not a ReplicaSet.",
            "Exposing pods via a stable network endpoint": "Wrong — that's the role of a Service, not a ReplicaSet.",
            "Managing persistent storage volumes": "Wrong — that's the role of PersistentVolumes/Claims, unrelated to ReplicaSets.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a ConfigMap?",
        "options": [
            "Stores non-sensitive configuration data that can be consumed by pods",
            "Stores encrypted secret data",
            "Defines network policies for the cluster",
            "Schedules pods onto specific nodes",
        ],
        "correct_answer": "Stores non-sensitive configuration data that can be consumed by pods",
        "explanation_correct": "ConfigMaps hold key-value configuration data (like environment settings) that pods can consume, separate from container images, without needing to store sensitive information.",
        "explanation_incorrect": {
            "Stores encrypted secret data": "Wrong — that's the role of a Secret, a related but distinct resource intended for sensitive data.",
            "Defines network policies for the cluster": "Wrong — that's the role of a NetworkPolicy, unrelated to ConfigMaps.",
            "Schedules pods onto specific nodes": "Wrong — that's the role of the scheduler (or node affinity rules), unrelated to ConfigMaps.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of labels in Kubernetes?",
        "options": [
            "Key-value pairs attached to objects, used to organize and select subsets of resources",
            "Encrypted metadata used for security purposes",
            "A way to version container images",
            "A type of persistent storage",
        ],
        "correct_answer": "Key-value pairs attached to objects, used to organize and select subsets of resources",
        "explanation_correct": "Labels are arbitrary key-value metadata attached to Kubernetes objects, commonly used by Services and other resources to select which pods they should target.",
        "explanation_incorrect": {
            "Encrypted metadata used for security purposes": "Wrong — labels are plain, unencrypted metadata used for organization and selection, not security.",
            "A way to version container images": "Wrong — image versioning is done via image tags, a separate concept from Kubernetes labels.",
            "A type of persistent storage": "Wrong — labels are metadata, unrelated to storage mechanisms like PersistentVolumes.",
        },
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "mcq",
        "prompt": "What does `kubectl get pods` display?",
        "options": [
            "A list of pods in the current namespace along with basic status information",
            "The complete YAML definition for every pod",
            "Only pod names, with no other information",
            "The application logs for all pods",
        ],
        "correct_answer": "A list of pods in the current namespace along with basic status information",
        "explanation_correct": "`kubectl get pods` returns a summary table showing each pod's name, ready status, restart count, and age.",
        "explanation_incorrect": {
            "The complete YAML definition for every pod": "Wrong — that's what `kubectl get pod <name> -o yaml` would show, not the default get pods output.",
            "Only pod names, with no other information": "Wrong — the default output includes status, restarts, and age alongside the name, not just the name.",
            "The application logs for all pods": "Wrong — that's the role of kubectl logs, a completely different command.",
        },
    },

    # ---------------- FILL-IN-BLANK (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The smallest deployable unit in Kubernetes, typically containing one or more containers, is called a ____.",
        "options": None,
        "correct_answer": "Pod",
        "explanation_correct": "A Pod wraps one or more containers that share networking and storage as a single deployable unit.",
        "explanation_incorrect": "The blank should be filled with the name of this smallest deployable unit: Pod.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A Kubernetes ____ provides a stable network endpoint to access a set of pods, even as individual pods are created or destroyed.",
        "options": None,
        "correct_answer": "Service",
        "explanation_correct": "A Service gives pods a consistent address, load-balancing traffic across whichever pods currently match its selector.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: Service.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A Kubernetes ____ manages the desired state and lifecycle of a set of replica pods, including rolling updates.",
        "options": None,
        "correct_answer": "Deployment",
        "explanation_correct": "A Deployment manages a set of pods declaratively, handling scaling and rolling updates.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: Deployment.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A Kubernetes ____ provides a way to divide cluster resources into logically isolated groups.",
        "options": None,
        "correct_answer": "Namespace",
        "explanation_correct": "Namespaces partition a cluster's resources into separate logical groups.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: Namespace.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The `kubectl ____` command creates or updates resources in the cluster to match a manifest file's defined state.",
        "options": None,
        "correct_answer": "apply",
        "explanation_correct": "kubectl apply declaratively reconciles cluster state toward the manifest's defined state.",
        "explanation_incorrect": "The blank should be filled with the kubectl subcommand used for this: apply.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A ____ is responsible for ensuring a specified number of identical pod replicas are running at all times.",
        "options": None,
        "correct_answer": "ReplicaSet",
        "explanation_correct": "A ReplicaSet maintains the desired count of matching pod replicas.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: ReplicaSet.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A ____ stores non-sensitive configuration data that can be consumed by pods.",
        "options": None,
        "correct_answer": "ConfigMap",
        "explanation_correct": "A ConfigMap holds configuration data separately from container images, for pods to consume.",
        "explanation_incorrect": "The blank should be filled with the name of this resource type: ConfigMap.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Key-value pairs attached to Kubernetes objects, used to organize and select subsets of resources, are called ____.",
        "options": None,
        "correct_answer": "labels",
        "explanation_correct": "Labels are metadata used for organizing and selecting Kubernetes objects.",
        "explanation_incorrect": "The blank should be filled with the term for this metadata mechanism: labels.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The command-line tool used to interact with a Kubernetes cluster is called ____.",
        "options": None,
        "correct_answer": "kubectl",
        "explanation_correct": "kubectl is the standard CLI for managing Kubernetes clusters and resources.",
        "explanation_incorrect": "The blank should be filled with the name of this CLI tool: kubectl.",
    },

    # ---------------- DRAG-AND-DROP (9) ----------------

    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for deploying an application to Kubernetes.",
        "options": ["Run `kubectl get pods` to confirm the pods are running", "Write a Deployment manifest YAML file", "Run `kubectl apply -f deployment.yaml` to create it"],
        "correct_answer": '["Write a Deployment manifest YAML file", "Run `kubectl apply -f deployment.yaml` to create it", "Run `kubectl get pods` to confirm the pods are running"]',
        "explanation_correct": "Correct -- the manifest must exist before it can be applied, and confirming pods are running is the final verification step after applying it.",
        "explanation_incorrect": "The manifest must be written before it can be applied to the cluster, and verifying pod status is a natural final step after that apply.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for exposing a Deployment with a Service.",
        "options": ["Write a Service manifest selecting the deployment's pods via labels", "Create the Deployment first", "Run `kubectl apply -f service.yaml` to create the service"],
        "correct_answer": '["Create the Deployment first", "Write a Service manifest selecting the deployment\'s pods via labels", "Run `kubectl apply -f service.yaml` to create the service"]',
        "explanation_correct": "Correct -- the Deployment's pods (and their labels) should exist before a Service manifest selecting them is written, and the Service manifest must exist before it can be applied.",
        "explanation_incorrect": "The pods (with their labels) need to exist for the Service's selector to be meaningful, and the Service manifest must be written before it can be applied to the cluster.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for troubleshooting a failing pod.",
        "options": ["Run `kubectl logs <name>` to review the pod's application logs", "Run `kubectl get pods` to identify the failing pod", "Run `kubectl describe pod <name>` to see events and status details"],
        "correct_answer": '["Run `kubectl get pods` to identify the failing pod", "Run `kubectl describe pod <name>` to see events and status details", "Run `kubectl logs <name>` to review the pod\'s application logs"]',
        "explanation_correct": "Correct -- the failing pod must be identified before you can target it with describe or logs, and checking events (describe) before diving into application logs is a reasonable diagnostic order.",
        "explanation_incorrect": "The specific pod must be identified before further commands can target it, and reviewing describe's events before diving into detailed application logs is a sensible troubleshooting order.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for scaling a Deployment.",
        "options": ["Run `kubectl get pods` to confirm the new replica count", "Run `kubectl get deployments` to check current replica count", "Run `kubectl scale deployment web-deployment --replicas=5` to scale it"],
        "correct_answer": '["Run `kubectl get deployments` to check current replica count", "Run `kubectl scale deployment web-deployment --replicas=5` to scale it", "Run `kubectl get pods` to confirm the new replica count"]',
        "explanation_correct": "Correct -- checking the current state is a sensible starting point, scaling comes next, and confirming the new pod count is the final verification step.",
        "explanation_incorrect": "Checking the current replica count provides a baseline before scaling, and confirming the new pod count is a reasonable final step after the scale command runs.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for creating a namespace and deploying resources into it.",
        "options": ["Run `kubectl get pods -n staging` to confirm resources exist there", "Run `kubectl create namespace staging` to create it", "Run `kubectl apply -f deployment.yaml -n staging` to deploy resources into it"],
        "correct_answer": '["Run `kubectl create namespace staging` to create it", "Run `kubectl apply -f deployment.yaml -n staging` to deploy resources into it", "Run `kubectl get pods -n staging` to confirm resources exist there"]',
        "explanation_correct": "Correct -- the namespace must exist before resources can be deployed into it, and confirming those resources exist is the final verification step.",
        "explanation_incorrect": "The namespace must be created before anything can be deployed into it, and verifying the deployment succeeded is a natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for accessing a pod's shell for debugging.",
        "options": ["Investigate the issue from inside the container", "Run `kubectl get pods` to find the pod's name", "Run `kubectl exec -it <pod-name> -- /bin/bash` to open an interactive shell"],
        "correct_answer": '["Run `kubectl get pods` to find the pod\'s name", "Run `kubectl exec -it <pod-name> -- /bin/bash` to open an interactive shell", "Investigate the issue from inside the container"]',
        "explanation_correct": "Correct -- the pod's name must be known before exec can target it, and investigation happens only after the shell session is actually opened.",
        "explanation_incorrect": "The pod's name must be identified before exec can be run against it, and investigating from inside the container can only happen once that shell is open.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for port-forwarding to access a pod locally.",
        "options": ["Access the application at localhost:8080", "Run `kubectl get pods` to identify the target pod", "Run `kubectl port-forward <pod-name> 8080:80` to forward the port"],
        "correct_answer": '["Run `kubectl get pods` to identify the target pod", "Run `kubectl port-forward <pod-name> 8080:80` to forward the port", "Access the application at localhost:8080"]',
        "explanation_correct": "Correct -- the target pod must be identified before port-forward can target it, and local access only becomes possible once the forward is active.",
        "explanation_incorrect": "The pod must be identified before port-forward can be run against it, and local access is only possible once the forwarding tunnel is actually active.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for updating a running Deployment with a new container image.",
        "options": ["Kubernetes performs a rolling update, replacing old pods with new ones", "Edit the Deployment manifest to reference the new image tag", "Run `kubectl apply -f deployment.yaml` to apply the change"],
        "correct_answer": '["Edit the Deployment manifest to reference the new image tag", "Run `kubectl apply -f deployment.yaml` to apply the change", "Kubernetes performs a rolling update, replacing old pods with new ones"]',
        "explanation_correct": "Correct -- the manifest must be edited before the change can be applied, and the rolling update happens as a result of that apply.",
        "explanation_incorrect": "The manifest must be edited before applying it, and the rolling update is triggered as a consequence of that apply, not before it.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for using a ConfigMap in a pod.",
        "options": ["Deploy the pod, which reads the configuration data at runtime", "Create a ConfigMap containing the configuration data", "Reference the ConfigMap in the pod's manifest (e.g. as an environment variable or volume)"],
        "correct_answer": '["Create a ConfigMap containing the configuration data", "Reference the ConfigMap in the pod\'s manifest (e.g. as an environment variable or volume)", "Deploy the pod, which reads the configuration data at runtime"]',
        "explanation_correct": "Correct -- the ConfigMap must exist before a pod manifest can reference it, and the pod must be deployed before it can actually read the referenced data.",
        "explanation_incorrect": "The ConfigMap must exist before it can be referenced in a pod manifest, and the pod must be deployed before it can actually consume that data.",
    },

    # ---------------- DROPDOWN-ORDER (8) ----------------

    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for checking cluster and node health.",
        "options": ["Run `kubectl describe node <name>` to investigate a specific node in detail", "Run `kubectl cluster-info` to check basic cluster connectivity", "Run `kubectl get nodes` to list cluster nodes and their status"],
        "correct_answer": '["Run `kubectl cluster-info` to check basic cluster connectivity", "Run `kubectl get nodes` to list cluster nodes and their status", "Run `kubectl describe node <name>` to investigate a specific node in detail"]',
        "explanation_correct": "Correct -- confirming basic connectivity is a sensible starting point, checking overall node status comes next, and drilling into a specific node is the most detailed final step.",
        "explanation_incorrect": "Verifying cluster connectivity first is a reasonable baseline check, listing node status follows, and investigating a specific node in detail is the natural final drill-down step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for deleting a pod cleanly and confirming it's gone.",
        "options": ["Run `kubectl get pods` again to confirm it's gone", "Run `kubectl get pods` to confirm the pod's exact name", "Run `kubectl delete pod <name>` to delete it"],
        "correct_answer": '["Run `kubectl get pods` to confirm the pod\'s exact name", "Run `kubectl delete pod <name>` to delete it", "Run `kubectl get pods` again to confirm it\'s gone"]',
        "explanation_correct": "Correct -- the exact pod name must be confirmed before targeting it for deletion, and the final check confirms the deletion actually took effect.",
        "explanation_incorrect": "The pod's name must be confirmed before it can be targeted for deletion, and a final check verifies the deletion actually succeeded.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a basic label-based pod selection workflow.",
        "options": ["Confirm only the intended pods are returned", "Add a label to a set of pods (e.g. via the Deployment template)", "Run `kubectl get pods -l app=web` to select pods matching that label"],
        "correct_answer": '["Add a label to a set of pods (e.g. via the Deployment template)", "Run `kubectl get pods -l app=web` to select pods matching that label", "Confirm only the intended pods are returned"]',
        "explanation_correct": "Correct -- pods must have the label before a selector query can match them, and confirming the results are correct is the final verification step.",
        "explanation_incorrect": "The label must exist on the pods before a selector-based query can match them, and confirming the correct pods were returned is the natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for creating a resource from a manifest and verifying it.",
        "options": ["Run `kubectl get <resource-type>` to confirm it was created", "Write the resource manifest in YAML", "Run `kubectl apply -f manifest.yaml`"],
        "correct_answer": '["Write the resource manifest in YAML", "Run `kubectl apply -f manifest.yaml`", "Run `kubectl get <resource-type>` to confirm it was created"]',
        "explanation_correct": "Correct -- the manifest must be written before it can be applied, and confirming the resource exists is the final step after applying it.",
        "explanation_incorrect": "The manifest must exist before it can be applied to the cluster, and verifying the resource's creation is a sensible final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for viewing and switching kubectl context.",
        "options": ["Run `kubectl config current-context` to confirm the active context", "Run `kubectl config get-contexts` to view available contexts", "Run `kubectl config use-context <name>` to switch to a different one"],
        "correct_answer": '["Run `kubectl config get-contexts` to view available contexts", "Run `kubectl config use-context <name>` to switch to a different one", "Run `kubectl config current-context` to confirm the active context"]',
        "explanation_correct": "Correct -- available contexts must be viewed before selecting one to switch to, and confirming the active context is the final verification step.",
        "explanation_incorrect": "Available contexts must be listed before one can be selected to switch to, and confirming the switch took effect is a natural final step.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a basic rollout status check after a deployment update.",
        "options": ["Confirm the rollout completes successfully", "Apply the updated Deployment manifest", "Run `kubectl rollout status deployment/web-deployment` to monitor progress"],
        "correct_answer": '["Apply the updated Deployment manifest", "Run `kubectl rollout status deployment/web-deployment` to monitor progress", "Confirm the rollout completes successfully"]',
        "explanation_correct": "Correct -- the update must be applied before there's a rollout to monitor, and confirming successful completion is the final step of watching that rollout.",
        "explanation_incorrect": "The manifest must be applied before a rollout is triggered to monitor, and confirming success is the natural conclusion of watching that rollout.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for listing and inspecting namespaces.",
        "options": ["Run `kubectl get pods -n <namespace>` to see resources within it", "Run `kubectl get namespaces` to list all namespaces", "Identify the namespace relevant to the task"],
        "correct_answer": '["Run `kubectl get namespaces` to list all namespaces", "Identify the namespace relevant to the task", "Run `kubectl get pods -n <namespace>` to see resources within it"]',
        "explanation_correct": "Correct -- all namespaces must be listed before a relevant one can be identified, and inspecting its resources only makes sense once that namespace is known.",
        "explanation_incorrect": "Namespaces must be listed before a specific relevant one can be identified, and inspecting resources within it requires knowing which namespace to target first.",
    },
    {
        "topic": "Kubernetes", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a basic Service connectivity check.",
        "options": ["Access the service at localhost:8080 to verify it responds", "Run `kubectl get services` to confirm the service exists and note its cluster IP", "Run `kubectl port-forward service/<name> 8080:80` to access it locally"],
        "correct_answer": '["Run `kubectl get services` to confirm the service exists and note its cluster IP", "Run `kubectl port-forward service/<name> 8080:80` to access it locally", "Access the service at localhost:8080 to verify it responds"]',
        "explanation_correct": "Correct -- the service must be confirmed to exist before port-forwarding can target it, and local access is only possible once that forwarding is active.",
        "explanation_incorrect": "The service must be confirmed to exist before it can be targeted for port-forwarding, and accessing it locally only becomes possible once that forward is active.",
    },
]
