"""
Linux - Hard batch, 50 questions total.
Distribution: 20 coding, 8 mcq, 8 fill-in-blank, 7 drag-and-drop, 7 dropdown-order.

Schema matches linux_easy_questions.py — see that file's header for full field notes.
Hard content covers cgroups/systemd resource control, kernel modules, VLAN interfaces,
LVM snapshots, ionice/iostat, SELinux context management (chcon/restorecon), dmesg,
systemd-analyze, package pinning, LUKS encryption, firewalld rich rules, vm.swappiness,
NUMA, per-process limits, and auditd.
"""

LINUX_HARD_QUESTIONS = [

    # ---------------- CODING (20) ----------------

    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the systemctl command to set a CPU quota of 50% on a running service named 'myapp', without restarting it.",
        "correct_answer": "systemctl set-property myapp.service CPUQuota=50%",
        "explanation_correct": "Correct — `systemctl set-property` applies the CPUQuota limit to the running unit immediately via cgroups, without requiring a restart.",
        "explanation_incorrect": "A correct solution must apply a live CPU quota change to myapp.service, typically using systemctl set-property with CPUQuota=50%.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to list all currently loaded kernel modules.",
        "correct_answer": "lsmod",
        "explanation_correct": "Correct — `lsmod` lists all kernel modules currently loaded into the running kernel.",
        "explanation_incorrect": "A correct solution must list loaded kernel modules, typically using lsmod.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to load a kernel module named 'br_netfilter'.",
        "correct_answer": "modprobe br_netfilter",
        "explanation_correct": "Correct — `modprobe` loads the specified module (and its dependencies) into the running kernel.",
        "explanation_incorrect": "A correct solution must load the br_netfilter module specifically, typically using modprobe.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to create a VLAN interface with ID 100 on top of eth0, naming the new interface eth0.100.",
        "correct_answer": "ip link add link eth0 name eth0.100 type vlan id 100",
        "explanation_correct": "Correct — this creates a VLAN sub-interface (eth0.100) tagged with VLAN ID 100, layered on top of the eth0 parent interface.",
        "explanation_incorrect": "A correct solution must create a VLAN interface with ID 100 on top of eth0, named eth0.100, typically using ip link add ... type vlan.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to create an LVM snapshot named 'data_snap' of logical volume 'data_lv' (in volume group vg_data), with a snapshot size of 5G.",
        "correct_answer": "lvcreate -L 5G -s -n data_snap /dev/vg_data/data_lv",
        "explanation_correct": "Correct — the -s flag creates a snapshot volume, capturing a point-in-time view of data_lv, sized to hold 5G of changes.",
        "explanation_incorrect": "A correct solution must create a snapshot (using the -s flag) of data_lv, named data_snap, with a size of 5G.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to display extended per-device I/O statistics, updating every 2 seconds, using iostat.",
        "correct_answer": "iostat -x 2",
        "explanation_correct": "Correct — the -x flag shows extended statistics per device, and the interval argument (2) refreshes the display every 2 seconds.",
        "explanation_incorrect": "A correct solution must show extended, continuously updating I/O statistics with a 2-second refresh interval, typically using iostat -x 2.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to run a script named backup.sh with the lowest best-effort I/O priority, using ionice.",
        "correct_answer": "ionice -c2 -n7 ./backup.sh",
        "explanation_correct": "Correct — class 2 (best-effort) with priority level 7 (the lowest within that class) minimizes this process's impact on disk I/O for other processes.",
        "explanation_incorrect": "A correct solution must run backup.sh with the lowest best-effort I/O priority (class 2, level 7), typically using ionice -c2 -n7.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to temporarily change the SELinux context type of '/var/www/html/index.html' to httpd_sys_content_t, using chcon.",
        "correct_answer": "chcon -t httpd_sys_content_t /var/www/html/index.html",
        "explanation_correct": "Correct — chcon with the -t flag changes the file's SELinux type context to httpd_sys_content_t.",
        "explanation_incorrect": "A correct solution must set the file's SELinux type context to httpd_sys_content_t specifically, using chcon -t.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to restore the default (policy-defined) SELinux context on '/var/www/html/index.html'.",
        "correct_answer": "restorecon /var/www/html/index.html",
        "explanation_correct": "Correct — `restorecon` resets a file's SELinux context to whatever the loaded policy defines as the default for its path.",
        "explanation_incorrect": "A correct solution must restore the file's context to the policy-defined default, typically using restorecon (not chcon, which sets an arbitrary context).",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to display all listening TCP sockets along with the process using each one, using ss.",
        "correct_answer": "ss -tlnp",
        "explanation_correct": "Correct — -t (TCP), -l (listening), -n (numeric), and -p (show process) together display listening sockets with their owning processes.",
        "explanation_incorrect": "A correct solution must show listening TCP sockets and their associated processes, typically using ss with the -t, -l, -n, and -p flags.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to display the kernel ring buffer messages, useful for diagnosing hardware or kernel-level issues.",
        "correct_answer": "dmesg",
        "explanation_correct": "Correct — `dmesg` prints messages from the kernel ring buffer, including boot messages, hardware events, and kernel warnings.",
        "explanation_incorrect": "A correct solution must display kernel ring buffer messages, typically using dmesg.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to show which systemd units took the longest to initialize during boot.",
        "correct_answer": "systemd-analyze blame",
        "explanation_correct": "Correct — `systemd-analyze blame` lists units sorted by the time each took to initialize during the boot process.",
        "explanation_incorrect": "A correct solution must show units ranked by startup time, typically using systemd-analyze blame.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to pin/hold the package 'nginx' at its current version on a Debian/Ubuntu system, preventing it from being upgraded.",
        "correct_answer": "apt-mark hold nginx",
        "explanation_correct": "Correct — `apt-mark hold` prevents the specified package from being automatically upgraded until the hold is removed.",
        "explanation_incorrect": "A correct solution must hold the nginx package at its current version, typically using apt-mark hold.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to encrypt the block device /dev/sdb1 using LUKS.",
        "correct_answer": "cryptsetup luksFormat /dev/sdb1",
        "explanation_correct": "Correct — `cryptsetup luksFormat` initializes the specified device with LUKS full-disk encryption.",
        "explanation_incorrect": "A correct solution must encrypt /dev/sdb1 using LUKS specifically, typically using cryptsetup luksFormat.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to unlock a LUKS-encrypted device /dev/sdb1, mapping it to the name 'secure_data'.",
        "correct_answer": "cryptsetup luksOpen /dev/sdb1 secure_data",
        "explanation_correct": "Correct — `cryptsetup luksOpen` decrypts and maps the encrypted device to a device-mapper name for use.",
        "explanation_incorrect": "A correct solution must unlock /dev/sdb1 and map it to secure_data specifically, typically using cryptsetup luksOpen.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the firewall-cmd command to add a permanent rich rule allowing SSH access only from IP address 192.168.1.100.",
        "correct_answer": "firewall-cmd --add-rich-rule='rule family=\"ipv4\" source address=\"192.168.1.100\" service name=\"ssh\" accept' --permanent",
        "explanation_correct": "Correct — the rich rule combines a specific source address with the SSH service and an accept action, and --permanent ensures the rule survives a reload/reboot.",
        "explanation_incorrect": "A correct solution must restrict SSH access specifically to the given source IP, using a rich rule (not a plain port/service rule, which couldn't express the source restriction), and should be persisted with --permanent.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to temporarily set the vm.swappiness kernel parameter to 10.",
        "correct_answer": "sysctl -w vm.swappiness=10",
        "explanation_correct": "Correct — `sysctl -w` applies the new value to the running kernel immediately, though it won't persist across reboots without also updating a config file.",
        "explanation_incorrect": "A correct solution must set vm.swappiness to 10 for the current running system, typically using sysctl -w.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to display the system's NUMA (Non-Uniform Memory Access) node hardware layout.",
        "correct_answer": "numactl --hardware",
        "explanation_correct": "Correct — `numactl --hardware` shows the available NUMA nodes, their CPUs, and their memory, along with inter-node distances.",
        "explanation_incorrect": "A correct solution must display the NUMA topology of the system, typically using numactl --hardware.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to display the resource limits currently in effect for a running process with PID 4321.",
        "correct_answer": "cat /proc/4321/limits",
        "explanation_correct": "Correct — /proc/<pid>/limits exposes the actual resource limits (soft and hard) in effect for that specific process.",
        "explanation_incorrect": "A correct solution must show the effective resource limits for PID 4321 specifically, typically by reading /proc/4321/limits.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to search audit logs for all events related to the file /etc/shadow, using ausearch.",
        "correct_answer": "ausearch -f /etc/shadow",
        "explanation_correct": "Correct — the -f flag filters audit log search results to events involving the specified file path.",
        "explanation_incorrect": "A correct solution must search audit logs for events related to /etc/shadow specifically, typically using ausearch -f.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of Linux cgroups (control groups)?",
        "options": [
            "Limits and isolates the resource usage (CPU, memory, I/O) of a group of processes",
            "Isolates network namespaces exclusively",
            "Manages user account permissions",
            "Schedules cron jobs",
        ],
        "correct_answer": "Limits and isolates the resource usage (CPU, memory, I/O) of a group of processes",
        "explanation_correct": "cgroups let the kernel allocate, limit, and account for resources like CPU, memory, and I/O bandwidth across groups of processes — the underlying mechanism systemd uses for features like CPUQuota.",
        "explanation_incorrect": {
            "Isolates network namespaces exclusively": "Wrong — network namespace isolation is a related but separate kernel feature; cgroups are broader, covering resource limiting across multiple resource types.",
            "Manages user account permissions": "Wrong — user/permission management is handled by IAM-style mechanisms (users, groups, sudoers), unrelated to cgroups.",
            "Schedules cron jobs": "Wrong — job scheduling is handled by cron or systemd timers, unrelated to cgroups' resource-limiting purpose.",
        },
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of `ionice`?",
        "options": [
            "Sets the I/O scheduling priority/class of a process",
            "Sets a process's CPU scheduling priority",
            "Limits a process's network bandwidth",
            "Monitors disk health and predicts failures",
        ],
        "correct_answer": "Sets the I/O scheduling priority/class of a process",
        "explanation_correct": "ionice influences how the I/O scheduler prioritizes a process's disk requests relative to others, similar in spirit to nice but for I/O rather than CPU.",
        "explanation_incorrect": {
            "Sets a process's CPU scheduling priority": "Wrong — that's the role of nice/renice, a separate mechanism from ionice.",
            "Limits a process's network bandwidth": "Wrong — that's the role of traffic-shaping tools like tc, unrelated to ionice.",
            "Monitors disk health and predicts failures": "Wrong — that's closer to the role of smartctl, unrelated to ionice's scheduling purpose.",
        },
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `dmesg` display?",
        "options": [
            "Kernel ring buffer messages, useful for diagnosing hardware/kernel-level issues",
            "A list of currently running background daemons",
            "Disk usage statistics per filesystem",
            "DNS resolution query logs",
        ],
        "correct_answer": "Kernel ring buffer messages, useful for diagnosing hardware/kernel-level issues",
        "explanation_correct": "dmesg prints messages the kernel has logged internally, including boot-time output, hardware detection, and kernel-level warnings or errors.",
        "explanation_incorrect": {
            "A list of currently running background daemons": "Wrong — that's the role of tools like ps or systemctl list-units, unrelated to dmesg.",
            "Disk usage statistics per filesystem": "Wrong — that's the role of df, unrelated to the kernel ring buffer.",
            "DNS resolution query logs": "Wrong — DNS query logging is handled by a resolver or DNS server, unrelated to dmesg.",
        },
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of `systemd-analyze blame`?",
        "options": [
            "Shows which systemd units took the longest to initialize during boot",
            "Shows which user account is responsible for a failed service",
            "Prevents a specific service from starting",
            "Analyzes network latency between hosts",
        ],
        "correct_answer": "Shows which systemd units took the longest to initialize during boot",
        "explanation_correct": "systemd-analyze blame sorts units by their initialization time, helping identify which services are slowing down the overall boot process.",
        "explanation_incorrect": {
            "Shows which user account is responsible for a failed service": "Wrong — this isn't about user accountability at all; it's purely about unit startup timing.",
            "Prevents a specific service from starting": "Wrong — that would be closer to masking a service (systemctl mask), a completely different action from blame.",
            "Analyzes network latency between hosts": "Wrong — network latency analysis is unrelated to systemd-analyze's boot-timing purpose.",
        },
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What does LUKS provide?",
        "options": [
            "Full disk/block device encryption on Linux",
            "An alternative to logical volume management",
            "A firewall rule configuration format",
            "A package signing and verification mechanism",
        ],
        "correct_answer": "Full disk/block device encryption on Linux",
        "explanation_correct": "LUKS (Linux Unified Key Setup) is the standard specification for full block-device encryption, managed via tools like cryptsetup.",
        "explanation_incorrect": {
            "An alternative to logical volume management": "Wrong — LUKS is about encryption, not volume management; it's commonly used alongside LVM, not as a replacement for it.",
            "A firewall rule configuration format": "Wrong — firewall rules are unrelated to LUKS, which is purely about disk encryption.",
            "A package signing and verification mechanism": "Wrong — package signing is a separate concern (e.g. GPG-signed repos), unrelated to LUKS.",
        },
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of a firewalld 'rich rule'?",
        "options": [
            "Allows more complex, fine-grained firewall rules (e.g. combining a source address with a specific service and action) beyond simple port/service rules",
            "Temporarily disables all firewall rules",
            "Applies exclusively to IPv6 traffic",
            "Completely replaces the concept of firewalld zones",
        ],
        "correct_answer": "Allows more complex, fine-grained firewall rules (e.g. combining a source address with a specific service and action) beyond simple port/service rules",
        "explanation_correct": "Rich rules support combining multiple conditions (like source address, service, and logging/action) into a single expressive rule, beyond what simple port or service rules alone can express.",
        "explanation_incorrect": {
            "Temporarily disables all firewall rules": "Wrong — rich rules add specific filtering logic; they don't disable the firewall.",
            "Applies exclusively to IPv6 traffic": "Wrong — rich rules can target IPv4 or IPv6 (specified via the family attribute), not exclusively IPv6.",
            "Completely replaces the concept of firewalld zones": "Wrong — rich rules work within zones, they don't replace the zone concept.",
        },
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What does the kernel parameter `vm.swappiness` control?",
        "options": [
            "How aggressively the kernel swaps memory pages to disk versus reclaiming page cache",
            "The maximum size of the swap file or partition",
            "Whether swap is enabled or disabled entirely",
            "How aggressively the CPU scheduler preempts running processes",
        ],
        "correct_answer": "How aggressively the kernel swaps memory pages to disk versus reclaiming page cache",
        "explanation_correct": "swappiness (0-100) tunes the kernel's balance between swapping out memory pages and reclaiming file-backed page cache — higher values favor swapping more readily.",
        "explanation_incorrect": {
            "The maximum size of the swap file or partition": "Wrong — swap size is determined by the actual swap device/file itself, not this tunable.",
            "Whether swap is enabled or disabled entirely": "Wrong — enabling/disabling swap is controlled by swapon/swapoff, not swappiness (which only tunes behavior when swap is available).",
            "How aggressively the CPU scheduler preempts running processes": "Wrong — CPU scheduling behavior is unrelated to this memory-management parameter.",
        },
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of `numactl`?",
        "options": [
            "Displays and controls NUMA (Non-Uniform Memory Access) policy for processes and system memory",
            "Manages network interface configuration",
            "Controls per-user disk quotas",
            "Schedules and manages kernel modules",
        ],
        "correct_answer": "Displays and controls NUMA (Non-Uniform Memory Access) policy for processes and system memory",
        "explanation_correct": "numactl shows NUMA topology and lets you bind processes/memory allocation to specific NUMA nodes, useful for performance tuning on multi-socket systems.",
        "explanation_incorrect": {
            "Manages network interface configuration": "Wrong — that's the role of tools like ip, unrelated to numactl.",
            "Controls per-user disk quotas": "Wrong — that's the role of the quota system, unrelated to numactl.",
            "Schedules and manages kernel modules": "Wrong — that's the role of modprobe/lsmod, unrelated to numactl's memory/CPU topology focus.",
        },
    },

    # ---------------- FILL-IN-BLANK (8) ----------------

    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Linux ____ (control groups) limit and isolate the resource usage (CPU, memory, I/O) of a group of processes.",
        "options": None,
        "correct_answer": "cgroups",
        "explanation_correct": "cgroups are the kernel mechanism underlying resource limiting features like systemd's CPUQuota and MemoryMax.",
        "explanation_incorrect": "The blank should be filled with the name of this resource-control mechanism: cgroups.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ command sets or displays a process's I/O scheduling priority and class.",
        "options": None,
        "correct_answer": "ionice",
        "explanation_correct": "ionice controls how the I/O scheduler prioritizes a process's disk requests.",
        "explanation_incorrect": "The blank should be filled with the name of this I/O priority tool: ionice.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ command displays kernel ring buffer messages, useful for diagnosing hardware and kernel-level issues.",
        "options": None,
        "correct_answer": "dmesg",
        "explanation_correct": "dmesg surfaces kernel-logged messages, including hardware detection and warnings.",
        "explanation_incorrect": "The blank should be filled with the name of this kernel message tool: dmesg.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The command `systemd-analyze ____` shows which systemd units took the longest to initialize during boot.",
        "options": None,
        "correct_answer": "blame",
        "explanation_correct": "systemd-analyze blame ranks units by their startup duration.",
        "explanation_incorrect": "The blank should be filled with the systemd-analyze subcommand used for this: blame.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ (Linux Unified Key Setup) provides standard full block-device encryption on Linux, managed via cryptsetup.",
        "options": None,
        "correct_answer": "LUKS",
        "explanation_correct": "LUKS is the standard on-disk format and specification for Linux full-disk encryption.",
        "explanation_incorrect": "The blank should be filled with the acronym for this encryption specification: LUKS.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A firewalld ____ rule allows more complex, fine-grained conditions (like combining a source address with a specific service and action) beyond simple port-based rules.",
        "options": None,
        "correct_answer": "rich",
        "explanation_correct": "Rich rules support multi-condition, expressive firewall logic beyond simple port/service rules.",
        "explanation_incorrect": "The blank should be filled with the name of this expressive rule type: rich.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The kernel parameter vm.____ controls how aggressively the kernel swaps memory pages to disk versus reclaiming page cache.",
        "options": None,
        "correct_answer": "swappiness",
        "explanation_correct": "swappiness tunes the kernel's balance between swapping and page cache reclamation.",
        "explanation_incorrect": "The blank should be filled with the name of this memory management parameter: swappiness.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ command displays and controls NUMA (Non-Uniform Memory Access) memory/CPU policy.",
        "options": None,
        "correct_answer": "numactl",
        "explanation_correct": "numactl shows NUMA topology and lets processes/memory be bound to specific nodes.",
        "explanation_incorrect": "The blank should be filled with the name of this NUMA management tool: numactl.",
    },

    # ---------------- DRAG-AND-DROP (7) ----------------

    {
        "topic": "Linux", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for encrypting, unlocking, and formatting a new block device with LUKS.",
        "options": ["Run `mkfs.ext4 /dev/mapper/secure_data` to format the unlocked mapping", "Run `cryptsetup luksFormat /dev/sdb1` to encrypt the device", "Run `cryptsetup luksOpen /dev/sdb1 secure_data` to unlock it"],
        "correct_answer": '["Run `cryptsetup luksFormat /dev/sdb1` to encrypt the device", "Run `cryptsetup luksOpen /dev/sdb1 secure_data` to unlock it", "Run `mkfs.ext4 /dev/mapper/secure_data` to format the unlocked mapping"]',
        "explanation_correct": "Correct — the device must be encrypted before it can be unlocked, and it must be unlocked (mapped) before a filesystem can be created on it.",
        "explanation_incorrect": "The device must be LUKS-formatted before it can be opened/unlocked, and it must be unlocked before a filesystem can be created on the resulting mapping.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for creating, using, and cleaning up an LVM snapshot.",
        "options": ["Remove the snapshot with `lvremove` once it's no longer needed", "Run `lvcreate -L 5G -s -n data_snap /dev/vg_data/data_lv` to create a snapshot", "Mount the snapshot to inspect a point-in-time view of the data"],
        "correct_answer": '["Run `lvcreate -L 5G -s -n data_snap /dev/vg_data/data_lv` to create a snapshot", "Mount the snapshot to inspect a point-in-time view of the data", "Remove the snapshot with `lvremove` once it\'s no longer needed"]',
        "explanation_correct": "Correct — the snapshot must exist before it can be mounted for inspection, and removal should come only after it's no longer needed.",
        "explanation_incorrect": "The snapshot must be created before it can be mounted, and it should only be removed once you're finished using it.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for relabeling a file's SELinux context back to its policy-defined default after a temporary change.",
        "options": ["Note that chcon changes don't survive a full relabel", "Run `chcon -t httpd_sys_content_t /var/www/html/index.html` to temporarily set the context", "Run `restorecon /var/www/html/index.html` to reset it to the policy-defined default"],
        "correct_answer": '["Run `chcon -t httpd_sys_content_t /var/www/html/index.html` to temporarily set the context", "Note that chcon changes don\'t survive a full relabel", "Run `restorecon /var/www/html/index.html` to reset it to the policy-defined default"]',
        "explanation_correct": "Correct — the temporary chcon change must be made before its impermanence is relevant, and restorecon (the reset action) comes last, undoing the earlier change.",
        "explanation_incorrect": "The temporary context change must happen before discussing its impermanence makes sense, and resetting with restorecon is the final corrective step.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing and addressing slow boot time with systemd-analyze.",
        "options": ["Investigate and optimize the specific slow-starting unit", "Run `systemd-analyze` to see total boot time", "Run `systemd-analyze blame` to identify the slowest units"],
        "correct_answer": '["Run `systemd-analyze` to see total boot time", "Run `systemd-analyze blame` to identify the slowest units", "Investigate and optimize the specific slow-starting unit"]',
        "explanation_correct": "Correct — confirming there's actually a boot-time problem comes first, identifying the specific slow units comes next, and targeted investigation follows once a culprit is known.",
        "explanation_incorrect": "Getting the overall boot time is a reasonable starting point, identifying specific slow units narrows the problem, and investigating a specific unit only makes sense once it's been identified as slow.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for changing a kernel parameter immediately and then verifying its persistence.",
        "options": ["Run `sysctl -p` to confirm the persisted setting reloads correctly", "Run `sysctl -w vm.swappiness=10` to change it immediately", "Add `vm.swappiness = 10` to /etc/sysctl.conf"],
        "correct_answer": '["Run `sysctl -w vm.swappiness=10` to change it immediately", "Add `vm.swappiness = 10` to /etc/sysctl.conf", "Run `sysctl -p` to confirm the persisted setting reloads correctly"]',
        "explanation_correct": "Correct — the immediate runtime change comes first, adding the persistent config entry comes next, and reloading from the config file verifies persistence last.",
        "explanation_incorrect": "The immediate change is applied first, the persistent config entry is added next, and reloading is the final verification step confirming the setting persists.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for auditing access to a sensitive file with auditd.",
        "options": ["Run `ausearch -f /etc/shadow` to review the logged events", "Ensure an audit rule is watching /etc/shadow (via auditctl -w)", "Trigger or wait for access to the file to occur"],
        "correct_answer": '["Ensure an audit rule is watching /etc/shadow (via auditctl -w)", "Trigger or wait for access to the file to occur", "Run `ausearch -f /etc/shadow` to review the logged events"]',
        "explanation_correct": "Correct — the watch rule must be in place before relevant access is logged, and reviewing logged events only makes sense after actual access has occurred and been recorded.",
        "explanation_incorrect": "The audit rule must be set up before any access events can be captured, and searching the logs only produces meaningful results after some access has actually happened.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for adding, applying, and verifying a firewalld rich rule.",
        "options": ["Run `firewall-cmd --list-rich-rules` to confirm it's active", "Run `firewall-cmd --add-rich-rule='...' --permanent` to add the rule", "Run `firewall-cmd --reload` to apply the permanent rule"],
        "correct_answer": '["Run `firewall-cmd --add-rich-rule=\'...\' --permanent` to add the rule", "Run `firewall-cmd --reload` to apply the permanent rule", "Run `firewall-cmd --list-rich-rules` to confirm it\'s active"]',
        "explanation_correct": "Correct — the permanent rule must be added before a reload can apply it, and confirming it's active naturally comes after the reload.",
        "explanation_incorrect": "The rule must be added to the permanent configuration before a reload can apply it, and verification should happen after that reload takes effect.",
    },

    # ---------------- DROPDOWN-ORDER (7) ----------------

    {
        "topic": "Linux", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for creating and configuring a VLAN interface.",
        "options": ["Run `ip addr add <address> dev eth0.100` to assign it an address", "Run `ip link add link eth0 name eth0.100 type vlan id 100` to create the VLAN interface", "Run `ip link set eth0.100 up` to bring the interface up"],
        "correct_answer": '["Run `ip link add link eth0 name eth0.100 type vlan id 100` to create the VLAN interface", "Run `ip link set eth0.100 up` to bring the interface up", "Run `ip addr add <address> dev eth0.100` to assign it an address"]',
        "explanation_correct": "Correct — the interface must exist before it can be brought up or assigned an address, and it's conventional to bring the link up before assigning addressing to it.",
        "explanation_incorrect": "The VLAN interface must be created before it can be configured further, and bringing it up before assigning an address is the conventional order.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for loading and verifying a kernel module.",
        "options": ["Check dmesg output for any related warnings", "Run `modprobe br_netfilter` to load the module", "Run `lsmod` to confirm it's loaded"],
        "correct_answer": '["Run `modprobe br_netfilter` to load the module", "Run `lsmod` to confirm it\'s loaded", "Check dmesg output for any related warnings"]',
        "explanation_correct": "Correct — the module must be loaded before it can be confirmed as loaded, and checking for related warnings is a reasonable final verification step.",
        "explanation_incorrect": "The module must be loaded before lsmod can confirm its presence, and checking dmesg for issues is a sensible final step after confirming the module loaded.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting and verifying a live CPU quota on a systemd service.",
        "options": ["Observe the service's actual CPU usage under load to confirm enforcement", "Run `systemctl set-property myapp.service CPUQuota=50%` to apply the limit immediately", "Run `systemctl show myapp.service -p CPUQuota` to confirm the setting took effect"],
        "correct_answer": '["Run `systemctl set-property myapp.service CPUQuota=50%` to apply the limit immediately", "Run `systemctl show myapp.service -p CPUQuota` to confirm the setting took effect", "Observe the service\'s actual CPU usage under load to confirm enforcement"]',
        "explanation_correct": "Correct — the quota must be set before it can be confirmed via systemctl show, and observing real enforcement under load is the final practical validation step.",
        "explanation_incorrect": "The property must be set before it can be confirmed, and observing actual behavior under load is a reasonable final step after confirming the configuration itself.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for holding a package and confirming the hold works.",
        "options": ["Run a normal `apt upgrade` and confirm nginx is skipped", "Run `apt-mark hold nginx` to prevent it from being upgraded", "Run `apt-mark showhold` to confirm the hold is active"],
        "correct_answer": '["Run `apt-mark hold nginx` to prevent it from being upgraded", "Run `apt-mark showhold` to confirm the hold is active", "Run a normal `apt upgrade` and confirm nginx is skipped"]',
        "explanation_correct": "Correct — the hold must be applied before it can be confirmed, and testing with an actual upgrade is the final practical verification step.",
        "explanation_incorrect": "The hold must be set before it can be confirmed as active, and testing with a real upgrade run is a reasonable final step after confirming the hold's configuration.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for investigating a process's effective resource limits.",
        "options": ["Compare against /etc/security/limits.conf to understand where those limits came from", "Identify the PID of the process in question", "Run `cat /proc/<PID>/limits` to view its current resource limits"],
        "correct_answer": '["Identify the PID of the process in question", "Run `cat /proc/<PID>/limits` to view its current resource limits", "Compare against /etc/security/limits.conf to understand where those limits came from"]',
        "explanation_correct": "Correct — the PID must be identified before its limits can be inspected, and tracing those limits back to their configured source is a natural follow-up step.",
        "explanation_incorrect": "The process must be identified before its limits can be viewed, and comparing against the configuration file is a reasonable follow-up once the actual effective limits are known.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for tuning a workload's process placement using NUMA awareness.",
        "options": ["Use `numactl --cpunodebind` and `--membind` to pin a process accordingly", "Run `numactl --hardware` to view the NUMA node layout", "Identify which NUMA node is closest to the relevant CPU/memory resources"],
        "correct_answer": '["Run `numactl --hardware` to view the NUMA node layout", "Identify which NUMA node is closest to the relevant CPU/memory resources", "Use `numactl --cpunodebind` and `--membind` to pin a process accordingly"]',
        "explanation_correct": "Correct — the topology must be understood before a suitable node can be identified, and pinning a process only makes sense once the target node has been determined.",
        "explanation_incorrect": "The NUMA layout must be reviewed before a specific node can be identified as optimal, and pinning a process to a node should happen only after that node has been chosen.",
    },
    {
        "topic": "Linux", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for generating an audit summary report with aureport.",
        "options": ["Allow time for relevant events to be logged", "Ensure auditd is running and rules are configured", "Run `aureport` to generate a summary report of audit events"],
        "correct_answer": '["Ensure auditd is running and rules are configured", "Allow time for relevant events to be logged", "Run `aureport` to generate a summary report of audit events"]',
        "explanation_correct": "Correct — auditd must be running with rules in place before any events can be captured, and generating a report only makes sense once some events have actually accumulated.",
        "explanation_incorrect": "Auditd and its rules must be active before events can be logged, and the summary report is only meaningful once some events have actually been recorded.",
    },
]
