"""
Linux - Medium batch, 50 questions total.
Distribution: 20 coding, 8 mcq, 8 fill-in-blank, 7 drag-and-drop, 7 dropdown-order.

Schema matches linux_easy_questions.py — see that file's header for full field notes.
Medium content covers SELinux, LVM, process priority (nice/renice), ulimit, network
troubleshooting (traceroute/tcpdump), SSH key auth, logrotate, ACLs, systemd targets,
strace, and rsync.
"""

LINUX_MEDIUM_QUESTIONS = [

    # ---------------- CODING (20) ----------------

    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to add an iptables rule allowing incoming TCP traffic on port 443.",
        "correct_answer": "iptables -A INPUT -p tcp --dport 443 -j ACCEPT",
        "explanation_correct": "Correct — this appends a rule to the INPUT chain accepting TCP traffic destined for port 443.",
        "explanation_incorrect": "A correct solution must add a rule permitting inbound TCP traffic specifically on port 443, typically appended to the INPUT chain.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to display the current SELinux enforcement mode.",
        "correct_answer": "getenforce",
        "explanation_correct": "Correct — `getenforce` prints the current SELinux mode (Enforcing, Permissive, or Disabled).",
        "explanation_incorrect": "A correct solution must display the current SELinux mode, typically using getenforce.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to temporarily set SELinux to permissive mode, without editing any configuration files.",
        "correct_answer": "setenforce 0",
        "explanation_correct": "Correct — `setenforce 0` switches SELinux to permissive mode for the current boot session, without touching /etc/selinux/config.",
        "explanation_incorrect": "A correct solution must temporarily switch SELinux to permissive mode via setenforce, not by editing a config file (which would persist across reboots).",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to list all partitions on disk /dev/sda using fdisk.",
        "correct_answer": "fdisk -l /dev/sda",
        "explanation_correct": "Correct — `fdisk -l` lists partition table information for the specified disk.",
        "explanation_incorrect": "A correct solution must list the partitions on /dev/sda specifically, typically using fdisk -l.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to create a new logical volume named 'data_lv' of size 10G from the volume group 'vg_data'.",
        "correct_answer": "lvcreate -L 10G -n data_lv vg_data",
        "explanation_correct": "Correct — lvcreate with -L (size) and -n (name) allocates the new logical volume from the specified volume group.",
        "explanation_incorrect": "A correct solution must create a 10G logical volume named data_lv, sourced from the vg_data volume group.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to change the scheduling priority (niceness) of an already-running process with PID 4321 to 10.",
        "correct_answer": "renice 10 -p 4321",
        "explanation_correct": "Correct — `renice` changes the priority of an already-running process, unlike `nice`, which sets priority only at launch.",
        "explanation_incorrect": "A correct solution must use renice (not nice) to change the priority of an already-running process with the given PID.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to display the current open file descriptor limit for the current shell.",
        "correct_answer": "ulimit -n",
        "explanation_correct": "Correct — `ulimit -n` prints the current soft limit on the number of open file descriptors.",
        "explanation_incorrect": "A correct solution must show the file descriptor limit specifically, typically using ulimit -n.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to trace the network path (hops) to a host named example.com.",
        "correct_answer": "traceroute example.com",
        "explanation_correct": "Correct — `traceroute` shows each network hop between the local machine and the target host.",
        "explanation_incorrect": "A correct solution must trace the network path to example.com, typically using traceroute.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to capture network packets on interface eth0 using tcpdump, showing only traffic on port 80.",
        "correct_answer": "tcpdump -i eth0 port 80",
        "explanation_correct": "Correct — the -i flag selects the capture interface, and the port filter limits capture to traffic on port 80.",
        "explanation_incorrect": "A correct solution must capture on eth0 specifically, filtered to port 80 traffic only.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to query which package owns the file /usr/bin/nginx on an RPM-based system.",
        "correct_answer": "rpm -qf /usr/bin/nginx",
        "explanation_correct": "Correct — `rpm -qf` looks up which installed package provides the given file path.",
        "explanation_incorrect": "A correct solution must identify the owning package for /usr/bin/nginx specifically, typically using rpm -qf.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to generate a new SSH key pair using the ed25519 algorithm, saving it to the default location.",
        "correct_answer": "ssh-keygen -t ed25519",
        "explanation_correct": "Correct — the -t flag specifies the ed25519 key type, and running with no -f path saves the key pair to the default location (~/.ssh/id_ed25519).",
        "explanation_incorrect": "A correct solution must generate a key pair using the ed25519 algorithm specifically, typically using ssh-keygen -t ed25519.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to copy your local public SSH key to a remote host 'user@remotehost' for passwordless login.",
        "correct_answer": "ssh-copy-id user@remotehost",
        "explanation_correct": "Correct — `ssh-copy-id` copies your public key to the remote host's authorized_keys file, enabling passwordless key-based login.",
        "explanation_incorrect": "A correct solution must copy the public key to the specified remote host, typically using ssh-copy-id.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to force logrotate to run immediately using the configuration file /etc/logrotate.conf.",
        "correct_answer": "logrotate -f /etc/logrotate.conf",
        "explanation_correct": "Correct — the -f flag forces log rotation to happen immediately, even if it wouldn't normally be due yet, using the specified config.",
        "explanation_incorrect": "A correct solution must force an immediate rotation using the specified config file, typically using logrotate -f.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to display current swap usage on the system.",
        "correct_answer": "swapon --show",
        "explanation_correct": "Correct — `swapon --show` lists active swap devices/files along with their size and usage.",
        "explanation_incorrect": "A correct solution must display current swap usage, typically using swapon --show (or free -h, which also shows swap).",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write a crontab line that runs the script /opt/scripts/backup.sh at 2:30 AM every day.",
        "correct_answer": "30 2 * * * /opt/scripts/backup.sh",
        "explanation_correct": "Correct — the cron schedule fields (minute=30, hour=2, all days/months/weekdays) correctly specify 2:30 AM daily.",
        "explanation_incorrect": "A correct solution must schedule the script to run at exactly 2:30 AM every day, using the correct 5-field cron time specification.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to set an ACL entry granting user 'appuser' read and write permissions on a file named shared.txt.",
        "correct_answer": "setfacl -m u:appuser:rw shared.txt",
        "explanation_correct": "Correct — `setfacl -m` modifies the ACL, granting the specified user read/write access beyond the standard owner/group/other permissions.",
        "explanation_incorrect": "A correct solution must grant appuser read and write access via an ACL entry, typically using setfacl -m u:appuser:rw.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to view the Access Control List entries currently set on a file named shared.txt.",
        "correct_answer": "getfacl shared.txt",
        "explanation_correct": "Correct — `getfacl` displays all ACL entries currently applied to the given file.",
        "explanation_incorrect": "A correct solution must display the ACL entries for shared.txt specifically, typically using getfacl.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to display which systemd target the system currently boots into by default.",
        "correct_answer": "systemctl get-default",
        "explanation_correct": "Correct — `systemctl get-default` prints the currently configured default boot target (e.g. multi-user.target or graphical.target).",
        "explanation_incorrect": "A correct solution must show the current default systemd boot target, typically using systemctl get-default.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to trace the system calls of a running process with PID 5678, attaching to it live, using strace.",
        "correct_answer": "strace -p 5678",
        "explanation_correct": "Correct — the -p flag attaches strace to an already-running process by PID, tracing its system calls live.",
        "explanation_incorrect": "A correct solution must attach strace to the running process with PID 5678 specifically, using the -p flag.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to synchronize a local directory '/data/' to a remote host 'user@remotehost:/backup/' using rsync, preserving permissions/attributes and only transferring differences.",
        "correct_answer": "rsync -av /data/ user@remotehost:/backup/",
        "explanation_correct": "Correct — the -a (archive) flag preserves permissions, timestamps, and other attributes while transferring only changed data, and -v adds verbose output.",
        "explanation_incorrect": "A correct solution must use rsync with the archive flag (-a) to preserve attributes and efficiently sync only differences, targeting the correct source and destination.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of SELinux (or AppArmor) on a Linux system?",
        "options": [
            "Enforces mandatory access control policies beyond standard file permissions",
            "Completely replaces standard file permissions",
            "Manages network firewall rules",
            "Schedules background tasks and cron jobs",
        ],
        "correct_answer": "Enforces mandatory access control policies beyond standard file permissions",
        "explanation_correct": "SELinux/AppArmor add an additional mandatory access control (MAC) layer, restricting what processes can do even if standard Unix permissions would otherwise allow it.",
        "explanation_incorrect": {
            "Completely replaces standard file permissions": "Wrong — SELinux works alongside standard permissions as an additional layer, it doesn't replace them.",
            "Manages network firewall rules": "Wrong — that's the role of tools like iptables/firewalld, a separate system from SELinux.",
            "Schedules background tasks and cron jobs": "Wrong — task scheduling is handled by cron or systemd timers, unrelated to SELinux's access control purpose.",
        },
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What does LVM (Logical Volume Manager) allow you to do that traditional partitioning doesn't easily support?",
        "options": [
            "Resize storage volumes dynamically without needing to repartition the underlying disk",
            "Automatically encrypt data at rest",
            "Entirely replace the need for a filesystem",
            "Only works with SSD storage devices",
        ],
        "correct_answer": "Resize storage volumes dynamically without needing to repartition the underlying disk",
        "explanation_correct": "LVM adds an abstraction layer over physical storage, letting you grow, shrink, and reorganize logical volumes more flexibly than fixed disk partitions allow.",
        "explanation_incorrect": {
            "Automatically encrypt data at rest": "Wrong — encryption is a separate concern (e.g. LUKS), not something LVM provides by itself.",
            "Entirely replace the need for a filesystem": "Wrong — LVM manages storage volumes, but a filesystem (like ext4 or xfs) is still needed on top of a logical volume.",
            "Only works with SSD storage devices": "Wrong — LVM works with any block storage device, not just SSDs.",
        },
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of the `nice`/`renice` commands?",
        "options": [
            "Adjust the scheduling priority of a process relative to other processes",
            "Automatically restart a crashed process",
            "Limit how much memory a process can use",
            "Rename a running process",
        ],
        "correct_answer": "Adjust the scheduling priority of a process relative to other processes",
        "explanation_correct": "Niceness values influence how the kernel scheduler prioritizes CPU time among competing processes; nice sets it at launch, renice adjusts it for an already-running process.",
        "explanation_incorrect": {
            "Automatically restart a crashed process": "Wrong — that's a supervisory feature of tools like systemd (Restart= settings), unrelated to nice/renice.",
            "Limit how much memory a process can use": "Wrong — memory limits are handled by ulimit or cgroups, not nice/renice.",
            "Rename a running process": "Wrong — nice/renice only affect scheduling priority, not a process's name.",
        },
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `ulimit` control?",
        "options": [
            "Resource limits, such as open file descriptors or process count, for a shell session and its children",
            "Disk usage quotas for a user account",
            "The maximum CPU clock frequency",
            "Network bandwidth limits for a connection",
        ],
        "correct_answer": "Resource limits, such as open file descriptors or process count, for a shell session and its children",
        "explanation_correct": "ulimit sets and displays per-session resource limits (like max open files, max processes, max memory) that apply to the shell and processes it spawns.",
        "explanation_incorrect": {
            "Disk usage quotas for a user account": "Wrong — that's the role of the quota system (edquota/repquota), a separate mechanism from ulimit.",
            "The maximum CPU clock frequency": "Wrong — CPU frequency scaling is managed separately (e.g. via cpufreq), unrelated to ulimit.",
            "Network bandwidth limits for a connection": "Wrong — bandwidth shaping is handled by tools like tc, not ulimit.",
        },
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of an ACL (Access Control List) on a Linux filesystem, beyond the standard owner/group/other permissions?",
        "options": [
            "Allows granting specific permissions to additional individual users or groups beyond the standard three permission classes",
            "Completely replaces the need for standard Unix permissions",
            "Only applies to network-mounted filesystems",
            "Encrypts the contents of the file",
        ],
        "correct_answer": "Allows granting specific permissions to additional individual users or groups beyond the standard three permission classes",
        "explanation_correct": "ACLs let you grant fine-grained permissions to specific users or groups beyond just the file's single owner, single group, and everyone else.",
        "explanation_incorrect": {
            "Completely replaces the need for standard Unix permissions": "Wrong — ACLs work alongside the standard permission model as an extension, not a replacement.",
            "Only applies to network-mounted filesystems": "Wrong — ACLs work on local filesystems too, as long as the filesystem supports them (e.g. ext4 with acl mount option).",
            "Encrypts the contents of the file": "Wrong — ACLs control access permissions, they don't provide any encryption.",
        },
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of `logrotate`?",
        "options": [
            "Automatically archives, compresses, and manages the rotation of log files to prevent unbounded growth",
            "Deletes all logs older than a fixed period with no configuration options",
            "Monitors logs in real time and alerts on errors",
            "Encrypts log files for secure storage",
        ],
        "correct_answer": "Automatically archives, compresses, and manages the rotation of log files to prevent unbounded growth",
        "explanation_correct": "logrotate periodically rotates, compresses, and optionally removes old log files based on configurable rules, keeping log directories from growing without bound.",
        "explanation_incorrect": {
            "Deletes all logs older than a fixed period with no configuration options": "Wrong — logrotate is highly configurable (rotation frequency, retention count, compression, etc.), not a fixed, non-configurable deletion tool.",
            "Monitors logs in real time and alerts on errors": "Wrong — that describes log monitoring/alerting tools, a different category from logrotate's rotation/archiving role.",
            "Encrypts log files for secure storage": "Wrong — encryption isn't logrotate's core function; it focuses on rotation and compression.",
        },
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `strace` do?",
        "options": [
            "Traces and displays the system calls made by a running or newly started process",
            "Traces network packets on a given interface",
            "Monitors disk I/O exclusively",
            "Displays a process's memory map only",
        ],
        "correct_answer": "Traces and displays the system calls made by a running or newly started process",
        "explanation_correct": "strace intercepts and logs the system calls a process makes, useful for diagnosing what a program is actually doing at the kernel interaction level.",
        "explanation_incorrect": {
            "Traces network packets on a given interface": "Wrong — that's the role of tcpdump, a different diagnostic tool from strace.",
            "Monitors disk I/O exclusively": "Wrong — strace covers all system calls, not just disk-related ones (tools like iotop focus specifically on I/O).",
            "Displays a process's memory map only": "Wrong — that's closer to what /proc/<pid>/maps or pmap shows; strace's focus is system call tracing, not just memory layout.",
        },
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of systemd timers, as an alternative to cron?",
        "options": [
            "Schedule units (like services) to run at specified times or intervals, integrated with systemd's dependency and logging system",
            "Completely replace the need for systemd itself",
            "Only support one-time (non-recurring) scheduled tasks",
            "Are used for rate-limiting network requests, not scheduling",
        ],
        "correct_answer": "Schedule units (like services) to run at specified times or intervals, integrated with systemd's dependency and logging system",
        "explanation_correct": "systemd timers trigger associated .service units on a schedule, benefiting from systemd's dependency management, logging (via journald), and status reporting, unlike standalone cron entries.",
        "explanation_incorrect": {
            "Completely replace the need for systemd itself": "Wrong — timers are a feature within systemd, not something that replaces systemd as a whole.",
            "Only support one-time (non-recurring) scheduled tasks": "Wrong — systemd timers support both one-time (OnCalendar with a specific date) and recurring schedules.",
            "Are used for rate-limiting network requests, not scheduling": "Wrong — that's not what systemd timers do at all; their purpose is time-based unit activation.",
        },
    },

    # ---------------- FILL-IN-BLANK (8) ----------------

    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "____ (or AppArmor) enforces mandatory access control policies on Linux, beyond standard file permissions.",
        "options": None,
        "correct_answer": "SELinux",
        "explanation_correct": "SELinux is a mandatory access control system commonly used on Red Hat-based distributions.",
        "explanation_incorrect": "The blank should be filled with the name of this access control system: SELinux.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command changes the priority of an already-running process (as opposed to nice, which sets priority only at launch).",
        "options": None,
        "correct_answer": "renice",
        "explanation_correct": "renice adjusts the niceness value of a process that's already running, identified by its PID.",
        "explanation_incorrect": "The blank should be filled with the command used to reprioritize a running process: renice.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command controls shell-level resource limits, such as the maximum number of open file descriptors.",
        "options": None,
        "correct_answer": "ulimit",
        "explanation_correct": "ulimit sets and displays per-session resource limits for the shell and its child processes.",
        "explanation_incorrect": "The blank should be filled with the command used to view/set resource limits: ulimit.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A logical volume manager, or ____, allows storage volumes to be resized dynamically without repartitioning the underlying disk.",
        "options": None,
        "correct_answer": "LVM",
        "explanation_correct": "LVM adds a flexible abstraction layer over physical storage devices.",
        "explanation_incorrect": "The blank should be filled with the acronym for this storage management system: LVM.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command captures and displays network packets on a given interface, useful for low-level network troubleshooting.",
        "options": None,
        "correct_answer": "tcpdump",
        "explanation_correct": "tcpdump captures live network traffic for inspection and filtering.",
        "explanation_incorrect": "The blank should be filled with the name of this packet capture tool: tcpdump.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command configures and applies Access Control List permissions on a file, beyond the standard owner/group/other model.",
        "options": None,
        "correct_answer": "setfacl",
        "explanation_correct": "setfacl modifies a file's ACL entries to grant fine-grained permissions.",
        "explanation_incorrect": "The blank should be filled with the command used to set ACLs: setfacl.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ utility automatically archives, compresses, and rotates log files to keep them from growing unbounded.",
        "options": None,
        "correct_answer": "logrotate",
        "explanation_correct": "logrotate manages the lifecycle of log files according to configurable rotation rules.",
        "explanation_incorrect": "The blank should be filled with the name of this log management utility: logrotate.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ command traces and displays the system calls made by a running process, useful for diagnosing low-level behavior.",
        "options": None,
        "correct_answer": "strace",
        "explanation_correct": "strace intercepts and logs a process's system calls.",
        "explanation_incorrect": "The blank should be filled with the name of this system call tracing tool: strace.",
    },

    # ---------------- DRAG-AND-DROP (7) ----------------

    {
        "topic": "Linux", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up passwordless SSH login to a remote host.",
        "options": ["SSH into the remote host without being prompted for a password", "Run `ssh-keygen -t ed25519` to generate a key pair", "Run `ssh-copy-id user@remotehost` to copy the public key to the remote host"],
        "correct_answer": '["Run `ssh-keygen -t ed25519` to generate a key pair", "Run `ssh-copy-id user@remotehost` to copy the public key to the remote host", "SSH into the remote host without being prompted for a password"]',
        "explanation_correct": "Correct — a key pair must exist before its public key can be copied anywhere, and copying the key must happen before passwordless login will actually work.",
        "explanation_incorrect": "A key pair must be generated before it can be copied to a remote host, and the copy must complete before passwordless authentication becomes possible.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for creating, formatting, and mounting an LVM logical volume.",
        "options": ["Run `mount /dev/vg_data/data_lv /mnt/data` to mount it", "Run `lvcreate -L 10G -n data_lv vg_data` to create the logical volume", "Run `mkfs.ext4 /dev/vg_data/data_lv` to format it"],
        "correct_answer": '["Run `lvcreate -L 10G -n data_lv vg_data` to create the logical volume", "Run `mkfs.ext4 /dev/vg_data/data_lv` to format it", "Run `mount /dev/vg_data/data_lv /mnt/data` to mount it"]',
        "explanation_correct": "Correct — the logical volume must exist before it can be formatted, and it must have a filesystem before it can be mounted.",
        "explanation_incorrect": "The logical volume must be created before formatting can target it, and a filesystem must exist on it before it can be mounted.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing a slow network connection.",
        "options": ["Analyze the captured packets to identify the root cause", "Run `traceroute example.com` to see the network path and identify slow hops", "Run `tcpdump -i eth0 port 80` to capture relevant traffic for deeper inspection"],
        "correct_answer": '["Run `traceroute example.com` to see the network path and identify slow hops", "Run `tcpdump -i eth0 port 80` to capture relevant traffic for deeper inspection", "Analyze the captured packets to identify the root cause"]',
        "explanation_correct": "Correct — a high-level path check comes first, deeper packet capture follows to gather more detail, and analysis of that captured data comes last.",
        "explanation_incorrect": "The broad path-level check (traceroute) is a reasonable starting point, with packet capture providing deeper detail afterward, and analysis following once that data has actually been captured.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting an ACL on a file and confirming it took effect.",
        "options": ["Confirm appuser now has the expected access", "Run `setfacl -m u:appuser:rw shared.txt` to grant the user read/write access", "Run `getfacl shared.txt` to view the current ACL entries"],
        "correct_answer": '["Run `setfacl -m u:appuser:rw shared.txt` to grant the user read/write access", "Run `getfacl shared.txt` to view the current ACL entries", "Confirm appuser now has the expected access"]',
        "explanation_correct": "Correct — the ACL must be set before there's anything new to view with getfacl, and confirming appuser's access follows after reviewing that output.",
        "explanation_incorrect": "The ACL change must be applied before getfacl has anything new to display, and final confirmation of access naturally comes after reviewing that output.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for adjusting a running process's priority.",
        "options": ["Confirm the change by checking the process's new niceness value", "Run `ps aux` or `top` to find the process's PID", "Run `renice 10 -p 4321` to adjust its priority"],
        "correct_answer": '["Run `ps aux` or `top` to find the process\'s PID", "Run `renice 10 -p 4321` to adjust its priority", "Confirm the change by checking the process\'s new niceness value"]',
        "explanation_correct": "Correct — the PID must be identified before renice can target it, and confirming the change naturally happens after the change has actually been applied.",
        "explanation_incorrect": "The process's PID must be found before renice can be used to target it, and verifying the change should happen only after the change has been made.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for troubleshooting a running process with strace.",
        "options": ["Review the output to diagnose unexpected behavior", "Identify the PID of the process to investigate", "Run `strace -p <PID>` to attach and trace its system calls live"],
        "correct_answer": '["Identify the PID of the process to investigate", "Run `strace -p <PID>` to attach and trace its system calls live", "Review the output to diagnose unexpected behavior"]',
        "explanation_correct": "Correct — the PID must be identified before strace can attach to it, and reviewing output naturally comes after tracing has actually produced some.",
        "explanation_incorrect": "The PID must be identified before strace can be attached to the correct process, and reviewing the traced output only makes sense once tracing has actually run.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for creating a systemd timer as a cron alternative.",
        "options": ["Enable and start the .timer unit with systemctl", "Create a .service unit defining the task to run", "Create a matching .timer unit defining the schedule"],
        "correct_answer": '["Create a .service unit defining the task to run", "Create a matching .timer unit defining the schedule", "Enable and start the .timer unit with systemctl"]',
        "explanation_correct": "Correct — the service unit (what to run) should be defined before the timer unit (when to run it) that references it, and both must exist before the timer can be enabled and started.",
        "explanation_incorrect": "The service defining the task should exist before the timer that schedules it is created, and both units must be in place before the timer can be enabled/started.",
    },

    # ---------------- DROPDOWN-ORDER (7) ----------------

    {
        "topic": "Linux", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for checking whether SELinux is causing an issue.",
        "options": ["Reproduce the issue to see if SELinux was the cause", "Run `getenforce` to check the current SELinux mode", "Run `setenforce 0` to switch to permissive mode temporarily"],
        "correct_answer": '["Run `getenforce` to check the current SELinux mode", "Run `setenforce 0` to switch to permissive mode temporarily", "Reproduce the issue to see if SELinux was the cause"]',
        "explanation_correct": "Correct — checking the current mode establishes a baseline before changing it, and reproducing the issue only makes sense after the mode has actually been switched.",
        "explanation_incorrect": "Checking the current mode is a sensible first step, switching to permissive comes next, and reproducing the issue to test the theory comes only after that change is in place.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for syncing files with rsync and verifying the result.",
        "options": ["Spot-check a few files on the remote host to confirm the sync", "Run `rsync -av /data/ user@remotehost:/backup/` to sync files, preserving attributes", "Review the rsync summary output for errors"],
        "correct_answer": '["Run `rsync -av /data/ user@remotehost:/backup/` to sync files, preserving attributes", "Review the rsync summary output for errors", "Spot-check a few files on the remote host to confirm the sync"]',
        "explanation_correct": "Correct — the sync must run before there's a summary to review, and spot-checking files naturally comes after confirming the summary looked clean.",
        "explanation_incorrect": "The rsync command must run before any output can be reviewed, and spot-checking individual files is a reasonable final verification step after reviewing the overall summary.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up a scheduled backup with cron.",
        "options": ["Save and exit; cron applies the new schedule automatically", "Run `crontab -e` to open the crontab for editing", "Add a line specifying the schedule and the backup script to run"],
        "correct_answer": '["Run `crontab -e` to open the crontab for editing", "Add a line specifying the schedule and the backup script to run", "Save and exit; cron applies the new schedule automatically"]',
        "explanation_correct": "Correct — the crontab must be opened before a new line can be added, and saving/exiting is the final step that commits the new schedule.",
        "explanation_incorrect": "The crontab file must be open for editing before a schedule line can be added, and saving is the final step that actually applies the change.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for checking swap usage and adding more if needed.",
        "options": ["Create and enable a new swap file if more space is required", "Run `swapon --show` (or `free -h`) to check current swap usage", "Determine if additional swap space is needed"],
        "correct_answer": '["Run `swapon --show` (or `free -h`) to check current swap usage", "Determine if additional swap space is needed", "Create and enable a new swap file if more space is required"]',
        "explanation_correct": "Correct — current usage must be checked before a decision about needing more can be made, and creating more swap only happens once that decision is reached.",
        "explanation_incorrect": "Checking current swap usage must come before deciding whether more is needed, and adding swap only happens after that decision has been made.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for identifying which package owns a file and checking its version.",
        "options": ["Note the returned package name", "Run `rpm -qf /usr/bin/nginx` to identify the owning package", "Use that package name for further package management actions (e.g. checking its version)"],
        "correct_answer": '["Run `rpm -qf /usr/bin/nginx` to identify the owning package", "Note the returned package name", "Use that package name for further package management actions (e.g. checking its version)"]',
        "explanation_correct": "Correct — the query must run before there's a package name to note, and that name must be noted before it can be used in further commands.",
        "explanation_incorrect": "The rpm query must run first to produce a package name, which must be noted before it can be used for any follow-up actions.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for checking and changing the default systemd boot target.",
        "options": ["Reboot for the new default target to take effect", "Run `systemctl get-default` to see the current default target", "Run `systemctl set-default multi-user.target` to change it if needed"],
        "correct_answer": '["Run `systemctl get-default` to see the current default target", "Run `systemctl set-default multi-user.target` to change it if needed", "Reboot for the new default target to take effect"]',
        "explanation_correct": "Correct — checking the current target establishes a baseline before changing it, and rebooting to observe the effect naturally follows the change.",
        "explanation_incorrect": "The current default should be checked before deciding to change it, and rebooting to verify the new default only makes sense after the change has been applied.",
    },
    {
        "topic": "Linux", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for capturing traffic to a file and reviewing it later.",
        "options": ["Review the captured packets in detail (e.g. with Wireshark or tcpdump -r)", "Run `tcpdump -i eth0 port 80 -w capture.pcap` to save traffic to a file", "Transfer or open the capture file"],
        "correct_answer": '["Run `tcpdump -i eth0 port 80 -w capture.pcap` to save traffic to a file", "Transfer or open the capture file", "Review the captured packets in detail (e.g. with Wireshark or tcpdump -r)"]',
        "explanation_correct": "Correct — the capture file must be created before it can be transferred or opened, and detailed review only makes sense once the file is accessible.",
        "explanation_incorrect": "The capture must be recorded to a file before it can be transferred or opened, and detailed review naturally comes after the file is accessible.",
    },
]
