"""
Linux - Easy batch, 50 questions total.
Distribution: 20 coding, 8 mcq, 8 fill-in-blank, 7 drag-and-drop, 7 dropdown-order.

Focused on sysadmin/DevOps fundamentals — permissions, users/groups, systemd, package
management, process management, disk/filesystem, firewalls, log review, grep/sed/awk
one-liners, and basic kernel tuning. Deliberately avoids bash scripting constructs
(loops, variables, functions) to keep this distinct from the Bash topic — "coding"
questions here are single commands/one-liners, not scripts.

Schema matches python_easy_questions.py / ansible_easy_questions.py — see those files'
headers for full field notes.
"""

LINUX_EASY_QUESTIONS = [

    # ---------------- CODING (20) ----------------

    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to change the permissions of 'script.sh' so only the owner can read, write, and execute it (mode 700).",
        "correct_answer": "chmod 700 script.sh",
        "explanation_correct": "Correct — octal mode 700 grants the owner full read/write/execute access while giving group and others no access at all.",
        "explanation_incorrect": "A correct solution must set the permissions to exactly 700 (owner: rwx, group: none, others: none) on script.sh.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to change the owner of 'data.txt' to user 'appuser' and group 'appgroup'.",
        "correct_answer": "chown appuser:appgroup data.txt",
        "explanation_correct": "Correct — chown with the user:group syntax updates both the owning user and group in a single command.",
        "explanation_incorrect": "A correct solution must set both the owner (appuser) and group (appgroup) on data.txt, typically using chown user:group syntax.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display detailed information (permissions, owner, size) for all files in the current directory, including hidden ones.",
        "correct_answer": "ls -la",
        "explanation_correct": "Correct — the -l flag shows the long/detailed listing format, and -a includes hidden (dotfile) entries.",
        "explanation_incorrect": "A correct solution must show detailed file information and include hidden files, typically using ls -la.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to find all files named '*.log' under the /var/log directory.",
        "correct_answer": "find /var/log -name \"*.log\"",
        "explanation_correct": "Correct — find searches the given directory tree, and -name \"*.log\" matches files ending in .log.",
        "explanation_incorrect": "A correct solution must search recursively under /var/log for files matching the *.log pattern.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to search for the string 'ERROR' within a file named app.log.",
        "correct_answer": "grep \"ERROR\" app.log",
        "explanation_correct": "Correct — grep searches the given file for lines containing the specified pattern.",
        "explanation_incorrect": "A correct solution must search app.log for the string 'ERROR', typically using grep.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display the last 20 lines of a file named app.log.",
        "correct_answer": "tail -n 20 app.log",
        "explanation_correct": "Correct — tail -n 20 prints exactly the last 20 lines of the given file.",
        "explanation_incorrect": "A correct solution must print exactly the last 20 lines of app.log, typically using tail -n.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display a live, continuously updating view of running processes and system resource usage.",
        "correct_answer": "top",
        "explanation_correct": "Correct — `top` shows a real-time, auto-refreshing view of running processes and resource usage.",
        "explanation_incorrect": "A correct solution must show a live, continuously updating process view, typically using top (or htop).",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to terminate a process with PID 1234.",
        "correct_answer": "kill 1234",
        "explanation_correct": "Correct — `kill` sends a termination signal (SIGTERM by default) to the process with the given PID.",
        "explanation_incorrect": "A correct solution must target PID 1234 specifically, using the kill command.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to check the current status of the systemd service 'nginx'.",
        "correct_answer": "systemctl status nginx",
        "explanation_correct": "Correct — `systemctl status` shows whether the given service is active, its recent log output, and other state information.",
        "explanation_incorrect": "A correct solution must check the status of the nginx service specifically, using systemctl status.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to configure the systemd service 'nginx' to start automatically at boot, without starting it right now.",
        "correct_answer": "systemctl enable nginx",
        "explanation_correct": "Correct — `systemctl enable` configures a service to start on future boots, without affecting whether it's running right now.",
        "explanation_incorrect": "A correct solution must enable nginx for boot-time startup specifically (not start it immediately), using systemctl enable.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to view the last 50 lines of the systemd journal for the 'sshd' service.",
        "correct_answer": "journalctl -u sshd -n 50",
        "explanation_correct": "Correct — the -u flag filters the journal to the given unit (sshd), and -n 50 limits output to the last 50 entries.",
        "explanation_incorrect": "A correct solution must filter journal output to the sshd unit specifically and limit it to the last 50 lines.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display disk space usage for all mounted filesystems in human-readable format.",
        "correct_answer": "df -h",
        "explanation_correct": "Correct — `df -h` lists disk usage per mounted filesystem, with sizes shown in human-readable units (K, M, G).",
        "explanation_incorrect": "A correct solution must show disk usage across mounted filesystems in human-readable units, typically using df -h.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display the total size of the /var/log directory in human-readable format.",
        "correct_answer": "du -sh /var/log",
        "explanation_correct": "Correct — the -s flag summarizes total usage for the directory (rather than listing every subdirectory), and -h formats it in human-readable units.",
        "explanation_incorrect": "A correct solution must show the total summarized size of /var/log in human-readable units, typically using du -sh.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to list all currently mounted filesystems.",
        "correct_answer": "mount",
        "explanation_correct": "Correct — running `mount` with no arguments lists all currently mounted filesystems and their options.",
        "explanation_incorrect": "A correct solution must list currently mounted filesystems, typically using the mount command with no arguments.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to install the package 'htop' on a Debian/Ubuntu system using apt.",
        "correct_answer": "apt install htop",
        "explanation_correct": "Correct — `apt install` installs the specified package using the system's configured repositories.",
        "explanation_incorrect": "A correct solution must install the htop package specifically, using apt install.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to list all currently listening TCP ports on the system, using ss.",
        "correct_answer": "ss -tln",
        "explanation_correct": "Correct — -t filters to TCP sockets, -l shows only listening sockets, and -n shows numeric ports/addresses instead of resolving names.",
        "explanation_incorrect": "A correct solution must show only listening TCP ports, typically using ss with the -t and -l flags.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to add a new user named 'deploy' with a home directory.",
        "correct_answer": "useradd -m deploy",
        "explanation_correct": "Correct — the -m flag ensures a home directory is created for the new user, in addition to creating the account itself.",
        "explanation_incorrect": "A correct solution must create the user 'deploy' with a home directory, typically using useradd -m.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to add an existing user 'deploy' to the group 'sudo', without removing them from their other groups.",
        "correct_answer": "usermod -aG sudo deploy",
        "explanation_correct": "Correct — the -aG flags append the user to the specified supplementary group, rather than replacing their existing group memberships.",
        "explanation_incorrect": "A correct solution must add deploy to the sudo group while preserving their existing group memberships (the -a flag is important here).",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write an awk one-liner that prints the 3rd column of a space-separated file named data.txt.",
        "correct_answer": "awk '{print $3}' data.txt",
        "explanation_correct": "Correct — awk splits each line into fields by whitespace by default, and $3 refers to the third field.",
        "explanation_incorrect": "A correct solution must print only the third whitespace-separated field of each line in data.txt, typically using awk.",
        "options": None,
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "coding",
        "prompt": "Write a sed one-liner that replaces all occurrences of 'foo' with 'bar' in a file named config.txt, printing the result to stdout without modifying the file.",
        "correct_answer": "sed 's/foo/bar/g' config.txt",
        "explanation_correct": "Correct — without the -i flag, sed prints the transformed output to stdout, leaving the original file untouched; the 's/foo/bar/g' expression replaces every occurrence.",
        "explanation_incorrect": "A correct solution must replace every occurrence of 'foo' with 'bar' and print the result to stdout, without using the -i (in-place edit) flag.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "What permissions does `chmod 755 script.sh` set?",
        "options": [
            "Owner: read/write/execute, Group: read/execute, Others: read/execute",
            "Owner: read/write, Group: read, Others: read",
            "Owner: execute only, Group: none, Others: none",
            "Owner: read only, Group: read only, Others: read only",
        ],
        "correct_answer": "Owner: read/write/execute, Group: read/execute, Others: read/execute",
        "explanation_correct": "755 in octal breaks down as 7 (rwx) for owner, 5 (r-x) for group, and 5 (r-x) for others.",
        "explanation_incorrect": {
            "Owner: read/write, Group: read, Others: read": "Wrong — that would correspond to mode 644, not 755 (which grants execute permission to all three).",
            "Owner: execute only, Group: none, Others: none": "Wrong — that would correspond to mode 100, far more restrictive than 755.",
            "Owner: read only, Group: read only, Others: read only": "Wrong — that would correspond to mode 444, with no write or execute permissions at all.",
        },
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "Which directory conventionally contains system and application log files on most Linux distributions?",
        "options": ["/var/log", "/etc/log", "/usr/log", "/tmp/log"],
        "correct_answer": "/var/log",
        "explanation_correct": "/var/log is the standard location for system and application logs on Linux, following the Filesystem Hierarchy Standard.",
        "explanation_incorrect": {
            "/etc/log": "Wrong — /etc conventionally holds configuration files, not logs.",
            "/usr/log": "Wrong — this isn't a standard log directory; /usr conventionally holds installed software.",
            "/tmp/log": "Wrong — /tmp is for temporary files that may be cleared on reboot, not the conventional persistent log location.",
        },
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of the `sudo` command?",
        "options": [
            "Executes a single command with elevated (typically root) privileges",
            "Permanently switches the current session to a different user's shell",
            "Displays general system information",
            "Schedules a command to run at a later time",
        ],
        "correct_answer": "Executes a single command with elevated (typically root) privileges",
        "explanation_correct": "sudo runs the specified command with elevated privileges (based on configured policy), typically requiring the user's own password rather than root's.",
        "explanation_incorrect": {
            "Permanently switches the current session to a different user's shell": "Wrong — that's closer to the role of `su`, and even su doesn't make the switch permanent beyond that shell session.",
            "Displays general system information": "Wrong — that's unrelated to sudo's purpose, which is specifically about privilege escalation for a command.",
            "Schedules a command to run at a later time": "Wrong — that's the role of tools like at or cron, not sudo.",
        },
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "What does `systemctl enable <service>` do, as opposed to `systemctl start <service>`?",
        "options": [
            "Configures the service to start automatically at boot, without starting it immediately",
            "Starts the service immediately without enabling it at boot",
            "Both starts the service and enables it at boot in one step",
            "Disables the service entirely so it can never run",
        ],
        "correct_answer": "Configures the service to start automatically at boot, without starting it immediately",
        "explanation_correct": "enable only affects boot-time behavior (creating the necessary symlinks); it doesn't start the service in the current session — that's what start is for.",
        "explanation_incorrect": {
            "Starts the service immediately without enabling it at boot": "Wrong — that's backwards; enable affects boot-time behavior while start affects the current session, the opposite of this description.",
            "Both starts the service and enables it at boot in one step": "Wrong — enable and start are separate actions; running enable alone does not start the service right now.",
            "Disables the service entirely so it can never run": "Wrong — that describes `systemctl disable`, the opposite command.",
        },
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of the /etc/passwd file?",
        "options": [
            "Stores user account information, such as username, UID, home directory, and default shell",
            "Stores encrypted user passwords directly",
            "Stores firewall rules",
            "Stores a list of currently installed packages",
        ],
        "correct_answer": "Stores user account information, such as username, UID, home directory, and default shell",
        "explanation_correct": "/etc/passwd holds basic account metadata for each user; the actual encrypted password hashes are stored separately in /etc/shadow.",
        "explanation_incorrect": {
            "Stores encrypted user passwords directly": "Wrong — despite the filename, actual password hashes live in /etc/shadow, not /etc/passwd.",
            "Stores firewall rules": "Wrong — firewall configuration is handled by tools like iptables/firewalld/ufw, unrelated to /etc/passwd.",
            "Stores a list of currently installed packages": "Wrong — package information is tracked by the package manager (e.g. dpkg, rpm databases), not /etc/passwd.",
        },
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "What does the `grep -r` flag do?",
        "options": [
            "Searches recursively through all files in a directory and its subdirectories",
            "Reverses the order of search results",
            "Only returns the count of matches, not the matching lines",
            "Performs a case-insensitive search",
        ],
        "correct_answer": "Searches recursively through all files in a directory and its subdirectories",
        "explanation_correct": "The -r (recursive) flag makes grep search through every file in the given directory tree, rather than requiring a single specific file.",
        "explanation_incorrect": {
            "Reverses the order of search results": "Wrong — grep doesn't have a result-reversal option tied to -r; -v inverts matches (shows non-matching lines), which is a different behavior entirely.",
            "Only returns the count of matches, not the matching lines": "Wrong — that's the role of the -c flag, not -r.",
            "Performs a case-insensitive search": "Wrong — that's the role of the -i flag, not -r.",
        },
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a firewall tool like ufw or firewalld on Linux?",
        "options": [
            "Controls which network traffic is allowed in or out of the system based on defined rules",
            "Automatically encrypts all network traffic",
            "Manages DNS resolution for the system",
            "Compresses network packets to improve transfer speed",
        ],
        "correct_answer": "Controls which network traffic is allowed in or out of the system based on defined rules",
        "explanation_correct": "Firewall tools like ufw and firewalld provide a simpler interface over the kernel's packet filtering, letting you define rules for which traffic is permitted or blocked.",
        "explanation_incorrect": {
            "Automatically encrypts all network traffic": "Wrong — encryption is a separate concern (e.g. TLS, VPNs), unrelated to a firewall's filtering role.",
            "Manages DNS resolution for the system": "Wrong — DNS resolution is handled by resolver configuration (e.g. /etc/resolv.conf) or services like systemd-resolved, not a firewall.",
            "Compresses network packets to improve transfer speed": "Wrong — packet compression isn't a firewall's role; firewalls filter traffic, they don't compress it.",
        },
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "mcq",
        "prompt": "What does the `df -h` command show?",
        "options": [
            "Disk space usage for mounted filesystems, in human-readable format",
            "A list of currently running processes",
            "The contents of the current directory",
            "The permissions of a specific file",
        ],
        "correct_answer": "Disk space usage for mounted filesystems, in human-readable format",
        "explanation_correct": "df -h reports how much space is used and available on each mounted filesystem, formatted in units like K, M, and G rather than raw byte counts.",
        "explanation_incorrect": {
            "A list of currently running processes": "Wrong — that's the role of commands like ps or top, unrelated to df.",
            "The contents of the current directory": "Wrong — that's the role of ls, unrelated to df.",
            "The permissions of a specific file": "Wrong — that's shown by ls -l or stat, unrelated to df, which reports filesystem-level usage.",
        },
    },

    # ---------------- FILL-IN-BLANK (8) ----------------

    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command displays or sets file permissions using symbolic or octal notation.",
        "options": None,
        "correct_answer": "chmod",
        "explanation_correct": "chmod changes a file's permission bits, accepting either symbolic (u+x) or octal (755) notation.",
        "explanation_incorrect": "The blank should be filled with the command used to change file permissions: chmod.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command changes the owner and/or group of a file or directory.",
        "options": None,
        "correct_answer": "chown",
        "explanation_correct": "chown changes a file's owning user and/or group.",
        "explanation_incorrect": "The blank should be filled with the command used to change ownership: chown.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "On most Linux distributions, system and application log files are conventionally stored under /var/____.",
        "options": None,
        "correct_answer": "log",
        "explanation_correct": "/var/log is the standard directory for persistent log files.",
        "explanation_incorrect": "The blank should be filled with the standard log directory name: log.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command manages systemd services, supporting actions like start, stop, enable, and status.",
        "options": None,
        "correct_answer": "systemctl",
        "explanation_correct": "systemctl is the primary command-line tool for controlling systemd units.",
        "explanation_incorrect": "The blank should be filled with the name of this systemd management command: systemctl.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command displays currently running processes in a continuously updating, interactive view.",
        "options": None,
        "correct_answer": "top",
        "explanation_correct": "top provides a real-time, auto-refreshing view of system processes and resource usage.",
        "explanation_incorrect": "The blank should be filled with the name of this live process-monitoring command: top.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command searches for text patterns within files, and supports a recursive flag (-r) to search entire directories.",
        "options": None,
        "correct_answer": "grep",
        "explanation_correct": "grep is the standard Linux tool for pattern searching within file contents.",
        "explanation_incorrect": "The blank should be filled with the name of this text-search command: grep.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The /etc/____ file stores basic user account information, including username, UID, home directory, and default shell.",
        "options": None,
        "correct_answer": "passwd",
        "explanation_correct": "/etc/passwd holds core account metadata for every user on the system.",
        "explanation_incorrect": "The blank should be filled with the name of this account information file: passwd.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The Linux kernel parameter tuning tool ____ allows you to view and modify kernel parameters at runtime, e.g. via -w net.ipv4.ip_forward=1.",
        "options": None,
        "correct_answer": "sysctl",
        "explanation_correct": "sysctl reads and writes kernel runtime parameters exposed under /proc/sys.",
        "explanation_incorrect": "The blank should be filled with the name of this kernel parameter tool: sysctl.",
    },

    # ---------------- DRAG-AND-DROP (7) ----------------

    {
        "topic": "Linux", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for checking, enabling, and starting a systemd service.",
        "options": ["Run `systemctl start nginx` to start it immediately", "Run `systemctl status nginx` to check current status", "Run `systemctl enable nginx` to enable it at boot"],
        "correct_answer": '["Run `systemctl status nginx` to check current status", "Run `systemctl enable nginx` to enable it at boot", "Run `systemctl start nginx` to start it immediately"]',
        "explanation_correct": "Correct — checking the current state first is a sensible starting point, and enabling (for future boots) and starting (for right now) are two distinct actions typically done together, in this order.",
        "explanation_incorrect": "Checking status first establishes a baseline, and while enable/start order is somewhat flexible, this reflects a common sequence — confirm state, ensure it starts at boot, then start it now.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for locating an error in a log file and viewing its surrounding context.",
        "options": ["Note the line number of interest", "Use `sed -n '95,105p' app.log` to view the surrounding lines", "Use `grep -n \"ERROR\" app.log` to find matching lines with line numbers"],
        "correct_answer": '["Use `grep -n \\"ERROR\\" app.log` to find matching lines with line numbers", "Note the line number of interest", "Use `sed -n \'95,105p\' app.log` to view the surrounding lines"]',
        "explanation_correct": "Correct — you need to find the matching line and its number before you can note it, and you need the noted line number before you can target that range with sed.",
        "explanation_incorrect": "The grep search must run first to reveal the relevant line number, which must be noted before it can be used to target a range with sed.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for adding a new user and setting up sudo access.",
        "options": ["Run `usermod -aG sudo deploy` to add the user to the sudo group", "Run `useradd -m deploy` to create the user with a home directory", "Run `passwd deploy` to set the user's password"],
        "correct_answer": '["Run `useradd -m deploy` to create the user with a home directory", "Run `passwd deploy` to set the user\'s password", "Run `usermod -aG sudo deploy` to add the user to the sudo group"]',
        "explanation_correct": "Correct — the user account must exist before a password can be set for it or before it can be added to a group.",
        "explanation_incorrect": "The user account must be created before a password can be set for it, and the account must exist before it can be added to any group.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for installing a package and ensuring its service runs reliably.",
        "options": ["Run `systemctl enable nginx` to ensure it starts on boot", "Run `apt install nginx` to install the package", "Run `systemctl start nginx` to start the service"],
        "correct_answer": '["Run `apt install nginx` to install the package", "Run `systemctl start nginx` to start the service", "Run `systemctl enable nginx` to ensure it starts on boot"]',
        "explanation_correct": "Correct — the package must be installed before its service can be started, and starting/enabling naturally follow once the software actually exists on the system.",
        "explanation_incorrect": "The package must be installed before its systemd service exists to be started or enabled, so installation always comes first.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing which directories are consuming the most disk space.",
        "options": ["Identify a filesystem that is nearly full", "Run `df -h` to see overall filesystem usage", "Run `du -sh /path/*` within that filesystem to find which directories are using the most space"],
        "correct_answer": '["Run `df -h` to see overall filesystem usage", "Identify a filesystem that is nearly full", "Run `du -sh /path/*` within that filesystem to find which directories are using the most space"]',
        "explanation_correct": "Correct — the overall picture from df must come first before a specific problem filesystem can be identified, and narrowing down with du only makes sense once that target is known.",
        "explanation_incorrect": "The high-level overview (df) must come before identifying a specific problem area, and the more detailed investigation (du) should be scoped to that identified area, not run blindly first.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for identifying and terminating a runaway process.",
        "options": ["Run `kill -9 <PID>` to forcefully terminate it", "Run `top` or `ps aux` to identify the process and its PID", "Note the PID of the problematic process"],
        "correct_answer": '["Run `top` or `ps aux` to identify the process and its PID", "Note the PID of the problematic process", "Run `kill -9 <PID>` to forcefully terminate it"]',
        "explanation_correct": "Correct — the process must be identified before its PID can be noted, and that PID is needed before kill can target the correct process.",
        "explanation_incorrect": "The process must first be identified (and its PID noted) before kill can be given the correct target to terminate.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting correct ownership and permissions on a file, then confirming the result.",
        "options": ["Verify with `ls -l file.txt`", "Run `chown appuser:appgroup file.txt` to set the correct owner and group", "Run `chmod 640 file.txt` to set appropriate permissions"],
        "correct_answer": '["Run `chown appuser:appgroup file.txt` to set the correct owner and group", "Run `chmod 640 file.txt` to set appropriate permissions", "Verify with `ls -l file.txt`"]',
        "explanation_correct": "Correct — setting ownership and permissions are independent changes that can happen in either order, but verifying the final result naturally comes last, after both changes are applied.",
        "explanation_incorrect": "Both ownership and permission changes should be applied before verification, since checking the result only makes sense once the intended changes have actually been made.",
    },

    # ---------------- DROPDOWN-ORDER (7) ----------------

    {
        "topic": "Linux", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for reviewing and following logs for a specific service.",
        "options": ["Add `-f` to follow new log entries in real time", "Run `journalctl -u sshd` to view logs for the sshd service", "Add `-n 50` to limit output to the last 50 lines"],
        "correct_answer": '["Run `journalctl -u sshd` to view logs for the sshd service", "Add `-n 50` to limit output to the last 50 lines", "Add `-f` to follow new log entries in real time"]',
        "explanation_correct": "Correct — the base command targeting the service comes first, with -n limiting historical output and -f (typically added once you want to switch to live tailing) building on that base query.",
        "explanation_incorrect": "The base journalctl command targeting the service is the starting point, with additional flags like -n and -f layered on as refinements to that base query.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up a basic ufw firewall rule.",
        "options": ["Run `ufw status` to confirm the rule is active", "Run `ufw allow 22/tcp` to permit SSH traffic", "Run `ufw enable` to activate the firewall"],
        "correct_answer": '["Run `ufw allow 22/tcp` to permit SSH traffic", "Run `ufw enable` to activate the firewall", "Run `ufw status` to confirm the rule is active"]',
        "explanation_correct": "Correct — allowing SSH before enabling the firewall avoids locking yourself out, and checking status afterward confirms the final active configuration.",
        "explanation_incorrect": "Allowing SSH access before enabling the firewall is important to avoid losing remote access, and checking status is the natural final confirmation step.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for finding and cleaning up large files.",
        "options": ["Remove or archive files that are no longer needed", "Run `find / -type f -size +100M` to locate files larger than 100MB", "Review the resulting file list"],
        "correct_answer": '["Run `find / -type f -size +100M` to locate files larger than 100MB", "Review the resulting file list", "Remove or archive files that are no longer needed"]',
        "explanation_correct": "Correct — the search must run before there's a list to review, and cleanup decisions should follow that review rather than precede it.",
        "explanation_incorrect": "The find command must run first to produce a list of candidate files, and any cleanup action should follow review of that list, not come before it.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a basic grep/awk text-processing pipeline that saves results to a file.",
        "options": ["Redirect the final output to a new file with `>`", "Use `grep \"ERROR\" app.log` to filter matching lines", "Pipe the output to `awk '{print $1, $3}'` to extract specific columns"],
        "correct_answer": '["Use `grep \\"ERROR\\" app.log` to filter matching lines", "Pipe the output to `awk \'{print $1, $3}\'` to extract specific columns", "Redirect the final output to a new file with `>`"]',
        "explanation_correct": "Correct — filtering must happen before columns can be extracted from the filtered lines, and redirection to a file is the final step capturing the fully processed output.",
        "explanation_incorrect": "The filtering step must come before column extraction can operate on the filtered results, and output redirection is the final step, capturing everything that came before it.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for formatting and mounting a new disk.",
        "options": ["Run `mount /dev/sdX1 /mnt/data` to mount it", "Run `lsblk` to identify the new disk device", "Run `mkfs.ext4 /dev/sdX1` to format the partition"],
        "correct_answer": '["Run `lsblk` to identify the new disk device", "Run `mkfs.ext4 /dev/sdX1` to format the partition", "Run `mount /dev/sdX1 /mnt/data` to mount it"]',
        "explanation_correct": "Correct — the disk device must be identified before it can be formatted, and formatting must happen before the filesystem can be mounted.",
        "explanation_incorrect": "The device must be identified before any action can target it, and a filesystem must exist on the partition (via formatting) before it can be mounted.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for scheduling a recurring task with cron.",
        "options": ["Save and exit; cron picks up the new schedule automatically", "Run `crontab -e` to open the current user's crontab for editing", "Add a line specifying the schedule and command to run"],
        "correct_answer": '["Run `crontab -e` to open the current user\'s crontab for editing", "Add a line specifying the schedule and command to run", "Save and exit; cron picks up the new schedule automatically"]',
        "explanation_correct": "Correct — the crontab must be opened for editing before a new line can be added to it, and saving/exiting is the final step that actually applies the change.",
        "explanation_incorrect": "The crontab file must be opened before a new schedule line can be added, and saving is the final step that commits the change for cron to pick up.",
    },
    {
        "topic": "Linux", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for tuning a kernel parameter temporarily, then persisting it across reboots.",
        "options": ["Run `sysctl -p` to reload settings from the config file, confirming persistence", "Run `sysctl -w net.ipv4.ip_forward=1` to change the setting immediately", "Add `net.ipv4.ip_forward = 1` to /etc/sysctl.conf"],
        "correct_answer": '["Run `sysctl -w net.ipv4.ip_forward=1` to change the setting immediately", "Add `net.ipv4.ip_forward = 1` to /etc/sysctl.conf", "Run `sysctl -p` to reload settings from the config file, confirming persistence"]',
        "explanation_correct": "Correct — applying the immediate runtime change comes first, adding it to the persistent config file comes next, and reloading from that file confirms it will survive future reboots.",
        "explanation_incorrect": "The immediate runtime change is applied first, the persistent config entry is added next, and reloading from the config file is the final step that verifies the persisted setting.",
    },
]
