"""
Networking - Easy batch, 50 questions total.
Distribution: even split -- 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.
(Regenerated with a lighter coding weighting, matching the Terraform/AWS pattern.)

Focused on DevOps-relevant networking fundamentals (DNS, TCP/UDP, subnetting, gateways,
ports, NAT, firewalls) plus practical Linux-native diagnostic commands. Deliberately
avoids vendor-specific tooling (e.g. Cisco IOS) -- all "coding" questions use standard
Linux command-line tools.

Schema matches terraform_easy_questions.py -- see that file's header for full field notes.
"""

NETWORKING_EASY_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display all IP addresses assigned to network interfaces on the system.",
        "correct_answer": "ip addr show",
        "explanation_correct": "Correct -- `ip addr show` (or `ip a`) lists every network interface along with its assigned IP addresses.",
        "explanation_incorrect": "A correct solution must show IP addresses for all interfaces, typically using ip addr show (the modern replacement for ifconfig).",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display the system's routing table, including the default gateway.",
        "correct_answer": "ip route show",
        "explanation_correct": "Correct -- `ip route show` (or `ip r`) lists the kernel's current routing table, including the default route.",
        "explanation_incorrect": "A correct solution must display the routing table, typically using ip route show.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to test connectivity to a host named example.com by sending exactly 4 ICMP echo requests.",
        "correct_answer": "ping -c 4 example.com",
        "explanation_correct": "Correct -- the -c flag limits ping to sending exactly 4 echo requests before stopping automatically.",
        "explanation_incorrect": "A correct solution must send exactly 4 pings to example.com, typically using ping -c 4.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to resolve the IP address of the domain example.com using dig.",
        "correct_answer": "dig example.com",
        "explanation_correct": "Correct -- `dig` queries DNS and returns the resolved records (including the A record IP address) for the given domain.",
        "explanation_incorrect": "A correct solution must resolve example.com using dig specifically.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display the hostname of the current system.",
        "correct_answer": "hostname",
        "explanation_correct": "Correct -- running `hostname` with no arguments prints the system's current hostname.",
        "explanation_incorrect": "A correct solution must display the current system's hostname, typically using the hostname command.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display all active network connections and listening ports.",
        "correct_answer": "ss -tulnp",
        "explanation_correct": "Correct -- combining -t (TCP), -u (UDP), -l (listening), -n (numeric), and -p (process) shows all listening/active sockets with their owning processes.",
        "explanation_incorrect": "A correct solution must display active connections and listening ports, typically using ss with appropriate flags (or the legacy netstat).",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to assign the IP address 192.168.1.50 with a /24 subnet mask to interface eth0.",
        "correct_answer": "ip addr add 192.168.1.50/24 dev eth0",
        "explanation_correct": "Correct -- `ip addr add` assigns the given address (with CIDR prefix) to the specified device.",
        "explanation_incorrect": "A correct solution must assign 192.168.1.50/24 to eth0 specifically, typically using ip addr add.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to add a default route via gateway 192.168.1.1.",
        "correct_answer": "ip route add default via 192.168.1.1",
        "explanation_correct": "Correct -- `ip route add default via <gateway>` sets the specified address as the default gateway for outbound traffic.",
        "explanation_incorrect": "A correct solution must add a default route pointing to 192.168.1.1 specifically, typically using ip route add default via.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to test whether TCP port 443 is open on host example.com, using nc (netcat).",
        "correct_answer": "nc -zv example.com 443",
        "explanation_correct": "Correct -- the -z flag tests the connection without sending data, and -v provides verbose output showing whether the port is open.",
        "explanation_incorrect": "A correct solution must test connectivity to port 443 on example.com specifically, typically using nc -zv.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "coding",
        "prompt": "Write the command to display the contents of /etc/resolv.conf, showing the system's configured DNS servers.",
        "correct_answer": "cat /etc/resolv.conf",
        "explanation_correct": "Correct -- `cat` prints the file's contents, which include the configured nameserver entries.",
        "explanation_incorrect": "A correct solution must display the contents of /etc/resolv.conf, typically using cat.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What layer of the OSI model does IP (Internet Protocol) operate at?",
        "options": ["Network layer (Layer 3)", "Transport layer (Layer 4)", "Data Link layer (Layer 2)", "Application layer (Layer 7)"],
        "correct_answer": "Network layer (Layer 3)",
        "explanation_correct": "IP handles logical addressing and routing between networks, which is the defining responsibility of the Network layer (Layer 3).",
        "explanation_incorrect": {
            "Transport layer (Layer 4)": "Wrong -- that's where protocols like TCP and UDP operate, handling end-to-end delivery, not IP itself.",
            "Data Link layer (Layer 2)": "Wrong -- that's where protocols like Ethernet operate, handling local-network framing, not IP.",
            "Application layer (Layer 7)": "Wrong -- that's where protocols like HTTP and DNS operate, far above IP's role in routing packets.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of DNS?",
        "options": [
            "Translates human-readable domain names into IP addresses",
            "Encrypts network traffic between hosts",
            "Automatically assigns IP addresses to devices",
            "Routes packets between separate networks",
        ],
        "correct_answer": "Translates human-readable domain names into IP addresses",
        "explanation_correct": "DNS (Domain Name System) resolves domain names like example.com into the numeric IP addresses computers use to actually connect.",
        "explanation_incorrect": {
            "Encrypts network traffic between hosts": "Wrong -- encryption is handled by protocols like TLS, unrelated to DNS's name resolution role.",
            "Automatically assigns IP addresses to devices": "Wrong -- that's the role of DHCP, not DNS.",
            "Routes packets between separate networks": "Wrong -- that's the role of routers and routing protocols, not DNS.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the default port used by HTTPS?",
        "options": ["443", "80", "22", "21"],
        "correct_answer": "443",
        "explanation_correct": "HTTPS (HTTP over TLS) conventionally uses TCP port 443.",
        "explanation_incorrect": {
            "80": "Wrong -- port 80 is the default for plain, unencrypted HTTP, not HTTPS.",
            "22": "Wrong -- port 22 is the default for SSH, unrelated to HTTPS.",
            "21": "Wrong -- port 21 is the default for FTP control connections, unrelated to HTTPS.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of DHCP?",
        "options": [
            "Automatically assigns IP addresses and network configuration to devices on a network",
            "Translates domain names into IP addresses",
            "Encrypts network traffic automatically",
            "Filters network traffic based on defined rules",
        ],
        "correct_answer": "Automatically assigns IP addresses and network configuration to devices on a network",
        "explanation_correct": "DHCP (Dynamic Host Configuration Protocol) automatically hands out IP addresses, subnet masks, gateways, and DNS servers to devices as they join a network.",
        "explanation_incorrect": {
            "Translates domain names into IP addresses": "Wrong -- that's the role of DNS, not DHCP.",
            "Encrypts network traffic automatically": "Wrong -- DHCP is about configuration assignment, not encryption.",
            "Filters network traffic based on defined rules": "Wrong -- that's the role of a firewall, unrelated to DHCP's configuration-assignment purpose.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the key difference between TCP and UDP?",
        "options": [
            "TCP is connection-oriented and reliable; UDP is connectionless and doesn't guarantee delivery",
            "TCP is connectionless; UDP is connection-oriented",
            "They are functionally identical in every respect",
            "UDP is always slower than TCP in every scenario",
        ],
        "correct_answer": "TCP is connection-oriented and reliable; UDP is connectionless and doesn't guarantee delivery",
        "explanation_correct": "TCP establishes a connection and guarantees ordered, reliable delivery (with retransmission), while UDP simply sends packets without those guarantees, trading reliability for lower overhead.",
        "explanation_incorrect": {
            "TCP is connectionless; UDP is connection-oriented": "Wrong -- this is backwards; TCP is the connection-oriented one, and UDP is connectionless.",
            "They are functionally identical in every respect": "Wrong -- their reliability guarantees and connection models differ significantly.",
            "UDP is always slower than TCP in every scenario": "Wrong -- UDP's lack of overhead (no handshake, no retransmission) often makes it faster, not slower, which is why it's used for latency-sensitive traffic like streaming or DNS.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What does a subnet mask (e.g. 255.255.255.0) define?",
        "options": [
            "Which portion of an IP address represents the network versus the host",
            "The maximum number of devices allowed to ever exist on any network",
            "The default gateway's address",
            "The address of the DNS server",
        ],
        "correct_answer": "Which portion of an IP address represents the network versus the host",
        "explanation_correct": "A subnet mask divides an IP address into a network portion and a host portion, determining which addresses are considered part of the same local network.",
        "explanation_incorrect": {
            "The maximum number of devices allowed to ever exist on any network": "Wrong -- while the mask does imply a maximum host count for that specific subnet, it's not a global device limit, and that's a side effect rather than its core purpose.",
            "The default gateway's address": "Wrong -- the gateway is a separate, explicitly configured address, not something the subnet mask itself specifies.",
            "The address of the DNS server": "Wrong -- DNS server addresses are configured separately (e.g. in /etc/resolv.conf), unrelated to the subnet mask.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a default gateway?",
        "options": [
            "The device (typically a router) that traffic is sent to when the destination is outside the local network",
            "A backup DNS server used when the primary fails",
            "A firewall rule blocking unwanted traffic",
            "A load balancer distributing traffic across servers",
        ],
        "correct_answer": "The device (typically a router) that traffic is sent to when the destination is outside the local network",
        "explanation_correct": "When a host needs to reach an address outside its own subnet, it forwards that traffic to the default gateway, which routes it onward.",
        "explanation_incorrect": {
            "A backup DNS server used when the primary fails": "Wrong -- DNS server configuration is separate from the gateway concept entirely.",
            "A firewall rule blocking unwanted traffic": "Wrong -- a gateway routes traffic onward; it isn't itself a firewall rule.",
            "A load balancer distributing traffic across servers": "Wrong -- load balancing is a distinct function from the basic routing role of a default gateway.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What does the `ping` command test?",
        "options": [
            "Basic network reachability and round-trip latency to a host, using ICMP echo requests",
            "DNS resolution speed specifically",
            "HTTP response time for a web server",
            "Local disk I/O speed",
        ],
        "correct_answer": "Basic network reachability and round-trip latency to a host, using ICMP echo requests",
        "explanation_correct": "ping sends ICMP echo requests to a target and measures whether (and how quickly) it responds, providing a basic reachability/latency check.",
        "explanation_incorrect": {
            "DNS resolution speed specifically": "Wrong -- while ping does need to resolve a hostname if given one, its core purpose is reachability testing via ICMP, not DNS timing (dig is better suited for that).",
            "HTTP response time for a web server": "Wrong -- that would require an actual HTTP request (e.g. via curl), which ping doesn't perform.",
            "Local disk I/O speed": "Wrong -- disk performance is unrelated to ping, which is purely a network reachability tool.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of a firewall in networking?",
        "options": [
            "Filters network traffic based on defined rules, allowing or blocking specific traffic",
            "Encrypts all network traffic automatically",
            "Assigns IP addresses to devices on a network",
            "Resolves domain names into IP addresses",
        ],
        "correct_answer": "Filters network traffic based on defined rules, allowing or blocking specific traffic",
        "explanation_correct": "A firewall inspects traffic against a defined rule set and permits or denies it accordingly, controlling what's allowed in or out of a system or network.",
        "explanation_incorrect": {
            "Encrypts all network traffic automatically": "Wrong -- encryption is a separate concern (e.g. TLS), unrelated to a firewall's filtering role.",
            "Assigns IP addresses to devices on a network": "Wrong -- that's the role of DHCP, not a firewall.",
            "Resolves domain names into IP addresses": "Wrong -- that's the role of DNS, not a firewall.",
        },
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "mcq",
        "prompt": "What does NAT (Network Address Translation) do?",
        "options": [
            "Translates private IP addresses to a public IP address (and vice versa) for internet communication",
            "Encrypts network traffic between hosts",
            "Assigns dynamic IP addresses to new devices",
            "Filters malicious traffic based on signatures",
        ],
        "correct_answer": "Translates private IP addresses to a public IP address (and vice versa) for internet communication",
        "explanation_correct": "NAT lets multiple devices on a private network share a single public IP address, translating addresses as traffic crosses between the private and public network.",
        "explanation_incorrect": {
            "Encrypts network traffic between hosts": "Wrong -- NAT is about address translation, not encryption.",
            "Assigns dynamic IP addresses to new devices": "Wrong -- that's the role of DHCP, a separate mechanism from NAT.",
            "Filters malicious traffic based on signatures": "Wrong -- that's closer to the role of an intrusion detection/prevention system, unrelated to NAT's address-translation purpose.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command displays and configures IP addresses, routes, and network interfaces on modern Linux systems (replacing the older ifconfig).",
        "options": None,
        "correct_answer": "ip",
        "explanation_correct": "The ip command (from iproute2) is the modern tool for managing Linux networking configuration.",
        "explanation_incorrect": "The blank should be filled with the name of this modern networking command: ip.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command tests basic network reachability to a host using ICMP echo requests.",
        "options": None,
        "correct_answer": "ping",
        "explanation_correct": "ping sends ICMP echo requests and reports whether and how quickly the target responds.",
        "explanation_incorrect": "The blank should be filled with the name of this reachability-testing command: ping.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "____ translates human-readable domain names into IP addresses.",
        "options": None,
        "correct_answer": "DNS",
        "explanation_correct": "DNS (Domain Name System) resolves domain names into the IP addresses used for actual network connections.",
        "explanation_incorrect": "The blank should be filled with the name of this name-resolution system: DNS.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The default port used by unencrypted HTTP is ____.",
        "options": None,
        "correct_answer": "80",
        "explanation_correct": "Port 80 is the conventional default for plain HTTP traffic.",
        "explanation_incorrect": "The blank should be filled with the default HTTP port number: 80.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ protocol automatically assigns IP addresses and network configuration to devices on a network.",
        "options": None,
        "correct_answer": "DHCP",
        "explanation_correct": "DHCP hands out IP addresses and related configuration to devices as they connect to a network.",
        "explanation_incorrect": "The blank should be filled with the name of this automatic configuration protocol: DHCP.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A ____ mask defines which portion of an IP address represents the network versus the host.",
        "options": None,
        "correct_answer": "subnet",
        "explanation_correct": "The subnet mask divides an IP address into its network and host portions.",
        "explanation_incorrect": "The blank should be filled with the term for this network/host-dividing value: subnet.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command displays active network connections and listening ports on modern Linux systems, largely replacing the older netstat.",
        "options": None,
        "correct_answer": "ss",
        "explanation_correct": "ss (socket statistics) is the modern tool for inspecting sockets and listening ports on Linux.",
        "explanation_incorrect": "The blank should be filled with the name of this modern socket-inspection command: ss.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The /etc/____ file lists the DNS servers a Linux system uses for name resolution.",
        "options": None,
        "correct_answer": "resolv.conf",
        "explanation_correct": "/etc/resolv.conf contains the nameserver entries used for DNS lookups on a Linux system.",
        "explanation_incorrect": "The blank should be filled with the name of this DNS configuration file: resolv.conf.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A ____ is a network security device or software that filters traffic based on defined rules.",
        "options": None,
        "correct_answer": "firewall",
        "explanation_correct": "A firewall permits or denies traffic based on configured rules, controlling what's allowed in or out.",
        "explanation_incorrect": "The blank should be filled with the term for this traffic-filtering security tool: firewall.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "____ (Network Address Translation) allows multiple devices on a private network to share a single public IP address.",
        "options": None,
        "correct_answer": "NAT",
        "explanation_correct": "NAT translates between private and public IP addresses, letting many devices share one public address for internet access.",
        "explanation_incorrect": "The blank should be filled with the acronym for this address-translation technique: NAT.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing why a website is unreachable.",
        "options": ["Run `curl -I https://example.com` to check if the web server responds", "Run `ping example.com` to check basic reachability", "Run `dig example.com` to confirm DNS resolution is working"],
        "correct_answer": '["Run `ping example.com` to check basic reachability", "Run `dig example.com` to confirm DNS resolution is working", "Run `curl -I https://example.com` to check if the web server responds"]',
        "explanation_correct": "Correct -- checking basic reachability first is a sensible starting point, confirming DNS resolution comes next, and testing the actual web server response is the most specific, final check.",
        "explanation_incorrect": "Starting with basic reachability, then confirming name resolution, then testing the actual application-layer response moves from broad to specific, isolating where the failure occurs.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for manually configuring a network interface.",
        "options": ["Run `ip route add default via 192.168.1.1` to set the default gateway", "Run `ip link set eth0 up` to bring the interface up", "Run `ip addr add 192.168.1.50/24 dev eth0` to assign an address"],
        "correct_answer": '["Run `ip link set eth0 up` to bring the interface up", "Run `ip addr add 192.168.1.50/24 dev eth0` to assign an address", "Run `ip route add default via 192.168.1.1` to set the default gateway"]',
        "explanation_correct": "Correct -- the interface should be brought up before an address is assigned to it, and a default route pointing to a gateway on that address's subnet is set last.",
        "explanation_incorrect": "Bringing the interface up is the conventional first step, assigning it an address follows, and configuring the default route (which depends on being reachable via that address) comes last.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for checking port availability before starting a new service.",
        "options": ["Start the new service, which will bind to that port", "Run `ss -tlnp` to see currently listening ports", "Confirm the desired port is not already in use"],
        "correct_answer": '["Run `ss -tlnp` to see currently listening ports", "Confirm the desired port is not already in use", "Start the new service, which will bind to that port"]',
        "explanation_correct": "Correct -- the current listening ports must be checked before you can confirm availability, and starting the service only makes sense once you've confirmed the port is free.",
        "explanation_incorrect": "Checking current listeners must happen before confirming the port is free, and starting the service should come only after confirming there's no conflict.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for basic bottom-up connectivity troubleshooting on a host.",
        "options": ["Check routing with `ip route show`", "Check physical/interface status with `ip link show eth0`", "Check IP configuration with `ip addr show eth0`"],
        "correct_answer": '["Check physical/interface status with `ip link show eth0`", "Check IP configuration with `ip addr show eth0`", "Check routing with `ip route show`"]',
        "explanation_correct": "Correct -- this follows a logical bottom-up order: confirm the link itself is up before checking whether it has an address, and confirm addressing before checking routing built on top of it.",
        "explanation_incorrect": "A sensible troubleshooting order checks the most fundamental layer (link status) first, then addressing, then routing -- each layer depends on the one below it working correctly.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for checking DNS server configuration and testing resolution.",
        "options": ["Compare the result to expectations", "Run `cat /etc/resolv.conf` to see configured DNS servers", "Run `dig example.com` to test resolution against those servers"],
        "correct_answer": '["Run `cat /etc/resolv.conf` to see configured DNS servers", "Run `dig example.com` to test resolution against those servers", "Compare the result to expectations"]',
        "explanation_correct": "Correct -- knowing which servers are configured comes first, testing resolution against them comes next, and comparing the result to expectations is the final analysis step.",
        "explanation_incorrect": "Checking the configured servers provides context before testing resolution, and comparing results to expectations naturally comes after the test has actually run.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for testing whether a remote port is reachable and diagnosing a firewall block.",
        "options": ["Determine if a firewall is blocking the port based on the result", "Run `nc -zv example.com 443` to test the port", "Observe whether the connection succeeds or times out"],
        "correct_answer": '["Run `nc -zv example.com 443` to test the port", "Observe whether the connection succeeds or times out", "Determine if a firewall is blocking the port based on the result"]',
        "explanation_correct": "Correct -- the test must run before there's a result to observe, and drawing a conclusion about a firewall follows from observing that result.",
        "explanation_incorrect": "The connection test must be run before its outcome can be observed, and diagnosing the likely cause (like a firewall block) should follow from that observed outcome.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up NAT so a private network can reach the internet.",
        "options": ["Private network devices can now reach the internet through the NAT gateway", "Enable IP forwarding with `sysctl -w net.ipv4.ip_forward=1`", "Add an iptables MASQUERADE rule for outbound traffic on the external interface"],
        "correct_answer": '["Enable IP forwarding with `sysctl -w net.ipv4.ip_forward=1`", "Add an iptables MASQUERADE rule for outbound traffic on the external interface", "Private network devices can now reach the internet through the NAT gateway"]',
        "explanation_correct": "Correct -- IP forwarding must be enabled before the gateway will route traffic between interfaces at all, and the MASQUERADE rule (which enables the actual address translation) must be in place before private devices can successfully reach the internet.",
        "explanation_incorrect": "IP forwarding must be enabled before any routing between interfaces happens, and the NAT rule must be configured before private devices' traffic can be correctly translated and reach the internet.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a basic allow-list firewall policy for a single port.",
        "options": ["Verify the rules with a listing command", "Add a rule allowing traffic on the desired port", "Add a default deny rule for all other inbound traffic"],
        "correct_answer": '["Add a rule allowing traffic on the desired port", "Add a default deny rule for all other inbound traffic", "Verify the rules with a listing command"]',
        "explanation_correct": "Correct -- the allow rule for the needed port should be added before a default deny rule closes off everything else, and verifying the final rule set is the last step.",
        "explanation_incorrect": "The specific allow rule should be added before a broad deny rule closes off other access (otherwise the needed traffic could be blocked too), and verification naturally comes after the rules are in place.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order describing a request passing through a load balancer to a backend server.",
        "options": ["Backend server processes the request and sends the response back through the load balancer", "Client sends a request to the load balancer's public address", "Load balancer forwards the request to a healthy backend server"],
        "correct_answer": '["Client sends a request to the load balancer\'s public address", "Load balancer forwards the request to a healthy backend server", "Backend server processes the request and sends the response back through the load balancer"]',
        "explanation_correct": "Correct -- the request must reach the load balancer before it can be forwarded, and the backend can only respond after actually receiving the forwarded request.",
        "explanation_incorrect": "The client's request must arrive at the load balancer before it can be routed anywhere, and the backend server can only process and respond after receiving that forwarded request.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for downloading and using a remote file.",
        "options": ["Extract or use the downloaded file", "Run `wget https://example.com/file.tar.gz` to download the file", "Confirm the file was downloaded successfully"],
        "correct_answer": '["Run `wget https://example.com/file.tar.gz` to download the file", "Confirm the file was downloaded successfully", "Extract or use the downloaded file"]',
        "explanation_correct": "Correct -- the file must be downloaded before its success can be confirmed, and it must be confirmed present before it can be extracted or used.",
        "explanation_incorrect": "The download must happen before there's anything to confirm, and confirmation should happen before you attempt to use a file that might not have downloaded correctly.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order describing how data moves down through the network stack when a request is sent.",
        "options": ["Network layer adds IP addressing to route the packet", "Application layer generates data (e.g. an HTTP request)", "Transport layer breaks data into segments (e.g. TCP)"],
        "correct_answer": '["Application layer generates data (e.g. an HTTP request)", "Transport layer breaks data into segments (e.g. TCP)", "Network layer adds IP addressing to route the packet"]',
        "explanation_correct": "Correct -- data originates at the application layer, is segmented by the transport layer, and is then addressed for routing by the network layer, following the OSI model's top-down encapsulation order.",
        "explanation_incorrect": "Data is generated at the application layer first, then handed down to the transport layer for segmentation, then to the network layer for addressing -- each layer wraps the data from the layer above it.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order describing a basic curl GET request.",
        "options": ["curl displays the response body in the terminal", "Run `curl https://example.com` to send a GET request", "The server processes the request and returns a response"],
        "correct_answer": '["Run `curl https://example.com` to send a GET request", "The server processes the request and returns a response", "curl displays the response body in the terminal"]',
        "explanation_correct": "Correct -- the request must be sent before the server can respond, and curl can only display the response after it has actually been received.",
        "explanation_incorrect": "The request must be sent before a response can be generated, and displaying that response can only happen after it's been received.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for checking and using the ARP table.",
        "options": ["Use that MAC address for further network diagnostics", "Run `arp -a` (or `ip neigh`) to view the current ARP table", "Identify the MAC address associated with a given IP"],
        "correct_answer": '["Run `arp -a` (or `ip neigh`) to view the current ARP table", "Identify the MAC address associated with a given IP", "Use that MAC address for further network diagnostics"]',
        "explanation_correct": "Correct -- the ARP table must be viewed before a specific MAC address can be identified within it, and that identified address must be known before it can be used further.",
        "explanation_incorrect": "The ARP table must be displayed before a specific entry can be identified, and the MAC address must be identified before it can be used in any further diagnostics.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct conceptual order describing a DHCP lease renewal.",
        "options": ["The DHCP server responds with a new (or renewed) IP address assignment", "The client releases its current IP lease", "The client broadcasts a new DHCP request"],
        "correct_answer": '["The client releases its current IP lease", "The client broadcasts a new DHCP request", "The DHCP server responds with a new (or renewed) IP address assignment"]',
        "explanation_correct": "Correct -- the old lease is given up before a new request goes out, and the server can only respond after receiving that new request.",
        "explanation_incorrect": "The client must release or expire its current lease before requesting a new one, and the server's response naturally follows the client's request.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for checking and adjusting an interface's MTU.",
        "options": ["Run `ip link set eth0 mtu 1400` to adjust it", "Run `ip link show eth0` to check the current MTU", "Determine if a different MTU is needed for the network"],
        "correct_answer": '["Run `ip link show eth0` to check the current MTU", "Determine if a different MTU is needed for the network", "Run `ip link set eth0 mtu 1400` to adjust it"]',
        "explanation_correct": "Correct -- the current MTU must be checked before deciding whether a change is needed, and the adjustment itself is the final step once that need is confirmed.",
        "explanation_incorrect": "Checking the current value comes before deciding whether a change is necessary, and making the actual adjustment is the final step once that decision has been made.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct conceptual order for a simplified HTTPS/TLS handshake.",
        "options": ["Client and server establish an encrypted session", "Client sends a ClientHello to initiate the TLS handshake", "Server responds with its certificate"],
        "correct_answer": '["Client sends a ClientHello to initiate the TLS handshake", "Server responds with its certificate", "Client and server establish an encrypted session"]',
        "explanation_correct": "Correct -- the handshake must be initiated before the server can respond with its certificate, and the encrypted session is only established once that exchange has completed.",
        "explanation_incorrect": "The handshake must begin before the server can present its certificate, and the encrypted session is established only after that certificate exchange has taken place.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for troubleshooting slow DNS resolution.",
        "options": ["Test resolution against a different DNS server to compare speed", "Run `dig example.com` and note the query time", "Check /etc/resolv.conf to see which DNS servers are configured"],
        "correct_answer": '["Run `dig example.com` and note the query time", "Check /etc/resolv.conf to see which DNS servers are configured", "Test resolution against a different DNS server to compare speed"]',
        "explanation_correct": "Correct -- observing the slow query time comes first, checking which server is being used provides context, and testing an alternate server is the final comparative step.",
        "explanation_incorrect": "Noting the slow query time is the starting observation, checking the configured server provides context for that result, and comparing against an alternate server is a reasonable final diagnostic step.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a basic TCP three-way handshake.",
        "options": ["Client sends an ACK, completing the handshake", "Client sends a SYN packet to initiate a connection", "Server responds with a SYN-ACK"],
        "correct_answer": '["Client sends a SYN packet to initiate a connection", "Server responds with a SYN-ACK", "Client sends an ACK, completing the handshake"]',
        "explanation_correct": "Correct -- the client's SYN must be sent first, the server's SYN-ACK responds to it, and the client's final ACK completes the three-way handshake.",
        "explanation_incorrect": "The handshake starts with the client's SYN, the server replies with SYN-ACK, and the client's ACK is the final step that establishes the connection.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct conceptual order describing how traceroute maps a network path.",
        "options": ["The client records each router's response to map out the path", "Client sends packets with increasing TTL values", "Each intermediate router decrements the TTL and returns an error once it hits zero"],
        "correct_answer": '["Client sends packets with increasing TTL values", "Each intermediate router decrements the TTL and returns an error once it hits zero", "The client records each router\'s response to map out the path"]',
        "explanation_correct": "Correct -- the packets with increasing TTL must be sent before routers can respond to them, and the client can only record responses after routers have actually sent them back.",
        "explanation_incorrect": "The TTL-incrementing packets must be sent before any router can respond based on TTL expiry, and recording those responses can only happen after they've been received.",
    },
    {
        "topic": "Networking", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for checking and adding a static route.",
        "options": ["Run `ip route show` again to confirm the new route was added", "Run `ip route show` to view current routes", "Run `ip route add <network> via <gateway>` to add a specific route if needed"],
        "correct_answer": '["Run `ip route show` to view current routes", "Run `ip route add <network> via <gateway>` to add a specific route if needed", "Run `ip route show` again to confirm the new route was added"]',
        "explanation_correct": "Correct -- the current routes must be checked before deciding a new one is needed, and confirming the addition requires checking the routing table again after the change.",
        "explanation_incorrect": "The routing table should be reviewed before adding a new route, and confirming the change requires checking the table again after the route has actually been added.",
    },
]
