"""
Networking - Medium batch, 50 questions total.
Distribution: even split -- 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.

Schema matches networking_easy_questions.py -- see that file's header for full field notes.
Medium content covers static routing, iptables blocking rules, TCP connection states,
tcpdump filtering, iperf3 throughput testing, conntrack, network namespaces, IPv6,
CIDR/subnet math, reverse proxies, VPNs, DNS record types, and network bonding.
"""

NETWORKING_MEDIUM_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to calculate and display subnet details (network address, broadcast address, usable host range) for the CIDR block 192.168.1.0/24, using ipcalc.",
        "correct_answer": "ipcalc 192.168.1.0/24",
        "explanation_correct": "Correct -- `ipcalc` computes and displays subnet details like the network address, broadcast address, and usable host range for the given CIDR block.",
        "explanation_incorrect": "A correct solution must calculate subnet details for 192.168.1.0/24 specifically, typically using ipcalc.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to add a static route to reach network 10.0.0.0/24 via gateway 192.168.1.254.",
        "correct_answer": "ip route add 10.0.0.0/24 via 192.168.1.254",
        "explanation_correct": "Correct -- `ip route add` with the target network and via gateway correctly configures a static route to that network.",
        "explanation_incorrect": "A correct solution must add a route to 10.0.0.0/24 via 192.168.1.254 specifically, typically using ip route add.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to delete a previously configured route to network 10.0.0.0/24.",
        "correct_answer": "ip route del 10.0.0.0/24",
        "explanation_correct": "Correct -- `ip route del` removes the specified route from the routing table.",
        "explanation_incorrect": "A correct solution must remove the route to 10.0.0.0/24 specifically, typically using ip route del.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to add an iptables rule that blocks all incoming traffic from IP address 203.0.113.5.",
        "correct_answer": "iptables -A INPUT -s 203.0.113.5 -j DROP",
        "explanation_correct": "Correct -- this appends a rule to the INPUT chain that drops all traffic sourced from the specified IP address.",
        "explanation_incorrect": "A correct solution must block incoming traffic from 203.0.113.5 specifically, typically using iptables -A INPUT -s <ip> -j DROP.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to display detailed TCP connection states (e.g. ESTABLISHED, TIME_WAIT) for all connections.",
        "correct_answer": "ss -tan",
        "explanation_correct": "Correct -- -t (TCP), -a (all, including non-listening), and -n (numeric) together display every TCP connection with its current state.",
        "explanation_incorrect": "A correct solution must show TCP connection states for all connections (not just listening ones), typically using ss -tan.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to capture packets on interface eth0, filtered to traffic involving IP 10.0.0.5, saving the capture to a file named capture.pcap.",
        "correct_answer": "tcpdump -i eth0 host 10.0.0.5 -w capture.pcap",
        "explanation_correct": "Correct -- the host filter limits the capture to traffic to/from 10.0.0.5, and -w writes the captured packets to the given file.",
        "explanation_incorrect": "A correct solution must capture on eth0, filtered to traffic involving 10.0.0.5, and save the result to capture.pcap.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to test network throughput between the local machine and a server at 10.0.0.5, using iperf3 in client mode.",
        "correct_answer": "iperf3 -c 10.0.0.5",
        "explanation_correct": "Correct -- the -c flag runs iperf3 in client mode, connecting to the specified server (which must already be running iperf3 -s) to measure throughput.",
        "explanation_incorrect": "A correct solution must run iperf3 in client mode against 10.0.0.5 specifically, using the -c flag.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to display the current connection tracking table, showing active tracked connections.",
        "correct_answer": "conntrack -L",
        "explanation_correct": "Correct -- `conntrack -L` lists all connections currently tracked by the kernel's connection tracking system.",
        "explanation_incorrect": "A correct solution must display the current conntrack table, typically using conntrack -L.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to create a network namespace named 'ns1'.",
        "correct_answer": "ip netns add ns1",
        "explanation_correct": "Correct -- `ip netns add` creates a new, isolated network namespace with the given name.",
        "explanation_incorrect": "A correct solution must create a network namespace named ns1 specifically, typically using ip netns add.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "coding",
        "prompt": "Write the command to display all configured IPv6 addresses on the system.",
        "correct_answer": "ip -6 addr show",
        "explanation_correct": "Correct -- the -6 flag restricts `ip addr show` output to IPv6 addresses specifically.",
        "explanation_incorrect": "A correct solution must show only IPv6 addresses (not IPv4), typically using ip -6 addr show.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "What does CIDR notation like /24 represent?",
        "options": ["The number of bits used for the network portion of an IP address", "The number of hosts on the network", "A port number", "A TTL (time-to-live) value"],
        "correct_answer": "The number of bits used for the network portion of an IP address",
        "explanation_correct": "The number after the slash indicates how many of the address's bits are fixed as the network portion, with the remaining bits available for host addressing.",
        "explanation_incorrect": {
            "The number of hosts on the network": "Wrong — while the prefix length determines the host count indirectly, it's not itself a host count; a /24 has 254 usable hosts, not 24.",
            "A port number": "Wrong — port numbers are unrelated to CIDR notation, which describes IP address/subnet structure.",
            "A TTL (time-to-live) value": "Wrong — TTL is a separate packet field controlling how many hops a packet can traverse, unrelated to CIDR notation.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "How many usable host addresses are available in a standard /24 IPv4 subnet (excluding the network and broadcast addresses)?",
        "options": ["254", "256", "255", "128"],
        "correct_answer": "254",
        "explanation_correct": "A /24 subnet has 256 total addresses, but the first (network address) and last (broadcast address) are reserved, leaving 254 usable for hosts.",
        "explanation_incorrect": {
            "256": "Wrong — that's the total address count, before subtracting the reserved network and broadcast addresses.",
            "255": "Wrong — this only subtracts one reserved address; both the network and broadcast addresses are reserved, not just one.",
            "128": "Wrong — 128 usable addresses would correspond to a /25 subnet, not a /24.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a reverse proxy?",
        "options": [
            "Forwards client requests to one or more backend servers, hiding their details from the client",
            "Forwards a client's own outbound requests to external servers on the client's behalf",
            "Encrypts DNS traffic between a client and resolver",
            "Translates private IP addresses to a public IP address",
        ],
        "correct_answer": "Forwards client requests to one or more backend servers, hiding their details from the client",
        "explanation_correct": "A reverse proxy sits in front of one or more backend servers, receiving client requests and forwarding them onward, so clients interact with the proxy rather than the backends directly.",
        "explanation_incorrect": {
            "Forwards a client's own outbound requests to external servers on the client's behalf": "Wrong — that describes a forward proxy, which acts on behalf of clients going out to the internet, the opposite direction from a reverse proxy.",
            "Encrypts DNS traffic between a client and resolver": "Wrong — that's closer to the role of DNS-over-HTTPS/TLS, unrelated to a reverse proxy's purpose.",
            "Translates private IP addresses to a public IP address": "Wrong — that's the role of NAT, a different mechanism from a reverse proxy.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the TCP connection state TIME_WAIT indicate?",
        "options": [
            "The connection was closed locally, and the OS is waiting to ensure the remote end received the final acknowledgment",
            "The connection is actively transmitting data",
            "The connection is waiting to be established",
            "The connection has timed out due to inactivity",
        ],
        "correct_answer": "The connection was closed locally, and the OS is waiting to ensure the remote end received the final acknowledgment",
        "explanation_correct": "TIME_WAIT is a normal part of TCP's connection teardown, holding the socket briefly to handle any delayed packets and confirm the close was fully acknowledged.",
        "explanation_incorrect": {
            "The connection is actively transmitting data": "Wrong — that would be the ESTABLISHED state, not TIME_WAIT, which occurs after closing.",
            "The connection is waiting to be established": "Wrong — that would be closer to SYN_SENT or SYN_RECV, states during connection setup, not teardown.",
            "The connection has timed out due to inactivity": "Wrong — TIME_WAIT is a deliberate, expected part of normal connection closure, not a timeout/failure condition.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a VPN?",
        "options": [
            "Creates an encrypted tunnel over an untrusted network, extending private network access remotely",
            "Load balances traffic between multiple servers",
            "Translates domain names into IP addresses",
            "Filters malicious traffic based on known signatures",
        ],
        "correct_answer": "Creates an encrypted tunnel over an untrusted network, extending private network access remotely",
        "explanation_correct": "A VPN (Virtual Private Network) establishes an encrypted tunnel across a public/untrusted network, letting a remote client securely access resources as if it were on the private network.",
        "explanation_incorrect": {
            "Load balances traffic between multiple servers": "Wrong — that's the role of a load balancer, unrelated to a VPN's tunneling purpose.",
            "Translates domain names into IP addresses": "Wrong — that's the role of DNS, unrelated to a VPN.",
            "Filters malicious traffic based on known signatures": "Wrong — that's closer to the role of an intrusion detection/prevention system, a different security mechanism from a VPN.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of network bonding (or teaming)?",
        "options": [
            "Combines multiple physical network interfaces into a single logical interface for redundancy and/or increased throughput",
            "Encrypts traffic exchanged between two bonded hosts",
            "Limits bandwidth for lower-priority traffic classes",
            "Translates IPv4 addresses to IPv6 addresses",
        ],
        "correct_answer": "Combines multiple physical network interfaces into a single logical interface for redundancy and/or increased throughput",
        "explanation_correct": "Bonding aggregates two or more NICs into one logical interface, providing failover (if one link goes down) and/or combined throughput, depending on the bonding mode.",
        "explanation_incorrect": {
            "Encrypts traffic exchanged between two bonded hosts": "Wrong — bonding is about combining interfaces, not encryption, which is an unrelated concern.",
            "Limits bandwidth for lower-priority traffic classes": "Wrong — that describes traffic shaping/QoS, a different mechanism from bonding.",
            "Translates IPv4 addresses to IPv6 addresses": "Wrong — that's a separate concern (e.g. via NAT64), unrelated to interface bonding.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "Which DNS record type maps a domain name to an IPv4 address?",
        "options": ["A record", "CNAME record", "MX record", "TXT record"],
        "correct_answer": "A record",
        "explanation_correct": "An A record maps a hostname directly to an IPv4 address.",
        "explanation_incorrect": {
            "CNAME record": "Wrong — a CNAME maps a hostname to another hostname (an alias), not directly to an IP address.",
            "MX record": "Wrong — MX records specify mail servers for a domain, unrelated to IPv4 address mapping.",
            "TXT record": "Wrong — TXT records hold arbitrary text data (often for verification or SPF/DKIM), not IP address mappings.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "Which DNS record type specifies the mail servers responsible for receiving email for a domain?",
        "options": ["MX record", "A record", "CNAME record", "NS record"],
        "correct_answer": "MX record",
        "explanation_correct": "MX (Mail Exchange) records list the mail servers, with priorities, that should handle email for a domain.",
        "explanation_incorrect": {
            "A record": "Wrong — A records map hostnames to IPv4 addresses, not mail server assignments specifically.",
            "CNAME record": "Wrong — CNAME records alias one hostname to another, unrelated to mail routing.",
            "NS record": "Wrong — NS records specify a domain's authoritative name servers, not its mail servers.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of a network namespace in Linux?",
        "options": [
            "Provides an isolated network stack (interfaces, routes, ports) for a group of processes, separate from the host's",
            "Encrypts all traffic passing through that namespace",
            "Limits network bandwidth for a specific process",
            "Automatically assigns static IP addresses to processes",
        ],
        "correct_answer": "Provides an isolated network stack (interfaces, routes, ports) for a group of processes, separate from the host's",
        "explanation_correct": "A network namespace gives a set of processes their own private view of network interfaces, routing tables, and ports, isolated from the host's default namespace — a core building block for container networking.",
        "explanation_incorrect": {
            "Encrypts all traffic passing through that namespace": "Wrong — namespaces provide isolation, not automatic encryption of traffic.",
            "Limits network bandwidth for a specific process": "Wrong — that's closer to the role of traffic shaping/cgroups, a different mechanism from network namespace isolation.",
            "Automatically assigns static IP addresses to processes": "Wrong — a namespace provides isolation, but addressing within it must still be explicitly configured.",
        },
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `conntrack` track in the Linux kernel?",
        "options": [
            "The state of active network connections passing through the system, useful for stateful firewalls and NAT",
            "The physical location of network cables",
            "DNS query history",
            "CPU usage attributed to each network connection",
        ],
        "correct_answer": "The state of active network connections passing through the system, useful for stateful firewalls and NAT",
        "explanation_correct": "Connection tracking maintains state for active connections (like TCP handshake progress), which stateful firewalls and NAT rely on to correctly handle related packets.",
        "explanation_incorrect": {
            "The physical location of network cables": "Wrong — conntrack is a purely logical/software concept, unrelated to physical cabling.",
            "DNS query history": "Wrong — DNS query logging is a separate concern (e.g. via resolver logs), unrelated to conntrack.",
            "CPU usage attributed to each network connection": "Wrong — conntrack tracks connection state, not per-connection resource usage.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "CIDR notation (e.g. /24) specifies the number of bits used for the ____ portion of an IP address.",
        "options": None,
        "correct_answer": "network",
        "explanation_correct": "The CIDR prefix length indicates how many leading bits are fixed as the network portion of the address.",
        "explanation_incorrect": "The blank should be filled with the term for the portion CIDR notation specifies: network.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A standard /24 IPv4 subnet provides ____ usable host addresses (excluding the network and broadcast addresses).",
        "options": None,
        "correct_answer": "254",
        "explanation_correct": "A /24 has 256 total addresses, minus the reserved network and broadcast addresses, leaving 254 usable for hosts.",
        "explanation_incorrect": "The blank should be filled with the usable host count for a /24 subnet: 254.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ proxy forwards client requests to one or more backend servers, hiding the backend servers' details from the client.",
        "options": None,
        "correct_answer": "reverse",
        "explanation_correct": "A reverse proxy sits in front of backend servers, forwarding client requests to them.",
        "explanation_incorrect": "The blank should be filled with the type of proxy that forwards to backends: reverse.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The TCP connection state ____ indicates a connection was closed locally but the OS is waiting to ensure the remote end received the final acknowledgment.",
        "options": None,
        "correct_answer": "TIME_WAIT",
        "explanation_correct": "TIME_WAIT is a normal part of TCP's connection teardown process.",
        "explanation_incorrect": "The blank should be filled with the name of this TCP state: TIME_WAIT.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ creates an encrypted tunnel over an untrusted network, extending private network access remotely.",
        "options": None,
        "correct_answer": "VPN",
        "explanation_correct": "A VPN (Virtual Private Network) provides a secure, encrypted tunnel across an untrusted network.",
        "explanation_incorrect": "The blank should be filled with the acronym for this secure tunneling technology: VPN.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Network ____ combines multiple physical network interfaces into a single logical interface for redundancy or increased throughput.",
        "options": None,
        "correct_answer": "bonding",
        "explanation_correct": "Bonding (also called teaming) aggregates multiple NICs into one logical interface.",
        "explanation_incorrect": "The blank should be filled with the term for this interface-aggregation technique: bonding.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A DNS ____ record maps a domain name directly to an IPv4 address.",
        "options": None,
        "correct_answer": "A",
        "explanation_correct": "An A record maps a hostname to an IPv4 address.",
        "explanation_incorrect": "The blank should be filled with the name of this DNS record type: A.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A DNS ____ record specifies which mail servers are responsible for receiving email for a domain.",
        "options": None,
        "correct_answer": "MX",
        "explanation_correct": "MX (Mail Exchange) records list the mail servers assigned to handle a domain's email.",
        "explanation_incorrect": "The blank should be filled with the name of this DNS record type: MX.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A network ____ in Linux provides an isolated network stack (interfaces, routes, ports) for a group of processes.",
        "options": None,
        "correct_answer": "namespace",
        "explanation_correct": "Network namespaces isolate the network stack for a set of processes, a core building block for containers.",
        "explanation_incorrect": "The blank should be filled with the term for this isolation mechanism: namespace.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ tool tracks the state of active network connections passing through a Linux system, useful for stateful firewalls and NAT.",
        "options": None,
        "correct_answer": "conntrack",
        "explanation_correct": "conntrack manages and exposes the kernel's connection tracking table.",
        "explanation_incorrect": "The blank should be filled with the name of this connection tracking tool: conntrack.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for adding and verifying a static route.",
        "options": ["Test connectivity to a host in that network to confirm the route works", "Run `ip route add 10.0.0.0/24 via 192.168.1.254` to add the route", "Run `ip route show` to confirm the route was added"],
        "correct_answer": '["Run `ip route add 10.0.0.0/24 via 192.168.1.254` to add the route", "Run `ip route show` to confirm the route was added", "Test connectivity to a host in that network to confirm the route works"]',
        "explanation_correct": "Correct — the route must be added before it can be confirmed in the routing table, and testing actual connectivity is the final practical verification step.",
        "explanation_incorrect": "The route must be added before it appears in the routing table for confirmation, and connectivity testing is a reasonable final step after configuration is confirmed.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for creating a network namespace and inspecting it.",
        "options": ["Assign an interface to the namespace to give it connectivity", "Run `ip netns add ns1` to create the namespace", "Run `ip netns exec ns1 ip addr show` to view its (initially empty) interfaces"],
        "correct_answer": '["Run `ip netns add ns1` to create the namespace", "Run `ip netns exec ns1 ip addr show` to view its (initially empty) interfaces", "Assign an interface to the namespace to give it connectivity"]',
        "explanation_correct": "Correct — the namespace must exist before its interfaces can be inspected, and assigning connectivity is a natural next step after observing it starts out empty.",
        "explanation_incorrect": "The namespace must be created before its (empty) interface list can be viewed, and assigning an interface for connectivity follows after confirming the initial empty state.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for blocking a malicious IP address with iptables and confirming it works.",
        "options": ["Confirm traffic from that IP is now blocked", "Run `iptables -A INPUT -s 203.0.113.5 -j DROP` to block the IP", "Run `iptables -L` to verify the rule is in place"],
        "correct_answer": '["Run `iptables -A INPUT -s 203.0.113.5 -j DROP` to block the IP", "Run `iptables -L` to verify the rule is in place", "Confirm traffic from that IP is now blocked"]',
        "explanation_correct": "Correct — the rule must be added before it can be verified in the rule list, and confirming actual blocking is the final practical validation step.",
        "explanation_incorrect": "The rule must be added before it can be listed and verified, and confirming the block actually works in practice is a reasonable final step.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing TCP connection state issues.",
        "options": ["Investigate the application or configuration causing that state", "Run `ss -tan` to view current connection states", "Identify connections stuck in an unexpected state (e.g. excessive TIME_WAIT)"],
        "correct_answer": '["Run `ss -tan` to view current connection states", "Identify connections stuck in an unexpected state (e.g. excessive TIME_WAIT)", "Investigate the application or configuration causing that state"]',
        "explanation_correct": "Correct — connection states must be viewed before a problematic pattern can be identified, and investigation of the underlying cause follows once that pattern is spotted.",
        "explanation_incorrect": "Connection states must be observed before a specific problem pattern can be identified, and root-cause investigation follows once that pattern has been noticed.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for capturing and analyzing specific traffic with tcpdump.",
        "options": ["Open it in a tool like Wireshark for detailed inspection", "Run `tcpdump -i eth0 host 10.0.0.5 -w capture.pcap` to capture relevant traffic", "Transfer the capture file for analysis"],
        "correct_answer": '["Run `tcpdump -i eth0 host 10.0.0.5 -w capture.pcap` to capture relevant traffic", "Transfer the capture file for analysis", "Open it in a tool like Wireshark for detailed inspection"]',
        "explanation_correct": "Correct — the capture file must exist before it can be transferred, and it must be accessible before it can be opened for detailed inspection.",
        "explanation_incorrect": "The capture must be recorded before the file can be transferred, and it must be transferred (or otherwise accessible) before it can be opened for review.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for testing network throughput with iperf3.",
        "options": ["Review the reported bandwidth results", "Start iperf3 in server mode on the target host", "Run `iperf3 -c 10.0.0.5` on the client to connect to that server"],
        "correct_answer": '["Start iperf3 in server mode on the target host", "Run `iperf3 -c 10.0.0.5` on the client to connect to that server", "Review the reported bandwidth results"]',
        "explanation_correct": "Correct — the server must be listening before a client can connect to it, and results can only be reviewed after the test has actually run.",
        "explanation_incorrect": "The server side must be running before the client can connect to it, and reviewing bandwidth results only makes sense after the test has completed.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up basic load balancing across backend servers.",
        "options": ["Clients connect to the load balancer's single address instead of individual backends", "Deploy multiple backend server instances", "Configure a load balancer (or reverse proxy) to distribute traffic across them"],
        "correct_answer": '["Deploy multiple backend server instances", "Configure a load balancer (or reverse proxy) to distribute traffic across them", "Clients connect to the load balancer\'s single address instead of individual backends"]',
        "explanation_correct": "Correct — backend servers must exist before a load balancer can distribute traffic across them, and clients only start using the load balancer's address once that distribution is configured.",
        "explanation_incorrect": "The backend instances must be deployed before a load balancer can be configured to distribute across them, and client usage of the load balancer address is the intended final state.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for configuring a reverse proxy to forward requests to a backend application.",
        "options": ["Clients access the application through the reverse proxy's address", "Install and configure a reverse proxy (e.g. nginx)", "Define a rule forwarding incoming requests to the backend application's address"],
        "correct_answer": '["Install and configure a reverse proxy (e.g. nginx)", "Define a rule forwarding incoming requests to the backend application\'s address", "Clients access the application through the reverse proxy\'s address"]',
        "explanation_correct": "Correct — the reverse proxy must be installed before forwarding rules can be defined on it, and clients only begin accessing the app through it once that forwarding is configured.",
        "explanation_incorrect": "The proxy must be installed before a forwarding rule can be configured on it, and client access through the proxy only becomes possible once that rule is in place.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for troubleshooting a DNS mail server configuration issue.",
        "options": ["Update the DNS zone if a discrepancy is found", "Run `dig example.com MX` to check the domain's mail server records", "Compare the returned records to the expected configuration"],
        "correct_answer": '["Run `dig example.com MX` to check the domain\'s mail server records", "Compare the returned records to the expected configuration", "Update the DNS zone if a discrepancy is found"]',
        "explanation_correct": "Correct — the current records must be queried before they can be compared to expectations, and any zone update only happens after a discrepancy is actually found.",
        "explanation_incorrect": "The current records must be retrieved before comparison is possible, and making changes to the zone should only follow after confirming there's actually a discrepancy.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up network bonding for interface redundancy.",
        "options": ["Assign an IP address to the bond interface instead of the individual NICs", "Create a bond interface combining two physical NICs", "Configure the bonding mode (e.g. active-backup)"],
        "correct_answer": '["Create a bond interface combining two physical NICs", "Configure the bonding mode (e.g. active-backup)", "Assign an IP address to the bond interface instead of the individual NICs"]',
        "explanation_correct": "Correct — the bond interface must exist before its mode can be configured, and addressing is applied to the bond interface only once it's fully set up.",
        "explanation_incorrect": "The bond interface must be created before its mode can be set, and IP addressing should be applied to the bonded interface only after it's properly configured.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for calculating subnet details with ipcalc.",
        "options": ["Use this information to plan IP address allocation", "Run `ipcalc 192.168.1.0/24` to calculate subnet details", "Review the network address, broadcast address, and usable host range"],
        "correct_answer": '["Run `ipcalc 192.168.1.0/24` to calculate subnet details", "Review the network address, broadcast address, and usable host range", "Use this information to plan IP address allocation"]',
        "explanation_correct": "Correct — the calculation must run before there's anything to review, and planning based on that information naturally follows the review.",
        "explanation_incorrect": "The ipcalc command must run before its output can be reviewed, and using that information for planning comes only after reviewing it.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct conceptual order for a VPN connection being established.",
        "options": ["Client traffic destined for the private network is routed through the tunnel", "Client authenticates to the VPN server", "An encrypted tunnel is established between client and server"],
        "correct_answer": '["Client authenticates to the VPN server", "An encrypted tunnel is established between client and server", "Client traffic destined for the private network is routed through the tunnel"]',
        "explanation_correct": "Correct — authentication must succeed before a tunnel is established, and traffic can only be routed through the tunnel once it actually exists.",
        "explanation_incorrect": "Authentication must happen before the tunnel is set up, and traffic routing through the tunnel only becomes possible once the tunnel is established.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for troubleshooting excessive TIME_WAIT connections.",
        "options": ["Consider tuning relevant kernel parameters if the count is problematic", "Run `ss -tan` and count connections in TIME_WAIT state", "Determine if this is expected given the application's connection pattern"],
        "correct_answer": '["Run `ss -tan` and count connections in TIME_WAIT state", "Determine if this is expected given the application\'s connection pattern", "Consider tuning relevant kernel parameters if the count is problematic"]',
        "explanation_correct": "Correct — the count must be observed before a judgment about whether it's expected can be made, and tuning is only considered once it's judged to actually be a problem.",
        "explanation_incorrect": "The TIME_WAIT count must be observed before evaluating whether it's normal, and any tuning action should follow only after concluding there's a real problem.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for reviewing and cleaning up the conntrack table.",
        "options": ["Run `conntrack -D` with appropriate filters to delete specific entries if needed", "Run `conntrack -L` to view the current connection tracking table", "Identify any stale or unwanted tracked connections"],
        "correct_answer": '["Run `conntrack -L` to view the current connection tracking table", "Identify any stale or unwanted tracked connections", "Run `conntrack -D` with appropriate filters to delete specific entries if needed"]',
        "explanation_correct": "Correct — the table must be viewed before stale entries can be identified, and deletion only happens once specific entries have been identified as unwanted.",
        "explanation_incorrect": "The table must be listed before any specific entries can be identified as stale, and deletion should only follow that identification step.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up and verifying IPv6 addressing on an interface.",
        "options": ["Verify connectivity using `ping6` or `ping -6`", "Run `ip -6 addr show` to check current IPv6 addresses", "Run `ip -6 addr add <address>/<prefix> dev eth0` to add a new IPv6 address if needed"],
        "correct_answer": '["Run `ip -6 addr show` to check current IPv6 addresses", "Run `ip -6 addr add <address>/<prefix> dev eth0` to add a new IPv6 address if needed", "Verify connectivity using `ping6` or `ping -6`"]',
        "explanation_correct": "Correct — the current state must be checked before deciding whether to add an address, and verifying connectivity is the final step once addressing is confirmed.",
        "explanation_incorrect": "The current IPv6 configuration should be checked before deciding whether an address needs to be added, and connectivity verification is a sensible final step.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a basic multi-record-type DNS lookup workflow.",
        "options": ["Run `dig example.com TXT` to check text records (e.g. for domain verification)", "Run `dig example.com A` to check the IPv4 address record", "Run `dig example.com MX` to check mail server records"],
        "correct_answer": '["Run `dig example.com A` to check the IPv4 address record", "Run `dig example.com MX` to check mail server records", "Run `dig example.com TXT` to check text records (e.g. for domain verification)"]',
        "explanation_correct": "Correct — this reflects a reasonable investigative order, starting with the most fundamental record type (A) before checking more specialized ones (MX, then TXT).",
        "explanation_incorrect": "While these queries can technically run in any order, checking the basic address record first, then mail routing, then auxiliary text records is a natural, systematic progression.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for diagnosing whether a firewall is dropping traffic, using conntrack and iptables together.",
        "options": ["Correlate the two to determine whether traffic is being dropped before or after connection tracking", "Run `iptables -L -v` to check rule hit counters", "Run `conntrack -L` to see if the connection is even being tracked"],
        "correct_answer": '["Run `iptables -L -v` to check rule hit counters", "Run `conntrack -L` to see if the connection is even being tracked", "Correlate the two to determine whether traffic is being dropped before or after connection tracking"]',
        "explanation_correct": "Correct — both individual data sources should be gathered before they can be correlated, so checking rule counters and the tracking table come first, with correlation as the final analytical step.",
        "explanation_incorrect": "Both the iptables counters and the conntrack table need to be checked individually before they can be meaningfully correlated to pinpoint where traffic is being affected.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up basic traffic prioritization (a simplified QoS concept).",
        "options": ["Monitor to confirm the prioritized traffic experiences lower latency", "Identify the traffic that needs priority (e.g. VoIP)", "Configure traffic shaping rules to prioritize that traffic"],
        "correct_answer": '["Identify the traffic that needs priority (e.g. VoIP)", "Configure traffic shaping rules to prioritize that traffic", "Monitor to confirm the prioritized traffic experiences lower latency"]',
        "explanation_correct": "Correct — the traffic needing priority must be identified before rules can target it, and monitoring the effect is the final step confirming the configuration worked.",
        "explanation_incorrect": "The traffic type must be identified before rules can be written to prioritize it, and monitoring for the intended effect is a sensible final verification step.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for verifying a reverse proxy is correctly forwarding requests.",
        "options": ["Compare the response to what the backend would return directly", "Send a request directly to the reverse proxy's address", "Confirm the request reaches the intended backend server"],
        "correct_answer": '["Send a request directly to the reverse proxy\'s address", "Confirm the request reaches the intended backend server", "Compare the response to what the backend would return directly"]',
        "explanation_correct": "Correct — the request must be sent through the proxy before you can confirm it reached the backend, and comparing responses is the final validation step.",
        "explanation_incorrect": "The request must go through the proxy before confirming backend receipt, and comparing the proxied response to a direct one is a reasonable final check.",
    },
    {
        "topic": "Networking", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for planning IP address allocation across multiple subnets.",
        "options": ["Allocate non-overlapping address ranges to each subnet", "Determine the total number of hosts needed per subnet", "Choose an appropriate CIDR prefix size for each subnet"],
        "correct_answer": '["Determine the total number of hosts needed per subnet", "Choose an appropriate CIDR prefix size for each subnet", "Allocate non-overlapping address ranges to each subnet"]',
        "explanation_correct": "Correct — the host count requirement must be known before an appropriate CIDR size can be chosen, and actual address ranges are allocated only once the sizing is decided.",
        "explanation_incorrect": "Host count requirements must be determined before a fitting CIDR prefix can be chosen, and final allocation of address ranges depends on that sizing decision being made first.",
    },
]
