"""
Networking - Hard batch, 50 questions total.
Distribution: even split -- 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.

Schema matches networking_easy_questions.py -- see that file's header for full field notes.
Hard content covers WireGuard, GRE tunnels, iptables NAT/custom chains, traffic control (tc),
jumbo frames, openssl TLS inspection, kernel socket buffer tuning, eBPF, VXLAN, ECMP,
SYN flood mitigation, mTLS, VRRP/keepalived, Path MTU Discovery, anycast, and LACP bonding.
"""

NETWORKING_HARD_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to generate a new WireGuard private key.",
        "correct_answer": "wg genkey",
        "explanation_correct": "Correct -- `wg genkey` generates a new WireGuard private key and prints it to standard output.",
        "explanation_incorrect": "A correct solution must generate a WireGuard private key specifically, using wg genkey.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to derive a WireGuard public key from a private key stored in a file named privatekey.",
        "correct_answer": "wg pubkey < privatekey",
        "explanation_correct": "Correct -- piping the private key file into `wg pubkey` derives and prints the corresponding public key.",
        "explanation_incorrect": "A correct solution must derive the public key from the given private key file, typically using wg pubkey with input redirection.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to create a GRE tunnel interface named gre1 between local IP 203.0.113.1 and remote IP 198.51.100.1.",
        "correct_answer": "ip tunnel add gre1 mode gre remote 198.51.100.1 local 203.0.113.1",
        "explanation_correct": "Correct -- `ip tunnel add` with mode gre and the given local/remote endpoints creates a GRE tunnel interface between the two sites.",
        "explanation_incorrect": "A correct solution must create a GRE tunnel interface named gre1 with the correct local and remote endpoints.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to add an iptables NAT MASQUERADE rule for outbound traffic on interface eth0.",
        "correct_answer": "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE",
        "explanation_correct": "Correct -- adding this rule to the nat table's POSTROUTING chain masquerades outbound traffic leaving via eth0, translating source addresses as needed.",
        "explanation_incorrect": "A correct solution must add a MASQUERADE rule to the nat table's POSTROUTING chain, targeting eth0 as the outbound interface.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to display the current traffic control (tc) queueing discipline configured on interface eth0.",
        "correct_answer": "tc qdisc show dev eth0",
        "explanation_correct": "Correct -- `tc qdisc show` displays the queueing discipline currently applied to the specified interface.",
        "explanation_incorrect": "A correct solution must show the current qdisc for eth0 specifically, typically using tc qdisc show dev eth0.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to set interface eth0 to use jumbo frames with an MTU of 9000.",
        "correct_answer": "ip link set eth0 mtu 9000",
        "explanation_correct": "Correct -- `ip link set <interface> mtu <value>` changes the interface's MTU, and 9000 is the standard jumbo frame size.",
        "explanation_incorrect": "A correct solution must set eth0's MTU to exactly 9000, typically using ip link set eth0 mtu 9000.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to inspect the TLS certificate and cipher suite offered by a server at example.com on port 443, using openssl.",
        "correct_answer": "openssl s_client -connect example.com:443",
        "explanation_correct": "Correct -- `openssl s_client -connect` establishes a TLS connection to the given host/port and displays the negotiated certificate and cipher details.",
        "explanation_incorrect": "A correct solution must connect to example.com on port 443 and display its TLS details, typically using openssl s_client -connect.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command(s) to permanently set the kernel parameter net.core.rmem_max to 16777216 by adding it to /etc/sysctl.conf and reloading.",
        "correct_answer": "echo \"net.core.rmem_max = 16777216\" >> /etc/sysctl.conf && sysctl -p",
        "explanation_correct": "Correct -- appending the setting to sysctl.conf persists it across reboots, and sysctl -p reloads the configuration to apply it immediately as well.",
        "explanation_incorrect": "A correct solution must both add the setting to /etc/sysctl.conf for persistence and reload it (via sysctl -p) so it takes effect now, not just one or the other.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to display currently loaded eBPF programs on the system, using bpftool.",
        "correct_answer": "bpftool prog show",
        "explanation_correct": "Correct -- `bpftool prog show` lists all eBPF programs currently loaded into the kernel.",
        "explanation_incorrect": "A correct solution must display currently loaded eBPF programs, typically using bpftool prog show.",
        "options": None,
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "coding",
        "prompt": "Write the command to enable tcp_tw_reuse (allowing reuse of sockets in TIME_WAIT state for new outgoing connections) via sysctl.",
        "correct_answer": "sysctl -w net.ipv4.tcp_tw_reuse=1",
        "explanation_correct": "Correct -- setting net.ipv4.tcp_tw_reuse to 1 allows the kernel to reuse TIME_WAIT sockets for new outgoing connections when safe to do so.",
        "explanation_incorrect": "A correct solution must enable tcp_tw_reuse specifically (not tcp_tw_recycle, a different and largely deprecated setting), typically using sysctl -w.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of eBPF in modern Linux networking?",
        "options": [
            "Allows running sandboxed programs in the kernel for tasks like packet filtering, monitoring, and load balancing, without traditional kernel modules",
            "Replaces iptables entirely by default on all Linux systems",
            "Is used exclusively for CPU profiling, unrelated to networking",
            "Is a userspace-only technology with no kernel interaction",
        ],
        "correct_answer": "Allows running sandboxed programs in the kernel for tasks like packet filtering, monitoring, and load balancing, without traditional kernel modules",
        "explanation_correct": "eBPF lets verified, sandboxed programs run inside the kernel, enabling high-performance packet processing, observability, and load balancing without the risks of writing full kernel modules.",
        "explanation_incorrect": {
            "Replaces iptables entirely by default on all Linux systems": "Wrong — while eBPF-based tools (like Cilium) can replace iptables in some setups, this isn't automatic or default across all systems; iptables remains widely used.",
            "Is used exclusively for CPU profiling, unrelated to networking": "Wrong — while eBPF does support profiling use cases, it's heavily used in networking (filtering, load balancing) as well, not exclusively for profiling.",
            "Is a userspace-only technology with no kernel interaction": "Wrong — eBPF programs run inside the kernel itself, which is the whole point of the technology.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is a primary advantage of WireGuard over traditional VPN protocols like IPSec or OpenVPN?",
        "options": [
            "A smaller codebase with modern cryptography, generally offering simpler configuration and better performance",
            "It doesn't use any encryption, prioritizing speed instead",
            "It only works over TCP port 443, disguising itself as HTTPS traffic",
            "It requires no key management of any kind",
        ],
        "correct_answer": "A smaller codebase with modern cryptography, generally offering simpler configuration and better performance",
        "explanation_correct": "WireGuard is designed to be minimal and auditable (a much smaller codebase than IPSec or OpenVPN), using modern cryptographic primitives, which contributes to easier configuration and often better performance.",
        "explanation_incorrect": {
            "It doesn't use any encryption, prioritizing speed instead": "Wrong — WireGuard absolutely uses strong modern encryption; forgoing encryption isn't part of its design at all.",
            "It only works over TCP port 443, disguising itself as HTTPS traffic": "Wrong — WireGuard typically uses UDP, and doesn't have a fixed port disguised as HTTPS traffic by design.",
            "It requires no key management of any kind": "Wrong — WireGuard still requires generating and exchanging public/private key pairs; it doesn't eliminate key management.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What does ECMP (Equal-Cost Multi-Path) routing provide?",
        "options": [
            "Distributes traffic across multiple paths of equal routing cost, for load balancing and redundancy",
            "Encrypts traffic as it travels across multiple paths",
            "Guarantees the single lowest-latency path is always chosen",
            "Only functions with IPv6 addressing",
        ],
        "correct_answer": "Distributes traffic across multiple paths of equal routing cost, for load balancing and redundancy",
        "explanation_correct": "When multiple routes to a destination have the same cost metric, ECMP spreads traffic across them (often via hashing), improving both throughput and resilience to a single path's failure.",
        "explanation_incorrect": {
            "Encrypts traffic as it travels across multiple paths": "Wrong — ECMP is purely about path selection/load distribution, not encryption.",
            "Guarantees the single lowest-latency path is always chosen": "Wrong — ECMP distributes across equal-cost paths rather than always picking one 'best' path; that's closer to a single-path routing decision, the opposite of ECMP's purpose.",
            "Only functions with IPv6 addressing": "Wrong — ECMP works with both IPv4 and IPv6, it isn't restricted to IPv6.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of VXLAN?",
        "options": [
            "Creates Layer 2 overlay networks on top of Layer 3 infrastructure, commonly used in virtualized/cloud environments",
            "Encrypts VLAN traffic for secure transport",
            "Replaces the need for IP addressing entirely",
            "Defines a physical cabling standard for data centers",
        ],
        "correct_answer": "Creates Layer 2 overlay networks on top of Layer 3 infrastructure, commonly used in virtualized/cloud environments",
        "explanation_correct": "VXLAN encapsulates Layer 2 Ethernet frames inside Layer 3 UDP packets, allowing virtual Layer 2 networks to span across routed IP infrastructure — common in cloud and virtualization platforms needing many isolated logical networks.",
        "explanation_incorrect": {
            "Encrypts VLAN traffic for secure transport": "Wrong — VXLAN provides overlay networking/encapsulation, not encryption by itself.",
            "Replaces the need for IP addressing entirely": "Wrong — VXLAN actually relies on IP (Layer 3) transport underneath its overlay; it doesn't eliminate IP addressing.",
            "Defines a physical cabling standard for data centers": "Wrong — VXLAN is a logical/software overlay protocol, unrelated to physical cabling standards.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is a SYN flood attack, and what is a common mitigation?",
        "options": [
            "An attack that sends many SYN packets without completing the handshake to exhaust server resources, commonly mitigated with SYN cookies",
            "An attack targeting DNS servers, commonly mitigated by rate-limiting HTTP requests",
            "An attack that exploits weak passwords, commonly mitigated with two-factor authentication",
            "An attack that floods the network with ICMP requests, commonly mitigated by disabling ping entirely",
        ],
        "correct_answer": "An attack that sends many SYN packets without completing the handshake to exhaust server resources, commonly mitigated with SYN cookies",
        "explanation_correct": "A SYN flood exploits the half-open connection state during the TCP handshake, exhausting server connection resources; SYN cookies let the server avoid allocating state until the handshake actually completes, mitigating the resource exhaustion.",
        "explanation_incorrect": {
            "An attack targeting DNS servers, commonly mitigated by rate-limiting HTTP requests": "Wrong — this describes an unrelated attack/mitigation pairing (DNS attacks and HTTP rate-limiting aren't the SYN flood scenario).",
            "An attack that exploits weak passwords, commonly mitigated with two-factor authentication": "Wrong — SYN floods are a network-layer resource exhaustion attack, entirely unrelated to password strength or authentication.",
            "An attack that floods the network with ICMP requests, commonly mitigated by disabling ping entirely": "Wrong — that describes a ping/ICMP flood, a different attack from a SYN flood, which specifically targets the TCP handshake.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of mTLS (mutual TLS)?",
        "options": [
            "Both the client and server authenticate each other using certificates, rather than only the server authenticating to the client",
            "It encrypts DNS traffic specifically, unrelated to general TLS connections",
            "It's used exclusively for VPN connections",
            "It requires no certificates at all, using passwords instead",
        ],
        "correct_answer": "Both the client and server authenticate each other using certificates, rather than only the server authenticating to the client",
        "explanation_correct": "In standard TLS, only the server presents a certificate for the client to verify; mTLS adds client-side certificate authentication as well, so both parties cryptographically verify each other's identity.",
        "explanation_incorrect": {
            "It encrypts DNS traffic specifically, unrelated to general TLS connections": "Wrong — mTLS is a general TLS authentication pattern applicable to any TLS-secured connection, not specifically DNS.",
            "It's used exclusively for VPN connections": "Wrong — mTLS is commonly used for service-to-service authentication (e.g. in microservices/service mesh setups), not just VPNs.",
            "It requires no certificates at all, using passwords instead": "Wrong — mTLS is specifically about certificate-based mutual authentication; it doesn't substitute passwords for certificates.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What does VRRP (Virtual Router Redundancy Protocol) provide?",
        "options": [
            "Automatic failover of a virtual gateway IP address between redundant routers",
            "Encryption for traffic passing between routers",
            "Load balancing between multiple web servers",
            "DNS-based failover for a domain name",
        ],
        "correct_answer": "Automatic failover of a virtual gateway IP address between redundant routers",
        "explanation_correct": "VRRP lets multiple routers share a virtual IP, with one acting as the active master; if it fails, another router automatically takes over the virtual IP, providing gateway-level high availability.",
        "explanation_incorrect": {
            "Encryption for traffic passing between routers": "Wrong — VRRP is about gateway redundancy/failover, not encrypting inter-router traffic.",
            "Load balancing between multiple web servers": "Wrong — that's the role of a load balancer, a different concern from gateway-level failover.",
            "DNS-based failover for a domain name": "Wrong — that describes a DNS failover mechanism (like Route 53 health checks), unrelated to VRRP's network-layer gateway redundancy.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of Path MTU Discovery?",
        "options": [
            "Determines the largest packet size that can traverse a network path without fragmentation",
            "Discovers every router along a network path",
            "Measures round-trip latency between two hosts",
            "Determines the fastest available DNS server",
        ],
        "correct_answer": "Determines the largest packet size that can traverse a network path without fragmentation",
        "explanation_correct": "Path MTU Discovery finds the smallest MTU along the route between two hosts, allowing senders to avoid fragmentation by sizing packets appropriately for the whole path.",
        "explanation_incorrect": {
            "Discovers every router along a network path": "Wrong — that's closer to what traceroute does; Path MTU Discovery is specifically about finding the maximum non-fragmenting packet size.",
            "Measures round-trip latency between two hosts": "Wrong — that's the role of tools like ping, unrelated to MTU discovery's purpose.",
            "Determines the fastest available DNS server": "Wrong — DNS server selection is unrelated to Path MTU Discovery, which concerns packet size along a network path.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is a key difference between anycast and unicast addressing?",
        "options": [
            "Anycast allows multiple servers to share the same IP address, with routing directing clients to the nearest/best instance",
            "Unicast allows multiple servers to share an IP address with no routing distinction between them",
            "Anycast is only ever used for DNS traffic",
            "Anycast requires IPv6 and cannot be used with IPv4",
        ],
        "correct_answer": "Anycast allows multiple servers to share the same IP address, with routing directing clients to the nearest/best instance",
        "explanation_correct": "With anycast, the same IP is advertised from multiple locations, and normal routing (typically based on path cost) directs a given client to whichever advertising instance is topologically closest or best.",
        "explanation_incorrect": {
            "Unicast allows multiple servers to share an IP address with no routing distinction between them": "Wrong — unicast addressing is specifically one-to-one (a single destination per address); sharing an address across multiple servers with routing-based selection is exactly what defines anycast, not unicast.",
            "Anycast is only ever used for DNS traffic": "Wrong — while anycast is famously used for root DNS servers, it's also used for CDNs and other latency-sensitive services, not exclusively DNS.",
            "Anycast requires IPv6 and cannot be used with IPv4": "Wrong — anycast works with both IPv4 and IPv6; it isn't an IPv6-exclusive feature.",
        },
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of LACP (Link Aggregation Control Protocol, 802.3ad) in network bonding?",
        "options": [
            "Dynamically negotiates and manages link aggregation between two devices, providing more robust failure detection than static bonding",
            "Encrypts traffic that flows across the bonded links",
            "Only works with a single physical network link",
            "Eliminates the need for network switches entirely",
        ],
        "correct_answer": "Dynamically negotiates and manages link aggregation between two devices, providing more robust failure detection than static bonding",
        "explanation_correct": "LACP allows two connected devices (e.g. a server and a switch) to dynamically negotiate which links participate in an aggregated bundle and detect link failures more reliably than a purely static bonding configuration.",
        "explanation_incorrect": {
            "Encrypts traffic that flows across the bonded links": "Wrong — LACP is about link negotiation and aggregation management, not encryption.",
            "Only works with a single physical network link": "Wrong — LACP's entire purpose is aggregating multiple physical links together, not operating on just one.",
            "Eliminates the need for network switches entirely": "Wrong — LACP is typically negotiated between a host and a switch; it doesn't remove switches from the topology.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ allows running sandboxed programs inside the Linux kernel for tasks like packet filtering and monitoring, without writing traditional kernel modules.",
        "options": None,
        "correct_answer": "eBPF",
        "explanation_correct": "eBPF (extended Berkeley Packet Filter) enables safe, high-performance in-kernel program execution.",
        "explanation_incorrect": "The blank should be filled with the name of this in-kernel sandboxed execution technology: eBPF.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ is a modern VPN protocol known for its small codebase, modern cryptography, and generally simpler configuration compared to IPSec or OpenVPN.",
        "options": None,
        "correct_answer": "WireGuard",
        "explanation_correct": "WireGuard is designed to be minimal, auditable, and performant compared to older VPN protocols.",
        "explanation_incorrect": "The blank should be filled with the name of this VPN protocol: WireGuard.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ (Equal-Cost Multi-Path) routing distributes traffic across multiple paths of equal routing cost.",
        "options": None,
        "correct_answer": "ECMP",
        "explanation_correct": "ECMP spreads traffic across multiple equally-costed routes, improving throughput and resilience.",
        "explanation_incorrect": "The blank should be filled with the acronym for this multi-path routing technique: ECMP.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ creates Layer 2 overlay networks on top of Layer 3 infrastructure, commonly used in virtualized and cloud environments.",
        "options": None,
        "correct_answer": "VXLAN",
        "explanation_correct": "VXLAN encapsulates Layer 2 frames inside Layer 3 UDP packets to create scalable overlay networks.",
        "explanation_incorrect": "The blank should be filled with the name of this overlay networking technology: VXLAN.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A SYN ____ attack sends many SYN packets without completing the TCP handshake, aiming to exhaust server resources.",
        "options": None,
        "correct_answer": "flood",
        "explanation_correct": "A SYN flood exploits half-open TCP connections to exhaust a server's connection resources.",
        "explanation_incorrect": "The blank should be filled with the term for this type of attack: flood.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ (mutual TLS) requires both the client and server to authenticate each other using certificates.",
        "options": None,
        "correct_answer": "mTLS",
        "explanation_correct": "mTLS extends standard TLS to require client-side certificate authentication as well as server-side.",
        "explanation_incorrect": "The blank should be filled with the acronym for this mutual authentication scheme: mTLS.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ (Virtual Router Redundancy Protocol) provides automatic failover of a virtual gateway IP between redundant routers.",
        "options": None,
        "correct_answer": "VRRP",
        "explanation_correct": "VRRP lets a backup router automatically take over a shared virtual gateway IP if the active router fails.",
        "explanation_incorrect": "The blank should be filled with the acronym for this gateway redundancy protocol: VRRP.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Path ____ Discovery determines the largest packet size that can traverse a network path without fragmentation.",
        "options": None,
        "correct_answer": "MTU",
        "explanation_correct": "Path MTU Discovery finds the smallest MTU along a route to avoid unnecessary fragmentation.",
        "explanation_incorrect": "The blank should be filled with the term this discovery process is about: MTU.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ addressing allows multiple servers to share the same IP address, with routing directing clients to the nearest or best instance.",
        "options": None,
        "correct_answer": "Anycast",
        "explanation_correct": "Anycast lets the same address be advertised from multiple locations, with normal routing selecting the closest instance.",
        "explanation_incorrect": "The blank should be filled with the name of this addressing scheme: Anycast.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "____ (802.3ad), used in network bonding, dynamically negotiates and manages link aggregation between two devices.",
        "options": None,
        "correct_answer": "LACP",
        "explanation_correct": "LACP (Link Aggregation Control Protocol) dynamically manages aggregated links between a host and switch.",
        "explanation_incorrect": "The blank should be filled with the acronym for this link aggregation protocol: LACP.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a WireGuard VPN connection.",
        "options": ["Bring the interface up with `wg-quick up wg0`", "Generate a private/public key pair with `wg genkey` and `wg pubkey`", "Configure the WireGuard interface with peer public keys and allowed IPs"],
        "correct_answer": '["Generate a private/public key pair with `wg genkey` and `wg pubkey`", "Configure the WireGuard interface with peer public keys and allowed IPs", "Bring the interface up with `wg-quick up wg0`"]',
        "explanation_correct": "Correct -- keys must exist before the interface configuration can reference them, and the configuration must be complete before the interface can be brought up.",
        "explanation_incorrect": "Keys must be generated before they can be referenced in the interface configuration, and that configuration must be in place before the interface is actually brought up.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up a GRE tunnel between two sites.",
        "options": ["Add a route directing relevant traffic through the tunnel", "Create the tunnel interface with `ip tunnel add gre1 mode gre remote ... local ...`", "Assign an IP address to the tunnel interface"],
        "correct_answer": '["Create the tunnel interface with `ip tunnel add gre1 mode gre remote ... local ...`", "Assign an IP address to the tunnel interface", "Add a route directing relevant traffic through the tunnel"]',
        "explanation_correct": "Correct -- the tunnel interface must exist before it can be addressed, and it must be addressed before routes can meaningfully direct traffic through it.",
        "explanation_incorrect": "The tunnel interface must be created before an address can be assigned to it, and addressing must be in place before routing traffic through it makes sense.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up outbound NAT with iptables MASQUERADE.",
        "options": ["Internal hosts can now reach the internet through the NAT gateway", "Enable IP forwarding with sysctl", "Add the MASQUERADE rule to the nat table's POSTROUTING chain"],
        "correct_answer": '["Enable IP forwarding with sysctl", "Add the MASQUERADE rule to the nat table\'s POSTROUTING chain", "Internal hosts can now reach the internet through the NAT gateway"]',
        "explanation_correct": "Correct -- IP forwarding must be enabled before the gateway will route traffic between interfaces at all, and the MASQUERADE rule must be in place before internal hosts can successfully reach the internet.",
        "explanation_incorrect": "IP forwarding must be enabled before any routing between interfaces happens, and the NAT rule must be configured before internal traffic can be correctly translated outbound.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for diagnosing and mitigating a SYN flood.",
        "options": ["Confirm the server remains responsive under the attack traffic", "Monitor for a high volume of half-open connections (SYN_RECV state)", "Enable SYN cookies via sysctl"],
        "correct_answer": '["Monitor for a high volume of half-open connections (SYN_RECV state)", "Enable SYN cookies via sysctl", "Confirm the server remains responsive under the attack traffic"]',
        "explanation_correct": "Correct -- the symptom must be observed before applying a mitigation, and confirming responsiveness is the final step validating that the mitigation actually worked.",
        "explanation_incorrect": "The problem pattern (excessive half-open connections) must be observed before the mitigation is applied, and verifying the outcome comes after that mitigation is in place.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up mTLS between a client and server.",
        "options": ["Configure the client to present its certificate during the TLS handshake", "Generate a certificate authority and issue certificates for both client and server", "Configure the server to require and verify client certificates"],
        "correct_answer": '["Generate a certificate authority and issue certificates for both client and server", "Configure the server to require and verify client certificates", "Configure the client to present its certificate during the TLS handshake"]',
        "explanation_correct": "Correct -- certificates must exist before either side can be configured to use them, and both the server's requirement and the client's presentation must be set up for the handshake to succeed.",
        "explanation_incorrect": "The CA and certificates must be issued before either side can be configured around them, with server-side enforcement and client-side presentation both needing to be in place.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for tuning socket buffer sizes for high-throughput connections.",
        "options": ["Persist the change in /etc/sysctl.conf for future boots", "Check current values with `sysctl net.core.rmem_max`", "Increase the value via sysctl for the current session"],
        "correct_answer": '["Check current values with `sysctl net.core.rmem_max`", "Increase the value via sysctl for the current session", "Persist the change in /etc/sysctl.conf for future boots"]',
        "explanation_correct": "Correct -- the current value should be checked before deciding on a new one, the immediate change is applied first, and persistence to survive reboots is the final step.",
        "explanation_incorrect": "Checking the current value provides a baseline before changing it, the immediate runtime change is applied next, and persisting it for future boots is the final step.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up VRRP-based gateway redundancy with keepalived.",
        "options": ["The higher-priority router becomes active, holding the virtual IP, with automatic failover if it goes down", "Configure keepalived on two routers with the same virtual IP and a priority for each", "Start keepalived on both routers"],
        "correct_answer": '["Configure keepalived on two routers with the same virtual IP and a priority for each", "Start keepalived on both routers", "The higher-priority router becomes active, holding the virtual IP, with automatic failover if it goes down"]',
        "explanation_correct": "Correct -- configuration must be in place before keepalived can be started, and the active/backup election (and resulting failover behavior) only happens once both instances are actually running.",
        "explanation_incorrect": "Configuration must be defined before the keepalived service can be started with it, and the election of an active router happens only after both instances are running.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for troubleshooting an MTU-related connectivity issue.",
        "options": ["Adjust the interface or tunnel MTU based on the discovered limit", "Notice large packets failing while small ones succeed", "Test with `ping -M do -s <size> <host>` to find the maximum non-fragmenting packet size"],
        "correct_answer": '["Notice large packets failing while small ones succeed", "Test with `ping -M do -s <size> <host>` to find the maximum non-fragmenting packet size", "Adjust the interface or tunnel MTU based on the discovered limit"]',
        "explanation_correct": "Correct -- the symptom must be observed before targeted testing begins, and adjusting the MTU only makes sense once the actual limit has been discovered through testing.",
        "explanation_incorrect": "The symptom (large packets failing) must be noticed before running specific size-testing, and the MTU adjustment should be based on what that testing actually reveals.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for inspecting a server's TLS configuration with openssl.",
        "options": ["Compare against expected/required TLS configuration standards", "Run `openssl s_client -connect example.com:443` to connect and view the certificate/cipher details", "Review the offered certificate chain and cipher suite"],
        "correct_answer": '["Run `openssl s_client -connect example.com:443` to connect and view the certificate/cipher details", "Review the offered certificate chain and cipher suite", "Compare against expected/required TLS configuration standards"]',
        "explanation_correct": "Correct -- the connection must be made before there's anything to review, and comparison against a standard is the final analytical step once the actual configuration is known.",
        "explanation_incorrect": "The openssl connection must be established before its output can be reviewed, and comparing against expected standards only makes sense once the actual configuration is known.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for setting up 802.3ad (LACP) bonding between two NICs.",
        "options": ["Verify the bond becomes active by checking `cat /proc/net/bonding/bond0`", "Configure both NICs as members of a bond interface using mode 802.3ad", "Ensure the connected switch ports are also configured for LACP"],
        "correct_answer": '["Configure both NICs as members of a bond interface using mode 802.3ad", "Ensure the connected switch ports are also configured for LACP", "Verify the bond becomes active by checking `cat /proc/net/bonding/bond0`"]',
        "explanation_correct": "Correct -- the host-side bond must be configured before matching switch-side configuration is meaningful, and verification is the final step confirming both sides negotiated successfully.",
        "explanation_incorrect": "The host bonding configuration should be set up, matching switch-side LACP configuration is needed for the negotiation to succeed, and verification comes last to confirm it worked.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for verifying eBPF programs are loaded and functioning.",
        "options": ["Check its associated statistics or logs to confirm it's functioning as expected", "Run `bpftool prog show` to list loaded eBPF programs", "Identify the specific program relevant to the task at hand"],
        "correct_answer": '["Run `bpftool prog show` to list loaded eBPF programs", "Identify the specific program relevant to the task at hand", "Check its associated statistics or logs to confirm it\'s functioning as expected"]',
        "explanation_correct": "Correct -- the list of loaded programs must be retrieved before a specific one can be identified, and checking its behavior comes only after that program has been identified.",
        "explanation_incorrect": "Loaded programs must be listed before a specific one can be identified within that list, and checking its function is the final step once it's been identified.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for enabling and persisting tcp_tw_reuse.",
        "options": ["Monitor connection reuse behavior to confirm the change took effect", "Run `sysctl -w net.ipv4.tcp_tw_reuse=1` to enable it", "Persist the setting in /etc/sysctl.conf"],
        "correct_answer": '["Run `sysctl -w net.ipv4.tcp_tw_reuse=1` to enable it", "Persist the setting in /etc/sysctl.conf", "Monitor connection reuse behavior to confirm the change took effect"]',
        "explanation_correct": "Correct -- the immediate runtime change comes first, persisting it for future boots follows, and monitoring the effect is the final verification step.",
        "explanation_incorrect": "The immediate change should be applied first, persisting it comes next, and monitoring for the expected behavioral change is a reasonable final step.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up VXLAN overlay networking between two hosts.",
        "options": ["Verify connectivity between hosts across the overlay", "Create a VXLAN interface specifying a VNI (VXLAN Network Identifier) and remote endpoint", "Assign an IP address within the overlay network to the VXLAN interface"],
        "correct_answer": '["Create a VXLAN interface specifying a VNI (VXLAN Network Identifier) and remote endpoint", "Assign an IP address within the overlay network to the VXLAN interface", "Verify connectivity between hosts across the overlay"]',
        "explanation_correct": "Correct -- the VXLAN interface must exist before it can be addressed, and connectivity can only be verified once addressing is in place on both ends.",
        "explanation_incorrect": "The VXLAN interface must be created before it can be assigned an address, and connectivity verification is the final step once addressing is configured.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for confirming ECMP routing is active across two equal-cost paths.",
        "options": ["Observe traffic being distributed across both paths", "Confirm two routes of equal metric exist to the same destination", "Verify the kernel is configured to use multipath routing (`ip route show` displaying multiple nexthops)"],
        "correct_answer": '["Confirm two routes of equal metric exist to the same destination", "Verify the kernel is configured to use multipath routing (`ip route show` displaying multiple nexthops)", "Observe traffic being distributed across both paths"]',
        "explanation_correct": "Correct -- the equal-cost routes must exist before multipath configuration can be confirmed against them, and observing actual traffic distribution is the final practical validation.",
        "explanation_incorrect": "Equal-cost routes must exist before multipath behavior can be confirmed, and observing traffic distribution is the final step validating the whole setup works in practice.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for detecting potential ARP spoofing on a network.",
        "options": ["Investigate or isolate the source of the suspicious ARP traffic", "Monitor the ARP table for unexpected or rapidly changing IP-to-MAC mappings", "Cross-reference suspicious entries against known legitimate device MAC addresses"],
        "correct_answer": '["Monitor the ARP table for unexpected or rapidly changing IP-to-MAC mappings", "Cross-reference suspicious entries against known legitimate device MAC addresses", "Investigate or isolate the source of the suspicious ARP traffic"]',
        "explanation_correct": "Correct -- suspicious mappings must be observed before they can be cross-referenced, and investigation/isolation follows once a mapping is confirmed suspicious.",
        "explanation_incorrect": "Anomalous ARP entries must first be noticed before they can be cross-checked against known devices, and taking action follows once suspicion is confirmed.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for configuring a custom iptables chain for organized rule management.",
        "options": ["Jump to the custom chain from an existing chain (e.g. INPUT) using `-j MYCHAIN`", "Create a new custom chain with `iptables -N MYCHAIN`", "Add rules to the custom chain"],
        "correct_answer": '["Create a new custom chain with `iptables -N MYCHAIN`", "Add rules to the custom chain", "Jump to the custom chain from an existing chain (e.g. INPUT) using `-j MYCHAIN`"]',
        "explanation_correct": "Correct -- the custom chain must exist before rules can be added to it, and it must have rules before it's useful to jump traffic into it from an existing chain.",
        "explanation_incorrect": "The chain must be created before rules can be added to it, and jumping traffic into it from another chain only makes sense once it actually has rules defined.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for testing anycast-style routing behavior in a simplified lab setup.",
        "options": ["Confirm clients are routed to the topologically nearest instance", "Configure the same IP address on multiple servers in different locations", "Advertise routes to that address from each location"],
        "correct_answer": '["Configure the same IP address on multiple servers in different locations", "Advertise routes to that address from each location", "Confirm clients are routed to the topologically nearest instance"]',
        "explanation_correct": "Correct -- the shared address must be configured on the servers before routes can be advertised for it, and observing near-instance routing is the final validation step.",
        "explanation_incorrect": "The address must be configured on the servers before routes advertising it make sense, and confirming client routing behavior is the final step once advertisement is active.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for setting up IPSec tunnel-mode encryption between two gateways.",
        "options": ["Verify the tunnel establishes and encrypted traffic flows between the gateways", "Configure IKE (Internet Key Exchange) parameters on both gateways for key negotiation", "Define the IPSec policy specifying which traffic should be encrypted"],
        "correct_answer": '["Configure IKE (Internet Key Exchange) parameters on both gateways for key negotiation", "Define the IPSec policy specifying which traffic should be encrypted", "Verify the tunnel establishes and encrypted traffic flows between the gateways"]',
        "explanation_correct": "Correct -- key negotiation parameters must be configured before a policy relying on that negotiated session can be defined, and verification is the final step confirming the whole setup works.",
        "explanation_incorrect": "IKE parameters must be configured before the IPSec policy can rely on the resulting negotiated keys, and verification is the natural final step once both are in place.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for diagnosing whether NAT is correctly translating traffic, using conntrack.",
        "options": ["Confirm the translation matches the expected NAT rule behavior", "Run `conntrack -L` to see tracked connections including their translated addresses", "Compare the original and translated (NAT'd) address/port shown for a given connection"],
        "correct_answer": '["Run `conntrack -L` to see tracked connections including their translated addresses", "Compare the original and translated (NAT\'d) address/port shown for a given connection", "Confirm the translation matches the expected NAT rule behavior"]',
        "explanation_correct": "Correct -- the tracked connection data must be retrieved before specific address translations can be compared, and confirming correctness is the final analytical step.",
        "explanation_incorrect": "The conntrack data must be retrieved before individual translations can be compared, and confirming they match expectations is the final step of the analysis.",
    },
    {
        "topic": "Networking", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for load testing an HTTP endpoint while monitoring connection reuse.",
        "options": ["Compare performance against a test with keep-alive disabled", "Send repeated requests using HTTP keep-alive enabled", "Monitor `ss -tan` to observe connections remaining in ESTABLISHED state rather than being torn down repeatedly"],
        "correct_answer": '["Send repeated requests using HTTP keep-alive enabled", "Monitor `ss -tan` to observe connections remaining in ESTABLISHED state rather than being torn down repeatedly", "Compare performance against a test with keep-alive disabled"]',
        "explanation_correct": "Correct -- the keep-alive test must run before its connection behavior can be observed, and a comparative test against keep-alive-disabled behavior is the final step for meaningful comparison.",
        "explanation_incorrect": "Requests must be sent before connection state can be observed via ss, and the comparison against a disabled-keep-alive baseline is the final analytical step.",
    },
]
