"""
Python - Medium batch, 50 questions total.
Distribution: 30 coding, 8 mcq, 6 fill-in-blank, 3 drag-and-drop, 3 dropdown-order.

Schema matches python_easy.py — see that file's header for full field notes.
"""

PYTHON_MEDIUM_QUESTIONS = [

    # ---------------- CODING (30) ----------------

    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `binary_search(lst, target)` that returns the index of target in a sorted list, or -1 if not found, using binary search (not linear search).",
        "correct_answer": "def binary_search(lst, target):\n    low, high = 0, len(lst) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if lst[mid] == target:\n            return mid\n        elif lst[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
        "explanation_correct": "Correct — this repeatedly halves the search range based on comparisons with the midpoint, achieving O(log n) search.",
        "explanation_incorrect": "A correct solution must use a divide-and-conquer approach (halving the search space each step), not a simple linear scan, and must return -1 when the target isn't present.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `is_balanced(s)` that returns True if a string of brackets `()[]{}` is balanced (every opening bracket has a matching closing bracket in the correct order).",
        "correct_answer": "def is_balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for c in s:\n        if c in '([{':\n            stack.append(c)\n        elif c in pairs:\n            if not stack or stack.pop() != pairs[c]:\n                return False\n    return not stack",
        "explanation_correct": "Correct — using a stack to track open brackets and matching each closer against the most recent opener correctly validates nesting and order.",
        "explanation_incorrect": "A correct solution must use a stack-like approach to ensure brackets close in the right order and that none are left unmatched.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `group_by_length(words)` that returns a dictionary mapping word length to a list of words of that length.",
        "correct_answer": "def group_by_length(words):\n    result = {}\n    for word in words:\n        result.setdefault(len(word), []).append(word)\n    return result",
        "explanation_correct": "Correct — using setdefault() to initialize each length's list on first use correctly groups every word by its length.",
        "explanation_incorrect": "A correct solution must produce a dict keyed by word length, where each value is a list of all words of that length.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `deep_flatten(lst)` that fully flattens an arbitrarily nested list of lists into a single flat list, e.g. [1, [2, [3, 4], 5]] -> [1, 2, 3, 4, 5].",
        "correct_answer": "def deep_flatten(lst):\n    result = []\n    for item in lst:\n        if isinstance(item, list):\n            result.extend(deep_flatten(item))\n        else:\n            result.append(item)\n    return result",
        "explanation_correct": "Correct — recursively flattening any nested list items, at any depth, correctly produces a fully flat list.",
        "explanation_incorrect": "A correct solution must handle nesting at arbitrary depth, not just one level (a plain single-level flatten with extend() alone is insufficient here).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `most_common_word(text)` that returns the most frequently occurring word in a string (words separated by whitespace, case-insensitive).",
        "correct_answer": "from collections import Counter\n\ndef most_common_word(text):\n    words = text.lower().split()\n    return Counter(words).most_common(1)[0][0]",
        "explanation_correct": "Correct — lowercasing and splitting the text, then using Counter to tally occurrences, correctly finds the most frequent word.",
        "explanation_incorrect": "A correct solution must count word frequencies case-insensitively and return the word with the highest count.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `chunk_list(lst, n)` that splits a list into chunks (sublists) of size n, with the last chunk possibly shorter.",
        "correct_answer": "def chunk_list(lst, n):\n    return [lst[i:i + n] for i in range(0, len(lst), n)]",
        "explanation_correct": "Correct — slicing the list in steps of n produces consecutive chunks, with the final slice naturally shorter if the list doesn't divide evenly.",
        "explanation_incorrect": "A correct solution must return a list of sublists, each of length n (except possibly the last), covering every element in order.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `memoized_fib(n)` that computes the nth Fibonacci number using memoization (caching previously computed results) to avoid redundant recursive calls.",
        "correct_answer": "def memoized_fib(n, cache={}):\n    if n in cache:\n        return cache[n]\n    if n <= 1:\n        return n\n    cache[n] = memoized_fib(n - 1, cache) + memoized_fib(n - 2, cache)\n    return cache[n]",
        "explanation_correct": "Correct — storing already-computed Fibonacci values in a cache and checking it before recursing avoids the exponential blowup of naive recursion.",
        "explanation_incorrect": "A correct solution must cache intermediate results so repeated subproblems aren't recomputed — plain unmemoized recursion is not sufficient here.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a decorator `log_call` that prints \"Calling <function name>\" before the decorated function runs, then calls and returns the function's result.",
        "correct_answer": "def log_call(func):\n    def wrapper(*args, **kwargs):\n        print(f\"Calling {func.__name__}\")\n        return func(*args, **kwargs)\n    return wrapper",
        "explanation_correct": "Correct — the wrapper prints the log message, then forwards all arguments to the original function and returns its result, preserving normal call behavior.",
        "explanation_incorrect": "A correct solution must return a wrapper function that prints the log message, calls the original function with any arguments passed to it, and returns its result.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a generator function `count_up_to(n)` that yields integers from 1 up to and including n.",
        "correct_answer": "def count_up_to(n):\n    for i in range(1, n + 1):\n        yield i",
        "explanation_correct": "Correct — using `yield` inside the loop makes this a generator that lazily produces 1 through n.",
        "explanation_incorrect": "A correct solution must be a generator (using yield) that produces each integer from 1 to n inclusive, one at a time.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `two_sum(lst, target)` that returns a list of index pairs (i, j) where lst[i] + lst[j] == target and i < j.",
        "correct_answer": "def two_sum(lst, target):\n    result = []\n    for i in range(len(lst)):\n        for j in range(i + 1, len(lst)):\n            if lst[i] + lst[j] == target:\n                result.append((i, j))\n    return result",
        "explanation_correct": "Correct — checking every pair of indices with i < j and comparing their sum to the target finds all valid pairs.",
        "explanation_incorrect": "A correct solution must find all pairs of indices (not just one) whose values sum to the target, without pairing an index with itself.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `rotate_list(lst, k)` that rotates a list to the right by k positions, e.g. rotate_list([1,2,3,4,5], 2) -> [4,5,1,2,3].",
        "correct_answer": "def rotate_list(lst, k):\n    if not lst:\n        return lst\n    k = k % len(lst)\n    return lst[-k:] + lst[:-k] if k else lst",
        "explanation_correct": "Correct — taking the last k elements and placing them in front of the remaining elements correctly rotates the list to the right, and using modulo handles k values larger than the list length.",
        "explanation_incorrect": "A correct solution must handle k being larger than the list length (via modulo) and correctly move the last k elements to the front.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `find_duplicates(lst)` that returns a list of the values that appear more than once in the input list (each duplicate value listed once).",
        "correct_answer": "def find_duplicates(lst):\n    seen = set()\n    dupes = set()\n    for item in lst:\n        if item in seen:\n            dupes.add(item)\n        else:\n            seen.add(item)\n    return list(dupes)",
        "explanation_correct": "Correct — tracking already-seen items and adding to a separate duplicates set on a repeat correctly identifies every value that occurs more than once.",
        "explanation_incorrect": "A correct solution must return each value that appears 2+ times exactly once in the output, not once per repeated occurrence.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `caesar_cipher(s, shift)` that shifts each letter in s by `shift` positions in the alphabet, wrapping around, and preserves case and non-letter characters unchanged.",
        "correct_answer": "def caesar_cipher(s, shift):\n    result = []\n    for c in s:\n        if c.isupper():\n            result.append(chr((ord(c) - 65 + shift) % 26 + 65))\n        elif c.islower():\n            result.append(chr((ord(c) - 97 + shift) % 26 + 97))\n        else:\n            result.append(c)\n    return ''.join(result)",
        "explanation_correct": "Correct — shifting within the correct alphabet range (uppercase or lowercase) with wraparound via modulo 26, while leaving non-letters untouched, matches a standard Caesar cipher.",
        "explanation_incorrect": "A correct solution must wrap around the alphabet (e.g. 'z' shifted by 1 becomes 'a'), preserve the original case, and leave non-letter characters unchanged.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `flatten_dict(d, parent_key='')` that flattens a nested dictionary into a single-level dictionary with dot-separated keys, e.g. {'a': {'b': 1}} -> {'a.b': 1}.",
        "correct_answer": "def flatten_dict(d, parent_key=''):\n    items = {}\n    for k, v in d.items():\n        new_key = f\"{parent_key}.{k}\" if parent_key else k\n        if isinstance(v, dict):\n            items.update(flatten_dict(v, new_key))\n        else:\n            items[new_key] = v\n    return items",
        "explanation_correct": "Correct — recursively descending into nested dicts and building dot-joined key paths correctly flattens the structure to one level.",
        "explanation_incorrect": "A correct solution must handle dictionaries nested at any depth, joining keys with a dot to represent the original path.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `is_subsequence(s, t)` that returns True if string s is a subsequence of string t (s's characters appear in t in the same relative order, not necessarily contiguous).",
        "correct_answer": "def is_subsequence(s, t):\n    it = iter(t)\n    return all(c in it for c in s)",
        "explanation_correct": "Correct — this idiom advances through the iterator of t as each character of s is matched, correctly checking subsequence order without requiring contiguity.",
        "explanation_incorrect": "A correct solution must confirm the characters of s appear in t in the same order, but they don't need to be adjacent in t.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `top_n(lst, n)` that returns the n largest values from a list, sorted in descending order.",
        "correct_answer": "def top_n(lst, n):\n    return sorted(lst, reverse=True)[:n]",
        "explanation_correct": "Correct — sorting descending and taking the first n elements correctly returns the n largest values, in descending order.",
        "explanation_incorrect": "A correct solution must return exactly n values (or fewer if the list is shorter), representing the largest values in the list, sorted from largest to smallest.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `word_frequencies(text)` that returns a dictionary of word counts from a string, case-insensitive, ignoring basic punctuation (.,!?).",
        "correct_answer": "import string\n\ndef word_frequencies(text):\n    cleaned = ''.join(c for c in text.lower() if c not in string.punctuation)\n    counts = {}\n    for word in cleaned.split():\n        counts[word] = counts.get(word, 0) + 1\n    return counts",
        "explanation_correct": "Correct — stripping punctuation and lowercasing before splitting and counting ensures words are compared consistently regardless of case or trailing punctuation.",
        "explanation_incorrect": "A correct solution must normalize case and strip out common punctuation before counting, so 'Word.' and 'word' are counted as the same word.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `matrix_transpose(matrix)` that returns the transpose of a 2D list (rows become columns), e.g. [[1,2,3],[4,5,6]] -> [[1,4],[2,5],[3,6]].",
        "correct_answer": "def matrix_transpose(matrix):\n    return [list(row) for row in zip(*matrix)]",
        "explanation_correct": "Correct — unpacking the matrix's rows into zip() pairs up elements at the same column index across all rows, producing the transposed rows.",
        "explanation_incorrect": "A correct solution must swap rows and columns so that the element at [i][j] in the input ends up at [j][i] in the output.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `safe_divide(a, b)` that returns a divided by b, or None if b is zero (do not let the function raise an exception).",
        "correct_answer": "def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None",
        "explanation_correct": "Correct — wrapping the division in a try/except that catches ZeroDivisionError and returns None avoids letting the exception propagate.",
        "explanation_incorrect": "A correct solution must catch the division-by-zero case (via try/except or an explicit check) and return None instead of raising.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a class `Stack` with methods `push(item)`, `pop()` (removes and returns the top item), `peek()` (returns the top item without removing it), and `is_empty()` (returns True if the stack has no items).",
        "correct_answer": "class Stack:\n    def __init__(self):\n        self.items = []\n\n    def push(self, item):\n        self.items.append(item)\n\n    def pop(self):\n        return self.items.pop()\n\n    def peek(self):\n        return self.items[-1]\n\n    def is_empty(self):\n        return len(self.items) == 0",
        "explanation_correct": "Correct — using a list as internal storage, with append/pop for push/pop and indexing the last item for peek, correctly implements standard LIFO stack behavior.",
        "explanation_incorrect": "A correct solution must implement all four methods with standard LIFO (last-in, first-out) behavior — pop() and peek() should both operate on the most recently pushed item.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `binary_to_decimal(b)` that converts a string of binary digits (e.g. '1011') to its decimal integer value, without using int(b, 2).",
        "correct_answer": "def binary_to_decimal(b):\n    result = 0\n    for digit in b:\n        result = result * 2 + int(digit)\n    return result",
        "explanation_correct": "Correct — processing digits left to right, doubling the running total and adding each new bit, correctly reconstructs the decimal value.",
        "explanation_incorrect": "A correct solution must compute the decimal value manually (e.g. by processing bits and applying powers of two), not by calling int(b, 2) directly.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `run_length_encode(s)` that compresses a string using run-length encoding, e.g. 'aaabbc' -> '3a2b1c'.",
        "correct_answer": "def run_length_encode(s):\n    if not s:\n        return ''\n    result = []\n    count = 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1]:\n            count += 1\n        else:\n            result.append(f\"{count}{s[i - 1]}\")\n            count = 1\n    result.append(f\"{count}{s[-1]}\")\n    return ''.join(result)",
        "explanation_correct": "Correct — tracking consecutive runs of the same character and appending the count followed by the character correctly produces run-length encoding.",
        "explanation_incorrect": "A correct solution must group consecutive identical characters and represent each group as a count followed by the character, in the original order.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `merge_sorted_lists(a, b)` that merges two already-sorted lists into a single sorted list.",
        "correct_answer": "def merge_sorted_lists(a, b):\n    result = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            result.append(a[i])\n            i += 1\n        else:\n            result.append(b[j])\n            j += 1\n    result.extend(a[i:])\n    result.extend(b[j:])\n    return result",
        "explanation_correct": "Correct — advancing through both lists together and always taking the smaller current element, then appending any leftover tail, correctly merges two sorted lists in O(n) time.",
        "explanation_incorrect": "A correct solution should merge in linear time by comparing the two lists' current elements (concatenating and calling sorted() works too, but doesn't take advantage of the inputs already being sorted).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `find_missing_number(lst)` where lst contains n distinct integers from 0 to n (inclusive) with exactly one missing — return the missing number.",
        "correct_answer": "def find_missing_number(lst):\n    n = len(lst)\n    expected_sum = n * (n + 1) // 2\n    return expected_sum - sum(lst)",
        "explanation_correct": "Correct — the sum of 0..n has a known formula; subtracting the actual sum of the list from that expected sum isolates the missing value.",
        "explanation_incorrect": "A correct solution must correctly identify the single missing integer from the range 0 to n, given that the list has n elements (one is missing from n+1 possible values).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `group_anagrams(words)` that groups a list of words into lists of anagrams, returning a list of these groups.",
        "correct_answer": "def group_anagrams(words):\n    groups = {}\n    for word in words:\n        key = ''.join(sorted(word))\n        groups.setdefault(key, []).append(word)\n    return list(groups.values())",
        "explanation_correct": "Correct — using the sorted letters of each word as a grouping key ensures all anagrams map to the same key and end up in the same group.",
        "explanation_incorrect": "A correct solution must group all words that are anagrams of each other together, and return each group as a separate list.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `apply_discount(prices, discount)` that returns a new list of prices with the discount (a decimal like 0.2 for 20%) applied and each result rounded to 2 decimal places.",
        "correct_answer": "def apply_discount(prices, discount):\n    return [round(p * (1 - discount), 2) for p in prices]",
        "explanation_correct": "Correct — multiplying each price by (1 - discount) applies the percentage reduction, and round() to 2 places matches typical currency formatting.",
        "explanation_incorrect": "A correct solution must reduce each price by the given discount fraction and round the result to 2 decimal places.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `moving_average(lst, window)` that returns a list of the moving averages of lst using the given window size, e.g. moving_average([1,2,3,4], 2) -> [1.5, 2.5, 3.5].",
        "correct_answer": "def moving_average(lst, window):\n    return [sum(lst[i:i + window]) / window for i in range(len(lst) - window + 1)]",
        "explanation_correct": "Correct — sliding a window of the given size across the list and averaging each window correctly produces the moving average sequence.",
        "explanation_incorrect": "A correct solution must return one average per valid window position, where each average covers `window` consecutive elements.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `validate_password(pw)` that returns True if pw is at least 8 characters long and contains at least one digit, one uppercase letter, and one lowercase letter.",
        "correct_answer": "def validate_password(pw):\n    if len(pw) < 8:\n        return False\n    has_digit = any(c.isdigit() for c in pw)\n    has_upper = any(c.isupper() for c in pw)\n    has_lower = any(c.islower() for c in pw)\n    return has_digit and has_upper and has_lower",
        "explanation_correct": "Correct — checking length and independently confirming the presence of at least one digit, uppercase letter, and lowercase letter correctly enforces all the stated rules.",
        "explanation_incorrect": "A correct solution must enforce all four conditions together: minimum length of 8, and at least one digit, one uppercase, and one lowercase character.",
        "options": None,
    },

    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `custom_zip(list1, list2)` that mimics the built-in zip() for exactly two lists, returning a list of tuples pairing elements at the same index (stop at the shorter list's length).",
        "correct_answer": "def custom_zip(list1, list2):\n    result = []\n    for i in range(min(len(list1), len(list2))):\n        result.append((list1[i], list2[i]))\n    return result",
        "explanation_correct": "Correct — iterating up to the shorter list's length and pairing elements at each index correctly replicates zip()'s behavior for two lists.",
        "explanation_incorrect": "A correct solution must pair elements at matching indices and stop once the shorter list is exhausted, without raising an index error on the longer list.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "coding",
        "prompt": "Write a function `flatten_and_sum(lst)` that takes an arbitrarily nested list of numbers and returns the sum of all numbers at every depth.",
        "correct_answer": "def flatten_and_sum(lst):\n    total = 0\n    for item in lst:\n        if isinstance(item, list):\n            total += flatten_and_sum(item)\n        else:\n            total += item\n    return total",
        "explanation_correct": "Correct — recursing into nested lists and accumulating a running total across all depths correctly sums every number regardless of nesting level.",
        "explanation_incorrect": "A correct solution must handle lists nested at any depth, summing every numeric value found, not just the top-level ones.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the list comprehension `[x for x in range(10) if x % 2 == 0]` produce?",
        "options": ["[0, 2, 4, 6, 8]", "[1, 3, 5, 7, 9]", "[0, 1, 2, ..., 9]", "[2, 4, 6, 8, 10]"],
        "correct_answer": "[0, 2, 4, 6, 8]",
        "explanation_correct": "The comprehension filters range(10) — which is 0 through 9 — down to only the even values, giving [0, 2, 4, 6, 8].",
        "explanation_incorrect": {
            "[1, 3, 5, 7, 9]": "Wrong — this is the odd numbers; the condition `x % 2 == 0` keeps evens, not odds.",
            "[0, 1, 2, ..., 9]": "Wrong — this ignores the `if` condition entirely; the filter removes the odd numbers.",
            "[2, 4, 6, 8, 10]": "Wrong — 10 is not included because range(10) stops before 10, and this list is also missing 0.",
        },
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the output of `print(*[1, 2, 3], sep='-')`?",
        "options": ["1-2-3", "[1, 2, 3]", "1 2 3", "'1-2-3'"],
        "correct_answer": "1-2-3",
        "explanation_correct": "The `*` unpacks the list into separate positional arguments to print(), and `sep='-'` joins them with a hyphen instead of the default space.",
        "explanation_incorrect": {
            "[1, 2, 3]": "Wrong — the `*` unpacks the list rather than printing it as a single list object.",
            "1 2 3": "Wrong — that would be the output without a custom sep, but sep='-' overrides the default space separator.",
            "'1-2-3'": "Wrong — print() outputs raw text without surrounding quotes.",
        },
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the first tuple produced by `enumerate(['a', 'b'], start=1)`?",
        "options": ["(1, 'a')", "(0, 'a')", "('a', 1)", "(1, 'b')"],
        "correct_answer": "(1, 'a')",
        "explanation_correct": "The `start=1` argument makes enumerate begin counting at 1, so the first item 'a' is paired with index 1.",
        "explanation_incorrect": {
            "(0, 'a')": "Wrong — that would be the result without start=1; the default start index is 0.",
            "('a', 1)": "Wrong — enumerate() yields (index, value) pairs, not (value, index).",
            "(1, 'b')": "Wrong — 'a' is the first element of the list, so it's paired with the first index, not 'b'.",
        },
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "What defines a generator function in Python?",
        "options": [
            "It uses the `yield` keyword instead of (or in addition to) `return`",
            "It is defined with the `gen` keyword",
            "It must return a list",
            "It cannot accept arguments",
        ],
        "correct_answer": "It uses the `yield` keyword instead of (or in addition to) `return`",
        "explanation_correct": "Any function containing a `yield` statement becomes a generator function, producing values lazily one at a time when iterated.",
        "explanation_incorrect": {
            "It is defined with the `gen` keyword": "Wrong — `gen` is not a Python keyword; generators are identified by the presence of `yield`.",
            "It must return a list": "Wrong — generators produce values one at a time via yield; they don't need to build or return a list at all.",
            "It cannot accept arguments": "Wrong — generator functions can accept arguments just like regular functions.",
        },
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `functools.reduce(lambda x, y: x + y, [1, 2, 3, 4])` return?",
        "options": ["10", "24", "[1, 2, 3, 4]", "4"],
        "correct_answer": "10",
        "explanation_correct": "reduce() applies the function cumulatively: ((1+2)+3)+4 = 10.",
        "explanation_incorrect": {
            "24": "Wrong — that would be the result of multiplying the numbers together, but the lambda here adds them.",
            "[1, 2, 3, 4]": "Wrong — reduce() collapses the iterable to a single accumulated value, not a list.",
            "4": "Wrong — that's just the last element; reduce() combines all elements, not just the final one.",
        },
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "Which syntax correctly applies a decorator named `my_decorator` to a function `greet`?",
        "options": [
            "@my_decorator\ndef greet():\n    pass",
            "def greet():\n    pass\n@my_decorator",
            "greet = decorator(my_decorator)",
            "def greet() @my_decorator:\n    pass",
        ],
        "correct_answer": "@my_decorator\ndef greet():\n    pass",
        "explanation_correct": "The `@decorator_name` syntax placed immediately above a function definition is the standard way to apply a decorator in Python.",
        "explanation_incorrect": {
            "def greet():\n    pass\n@my_decorator": "Wrong — the `@decorator` line must come before the function definition, not after it.",
            "greet = decorator(my_decorator)": "Wrong — this has the arguments backwards; it should be `greet = my_decorator(greet)`, which is exactly what the @ syntax does automatically.",
            "def greet() @my_decorator:\n    pass": "Wrong — this is not valid Python syntax; the decorator can't be placed inline in the function signature.",
        },
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `*args` allow a function to accept?",
        "options": [
            "A variable number of positional arguments",
            "A variable number of keyword arguments only",
            "Exactly one argument named 'args'",
            "No arguments at all",
        ],
        "correct_answer": "A variable number of positional arguments",
        "explanation_correct": "`*args` collects any number of extra positional arguments passed to the function into a tuple.",
        "explanation_incorrect": {
            "A variable number of keyword arguments only": "Wrong — that describes `**kwargs`, not `*args`.",
            "Exactly one argument named 'args'": "Wrong — `args` is just a conventional name; `*args` collects any number of positional arguments, not exactly one.",
            "No arguments at all": "Wrong — `*args` exists specifically to accept additional arguments.",
        },
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "mcq",
        "prompt": "What does `{k: v for k, v in zip(['a', 'b'], [1, 2])}` evaluate to?",
        "options": ["{'a': 1, 'b': 2}", "[('a', 1), ('b', 2)]", "{'1': 'a', '2': 'b'}", "{'a': 'b', 1: 2}"],
        "correct_answer": "{'a': 1, 'b': 2}",
        "explanation_correct": "zip() pairs up the two lists element-wise, and the dict comprehension turns each (key, value) pair into a dictionary entry.",
        "explanation_incorrect": {
            "[('a', 1), ('b', 2)]": "Wrong — that's what list(zip(...)) alone would give; wrapping it in a dict comprehension produces a dictionary, not a list of tuples.",
            "{'1': 'a', '2': 'b'}": "Wrong — the keys and values are reversed here, and zip() doesn't convert numbers to strings.",
            "{'a': 'b', 1: 2}": "Wrong — this incorrectly mixes elements across the two lists rather than pairing them positionally.",
        },
    },

    # ---------------- FILL-IN-BLANK (6) ----------------

    {
        "topic": "Python", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ keyword is used inside a function body to make that function a generator.",
        "options": None,
        "correct_answer": "yield",
        "explanation_correct": "Including `yield` anywhere in a function's body makes it a generator function.",
        "explanation_incorrect": "The blank should be filled with the keyword that turns a function into a generator: yield.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A parameter prefixed with two asterisks, conventionally named ____, collects an arbitrary number of keyword arguments into a dictionary.",
        "options": None,
        "correct_answer": "kwargs",
        "explanation_correct": "By convention, `**kwargs` is used to gather extra keyword arguments into a dictionary named kwargs.",
        "explanation_incorrect": "The blank should be filled with the conventional name for the double-asterisk keyword-argument parameter: kwargs.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The functools decorator ____ automatically caches a function's return values based on its arguments.",
        "options": None,
        "correct_answer": "lru_cache",
        "explanation_correct": "`functools.lru_cache` memoizes function calls, returning cached results for previously seen arguments.",
        "explanation_incorrect": "The blank should be filled with the name of the functools caching decorator: lru_cache.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ block runs when an exception matching its type is raised inside the preceding try block.",
        "options": None,
        "correct_answer": "except",
        "explanation_correct": "An `except` block catches and handles exceptions raised within its associated try block.",
        "explanation_incorrect": "The blank should be filled with the keyword used to catch exceptions: except.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "List comprehensions can include an optional ____ clause at the end to filter which elements are included in the result.",
        "options": None,
        "correct_answer": "if",
        "explanation_correct": "Adding an `if` clause to a list comprehension filters out elements that don't satisfy the condition.",
        "explanation_incorrect": "The blank should be filled with the keyword used to filter elements in a comprehension: if.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The built-in function ____ pairs up corresponding elements from two or more iterables into tuples.",
        "options": None,
        "correct_answer": "zip",
        "explanation_correct": "`zip()` combines multiple iterables element-wise into an iterator of tuples.",
        "explanation_incorrect": "The blank should be filled with the built-in function used to combine iterables element-wise: zip.",
    },

    # ---------------- DRAG-AND-DROP (3) ----------------

    {
        "topic": "Python", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to safely open a file and handle a missing-file error.",
        "options": ["    print('File not found')", "except FileNotFoundError:", "try:", "    f = open('data.txt')"],
        "correct_answer": '["try:", "    f = open(\'data.txt\')", "except FileNotFoundError:", "    print(\'File not found\')"]',
        "explanation_correct": "Correct — the risky operation must be inside the try block, followed by the except block that handles the specific error and its own indented body.",
        "explanation_incorrect": "A try block must come first and contain the risky operation; the matching except clause and its handling code must follow, not precede, the try.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to define a recursive factorial function.",
        "options": ["    return n * factorial(n - 1)", "def factorial(n):", "    if n <= 1:", "        return 1"],
        "correct_answer": '["def factorial(n):", "    if n <= 1:", "        return 1", "    return n * factorial(n - 1)"]',
        "explanation_correct": "Correct — the function definition must come first, followed by the base case check (to stop the recursion), and the recursive case last.",
        "explanation_incorrect": "The base case must be checked before the recursive call is made, or the function would never terminate — and the function header must come before any of its body lines.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to sort a list of dictionaries by the 'name' key.",
        "options": ["print(sorted_data)", "data = [{'name': 'B'}, {'name': 'A'}]", "sorted_data = sorted(data, key=lambda x: x['name'])"],
        "correct_answer": '["data = [{\'name\': \'B\'}, {\'name\': \'A\'}]", "sorted_data = sorted(data, key=lambda x: x[\'name\'])", "print(sorted_data)"]',
        "explanation_correct": "Correct — the data must exist before it can be sorted, and the sorted result must be computed before it's printed.",
        "explanation_incorrect": "Each line depends on the result of the one before it — data must be defined first, then sorted, then printed.",
    },

    # ---------------- DROPDOWN-ORDER (3) ----------------

    {
        "topic": "Python", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to read a JSON file and print a value from it.",
        "options": ["print(data['key'])", "import json", "with open('data.json') as f:\n    data = json.load(f)"],
        "correct_answer": '["import json", "with open(\'data.json\') as f:\\n    data = json.load(f)", "print(data[\'key\'])"]',
        "explanation_correct": "Correct — the json module must be imported before it's used, the file must be opened and parsed before the data exists, and only then can a value be printed.",
        "explanation_incorrect": "Each step depends on the previous one — the module must be imported before use, and the data must be loaded before any value can be accessed from it.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to define a function that raises a custom error for invalid input.",
        "options": ["    return age", "def check_age(age):", "        raise ValueError('Age cannot be negative')", "    if age < 0:"],
        "correct_answer": '["def check_age(age):", "    if age < 0:", "        raise ValueError(\'Age cannot be negative\')", "    return age"]',
        "explanation_correct": "Correct — the function header comes first, followed by the validation check, the error raised inside that check, and the return statement for valid input last.",
        "explanation_incorrect": "The validation check must come before the error is raised, and both must come before the final return — a function can't return a value before checking whether the input is valid.",
    },
    {
        "topic": "Python", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to compute and print the sum of squares of a list of numbers using a generator expression.",
        "options": ["print(squares_sum)", "numbers = [1, 2, 3, 4]", "squares_sum = sum(x**2 for x in numbers)"],
        "correct_answer": '["numbers = [1, 2, 3, 4]", "squares_sum = sum(x**2 for x in numbers)", "print(squares_sum)"]',
        "explanation_correct": "Correct — numbers must be defined before the generator expression can iterate over it, and the sum must be computed before it can be printed.",
        "explanation_incorrect": "Each line depends on data produced by the line before it — the list must exist first, then the sum can be computed, then printed.",
    },
]
