"""
Python - Easy batch, 50 questions total.
Distribution: 32 coding, 8 mcq, 6 fill-in-blank, 2 drag-and-drop, 2 dropdown-order.
"""

PYTHON_EASY_QUESTIONS = [

    # ---------------- CODING (32) ----------------

    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `add(a, b)` that returns the sum of two numbers.",
        "correct_answer": "def add(a, b):\n    return a + b",
        "explanation_correct": "Correct — the function returns the sum of its two arguments.",
        "explanation_incorrect": "A correct solution must accept two arguments and return their sum (not print it).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `is_even(n)` that returns True if n is even, False otherwise.",
        "correct_answer": "def is_even(n):\n    return n % 2 == 0",
        "explanation_correct": "Correct — using the modulo operator to check for a remainder of 0 correctly identifies even numbers.",
        "explanation_incorrect": "A correct solution must return a boolean based on whether n % 2 == 0, for both positive and negative integers.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `reverse_string(s)` that returns the reverse of a string.",
        "correct_answer": "def reverse_string(s):\n    return s[::-1]",
        "explanation_correct": "Correct — slicing with a step of -1 reverses the string.",
        "explanation_incorrect": "A correct solution must return the characters of s in reverse order, e.g. 'abc' -> 'cba'.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `list_length(lst)` that returns the number of items in a list without using the built-in len() function.",
        "correct_answer": "def list_length(lst):\n    count = 0\n    for _ in lst:\n        count += 1\n    return count",
        "explanation_correct": "Correct — manually counting items by iterating over the list avoids len() while still producing the right count.",
        "explanation_incorrect": "A correct solution must count the elements by iterating, not by calling len() directly.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `max_of_three(a, b, c)` that returns the largest of three numbers.",
        "correct_answer": "def max_of_three(a, b, c):\n    return max(a, b, c)",
        "explanation_correct": "Correct — max() with three arguments returns the largest value.",
        "explanation_incorrect": "A correct solution must correctly identify the largest of all three values, including when there are ties.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `count_vowels(s)` that returns the number of vowels (a, e, i, o, u, case-insensitive) in a string.",
        "correct_answer": "def count_vowels(s):\n    return sum(1 for c in s.lower() if c in 'aeiou')",
        "explanation_correct": "Correct — lowercasing the string and checking membership against the vowel set counts vowels case-insensitively.",
        "explanation_incorrect": "A correct solution must count both uppercase and lowercase vowels.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `is_palindrome(s)` that returns True if a string reads the same forwards and backwards.",
        "correct_answer": "def is_palindrome(s):\n    return s == s[::-1]",
        "explanation_correct": "Correct — comparing the string to its reverse correctly detects palindromes.",
        "explanation_incorrect": "A correct solution must compare the string against its reversed version and return a boolean.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `factorial(n)` that returns the factorial of a non-negative integer n.",
        "correct_answer": "def factorial(n):\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result",
        "explanation_correct": "Correct — multiplying all integers from 2 to n produces the factorial, and correctly handles 0! and 1! as 1.",
        "explanation_incorrect": "A correct solution must return 1 for n=0 and n=1, and the product of 1..n otherwise.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `squares(n)` that returns a list of the squares of the integers 1 through n.",
        "correct_answer": "def squares(n):\n    return [i * i for i in range(1, n + 1)]",
        "explanation_correct": "Correct — this builds a list of squares for 1 through n inclusive.",
        "explanation_incorrect": "A correct solution must return a list of length n, with the square of each integer from 1 to n.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `remove_duplicates(lst)` that returns a new list with duplicates removed, preserving the original order.",
        "correct_answer": "def remove_duplicates(lst):\n    seen = set()\n    result = []\n    for item in lst:\n        if item not in seen:\n            seen.add(item)\n            result.append(item)\n    return result",
        "explanation_correct": "Correct — tracking seen items and only appending unseen ones removes duplicates while preserving order.",
        "explanation_incorrect": "A correct solution must remove duplicates while keeping the first occurrence of each item in its original position (using set() alone won't preserve order).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `fibonacci(n)` that returns a list of the first n Fibonacci numbers, starting with 0, 1.",
        "correct_answer": "def fibonacci(n):\n    result = []\n    a, b = 0, 1\n    for _ in range(n):\n        result.append(a)\n        a, b = b, a + b\n    return result",
        "explanation_correct": "Correct — this generates the sequence iteratively and returns exactly n terms starting from 0.",
        "explanation_incorrect": "A correct solution must return a list of length n, starting with 0 and 1 (for n >= 2).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `char_count(s)` that returns a dictionary mapping each character in a string to how many times it appears.",
        "correct_answer": "def char_count(s):\n    counts = {}\n    for c in s:\n        counts[c] = counts.get(c, 0) + 1\n    return counts",
        "explanation_correct": "Correct — using .get() with a default of 0 correctly tallies occurrences of every character, including repeats.",
        "explanation_incorrect": "A correct solution must return a dict where each key is a character from the string and each value is its count.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `is_prime(n)` that returns True if n is a prime number, False otherwise.",
        "correct_answer": "def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n ** 0.5) + 1):\n        if n % i == 0:\n            return False\n    return True",
        "explanation_correct": "Correct — checking divisibility up to the square root of n, and excluding numbers below 2, correctly identifies primes.",
        "explanation_incorrect": "A correct solution must return False for numbers less than 2, and correctly test divisibility for all other cases.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `list_sum(lst)` that returns the sum of all numbers in a list.",
        "correct_answer": "def list_sum(lst):\n    total = 0\n    for n in lst:\n        total += n\n    return total",
        "explanation_correct": "Correct — accumulating a running total across all elements correctly sums the list.",
        "explanation_incorrect": "A correct solution must add up every element in the list and return the total (an empty list should return 0).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `to_upper(lst)` that returns a new list with every string in lst converted to uppercase.",
        "correct_answer": "def to_upper(lst):\n    return [s.upper() for s in lst]",
        "explanation_correct": "Correct — applying .upper() to each element via a list comprehension uppercases every string in the list.",
        "explanation_incorrect": "A correct solution must return a new list where every string has been uppercased, without modifying the original list in place.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `find_index(lst, target)` that returns the index of the first occurrence of target in lst, or -1 if not found.",
        "correct_answer": "def find_index(lst, target):\n    for i, item in enumerate(lst):\n        if item == target:\n            return i\n    return -1",
        "explanation_correct": "Correct — iterating with enumerate() and returning the index on the first match (or -1 if the loop finishes) matches the required behavior.",
        "explanation_incorrect": "A correct solution must return the index of the first match, and -1 specifically when the target isn't present.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `merge_dicts(d1, d2)` that returns a new dictionary combining d1 and d2 (values from d2 take precedence on key conflicts).",
        "correct_answer": "def merge_dicts(d1, d2):\n    result = d1.copy()\n    result.update(d2)\n    return result",
        "explanation_correct": "Correct — copying d1 and then updating with d2 merges both dicts while letting d2's values win on conflicts.",
        "explanation_incorrect": "A correct solution must return a new dict containing all keys from both inputs, with d2's value used whenever a key exists in both.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `average(lst)` that returns the average of a list of numbers.",
        "correct_answer": "def average(lst):\n    return sum(lst) / len(lst)",
        "explanation_correct": "Correct — dividing the sum by the count of elements correctly computes the average.",
        "explanation_incorrect": "A correct solution must divide the total by the number of elements (assume the list is non-empty).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `flatten(lst)` that flattens a list of lists by one level, e.g. [[1,2],[3],[4,5]] -> [1,2,3,4,5].",
        "correct_answer": "def flatten(lst):\n    result = []\n    for sub in lst:\n        result.extend(sub)\n    return result",
        "explanation_correct": "Correct — extending the result list with each sublist's items flattens one level, matching the expected output.",
        "explanation_incorrect": "A correct solution must combine the elements of all sublists into a single flat list, one level deep.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `swap_case(s)` that returns a copy of the string with uppercase letters made lowercase and vice versa.",
        "correct_answer": "def swap_case(s):\n    return s.swapcase()",
        "explanation_correct": "Correct — the built-in .swapcase() method does exactly this.",
        "explanation_incorrect": "A correct solution must invert the case of every letter in the string, leaving non-letter characters unchanged.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `all_unique(lst)` that returns True if all elements in the list are unique (no duplicates).",
        "correct_answer": "def all_unique(lst):\n    return len(lst) == len(set(lst))",
        "explanation_correct": "Correct — comparing the list length to the length of the set of its elements detects any duplicates.",
        "explanation_incorrect": "A correct solution must return False if any value appears more than once in the list.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `second_largest(lst)` that returns the second largest number in a list of distinct numbers.",
        "correct_answer": "def second_largest(lst):\n    return sorted(lst)[-2]",
        "explanation_correct": "Correct — sorting the list and taking the second-to-last element gives the second largest value.",
        "explanation_incorrect": "A correct solution must return the second highest distinct value, not just any second element of the unsorted list.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `word_count(sentence)` that returns the number of words in a sentence (words separated by whitespace).",
        "correct_answer": "def word_count(sentence):\n    return len(sentence.split())",
        "explanation_correct": "Correct — .split() with no arguments splits on any whitespace and handles extra spaces cleanly, so counting the resulting list gives the word count.",
        "explanation_incorrect": "A correct solution must count words split on whitespace, and should handle multiple spaces between words gracefully.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `evens_only(lst)` that returns a new list containing only the even numbers from the input list.",
        "correct_answer": "def evens_only(lst):\n    return [n for n in lst if n % 2 == 0]",
        "explanation_correct": "Correct — the list comprehension filters to only elements divisible by 2.",
        "explanation_incorrect": "A correct solution must return a new list with only the even numbers, preserving their original relative order.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `capitalize_words(s)` that returns the string with the first letter of each word capitalized.",
        "correct_answer": "def capitalize_words(s):\n    return s.title()",
        "explanation_correct": "Correct — .title() capitalizes the first letter of each word in the string.",
        "explanation_incorrect": "A correct solution must capitalize the first letter of every word while leaving the rest of each word's casing reasonable.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `digit_sum(n)` that returns the sum of the digits of a positive integer n.",
        "correct_answer": "def digit_sum(n):\n    return sum(int(d) for d in str(n))",
        "explanation_correct": "Correct — converting the number to a string, iterating over its characters as digits, and summing them gives the digit sum.",
        "explanation_incorrect": "A correct solution must sum the individual digits of n, e.g. digit_sum(123) should return 6.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `is_anagram(s1, s2)` that returns True if two strings are anagrams of each other (ignore case).",
        "correct_answer": "def is_anagram(s1, s2):\n    return sorted(s1.lower()) == sorted(s2.lower())",
        "explanation_correct": "Correct — sorting the lowercased characters of both strings and comparing them correctly detects anagrams.",
        "explanation_incorrect": "A correct solution must compare the letters of both strings regardless of order, and should be case-insensitive.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `index_map(lst)` that returns a dictionary mapping each element in the list to its index.",
        "correct_answer": "def index_map(lst):\n    return {item: i for i, item in enumerate(lst)}",
        "explanation_correct": "Correct — using enumerate() in a dict comprehension maps each element to its position in the list.",
        "explanation_incorrect": "A correct solution must return a dict where each list element is a key and its index is the value.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `remove_whitespace(s)` that returns the string with all whitespace characters removed.",
        "correct_answer": "def remove_whitespace(s):\n    return ''.join(s.split())",
        "explanation_correct": "Correct — splitting on whitespace and joining with an empty string removes all whitespace from the string.",
        "explanation_incorrect": "A correct solution must remove all spaces, tabs, and newlines from the string, not just leading/trailing whitespace.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `running_total(lst)` that returns a list of the cumulative sums of lst, e.g. [1,2,3] -> [1,3,6].",
        "correct_answer": "def running_total(lst):\n    result = []\n    total = 0\n    for n in lst:\n        total += n\n        result.append(total)\n    return result",
        "explanation_correct": "Correct — accumulating a running total and appending it at each step produces the cumulative sum sequence.",
        "explanation_incorrect": "A correct solution must return a list the same length as the input, where each element is the sum of all elements up to and including that position.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `is_sorted(lst)` that returns True if the list is sorted in ascending order.",
        "correct_answer": "def is_sorted(lst):\n    return all(lst[i] <= lst[i + 1] for i in range(len(lst) - 1))",
        "explanation_correct": "Correct — checking that every adjacent pair is non-decreasing correctly determines ascending order.",
        "explanation_incorrect": "A correct solution must return True only if every element is less than or equal to the next one.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "coding",
        "prompt": "Write a function `parse_csv_ints(s)` that converts a comma-separated string of numbers into a list of integers, e.g. '1,2,3' -> [1,2,3].",
        "correct_answer": "def parse_csv_ints(s):\n    return [int(x) for x in s.split(',')]",
        "explanation_correct": "Correct — splitting on commas and converting each piece to an int produces the expected list.",
        "explanation_incorrect": "A correct solution must split the string on commas and convert each resulting piece to an integer.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the output of `print(type(5 / 2))` in Python 3?",
        "options": ["int", "float", "str", "complex"],
        "correct_answer": "float",
        "explanation_correct": "In Python 3, the `/` operator always performs true division and returns a float, even when the operands are integers.",
        "explanation_incorrect": {
            "int": "Wrong — `/` always returns a float in Python 3; use `//` for integer (floor) division.",
            "str": "Wrong — division never returns a string type.",
            "complex": "Wrong — dividing two real numbers doesn't produce a complex result.",
        },
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "Which of the following Python data types is immutable?",
        "options": ["list", "dict", "tuple", "set"],
        "correct_answer": "tuple",
        "explanation_correct": "Tuples cannot be changed after creation — you can't add, remove, or reassign their elements.",
        "explanation_incorrect": {
            "list": "Wrong — lists are mutable; you can append, remove, and modify their elements.",
            "dict": "Wrong — dictionaries are mutable; keys and values can be added, changed, or removed.",
            "set": "Wrong — sets are mutable; items can be added or removed with .add() and .remove().",
        },
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the correct way to create an empty dictionary in Python?",
        "options": ["{}", "[]", "()", "dict[]"],
        "correct_answer": "{}",
        "explanation_correct": "`{}` creates an empty dictionary. It's also valid to write `dict()`.",
        "explanation_incorrect": {
            "[]": "Wrong — this creates an empty list, not a dictionary.",
            "()": "Wrong — this creates an empty tuple, not a dictionary.",
            "dict[]": "Wrong — this is not valid Python syntax for creating a dictionary.",
        },
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "What sequence of numbers does `range(5)` generate?",
        "options": ["1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "0, 1, 2, 3, 4, 5", "1, 2, 3, 4"],
        "correct_answer": "0, 1, 2, 3, 4",
        "explanation_correct": "`range(5)` starts at 0 by default and stops before 5, producing 0 through 4.",
        "explanation_incorrect": {
            "1, 2, 3, 4, 5": "Wrong — range() starts at 0 by default, not 1, unless a start value is given.",
            "0, 1, 2, 3, 4, 5": "Wrong — range(5) stops before 5, so 5 itself is not included.",
            "1, 2, 3, 4": "Wrong — this is missing 0, which range(5) does include by default.",
        },
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "Which keyword is used to define a function in Python?",
        "options": ["func", "def", "function", "lambda"],
        "correct_answer": "def",
        "explanation_correct": "`def` is the keyword used to define a named function in Python.",
        "explanation_incorrect": {
            "func": "Wrong — `func` is not a Python keyword.",
            "function": "Wrong — `function` is not the correct keyword; Python uses `def`.",
            "lambda": "Wrong — `lambda` creates small anonymous functions, but it's not used for defining named functions with a function body.",
        },
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "What does `bool(\"\")` evaluate to?",
        "options": ["True", "False", "None", "It raises an error"],
        "correct_answer": "False",
        "explanation_correct": "An empty string is falsy in Python, so `bool(\"\")` evaluates to False.",
        "explanation_incorrect": {
            "True": "Wrong — only non-empty strings are truthy; an empty string evaluates to False.",
            "None": "Wrong — `bool()` always returns a boolean, never None.",
            "It raises an error": "Wrong — this is valid, error-free code.",
        },
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "Which list method adds a single item to the end of a list?",
        "options": ["append()", "insert()", "add()", "push()"],
        "correct_answer": "append()",
        "explanation_correct": "`.append()` adds a single item to the end of a list.",
        "explanation_incorrect": {
            "insert()": "Wrong — insert() adds an item at a specific index, and requires that index as an argument.",
            "add()": "Wrong — add() is a set method, not a list method.",
            "push()": "Wrong — Python lists don't have a push() method (that's common in other languages like JavaScript).",
        },
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "mcq",
        "prompt": "What does `\"hello\"[1:3]` evaluate to?",
        "options": ["\"he\"", "\"el\"", "\"ell\"", "\"llo\""],
        "correct_answer": "\"el\"",
        "explanation_correct": "Slicing [1:3] includes index 1 up to (but not including) index 3, giving the characters 'e' and 'l'.",
        "explanation_incorrect": {
            "\"he\"": "Wrong — that would be the result of [0:2], not [1:3].",
            "\"ell\"": "Wrong — that's three characters; [1:3] only includes indices 1 and 2.",
            "\"llo\"": "Wrong — that starts at index 2, not index 1.",
        },
    },

    # ---------------- FILL-IN-BLANK (6) ----------------

    {
        "topic": "Python", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Complete the code to print the text Hello: ____(\"Hello\")",
        "options": None,
        "correct_answer": "print",
        "explanation_correct": "The `print()` function outputs text to the console.",
        "explanation_incorrect": "The blank should be filled with the function used to output text: print.",
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ loop is used to iterate over the items of a sequence, such as a list or string.",
        "options": None,
        "correct_answer": "for",
        "explanation_correct": "A `for` loop iterates over the elements of a sequence one at a time.",
        "explanation_incorrect": "The blank should be filled with the loop keyword used for iterating over sequences: for.",
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "To convert a string like \"42\" into an integer, use the ____() function.",
        "options": None,
        "correct_answer": "int",
        "explanation_correct": "`int()` converts a compatible string or float into an integer.",
        "explanation_incorrect": "The blank should be filled with the built-in conversion function: int.",
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The keyword ____ is used to exit a loop early, before it has finished iterating.",
        "options": None,
        "correct_answer": "break",
        "explanation_correct": "`break` immediately exits the nearest enclosing loop.",
        "explanation_incorrect": "The blank should be filled with the keyword used to exit a loop early: break.",
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Lists in Python are created using ____ brackets, for example [1, 2, 3].",
        "options": None,
        "correct_answer": "square",
        "explanation_correct": "Square brackets `[]` are used to define a list literal in Python.",
        "explanation_incorrect": "The blank should describe the type of bracket used for lists: square.",
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ operator is used to check whether a value exists in a list, e.g. `3 ____ [1, 2, 3]`.",
        "options": None,
        "correct_answer": "in",
        "explanation_correct": "The `in` operator checks membership within a list, string, or other collection.",
        "explanation_incorrect": "The blank should be filled with the membership-testing operator: in.",
    },

    # ---------------- DRAG-AND-DROP (2) ----------------

    {
        "topic": "Python", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to swap the values of two variables `a` and `b` using a temporary variable.",
        "options": ["b = temp", "temp = a", "a = b"],
        "correct_answer": '["temp = a", "a = b", "b = temp"]',
        "explanation_correct": "Correct — you must save `a`'s original value before overwriting it, then assign `b` into `a`, then assign the saved value into `b`.",
        "explanation_incorrect": "The temp variable must capture `a`'s value before `a` is overwritten, or the original value of `a` is lost before it can be assigned to `b`.",
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to open a file, write to it, and close it.",
        "options": ["f.close()", "f = open('file.txt', 'w')", "f.write('hello')"],
        "correct_answer": '["f = open(\'file.txt\', \'w\')", "f.write(\'hello\')", "f.close()"]',
        "explanation_correct": "Correct — a file must be opened before it can be written to, and closed only after all writing is finished.",
        "explanation_incorrect": "The file must be opened first, written to second, and closed last — writing or closing before opening would fail.",
    },

    # ---------------- DROPDOWN-ORDER (2) ----------------

    {
        "topic": "Python", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to convert 25 Celsius to Fahrenheit and print the result.",
        "options": ["print(fahrenheit)", "celsius = 25", "fahrenheit = celsius * 9 / 5 + 32"],
        "correct_answer": '["celsius = 25", "fahrenheit = celsius * 9 / 5 + 32", "print(fahrenheit)"]',
        "explanation_correct": "Correct — `celsius` must be defined before it's used in the conversion formula, and the result must be computed before it can be printed.",
        "explanation_incorrect": "Each line depends on variables defined in the line before it — celsius must exist before the formula runs, and fahrenheit must exist before it's printed.",
    },
    {
        "topic": "Python", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to read user input, clean it, and check it against a value.",
        "options": ["if cleaned == 'yes':", "cleaned = user_input.strip().lower()", "user_input = input()"],
        "correct_answer": '["user_input = input()", "cleaned = user_input.strip().lower()", "if cleaned == \'yes\':"]',
        "explanation_correct": "Correct — input must be captured before it can be cleaned, and cleaned before it can be checked against a value.",
        "explanation_incorrect": "Each step depends on the previous one's output — you need raw input before you can clean it, and a cleaned value before you can compare it.",
    },
]
