"""
Python - Hard batch, 50 questions total.
Distribution: 30 coding, 8 mcq, 6 fill-in-blank, 3 drag-and-drop, 3 dropdown-order.

Schema matches python_easy.py — see that file's header for full field notes.
"""

PYTHON_HARD_QUESTIONS = [

    # ---------------- CODING (30) ----------------

    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Implement an `LRUCache` class with `__init__(self, capacity)`, `get(key)` (returns the value or -1 if not present, and marks the key as recently used), and `put(key, value)` (inserts/updates a key, evicting the least recently used entry if capacity is exceeded).",
        "correct_answer": "from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        self.capacity = capacity\n        self.cache = OrderedDict()\n\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n\n    def put(self, key, value):\n        if key in self.cache:\n            self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.capacity:\n            self.cache.popitem(last=False)",
        "explanation_correct": "Correct — using an OrderedDict and moving accessed/updated keys to the end tracks recency, while popping from the front on overflow evicts the least recently used entry.",
        "explanation_incorrect": "A correct solution must support O(1)-ish get/put, update recency on both get and put, and evict the least recently used item (not the oldest inserted item, if it's since been accessed) when capacity is exceeded.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `quicksort(lst)` that returns a new sorted list using the quicksort algorithm (not the built-in sorted()/sort()).",
        "correct_answer": "def quicksort(lst):\n    if len(lst) <= 1:\n        return lst\n    pivot = lst[len(lst) // 2]\n    left = [x for x in lst if x < pivot]\n    middle = [x for x in lst if x == pivot]\n    right = [x for x in lst if x > pivot]\n    return quicksort(left) + middle + quicksort(right)",
        "explanation_correct": "Correct — partitioning around a pivot into less-than, equal, and greater-than groups, then recursively sorting the outer groups, is a valid quicksort implementation.",
        "explanation_incorrect": "A correct solution must implement the actual partition-and-recurse quicksort logic, not simply call the built-in sorted() or .sort().",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `mergesort(lst)` that returns a new sorted list using the mergesort algorithm.",
        "correct_answer": "def mergesort(lst):\n    if len(lst) <= 1:\n        return lst\n    mid = len(lst) // 2\n    left = mergesort(lst[:mid])\n    right = mergesort(lst[mid:])\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result",
        "explanation_correct": "Correct — recursively splitting the list in half, sorting each half, and merging the two sorted halves together is a valid mergesort implementation.",
        "explanation_incorrect": "A correct solution must implement the divide (split in half), conquer (recursively sort), and merge (combine sorted halves) steps, not just call a built-in sort.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `lcs_length(s1, s2)` that returns the length of the longest common subsequence of two strings, using dynamic programming.",
        "correct_answer": "def lcs_length(s1, s2):\n    m, n = len(s1), len(s2)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if s1[i - 1] == s2[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1] + 1\n            else:\n                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])\n    return dp[m][n]",
        "explanation_correct": "Correct — building a DP table where each cell represents the LCS length of prefixes, extending on matches and taking the max on mismatches, correctly computes the LCS length.",
        "explanation_incorrect": "A correct solution should use dynamic programming (building up from subproblems) rather than brute-force checking all subsequences, which is exponential.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `knapsack(weights, values, capacity)` that returns the maximum total value achievable without exceeding the given weight capacity, using 0/1 knapsack dynamic programming.",
        "correct_answer": "def knapsack(weights, values, capacity):\n    n = len(weights)\n    dp = [[0] * (capacity + 1) for _ in range(n + 1)]\n    for i in range(1, n + 1):\n        for w in range(capacity + 1):\n            if weights[i - 1] <= w:\n                dp[i][w] = max(dp[i - 1][w], dp[i - 1][w - weights[i - 1]] + values[i - 1])\n            else:\n                dp[i][w] = dp[i - 1][w]\n    return dp[n][capacity]",
        "explanation_correct": "Correct — the DP table considers, for each item and each capacity, whether including the item improves value without exceeding weight, correctly solving 0/1 knapsack.",
        "explanation_incorrect": "A correct solution must consider each item at most once (0/1, not fractional) and correctly track the best achievable value for every possible remaining capacity.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `climb_stairs(n)` that returns the number of distinct ways to climb n stairs, taking either 1 or 2 steps at a time.",
        "correct_answer": "def climb_stairs(n):\n    if n <= 2:\n        return n\n    a, b = 1, 2\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    return b",
        "explanation_correct": "Correct — this is structurally the Fibonacci recurrence (ways(n) = ways(n-1) + ways(n-2)), computed iteratively with correct base cases for n=1 and n=2.",
        "explanation_incorrect": "A correct solution must recognize this as a Fibonacci-like recurrence and return the correct count for the base cases (1 way for n=1, 2 ways for n=2).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `word_break(s, word_dict)` that returns True if the string s can be segmented into a sequence of one or more words from word_dict (a set of valid words).",
        "correct_answer": "def word_break(s, word_dict):\n    n = len(s)\n    dp = [False] * (n + 1)\n    dp[0] = True\n    for i in range(1, n + 1):\n        for j in range(i):\n            if dp[j] and s[j:i] in word_dict:\n                dp[i] = True\n                break\n    return dp[n]",
        "explanation_correct": "Correct — dp[i] tracks whether the prefix of length i can be segmented, and checking all valid split points j against the dictionary correctly propagates that answer to the full string.",
        "explanation_incorrect": "A correct solution must check whether the entire string can be split into dictionary words in sequence, not just whether any substring is a valid word.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `subsets(lst)` that returns all possible subsets (the power set) of a list, including the empty set and the full list.",
        "correct_answer": "def subsets(lst):\n    result = [[]]\n    for item in lst:\n        result += [subset + [item] for subset in result]\n    return result",
        "explanation_correct": "Correct — starting with the empty subset and, for each item, doubling the existing subsets by adding a version that includes it, generates every possible subset.",
        "explanation_incorrect": "A correct solution must return all 2^n subsets of the input, including the empty list and the list itself.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `permutations_list(lst)` that returns all permutations of a list, without using itertools.",
        "correct_answer": "def permutations_list(lst):\n    if len(lst) <= 1:\n        return [lst]\n    result = []\n    for i in range(len(lst)):\n        rest = lst[:i] + lst[i + 1:]\n        for p in permutations_list(rest):\n            result.append([lst[i]] + p)\n    return result",
        "explanation_correct": "Correct — recursively choosing each element as the first item and permuting the remainder builds every possible ordering of the list.",
        "explanation_incorrect": "A correct solution must return all n! orderings of the list's elements, generated without relying on itertools.permutations.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `is_valid_sudoku(board)` that returns True if a 9x9 sudoku board (a list of 9 lists, using '.' for empty cells) has no duplicate digits within any row, column, or 3x3 box (ignoring '.' cells).",
        "correct_answer": "def is_valid_sudoku(board):\n    rows = [set() for _ in range(9)]\n    cols = [set() for _ in range(9)]\n    boxes = [set() for _ in range(9)]\n    for r in range(9):\n        for c in range(9):\n            val = board[r][c]\n            if val == '.':\n                continue\n            b = (r // 3) * 3 + c // 3\n            if val in rows[r] or val in cols[c] or val in boxes[b]:\n                return False\n            rows[r].add(val)\n            cols[c].add(val)\n            boxes[b].add(val)\n    return True",
        "explanation_correct": "Correct — tracking seen values per row, column, and 3x3 box, and rejecting any value already seen in its group, correctly validates all sudoku constraints.",
        "explanation_incorrect": "A correct solution must check all three constraints — rows, columns, and 3x3 boxes — for duplicate non-empty digits, not just one of the three.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Given a `TreeNode` class with attributes `val`, `left`, and `right`, write a function `inorder_traversal(root)` that returns a list of node values in in-order (left, root, right).",
        "correct_answer": "def inorder_traversal(root):\n    if root is None:\n        return []\n    return inorder_traversal(root.left) + [root.val] + inorder_traversal(root.right)",
        "explanation_correct": "Correct — recursively visiting the left subtree, then the current node's value, then the right subtree, correctly produces the in-order sequence.",
        "explanation_incorrect": "A correct solution must visit nodes in left-root-right order and return an empty list for a None node without raising an error.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `bfs_shortest_path(graph, start, end)` that returns the length of the shortest path (in number of edges) between start and end in an unweighted graph represented as an adjacency dict, or -1 if no path exists.",
        "correct_answer": "from collections import deque\n\ndef bfs_shortest_path(graph, start, end):\n    if start == end:\n        return 0\n    visited = {start}\n    queue = deque([(start, 0)])\n    while queue:\n        node, dist = queue.popleft()\n        for neighbor in graph.get(node, []):\n            if neighbor == end:\n                return dist + 1\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append((neighbor, dist + 1))\n    return -1",
        "explanation_correct": "Correct — BFS explores nodes level by level from the start, guaranteeing the first time end is reached represents the shortest edge distance in an unweighted graph.",
        "explanation_incorrect": "A correct solution must use a breadth-first (not depth-first) approach to guarantee shortest distance in an unweighted graph, and must return -1 when no path connects start and end.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `count_connected_components(graph)` that returns the number of connected components in an undirected graph represented as an adjacency dict.",
        "correct_answer": "def count_connected_components(graph):\n    visited = set()\n    count = 0\n    def dfs(node):\n        visited.add(node)\n        for neighbor in graph.get(node, []):\n            if neighbor not in visited:\n                dfs(neighbor)\n    for node in graph:\n        if node not in visited:\n            count += 1\n            dfs(node)\n    return count",
        "explanation_correct": "Correct — running DFS from every unvisited node and counting each new DFS launch correctly counts the number of separate connected components.",
        "explanation_incorrect": "A correct solution must traverse (via DFS or BFS) all nodes reachable from each unvisited starting node, incrementing a counter once per group of connected nodes.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `dijkstra(graph, start)` that returns a dict of shortest distances from start to every other node, for a weighted graph represented as {node: [(neighbor, weight), ...]}.",
        "correct_answer": "import heapq\n\ndef dijkstra(graph, start):\n    distances = {node: float('inf') for node in graph}\n    distances[start] = 0\n    heap = [(0, start)]\n    while heap:\n        dist, node = heapq.heappop(heap)\n        if dist > distances[node]:\n            continue\n        for neighbor, weight in graph.get(node, []):\n            new_dist = dist + weight\n            if new_dist < distances.get(neighbor, float('inf')):\n                distances[neighbor] = new_dist\n                heapq.heappush(heap, (new_dist, neighbor))\n    return distances",
        "explanation_correct": "Correct — using a min-heap to always expand the currently-closest unvisited node, and relaxing edges to update shorter distances, is a correct Dijkstra's algorithm implementation.",
        "explanation_incorrect": "A correct solution must use a priority-queue-based (greedy shortest-first) approach and correctly update distances whenever a shorter path to a node is found.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Implement a `UnionFind` class with `find(x)` (returns the representative/root of x's set, using path compression) and `union(x, y)` (merges the sets containing x and y).",
        "correct_answer": "class UnionFind:\n    def __init__(self, elements):\n        self.parent = {e: e for e in elements}\n\n    def find(self, x):\n        if self.parent[x] != x:\n            self.parent[x] = self.find(self.parent[x])\n        return self.parent[x]\n\n    def union(self, x, y):\n        root_x, root_y = self.find(x), self.find(y)\n        if root_x != root_y:\n            self.parent[root_x] = root_y",
        "explanation_correct": "Correct — find() recursively follows and compresses parent pointers to the root, and union() attaches one root under the other, correctly implementing union-find.",
        "explanation_incorrect": "A correct solution must correctly track set membership via parent pointers, and union() must merge two sets by linking their roots together.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `max_subarray_sum(lst)` that returns the maximum sum of any contiguous subarray, using Kadane's algorithm.",
        "correct_answer": "def max_subarray_sum(lst):\n    max_so_far = lst[0]\n    current_max = lst[0]\n    for n in lst[1:]:\n        current_max = max(n, current_max + n)\n        max_so_far = max(max_so_far, current_max)\n    return max_so_far",
        "explanation_correct": "Correct — at each position, deciding whether to extend the current subarray or start fresh from the current element, and tracking the best sum seen, is exactly Kadane's algorithm.",
        "explanation_incorrect": "A correct solution must run in O(n) time (not brute-force checking all subarrays) and correctly handle lists where all numbers are negative.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `sliding_window_max(lst, k)` that returns a list of the maximum value in every contiguous window of size k.",
        "correct_answer": "from collections import deque\n\ndef sliding_window_max(lst, k):\n    dq = deque()\n    result = []\n    for i, n in enumerate(lst):\n        while dq and lst[dq[-1]] <= n:\n            dq.pop()\n        dq.append(i)\n        if dq[0] <= i - k:\n            dq.popleft()\n        if i >= k - 1:\n            result.append(lst[dq[0]])\n    return result",
        "explanation_correct": "Correct — maintaining a deque of indices with decreasing values (removing smaller values from the back and expired indices from the front) tracks the current window's max efficiently.",
        "explanation_incorrect": "A correct solution should return one max value per valid window position, ideally without recomputing the max of the entire window from scratch each time (an O(n*k) brute force is acceptable but less efficient).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `min_window_substring(s, t)` that returns the smallest substring of s that contains all characters of t (including duplicates), or an empty string if no such substring exists.",
        "correct_answer": "from collections import Counter\n\ndef min_window_substring(s, t):\n    if not t or not s:\n        return ''\n    need = Counter(t)\n    missing = len(t)\n    left = start = end = 0\n    for right, char in enumerate(s, 1):\n        if need[char] > 0:\n            missing -= 1\n        need[char] -= 1\n        if missing == 0:\n            while left < right and need[s[left]] < 0:\n                need[s[left]] += 1\n                left += 1\n            if end == 0 or right - left < end - start:\n                start, end = left, right\n    return s[start:end]",
        "explanation_correct": "Correct — expanding the right edge of the window until all of t's characters are covered, then contracting from the left to find the minimal valid window, correctly finds the shortest matching substring.",
        "explanation_incorrect": "A correct solution must find the shortest contiguous substring containing all characters of t (with correct multiplicity for duplicates), returning an empty string if impossible.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `n_queens(n)` that returns the number of distinct solutions to the n-queens problem (placing n queens on an n x n board so none attack each other).",
        "correct_answer": "def n_queens(n):\n    def backtrack(row, cols, diag1, diag2):\n        if row == n:\n            return 1\n        count = 0\n        for col in range(n):\n            if col in cols or (row - col) in diag1 or (row + col) in diag2:\n                continue\n            count += backtrack(row + 1, cols | {col}, diag1 | {row - col}, diag2 | {row + col})\n        return count\n    return backtrack(0, set(), set(), set())",
        "explanation_correct": "Correct — backtracking row by row while tracking used columns and both diagonals correctly counts all valid non-attacking placements.",
        "explanation_incorrect": "A correct solution must use backtracking (or an equivalent exhaustive-but-pruned search) that checks columns and both diagonals for conflicts, and count only fully valid placements.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `generate_parentheses(n)` that returns a list of all valid combinations of n pairs of balanced parentheses.",
        "correct_answer": "def generate_parentheses(n):\n    result = []\n    def backtrack(current, open_count, close_count):\n        if len(current) == 2 * n:\n            result.append(current)\n            return\n        if open_count < n:\n            backtrack(current + '(', open_count + 1, close_count)\n        if close_count < open_count:\n            backtrack(current + ')', open_count, close_count + 1)\n    backtrack('', 0, 0)\n    return result",
        "explanation_correct": "Correct — only adding an open paren while under the limit, and only adding a close paren while it wouldn't exceed the number of opens so far, guarantees every generated string is valid and complete.",
        "explanation_incorrect": "A correct solution must generate only valid (properly balanced and nested) combinations, not all 2^(2n) possible strings filtered afterward.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `deep_copy(obj)` that returns a deep copy of a nested structure of lists and dicts (containing only lists, dicts, and immutable values), without using the copy module.",
        "correct_answer": "def deep_copy(obj):\n    if isinstance(obj, list):\n        return [deep_copy(item) for item in obj]\n    if isinstance(obj, dict):\n        return {key: deep_copy(value) for key, value in obj.items()}\n    return obj",
        "explanation_correct": "Correct — recursively rebuilding lists and dicts element by element (rather than referencing the originals), while returning immutable values as-is, produces a true deep copy.",
        "explanation_incorrect": "A correct solution must recursively copy nested lists and dicts so that modifying the copy never affects the original, without relying on the copy module.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a context manager class `Timer` (using `__enter__` and `__exit__`) that records the elapsed wall-clock time of the `with` block in an attribute `elapsed` (in seconds).",
        "correct_answer": "import time\n\nclass Timer:\n    def __enter__(self):\n        self.start = time.time()\n        return self\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        self.elapsed = time.time() - self.start\n        return False",
        "explanation_correct": "Correct — recording the start time in __enter__ and computing the elapsed duration in __exit__ correctly times the with-block, and returning False/None lets any exception propagate normally.",
        "explanation_incorrect": "A correct solution must implement both __enter__ and __exit__, record a start time when entering, and compute elapsed = end - start when exiting, storing it as an accessible attribute.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a decorator factory `retry(times)` that returns a decorator which retries the wrapped function up to `times` times if it raises an exception, re-raising the last exception if all attempts fail.",
        "correct_answer": "def retry(times):\n    def decorator(func):\n        def wrapper(*args, **kwargs):\n            last_exception = None\n            for _ in range(times):\n                try:\n                    return func(*args, **kwargs)\n                except Exception as e:\n                    last_exception = e\n            raise last_exception\n        return wrapper\n    return decorator",
        "explanation_correct": "Correct — the three-level structure (factory -> decorator -> wrapper) correctly captures `times`, retries on exception up to that many attempts, and re-raises the final failure if none succeed.",
        "explanation_incorrect": "A correct solution must be a decorator factory (a function returning a decorator) that retries on exceptions and re-raises after exhausting all attempts, not silently swallowing the failure.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a class `FibonacciIterator` implementing `__iter__` and `__next__` that produces an infinite sequence of Fibonacci numbers starting from 0, 1 (so it can be used in a for loop with break, or with next()).",
        "correct_answer": "class FibonacciIterator:\n    def __init__(self):\n        self.a, self.b = 0, 1\n\n    def __iter__(self):\n        return self\n\n    def __next__(self):\n        result = self.a\n        self.a, self.b = self.b, self.a + self.b\n        return result",
        "explanation_correct": "Correct — __iter__ returning self makes the object its own iterator, and __next__ advancing the Fibonacci state and returning the current value correctly produces the sequence lazily and infinitely.",
        "explanation_incorrect": "A correct solution must implement both __iter__ (returning an iterator, typically self) and __next__ (advancing state and returning the next Fibonacci value) without ever raising StopIteration, since the sequence is infinite.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a generator function `flatten_generator(nested)` that lazily yields every non-list item from an arbitrarily nested list, without building an intermediate flat list.",
        "correct_answer": "def flatten_generator(nested):\n    for item in nested:\n        if isinstance(item, list):\n            yield from flatten_generator(item)\n        else:\n            yield item",
        "explanation_correct": "Correct — using `yield from` to delegate to the recursive call for nested lists, and yielding non-list items directly, lazily produces every flattened value without building an intermediate list.",
        "explanation_incorrect": "A correct solution must be a generator (using yield, not building and returning a list) that handles nesting at arbitrary depth.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `topological_sort(graph)` that returns a valid topological ordering of nodes for a directed acyclic graph represented as an adjacency dict, using Kahn's algorithm (in-degree tracking with a queue).",
        "correct_answer": "from collections import deque\n\ndef topological_sort(graph):\n    in_degree = {node: 0 for node in graph}\n    for node in graph:\n        for neighbor in graph[node]:\n            in_degree[neighbor] = in_degree.get(neighbor, 0) + 1\n    queue = deque([n for n in in_degree if in_degree[n] == 0])\n    result = []\n    while queue:\n        node = queue.popleft()\n        result.append(node)\n        for neighbor in graph.get(node, []):\n            in_degree[neighbor] -= 1\n            if in_degree[neighbor] == 0:\n                queue.append(neighbor)\n    return result",
        "explanation_correct": "Correct — repeatedly removing nodes with no remaining incoming edges, and decrementing their neighbors' in-degrees, produces a valid ordering where every node appears after all its prerequisites.",
        "explanation_incorrect": "A correct solution must produce an ordering where, for every directed edge u -> v, u appears before v in the result, using an in-degree-based (Kahn's) or DFS-based approach.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Given a `TreeNode` class with attributes `val`, `left`, and `right`, write a function `is_balanced(root)` that returns True if the binary tree is height-balanced (the height of the two subtrees of every node never differs by more than 1).",
        "correct_answer": "def is_balanced(root):\n    def check(node):\n        if node is None:\n            return 0\n        left = check(node.left)\n        if left == -1:\n            return -1\n        right = check(node.right)\n        if right == -1:\n            return -1\n        if abs(left - right) > 1:\n            return -1\n        return max(left, right) + 1\n    return check(root) != -1",
        "explanation_correct": "Correct — computing subtree heights bottom-up and short-circuiting with a sentinel value (-1) as soon as any imbalance is detected correctly determines overall balance in a single pass.",
        "explanation_incorrect": "A correct solution must check the height-balance condition at every node in the tree, not just at the root, and should avoid recomputing height from scratch at every node (which would be less efficient but still acceptable logically).",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `longest_increasing_subsequence(lst)` that returns the length of the longest strictly increasing subsequence in a list of integers.",
        "correct_answer": "def longest_increasing_subsequence(lst):\n    if not lst:\n        return 0\n    dp = [1] * len(lst)\n    for i in range(len(lst)):\n        for j in range(i):\n            if lst[j] < lst[i]:\n                dp[i] = max(dp[i], dp[j] + 1)\n    return max(dp)",
        "explanation_correct": "Correct — for each element, checking all earlier smaller elements and extending the best subsequence ending there correctly builds up the longest increasing subsequence length via dynamic programming.",
        "explanation_incorrect": "A correct solution must find the longest subsequence (not necessarily contiguous) that is strictly increasing, using an approach that considers all valid extensions, such as dynamic programming.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `rotate_matrix_in_place(matrix)` that rotates an n x n matrix (list of lists) 90 degrees clockwise, modifying it in place (returns None).",
        "correct_answer": "def rotate_matrix_in_place(matrix):\n    n = len(matrix)\n    for i in range(n):\n        for j in range(i + 1, n):\n            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n    for row in matrix:\n        row.reverse()",
        "explanation_correct": "Correct — transposing the matrix (swapping across the diagonal) and then reversing each row is a well-known in-place technique for a 90-degree clockwise rotation.",
        "explanation_incorrect": "A correct solution must modify the original matrix's rows in place (not return a new matrix) and correctly produce a 90-degree clockwise rotation.",
        "options": None,
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "coding",
        "prompt": "Write a function `find_all_paths(graph, start, end)` that returns a list of all simple paths (no repeated nodes) from start to end in a graph represented as an adjacency dict, using DFS backtracking.",
        "correct_answer": "def find_all_paths(graph, start, end, path=None):\n    if path is None:\n        path = []\n    path = path + [start]\n    if start == end:\n        return [path]\n    paths = []\n    for neighbor in graph.get(start, []):\n        if neighbor not in path:\n            paths.extend(find_all_paths(graph, neighbor, end, path))\n    return paths",
        "explanation_correct": "Correct — extending the current path at each step, recursing into unvisited neighbors, and collecting a completed path whenever the end node is reached correctly enumerates all simple paths.",
        "explanation_incorrect": "A correct solution must avoid revisiting nodes already in the current path (to prevent infinite loops on cyclic graphs) and must collect every distinct path that reaches the end node.",
        "options": None,
    },

    # ---------------- MCQ (8) ----------------

    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the worst-case time complexity of quicksort?",
        "options": ["O(n log n)", "O(n^2)", "O(n)", "O(log n)"],
        "correct_answer": "O(n^2)",
        "explanation_correct": "Quicksort's worst case occurs with a consistently poor pivot choice (e.g. always picking the smallest or largest element), degrading performance to O(n^2).",
        "explanation_incorrect": {
            "O(n log n)": "Wrong — O(n log n) is quicksort's average-case complexity, not its worst case.",
            "O(n)": "Wrong — no comparison-based general sort can achieve O(n) in the general case.",
            "O(log n)": "Wrong — this would be far too fast for a full sort of n elements; that's more typical of binary search.",
        },
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "For a custom class to be iterable via `for x in obj:`, what must its `__iter__` method return?",
        "options": ["An iterator object (an object implementing __next__)", "A list", "None", "True"],
        "correct_answer": "An iterator object (an object implementing __next__)",
        "explanation_correct": "`__iter__` must return an iterator — an object with a `__next__` method — which Python repeatedly calls to produce values (this is often `self`, if the class also implements `__next__`).",
        "explanation_incorrect": {
            "A list": "Wrong — while a list is iterable, __iter__ must return an iterator object specifically, not just any iterable container.",
            "None": "Wrong — returning None would break iteration, since Python expects an object it can call next() on.",
            "True": "Wrong — a boolean has no __next__ method and can't be used to drive iteration.",
        },
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the main advantage of a generator expression `(x for x in range(10**8))` over an equivalent list comprehension?",
        "options": [
            "It evaluates lazily, avoiding building the entire sequence in memory at once",
            "It always executes faster than a list comprehension",
            "It allows in-place mutation of the source data",
            "It is required syntax for any loop over a range",
        ],
        "correct_answer": "It evaluates lazily, avoiding building the entire sequence in memory at once",
        "explanation_correct": "Generator expressions produce values one at a time on demand, so they don't need to allocate memory for the entire sequence upfront, unlike a list comprehension.",
        "explanation_incorrect": {
            "It always executes faster than a list comprehension": "Wrong — generators aren't inherently faster for total computation time; their advantage is memory efficiency, not raw speed.",
            "It allows in-place mutation of the source data": "Wrong — generator expressions don't provide any special mutation capability over the source.",
            "It is required syntax for any loop over a range": "Wrong — a regular for loop over range() doesn't require a generator expression at all.",
        },
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "What does the Global Interpreter Lock (GIL) primarily restrict in CPython?",
        "options": [
            "True parallel execution of Python bytecode across multiple threads",
            "Network I/O operations",
            "Memory allocation for objects",
            "Importing modules",
        ],
        "correct_answer": "True parallel execution of Python bytecode across multiple threads",
        "explanation_correct": "The GIL ensures only one thread executes Python bytecode at a time in CPython, which prevents true CPU-bound parallelism across threads within a single process (multiprocessing sidesteps this by using separate processes).",
        "explanation_incorrect": {
            "Network I/O operations": "Wrong — the GIL is typically released during blocking I/O operations, so I/O-bound threads can still run concurrently.",
            "Memory allocation for objects": "Wrong — the GIL protects Python's internal state (like reference counts) generally, but its defining effect is on concurrent bytecode execution, not allocation specifically.",
            "Importing modules": "Wrong — module imports aren't the GIL's defining restriction; it applies broadly to bytecode execution across threads.",
        },
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the average-case time complexity of a key lookup in a Python dictionary?",
        "options": ["O(1)", "O(n)", "O(log n)", "O(n^2)"],
        "correct_answer": "O(1)",
        "explanation_correct": "Python dictionaries are implemented as hash tables, giving average-case constant-time lookups by key.",
        "explanation_incorrect": {
            "O(n)": "Wrong — O(n) would describe a linear scan, like searching an unsorted list, not a hash-table-backed dict.",
            "O(log n)": "Wrong — O(log n) describes something like a balanced tree lookup, not Python's hash-table-based dict.",
            "O(n^2)": "Wrong — this is far worse than dict lookups ever perform in typical (non-pathological) use.",
        },
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "What does applying `@functools.wraps(func)` inside a custom decorator's wrapper function accomplish?",
        "options": [
            "It preserves the original function's name, docstring, and other metadata on the wrapper",
            "It makes the wrapped function execute faster",
            "It automatically adds memoization/caching to the function",
            "It converts the function into a generator",
        ],
        "correct_answer": "It preserves the original function's name, docstring, and other metadata on the wrapper",
        "explanation_correct": "Without @wraps, a decorated function's __name__, __doc__, and other metadata get overwritten by the wrapper's own; @functools.wraps copies that metadata from the original function onto the wrapper.",
        "explanation_incorrect": {
            "It makes the wrapped function execute faster": "Wrong — @wraps has no effect on execution speed; it only preserves metadata.",
            "It automatically adds memoization/caching to the function": "Wrong — that's the role of functools.lru_cache, a different decorator entirely.",
            "It converts the function into a generator": "Wrong — @wraps doesn't change how the function executes or what it returns, only its introspection metadata.",
        },
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "Which data structure(s) are best suited for implementing an LRU cache with O(1) get and put operations?",
        "options": [
            "An OrderedDict, or a hash map combined with a doubly linked list",
            "A plain Python list",
            "A tuple",
            "A set",
        ],
        "correct_answer": "An OrderedDict, or a hash map combined with a doubly linked list",
        "explanation_correct": "An OrderedDict (or manually, a dict paired with a doubly linked list) supports O(1) lookups plus O(1) reordering/removal of the least recently used entry, which a plain list, tuple, or set cannot do efficiently.",
        "explanation_incorrect": {
            "A plain Python list": "Wrong — finding and moving an item to reflect recency in a list requires O(n) time, breaking the O(1) requirement.",
            "A tuple": "Wrong — tuples are immutable, making them unsuitable for a structure that needs frequent updates.",
            "A set": "Wrong — sets don't preserve insertion/access order, which is essential for tracking recency.",
        },
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "mcq",
        "prompt": "What does `yield from` do inside a generator function?",
        "options": [
            "Delegates iteration to a sub-generator or other iterable, yielding each of its values in turn",
            "Yields multiple values simultaneously as a tuple",
            "Immediately returns from the generator",
            "Always raises StopIteration",
        ],
        "correct_answer": "Delegates iteration to a sub-generator or other iterable, yielding each of its values in turn",
        "explanation_correct": "`yield from` iterates over the given iterable (often another generator) and yields each of its values to the caller, effectively delegating part of the generator's work.",
        "explanation_incorrect": {
            "Yields multiple values simultaneously as a tuple": "Wrong — it yields the sub-iterable's values one at a time, in sequence, not bundled together.",
            "Immediately returns from the generator": "Wrong — it delegates to the sub-iterable and continues after it's exhausted; it doesn't end the generator outright.",
            "Always raises StopIteration": "Wrong — StopIteration is used internally to signal the sub-iterable's exhaustion, but `yield from` handles that transparently rather than propagating it as an error.",
        },
    },

    # ---------------- FILL-IN-BLANK (6) ----------------

    {
        "topic": "Python", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Binary search on a sorted list of n elements runs in logarithmic time, i.e. O(____ n).",
        "options": None,
        "correct_answer": "log",
        "explanation_correct": "Binary search halves the search space on each step, giving O(log n) time complexity.",
        "explanation_incorrect": "The blank should be filled with the term describing this complexity class: log.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A decorator that accepts its own arguments (e.g. @retry(times=3)) requires an additional layer of nested functions, commonly called a decorator ____.",
        "options": None,
        "correct_answer": "factory",
        "explanation_correct": "A function that returns a decorator (rather than being a decorator itself) is commonly called a decorator factory.",
        "explanation_incorrect": "The blank should be filled with the term for a function that produces a decorator: factory.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "To make a custom class usable in a `with` statement, it must implement the ____ and __exit__ methods.",
        "options": None,
        "correct_answer": "__enter__",
        "explanation_correct": "`__enter__` runs when entering the with block, and `__exit__` runs when leaving it (even if an exception occurred).",
        "explanation_incorrect": "The blank should be filled with the method invoked when entering a with block: __enter__.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ module provides thread-safe queue implementations, commonly used to coordinate producer-consumer patterns between threads.",
        "options": None,
        "correct_answer": "queue",
        "explanation_correct": "The `queue` module provides Queue, LifoQueue, and PriorityQueue classes that are safe to use across threads.",
        "explanation_incorrect": "The blank should be filled with the name of the standard library module for thread-safe queues: queue.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "An algorithm that must examine every pair of elements in a list of n items runs in ____ time (the common one-word name for O(n^2) complexity).",
        "options": None,
        "correct_answer": "quadratic",
        "explanation_correct": "O(n^2) complexity is commonly referred to as quadratic time.",
        "explanation_incorrect": "The blank should be filled with the common name for O(n^2) time complexity: quadratic.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The built-in ____ module's `lru_cache` decorator provides automatic memoization of a function's results based on its arguments.",
        "options": None,
        "correct_answer": "functools",
        "explanation_correct": "`functools.lru_cache` is the standard library decorator for automatic memoization.",
        "explanation_incorrect": "The blank should be filled with the standard library module that provides lru_cache: functools.",
    },

    # ---------------- DRAG-AND-DROP (3) ----------------

    {
        "topic": "Python", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to perform one step of binary search on a sorted list.",
        "options": ["if lst[mid] == target:\n    return mid", "mid = (low + high) // 2", "low, high = 0, len(lst) - 1"],
        "correct_answer": '["low, high = 0, len(lst) - 1", "mid = (low + high) // 2", "if lst[mid] == target:\\n    return mid"]',
        "explanation_correct": "Correct — the search boundaries must be initialized first, then the midpoint calculated from them, before that midpoint can be checked against the target.",
        "explanation_incorrect": "The midpoint calculation depends on low and high already being defined, and the comparison depends on mid already being calculated.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to build a decorator factory that accepts an argument.",
        "options": ["            return func(*args, **kwargs)", "def retry(times):", "        def wrapper(*args, **kwargs):", "    def decorator(func):"],
        "correct_answer": '["def retry(times):", "    def decorator(func):", "        def wrapper(*args, **kwargs):", "            return func(*args, **kwargs)"]',
        "explanation_correct": "Correct — a decorator factory nests three levels: the outer function capturing the argument, the decorator capturing the target function, and the wrapper that actually runs it.",
        "explanation_incorrect": "Each nested function must be defined inside the one before it — the outer factory wraps decorator, which wraps wrapper — so the order reflects that nesting from outermost to innermost.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines of code into the correct order to set up a breadth-first search traversal.",
        "options": ["    node = queue.popleft()", "visited = set([start])", "while queue:", "queue = deque([start])"],
        "correct_answer": '["visited = set([start])", "queue = deque([start])", "while queue:", "    node = queue.popleft()"]',
        "explanation_correct": "Correct — the visited set and queue must be initialized with the start node before the traversal loop begins, and a node must be popped from the queue before it can be processed.",
        "explanation_incorrect": "The queue and visited set must be set up before the while loop starts, and popping from the queue only makes sense once inside that loop.",
    },

    # ---------------- DROPDOWN-ORDER (3) ----------------

    {
        "topic": "Python", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to define a Timer context manager that records elapsed time.",
        "options": [
            "    def __exit__(self, *args):\n        self.elapsed = time.time() - self.start",
            "class Timer:",
            "    def __enter__(self):\n        self.start = time.time()\n        return self",
        ],
        "correct_answer": '["class Timer:", "    def __enter__(self):\\n        self.start = time.time()\\n        return self", "    def __exit__(self, *args):\\n        self.elapsed = time.time() - self.start"]',
        "explanation_correct": "Correct — the class must be defined first, __enter__ (which records the start time) must exist before __exit__ can compute elapsed time from it.",
        "explanation_incorrect": "The class definition must come first, and __enter__ must set the start time before __exit__ can use it to compute the elapsed duration.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to implement a memoized recursive Fibonacci function using lru_cache.",
        "options": ["def fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)", "from functools import lru_cache", "@lru_cache(maxsize=None)"],
        "correct_answer": '["from functools import lru_cache", "@lru_cache(maxsize=None)", "def fib(n):\\n    return n if n < 2 else fib(n - 1) + fib(n - 2)"]',
        "explanation_correct": "Correct — lru_cache must be imported before it's used as a decorator, and the decorator line must directly precede the function it decorates.",
        "explanation_incorrect": "The import must come first, and a decorator line must appear immediately above the function definition it's meant to decorate, not after it.",
    },
    {
        "topic": "Python", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines in the correct order to compute in-degrees and seed the queue for a topological sort.",
        "options": [
            "queue = deque([n for n in in_degree if in_degree[n] == 0])",
            "in_degree = {node: 0 for node in graph}",
            "for node in graph:\n    for neighbor in graph[node]:\n        in_degree[neighbor] += 1",
        ],
        "correct_answer": '["in_degree = {node: 0 for node in graph}", "for node in graph:\\n    for neighbor in graph[node]:\\n        in_degree[neighbor] += 1", "queue = deque([n for n in in_degree if in_degree[n] == 0])"]',
        "explanation_correct": "Correct — the in-degree dict must be initialized before it can be populated by counting edges, and the queue can only be built from in_degree once those counts are final.",
        "explanation_incorrect": "in_degree must exist before it can be incremented, and the queue of zero-in-degree nodes can only be correctly built after all edges have been counted.",
    },
]
