"""
Terraform - Medium batch, 50 questions total.
Distribution: even split — 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.

Schema matches python_easy_questions.py / terraform_easy_questions.py — see those files'
headers for full field notes. Medium content steps up to dynamic blocks, complex variable
types, lifecycle management, remote state, state manipulation, and built-in functions.
"""

TERRAFORM_MEDIUM_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write a resource block for an aws_security_group named 'web' that uses a dynamic block to create an ingress rule for each port in a list variable var.ingress_ports (from_port and to_port both set to the port, protocol 'tcp').",
        "correct_answer": "resource \"aws_security_group\" \"web\" {\n  dynamic \"ingress\" {\n    for_each = var.ingress_ports\n    content {\n      from_port   = ingress.value\n      to_port     = ingress.value\n      protocol    = \"tcp\"\n      cidr_blocks = [\"0.0.0.0/0\"]\n    }\n  }\n}",
        "explanation_correct": "Correct — the dynamic block iterates over var.ingress_ports, generating one ingress block per port using the current iteration value.",
        "explanation_incorrect": "A correct solution must use a `dynamic \"ingress\"` block with a for_each over the ports list and a nested content block referencing ingress.value.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write a variable block named 'services' with type list(object({ name = string, port = number })).",
        "correct_answer": "variable \"services\" {\n  type = list(object({\n    name = string\n    port = number\n  }))\n}",
        "explanation_correct": "Correct — this declares a variable that must be a list of objects, each with a name (string) and port (number) attribute.",
        "explanation_incorrect": "A correct solution must declare the type as list(object({...})) with name and port attributes of the correct types.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write a local value 'uppercase_names' using a for expression that transforms a list variable var.instance_names into a map of each name to its uppercase version.",
        "correct_answer": "locals {\n  uppercase_names = { for name in var.instance_names : name => upper(name) }\n}",
        "explanation_correct": "Correct — this for expression iterates over the list and builds a map keyed by the original name, with the uppercase version as the value.",
        "explanation_incorrect": "A correct solution must use a for expression that produces a map (using => syntax) from the list, applying upper() to each value.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write a resource block for an aws_instance named 'web' with a lifecycle block setting create_before_destroy to true.",
        "correct_answer": "resource \"aws_instance\" \"web\" {\n  ami           = \"ami-12345\"\n  instance_type = \"t2.micro\"\n\n  lifecycle {\n    create_before_destroy = true\n  }\n}",
        "explanation_correct": "Correct — the nested lifecycle block with create_before_destroy = true tells Terraform to provision the replacement instance before destroying the old one.",
        "explanation_incorrect": "A correct solution must include a `lifecycle` block nested inside the resource with create_before_destroy set to true.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write a resource block for an aws_instance named 'web' where instance_type is set to 'm5.large' if var.environment equals 'prod', and 't2.micro' otherwise, using a conditional expression.",
        "correct_answer": "resource \"aws_instance\" \"web\" {\n  ami           = \"ami-12345\"\n  instance_type = var.environment == \"prod\" ? \"m5.large\" : \"t2.micro\"\n}",
        "explanation_correct": "Correct — the ternary-style conditional expression correctly selects between the two instance types based on the environment variable.",
        "explanation_incorrect": "A correct solution must use a conditional expression (condition ? true_val : false_val) comparing var.environment to \"prod\".",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write an output block named 'db_password' that outputs the value of aws_db_instance.main.password and marks the output as sensitive.",
        "correct_answer": "output \"db_password\" {\n  value     = aws_db_instance.main.password\n  sensitive = true\n}",
        "explanation_correct": "Correct — this exposes the password value while marking the output sensitive so it's hidden from standard CLI output.",
        "explanation_incorrect": "A correct solution must include both the value argument referencing the password attribute and sensitive = true.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write a terraform_remote_state data source named 'network' that reads state from an S3 backend with bucket 'my-tf-state', key 'network/terraform.tfstate', and region 'us-east-1'.",
        "correct_answer": "data \"terraform_remote_state\" \"network\" {\n  backend = \"s3\"\n  config = {\n    bucket = \"my-tf-state\"\n    key    = \"network/terraform.tfstate\"\n    region = \"us-east-1\"\n  }\n}",
        "explanation_correct": "Correct — this declares a terraform_remote_state data source pointing at the S3 backend with the correct bucket, key, and region configuration.",
        "explanation_incorrect": "A correct solution must use the `data \"terraform_remote_state\" \"network\"` block with backend = \"s3\" and a config map containing bucket, key, and region.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write the terraform command used to import an existing AWS EC2 instance with ID i-1234567890abcdef0 into the resource address aws_instance.web.",
        "correct_answer": "terraform import aws_instance.web i-1234567890abcdef0",
        "explanation_correct": "Correct — `terraform import <resource_address> <resource_id>` brings an existing real-world resource under Terraform's management by writing it into state.",
        "explanation_incorrect": "A correct solution must use `terraform import` followed by the resource address (aws_instance.web) and the actual resource ID.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write the terraform command used to apply changes to only the resource aws_instance.web, ignoring other changes in the plan.",
        "correct_answer": "terraform apply -target=aws_instance.web",
        "explanation_correct": "Correct — the -target flag scopes an apply (or plan) operation to a specific resource address and its dependencies.",
        "explanation_incorrect": "A correct solution must use `terraform apply` with the -target flag set to the specific resource address.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "coding",
        "prompt": "Write a resource block for aws_instance using for_each over a map variable var.instances (keys are instance names, values are objects with an 'ami' attribute), setting ami from each entry's value.",
        "correct_answer": "resource \"aws_instance\" \"this\" {\n  for_each = var.instances\n  ami      = each.value.ami\n}",
        "explanation_correct": "Correct — for_each over the map creates one instance per key, and each.value.ami correctly pulls the ami from the current map entry's object.",
        "explanation_incorrect": "A correct solution must use for_each set to the map variable and reference each.value (and its nested attribute) to configure each created instance.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What type of value does the `for_each` meta-argument accept?",
        "options": ["A map or a set of strings", "Only a list of strings", "Only a number", "A single string"],
        "correct_answer": "A map or a set of strings",
        "explanation_correct": "for_each requires a map or a set of strings (not a list), since it uses the keys to uniquely identify each created instance.",
        "explanation_incorrect": {
            "Only a list of strings": "Wrong — a plain list must first be converted (e.g. with toset()) before it can be used with for_each; lists aren't accepted directly.",
            "Only a number": "Wrong — a number describes how many copies to make with `count`, not the keyed iteration for_each requires.",
            "A single string": "Wrong — for_each needs a collection to iterate over, not a single scalar value.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `prevent_destroy` argument inside a resource's lifecycle block do?",
        "options": [
            "Causes Terraform to reject any plan that would destroy the resource",
            "Prevents Terraform from ever creating the resource",
            "Disables state locking for the resource",
            "Prevents the resource's provider from being upgraded",
        ],
        "correct_answer": "Causes Terraform to reject any plan that would destroy the resource",
        "explanation_correct": "Setting prevent_destroy = true makes Terraform error out on any plan/apply that would destroy that resource, guarding against accidental deletion.",
        "explanation_incorrect": {
            "Prevents Terraform from ever creating the resource": "Wrong — it only blocks destruction, not initial creation.",
            "Disables state locking for the resource": "Wrong — state locking is a separate backend feature, unrelated to prevent_destroy.",
            "Prevents the resource's provider from being upgraded": "Wrong — provider version constraints are handled separately in the terraform/required_providers block.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `terraform state mv` command do?",
        "options": [
            "Moves a resource's tracked state to a new address, without destroying and recreating it",
            "Moves the state file to a different storage backend",
            "Renames a resource in the .tf configuration file",
            "Migrates provider plugin binaries to a new location",
        ],
        "correct_answer": "Moves a resource's tracked state to a new address, without destroying and recreating it",
        "explanation_correct": "`terraform state mv` updates the internal state address of a resource (e.g. after renaming it in config), preserving the existing real infrastructure instead of destroying and recreating it.",
        "explanation_incorrect": {
            "Moves the state file to a different storage backend": "Wrong — changing backends is done via backend configuration and `terraform init -migrate-state`, not `state mv`.",
            "Renames a resource in the .tf configuration file": "Wrong — `state mv` only updates the state's internal address; it doesn't edit your configuration files.",
            "Migrates provider plugin binaries to a new location": "Wrong — this isn't related to provider plugin management at all.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "Which built-in function would you use to merge two maps into a single map?",
        "options": ["merge()", "combine()", "join()", "concat()"],
        "correct_answer": "merge()",
        "explanation_correct": "`merge()` combines multiple maps into one, with later arguments' keys taking precedence over earlier ones on conflicts.",
        "explanation_incorrect": {
            "combine()": "Wrong — this is not a real Terraform built-in function.",
            "join()": "Wrong — join() concatenates a list of strings into a single string using a separator; it doesn't work on maps.",
            "concat()": "Wrong — concat() combines lists together, not maps.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What is a 'remote backend' in Terraform?",
        "options": [
            "A location, such as S3 or Terraform Cloud, where Terraform stores its state instead of locally",
            "A provider plugin that manages remote virtual machines",
            "A special type of reusable module",
            "A CI/CD pipeline configuration",
        ],
        "correct_answer": "A location, such as S3 or Terraform Cloud, where Terraform stores its state instead of locally",
        "explanation_correct": "A remote backend stores the state file somewhere other than the local disk, commonly enabling team collaboration, locking, and encryption at rest.",
        "explanation_incorrect": {
            "A provider plugin that manages remote virtual machines": "Wrong — that describes a provider like aws or azurerm, a different concept from a backend.",
            "A special type of reusable module": "Wrong — modules are about reusing configuration, unrelated to where state is stored.",
            "A CI/CD pipeline configuration": "Wrong — a backend is specifically about state storage, not automation pipelines (though remote backends are often used alongside CI/CD).",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `ignore_changes` argument inside a lifecycle block do?",
        "options": [
            "Tells Terraform to disregard changes to specific attributes on future plans/applies",
            "Prevents any changes to the resource at all",
            "Silently ignores all errors during apply",
            "Disables drift detection for the entire configuration",
        ],
        "correct_answer": "Tells Terraform to disregard changes to specific attributes on future plans/applies",
        "explanation_correct": "ignore_changes takes a list of attribute names (or 'all') that Terraform should stop tracking for diffs after the resource is created, useful for attributes modified outside Terraform.",
        "explanation_incorrect": {
            "Prevents any changes to the resource at all": "Wrong — that's closer to what prevent_destroy does for deletions; ignore_changes is scoped to specific attributes, not all changes.",
            "Silently ignores all errors during apply": "Wrong — ignore_changes affects diff/drift detection on specific attributes, not error handling.",
            "Disables drift detection for the entire configuration": "Wrong — it only affects the specific attributes listed, not the whole configuration.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What is 'state drift' in the context of Terraform?",
        "options": [
            "When the real infrastructure differs from what's recorded in Terraform's state",
            "When the state file becomes corrupted or unreadable",
            "When a provider plugin becomes outdated",
            "When a plan takes an unusually long time to run",
        ],
        "correct_answer": "When the real infrastructure differs from what's recorded in Terraform's state",
        "explanation_correct": "Drift occurs when infrastructure is changed outside of Terraform (e.g. manually in a cloud console), causing the real-world state to diverge from what Terraform believes exists.",
        "explanation_incorrect": {
            "When the state file becomes corrupted or unreadable": "Wrong — that's state corruption, a different (and generally rarer) problem from drift.",
            "When a provider plugin becomes outdated": "Wrong — outdated providers are a version-management concern, unrelated to drift specifically.",
            "When a plan takes an unusually long time to run": "Wrong — plan duration isn't related to whether real infrastructure matches state.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What does the `depends_on` argument do when added to a resource block?",
        "options": [
            "Explicitly declares a dependency on another resource or module beyond what Terraform can infer automatically",
            "Sets environment variables for the resource's provisioners",
            "Imports a module from the Terraform Registry",
            "Marks the resource for deletion",
        ],
        "correct_answer": "Explicitly declares a dependency on another resource or module beyond what Terraform can infer automatically",
        "explanation_correct": "Terraform normally infers dependency order from references between resources; depends_on is used when a dependency exists that isn't expressed through a direct attribute reference.",
        "explanation_incorrect": {
            "Sets environment variables for the resource's provisioners": "Wrong — that's unrelated to depends_on; provisioners have their own environment configuration if needed.",
            "Imports a module from the Terraform Registry": "Wrong — module imports use a `module` block with a source argument, not depends_on.",
            "Marks the resource for deletion": "Wrong — depends_on affects ordering, not whether a resource is created or destroyed.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "What is the purpose of `terraform console`?",
        "options": [
            "An interactive REPL for evaluating Terraform expressions and functions against the current state/config",
            "A web-based dashboard for viewing infrastructure",
            "A way to SSH directly into managed instances",
            "A log viewer for past apply operations",
        ],
        "correct_answer": "An interactive REPL for evaluating Terraform expressions and functions against the current state/config",
        "explanation_correct": "`terraform console` opens an interactive session where you can experiment with expressions, functions, and resource references using the current configuration and state.",
        "explanation_incorrect": {
            "A web-based dashboard for viewing infrastructure": "Wrong — that describes something like Terraform Cloud's UI, not the console command, which is a local CLI REPL.",
            "A way to SSH directly into managed instances": "Wrong — Terraform doesn't provide SSH access to instances via this or any built-in command.",
            "A log viewer for past apply operations": "Wrong — console is for live expression evaluation, not for reviewing historical logs.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "mcq",
        "prompt": "Which of the following best describes a Terraform 'workspace'?",
        "options": [
            "A named instance of state, allowing one configuration to manage multiple distinct sets of infrastructure",
            "A folder containing .tf configuration files",
            "A local cache directory for downloaded provider plugins",
            "A remote Git repository hosting Terraform code",
        ],
        "correct_answer": "A named instance of state, allowing one configuration to manage multiple distinct sets of infrastructure",
        "explanation_correct": "Workspaces let the same configuration manage separate state files (e.g. for dev/staging/prod), switched between with `terraform workspace select`.",
        "explanation_incorrect": {
            "A folder containing .tf configuration files": "Wrong — that describes a working directory or module, not a workspace specifically.",
            "A local cache directory for downloaded provider plugins": "Wrong — that's the .terraform directory, unrelated to workspaces.",
            "A remote Git repository hosting Terraform code": "Wrong — workspaces are a Terraform state concept, not a version control concept.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ meta-argument on a resource block creates one instance per key in a map or set, as an alternative to numeric-index-based count.",
        "options": None,
        "correct_answer": "for_each",
        "explanation_correct": "for_each iterates over a map or set, creating one resource instance per key/element, addressable by that key rather than a numeric index.",
        "explanation_incorrect": "The blank should be filled with the meta-argument used for map/set-based resource iteration: for_each.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Setting create_before_destroy = true inside a ____ block changes replacement order so a new resource is created before the old one is destroyed.",
        "options": None,
        "correct_answer": "lifecycle",
        "explanation_correct": "The `lifecycle` block holds meta-arguments like create_before_destroy, prevent_destroy, and ignore_changes that customize a resource's lifecycle behavior.",
        "explanation_incorrect": "The blank should be filled with the block type that holds create_before_destroy: lifecycle.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ function returns the value for a specific key in a map, optionally with a fallback default if the key is missing.",
        "options": None,
        "correct_answer": "lookup",
        "explanation_correct": "`lookup(map, key, default)` retrieves a map value by key, returning the optional default if the key isn't present.",
        "explanation_incorrect": "The blank should be filled with the function used for safe map key lookups: lookup.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "To reference an output value from another Terraform configuration's state, use the ____ data source.",
        "options": None,
        "correct_answer": "terraform_remote_state",
        "explanation_correct": "The `terraform_remote_state` data source reads outputs from another configuration's state file, commonly used to share data between separate Terraform configurations.",
        "explanation_incorrect": "The blank should be filled with the data source used to read another configuration's state: terraform_remote_state.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The `terraform state ____` subcommand moves a resource's tracked state to a new address without destroying and recreating the underlying infrastructure.",
        "options": None,
        "correct_answer": "mv",
        "explanation_correct": "`terraform state mv` updates a resource's address in the state file, commonly used after renaming a resource in configuration.",
        "explanation_incorrect": "The blank should be filled with the state subcommand used to move a resource's state address: mv.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "A ____ block, nested inside a resource, generates repeated inner blocks (like multiple ingress rules) from a list or map, instead of writing each one out by hand.",
        "options": None,
        "correct_answer": "dynamic",
        "explanation_correct": "A `dynamic` block programmatically generates nested configuration blocks by iterating over a collection.",
        "explanation_incorrect": "The blank should be filled with the block type used for generating repeated nested blocks: dynamic.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ function combines two or more maps into a single map, with keys from later arguments taking precedence over earlier ones on conflicts.",
        "options": None,
        "correct_answer": "merge",
        "explanation_correct": "`merge()` combines multiple maps, resolving key conflicts in favor of later arguments.",
        "explanation_incorrect": "The blank should be filled with the function used to combine maps: merge.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Terraform's ____ block (available since Terraform 1.5) lets you declaratively import existing infrastructure into state as part of a normal plan/apply, instead of running a separate CLI command.",
        "options": None,
        "correct_answer": "import",
        "explanation_correct": "The declarative `import` block specifies a resource address and an id, and Terraform generates the import as part of the plan.",
        "explanation_incorrect": "The blank should be filled with the block type used for declarative imports: import.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "The ____ meta-argument explicitly declares a dependency between resources that Terraform can't automatically infer from attribute references.",
        "options": None,
        "correct_answer": "depends_on",
        "explanation_correct": "depends_on tells Terraform about an ordering requirement that isn't visible through normal expression references.",
        "explanation_incorrect": "The blank should be filled with the meta-argument used for explicit dependencies: depends_on.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "fill-in-blank",
        "prompt": "Setting the ____ argument inside a lifecycle block to a list of attribute names tells Terraform to disregard changes to those specific attributes on future applies.",
        "options": None,
        "correct_answer": "ignore_changes",
        "explanation_correct": "ignore_changes prevents Terraform from proposing updates to the listed attributes, useful when something else manages those values outside Terraform.",
        "explanation_incorrect": "The blank should be filled with the lifecycle argument used to disregard specific attribute changes: ignore_changes.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested dynamic block for generating multiple ingress rules inside a security group resource.",
        "options": ["resource \"aws_security_group\" \"web\" {", "  dynamic \"ingress\" {\n    for_each = var.ingress_ports\n    content {\n      from_port = ingress.value\n      to_port   = ingress.value\n      protocol  = \"tcp\"\n    }\n  }", "}"],
        "correct_answer": '["resource \\"aws_security_group\\" \\"web\\" {", "  dynamic \\"ingress\\" {\\n    for_each = var.ingress_ports\\n    content {\\n      from_port = ingress.value\\n      to_port   = ingress.value\\n      protocol  = \\"tcp\\"\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block must be opened before the nested dynamic block appears, and closed only after the dynamic block's content is fully defined.",
        "explanation_incorrect": "The outer resource block must be opened before the dynamic block can be nested inside it, and closed only after.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured variable declaration with a complex object list type.",
        "options": ["variable \"services\" {", "  type = list(object({\n    name = string\n    port = number\n  }))", "}"],
        "correct_answer": '["variable \\"services\\" {", "  type = list(object({\\n    name = string\\n    port = number\\n  }))", "}"]',
        "explanation_correct": "Correct — the variable block must be opened before the type expression is declared, and closed only after.",
        "explanation_incorrect": "The variable block must be opened before its type argument can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested resource block that includes a lifecycle block with create_before_destroy.",
        "options": ["  lifecycle {\n    create_before_destroy = true\n  }", "resource \"aws_instance\" \"web\" {\n  ami = \"ami-12345\"", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {\\n  ami = \\"ami-12345\\"", "  lifecycle {\\n    create_before_destroy = true\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block and its basic arguments come first, the nested lifecycle block follows, and the outer closing brace comes last.",
        "explanation_incorrect": "The resource block must be opened (with its arguments) before the nested lifecycle block appears, and the final closing brace must come after everything inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested output block that marks its value as sensitive.",
        "options": ["}", "output \"db_password\" {", "  value     = aws_db_instance.main.password\n  sensitive = true"],
        "correct_answer": '["output \\"db_password\\" {", "  value     = aws_db_instance.main.password\\n  sensitive = true", "}"]',
        "explanation_correct": "Correct — the output block must be opened before its value and sensitive arguments are declared, and closed only after.",
        "explanation_incorrect": "The output block must be opened before its arguments can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested terraform_remote_state data source reading from an S3 backend.",
        "options": ["data \"terraform_remote_state\" \"network\" {", "  backend = \"s3\"\n  config = {\n    bucket = \"my-tf-state\"\n    key    = \"network/terraform.tfstate\"\n    region = \"us-east-1\"\n  }", "}"],
        "correct_answer": '["data \\"terraform_remote_state\\" \\"network\\" {", "  backend = \\"s3\\"\\n  config = {\\n    bucket = \\"my-tf-state\\"\\n    key    = \\"network/terraform.tfstate\\"\\n    region = \\"us-east-1\\"\\n  }", "}"]',
        "explanation_correct": "Correct — the data block must be opened before its backend and config arguments are declared, and closed only after.",
        "explanation_incorrect": "The data source block must be opened before its backend/config contents can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for bringing an existing, unmanaged AWS resource under Terraform management using the classic import workflow.",
        "options": ["Run `terraform plan` to confirm the configuration matches the imported resource with no diff", "Write a resource block in your .tf file matching the existing resource", "Run `terraform import aws_instance.web i-1234567890`"],
        "correct_answer": '["Write a resource block in your .tf file matching the existing resource", "Run `terraform import aws_instance.web i-1234567890`", "Run `terraform plan` to confirm the configuration matches the imported resource with no diff"]',
        "explanation_correct": "Correct — a matching resource block must exist before import (or Terraform has nothing to associate the imported state with), and a plan afterward confirms the configuration accurately describes the real resource.",
        "explanation_incorrect": "The resource block should exist before running import so Terraform knows what configuration the imported state belongs to, and checking with plan afterward confirms there's no unexpected drift.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested resource block using for_each over a map variable.",
        "options": ["resource \"aws_instance\" \"this\" {", "  for_each = var.instances\n  ami      = each.value.ami", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"this\\" {", "  for_each = var.instances\\n  ami      = each.value.ami", "}"]',
        "explanation_correct": "Correct — the resource block must be opened before for_each and other arguments are declared, and closed only after.",
        "explanation_incorrect": "The resource block must be opened before for_each can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested module block using for_each over a set of environment names.",
        "options": ["  source   = \"./modules/app\"\n  for_each = toset([\"dev\", \"staging\", \"prod\"])", "}", "module \"app\" {"],
        "correct_answer": '["module \\"app\\" {", "  source   = \\"./modules/app\\"\\n  for_each = toset([\\"dev\\", \\"staging\\", \\"prod\\"])", "}"]',
        "explanation_correct": "Correct — the module block must be opened before its source and for_each arguments are declared, and closed only after.",
        "explanation_incorrect": "The module block must be opened before its arguments (including for_each) can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested resource block that depends_on two other resources.",
        "options": ["}", "resource \"aws_instance\" \"web\" {\n  ami = \"ami-12345\"", "  depends_on = [aws_s3_bucket.example, aws_iam_role.example]"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {\\n  ami = \\"ami-12345\\"", "  depends_on = [aws_s3_bucket.example, aws_iam_role.example]", "}"]',
        "explanation_correct": "Correct — the resource block and its basic arguments come first, followed by the depends_on argument, and the closing brace comes last.",
        "explanation_incorrect": "The resource block must be opened before depends_on can be declared inside it, and closed only after.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for renaming a resource in configuration without Terraform destroying and recreating it.",
        "options": ["Run `terraform plan` to confirm no destroy/create is proposed, only the rename", "Rename the resource in your .tf configuration file", "Run `terraform state mv aws_instance.old_name aws_instance.new_name`"],
        "correct_answer": '["Rename the resource in your .tf configuration file", "Run `terraform state mv aws_instance.old_name aws_instance.new_name`", "Run `terraform plan` to confirm no destroy/create is proposed, only the rename"]',
        "explanation_correct": "Correct — the configuration must be renamed first, then the state address updated to match via `state mv`, and finally a plan confirms Terraform now sees no destructive change.",
        "explanation_incorrect": "Without renaming the config first there'd be nothing to align the state address to, and checking with plan should come last to confirm the rename didn't trigger an unwanted replacement.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested lifecycle block combining multiple lifecycle arguments.",
        "options": ["resource \"aws_instance\" \"web\" {\n  ami = \"ami-12345\"", "  lifecycle {\n    create_before_destroy = true\n    ignore_changes        = [tags]\n  }", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {\\n  ami = \\"ami-12345\\"", "  lifecycle {\\n    create_before_destroy = true\\n    ignore_changes        = [tags]\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block opens first, the nested lifecycle block with both arguments follows, and the outer closing brace comes last.",
        "explanation_incorrect": "The resource block must be opened before the lifecycle block is nested inside it, and closed only after.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a for expression that builds a map from a list, assigned to a local value.",
        "options": ["locals {", "  uppercase_names = { for name in var.instance_names : name => upper(name) }", "}"],
        "correct_answer": '["locals {", "  uppercase_names = { for name in var.instance_names : name => upper(name) }", "}"]',
        "explanation_correct": "Correct — the locals block must be opened before the for expression assignment appears, and closed only after.",
        "explanation_incorrect": "The locals block must be opened before a local value expression can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested Terraform Cloud remote backend configuration.",
        "options": ["terraform {", "  cloud {\n    organization = \"my-org\"\n    workspaces {\n      name = \"my-workspace\"\n    }\n  }", "}"],
        "correct_answer": '["terraform {", "  cloud {\\n    organization = \\"my-org\\"\\n    workspaces {\\n      name = \\"my-workspace\\"\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the outer terraform block must open before the nested cloud block, and the final closing brace closes the outer block after that nested content.",
        "explanation_incorrect": "The outer block must be opened before the nested cloud configuration can appear, and the closing brace must come after that nested content.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for inspecting and reviewing a specific resource's current state.",
        "options": ["terraform state show aws_instance.web", "terraform state list", "review the detailed attributes shown for that resource"],
        "correct_answer": '["terraform state list", "terraform state show aws_instance.web", "review the detailed attributes shown for that resource"]',
        "explanation_correct": "Correct — listing state first helps confirm the exact resource address to inspect, then `state show` displays its details, which can then be reviewed.",
        "explanation_incorrect": "Listing resource addresses is a natural first step to identify what to inspect further, and reviewing the output logically follows after `state show` has produced it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for making a targeted change to a single resource.",
        "options": ["terraform apply -target=aws_instance.web", "review the scoped plan output", "terraform plan -target=aws_instance.web"],
        "correct_answer": '["terraform plan -target=aws_instance.web", "review the scoped plan output", "terraform apply -target=aws_instance.web"]',
        "explanation_correct": "Correct — the scoped plan must be generated before it can be reviewed, and review naturally precedes the scoped apply that would enact those changes.",
        "explanation_incorrect": "A targeted plan should be generated and reviewed before running the corresponding targeted apply, the same as with an untargeted workflow.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested variable block with a complex object type and a description.",
        "options": ["variable \"services\" {", "  description = \"List of services to deploy\"\n  type        = list(object({\n    name = string\n    port = number\n  }))", "}"],
        "correct_answer": '["variable \\"services\\" {", "  description = \\"List of services to deploy\\"\\n  type        = list(object({\\n    name = string\\n    port = number\\n  }))", "}"]',
        "explanation_correct": "Correct — the variable block must be opened before its description and type arguments are declared, and closed only after.",
        "explanation_incorrect": "The variable block must be opened before its arguments can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested resource block containing a local-exec provisioner.",
        "options": ["resource \"aws_instance\" \"web\" {\n  ami = \"ami-12345\"", "  provisioner \"local-exec\" {\n    command = \"echo Instance created\"\n  }", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {\\n  ami = \\"ami-12345\\"", "  provisioner \\"local-exec\\" {\\n    command = \\"echo Instance created\\"\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block and its basic arguments come first, the nested provisioner block follows, and the outer closing brace comes last.",
        "explanation_incorrect": "The resource block must be opened before a provisioner block can be nested inside it, and closed only after.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly structured moved block used to rename a resource without destroying it.",
        "options": ["moved {", "  from = aws_instance.old_name\n  to   = aws_instance.new_name", "}"],
        "correct_answer": '["moved {", "  from = aws_instance.old_name\\n  to   = aws_instance.new_name", "}"]',
        "explanation_correct": "Correct — the moved block must be opened before its from/to arguments are declared, and closed only after.",
        "explanation_incorrect": "The moved block must be opened before its from and to arguments can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for safely replacing a single resource without a full apply.",
        "options": ["review the plan to confirm only the targeted resource is replaced", "terraform apply -replace=aws_instance.web", "terraform plan -replace=aws_instance.web"],
        "correct_answer": '["terraform plan -replace=aws_instance.web", "review the plan to confirm only the targeted resource is replaced", "terraform apply -replace=aws_instance.web"]',
        "explanation_correct": "Correct — generating the replace-scoped plan comes first, reviewing it naturally follows, and applying the confirmed change comes last.",
        "explanation_incorrect": "A plan should be generated and reviewed before the corresponding apply is run, the same principle as any other targeted or full apply.",
    },
    {
        "topic": "Terraform", "difficulty": "medium", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for switching between environments using workspaces and applying a change.",
        "options": ["terraform workspace select prod", "terraform apply", "terraform workspace list"],
        "correct_answer": '["terraform workspace list", "terraform workspace select prod", "terraform apply"]',
        "explanation_correct": "Correct — listing workspaces first confirms the target exists, selecting it makes it active, and only then does apply operate against that workspace's state.",
        "explanation_incorrect": "Confirming available workspaces before selecting one avoids selecting a workspace that doesn't exist, and the workspace must be selected as active before apply runs against it.",
    },
]
