"""
Terraform - Easy batch, 50 questions total.
Distribution: even split — 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.
(Less coding-heavy than the Python batches, per request — Terraform is more about
config structure/concepts than algorithmic problem-solving.)

Schema matches python_easy_questions.py — see that file's header for full field notes.
For "coding" questions here, correct_answer is a reference HCL snippet or CLI command,
graded leniently by LLM against the prompt (minor formatting/syntax variance is fine).
"""

TERRAFORM_EASY_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write a Terraform resource block that creates an AWS S3 bucket named 'example' (local name) with the bucket name 'my-terraform-bucket'.",
        "correct_answer": "resource \"aws_s3_bucket\" \"example\" {\n  bucket = \"my-terraform-bucket\"\n}",
        "explanation_correct": "Correct — this declares an aws_s3_bucket resource with the local name 'example' and sets the actual bucket name via the bucket argument.",
        "explanation_incorrect": "A correct solution must use the `resource \"aws_s3_bucket\" \"example\"` block syntax with a `bucket` argument set to the desired bucket name.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write a variable block named 'instance_type' of type string with a default value of 't2.micro'.",
        "correct_answer": "variable \"instance_type\" {\n  type    = string\n  default = \"t2.micro\"\n}",
        "explanation_correct": "Correct — this declares a string-typed input variable named instance_type with a sensible default.",
        "explanation_incorrect": "A correct solution must use the `variable \"instance_type\"` block, and should include type = string and default = \"t2.micro\".",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write an output block named 'bucket_arn' that outputs the value of aws_s3_bucket.example.arn.",
        "correct_answer": "output \"bucket_arn\" {\n  value = aws_s3_bucket.example.arn\n}",
        "explanation_correct": "Correct — this declares an output named bucket_arn that exposes the ARN attribute of the aws_s3_bucket.example resource.",
        "explanation_incorrect": "A correct solution must use the `output \"bucket_arn\"` block with a value argument referencing aws_s3_bucket.example.arn.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write a provider block configuring the AWS provider to use the 'us-east-1' region.",
        "correct_answer": "provider \"aws\" {\n  region = \"us-east-1\"\n}",
        "explanation_correct": "Correct — this configures the AWS provider with the region set to us-east-1.",
        "explanation_incorrect": "A correct solution must use the `provider \"aws\"` block with a region argument set to \"us-east-1\".",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write a terraform block that declares a required provider for AWS (source hashicorp/aws) with version constraint '~> 5.0'.",
        "correct_answer": "terraform {\n  required_providers {\n    aws = {\n      source  = \"hashicorp/aws\"\n      version = \"~> 5.0\"\n    }\n  }\n}",
        "explanation_correct": "Correct — this pins the AWS provider to the hashicorp/aws source with a version constraint allowing any 5.x release.",
        "explanation_incorrect": "A correct solution must use the terraform block with a nested required_providers block declaring the aws provider's source and version constraint.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write a resource block for an aws_instance named 'web' using ami 'ami-12345' and instance_type referencing var.instance_type.",
        "correct_answer": "resource \"aws_instance\" \"web\" {\n  ami           = \"ami-12345\"\n  instance_type = var.instance_type\n}",
        "explanation_correct": "Correct — this declares an aws_instance resource with a hardcoded ami and an instance_type pulled from the instance_type input variable.",
        "explanation_incorrect": "A correct solution must use the `resource \"aws_instance\" \"web\"` block with ami and instance_type arguments, referencing the variable as var.instance_type.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write a locals block that defines a local value named 'environment' set to 'production'.",
        "correct_answer": "locals {\n  environment = \"production\"\n}",
        "explanation_correct": "Correct — this defines a local value named environment that can be referenced elsewhere as local.environment.",
        "explanation_incorrect": "A correct solution must use the `locals` block with an environment key set to \"production\".",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write a data source block named 'example' that looks up the most recent Amazon-owned AMI using the aws_ami data source.",
        "correct_answer": "data \"aws_ami\" \"example\" {\n  most_recent = true\n  owners      = [\"amazon\"]\n}",
        "explanation_correct": "Correct — this declares a data source that queries for the most recent AMI owned by Amazon.",
        "explanation_incorrect": "A correct solution must use the `data \"aws_ami\" \"example\"` block with most_recent = true and an owners list including \"amazon\".",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write the terraform command used to initialize a working directory containing Terraform configuration files (downloading providers and setting up the backend).",
        "correct_answer": "terraform init",
        "explanation_correct": "Correct — `terraform init` prepares a working directory for use, downloading required providers and initializing the backend.",
        "explanation_incorrect": "A correct solution must be the `terraform init` command specifically — other commands like plan or apply assume initialization has already happened.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "coding",
        "prompt": "Write the terraform command used to preview the changes Terraform would make, without actually applying them.",
        "correct_answer": "terraform plan",
        "explanation_correct": "Correct — `terraform plan` shows an execution plan of proposed changes without modifying any real infrastructure.",
        "explanation_incorrect": "A correct solution must be the `terraform plan` command — `terraform apply` would actually make the changes rather than just previewing them.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "Which command initializes a Terraform working directory, downloading required providers and modules?",
        "options": ["terraform init", "terraform apply", "terraform plan", "terraform validate"],
        "correct_answer": "terraform init",
        "explanation_correct": "`terraform init` prepares a directory for use by downloading providers/modules and setting up the backend.",
        "explanation_incorrect": {
            "terraform apply": "Wrong — apply creates or updates real infrastructure; it doesn't handle initial provider/module setup.",
            "terraform plan": "Wrong — plan previews changes, but a directory typically needs to be initialized with `init` first.",
            "terraform validate": "Wrong — validate checks configuration syntax, but doesn't download providers or modules.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "What file extension do Terraform configuration files typically use?",
        "options": [".tf", ".tfvars", ".hcl", ".config"],
        "correct_answer": ".tf",
        "explanation_correct": "Terraform configuration files conventionally use the .tf extension (written in HCL syntax).",
        "explanation_incorrect": {
            ".tfvars": "Wrong — .tfvars files hold variable values, not the main resource/provider configuration.",
            ".hcl": "Wrong — while Terraform's language is called HCL, the file extension used is .tf, not .hcl.",
            ".config": "Wrong — .config is not a Terraform file extension.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the primary purpose of the `terraform plan` command?",
        "options": [
            "To show an execution plan of proposed changes without applying them",
            "To apply changes to infrastructure immediately",
            "To permanently destroy all managed infrastructure",
            "To download and install providers",
        ],
        "correct_answer": "To show an execution plan of proposed changes without applying them",
        "explanation_correct": "`terraform plan` compares the current state to the desired configuration and shows what changes would be made, without making them.",
        "explanation_incorrect": {
            "To apply changes to infrastructure immediately": "Wrong — that's the role of `terraform apply`, not `plan`.",
            "To permanently destroy all managed infrastructure": "Wrong — that's the role of `terraform destroy`, not `plan`.",
            "To download and install providers": "Wrong — that's handled by `terraform init`, not `plan`.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "Which block type is used to declare an input variable in Terraform?",
        "options": ["variable", "input", "param", "var"],
        "correct_answer": "variable",
        "explanation_correct": "The `variable` block declares an input variable that can be set via defaults, .tfvars files, CLI flags, or environment variables.",
        "explanation_incorrect": {
            "input": "Wrong — `input` is not a valid Terraform block type.",
            "param": "Wrong — `param` is not a valid Terraform block type.",
            "var": "Wrong — `var.` is the syntax used to reference a variable's value, but the block used to declare it is `variable`, not `var`.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "By default, what file does Terraform use to store the current state of your managed infrastructure?",
        "options": ["terraform.tfstate", "state.tf", "terraform.lock.hcl", "main.tf"],
        "correct_answer": "terraform.tfstate",
        "explanation_correct": "Terraform tracks the state of managed resources in a JSON file named terraform.tfstate by default (local backend).",
        "explanation_incorrect": {
            "state.tf": "Wrong — this isn't a real Terraform file; state files use the .tfstate extension, not .tf.",
            "terraform.lock.hcl": "Wrong — this file locks provider versions, it doesn't store resource state.",
            "main.tf": "Wrong — main.tf is a conventional name for a configuration file, not the state file.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "Which command permanently removes all resources managed by a Terraform configuration?",
        "options": ["terraform destroy", "terraform plan -destroy", "terraform remove", "terraform delete"],
        "correct_answer": "terraform destroy",
        "explanation_correct": "`terraform destroy` tears down all resources tracked in the current state.",
        "explanation_incorrect": {
            "terraform plan -destroy": "Wrong — this only previews what a destroy would do, it doesn't actually remove anything.",
            "terraform remove": "Wrong — this is not a real Terraform command.",
            "terraform delete": "Wrong — this is not a real Terraform command.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "What is the purpose of an `output` block in Terraform?",
        "options": [
            "It exposes values from your configuration for use elsewhere or display after apply",
            "It defines an input variable for the configuration",
            "It declares a provider plugin",
            "It imports an existing resource into state",
        ],
        "correct_answer": "It exposes values from your configuration for use elsewhere or display after apply",
        "explanation_correct": "Output blocks surface useful values (like resource IDs or ARNs) after apply, and can be consumed by other configurations (e.g. via remote state).",
        "explanation_incorrect": {
            "It defines an input variable for the configuration": "Wrong — that's the role of a `variable` block, not `output`.",
            "It declares a provider plugin": "Wrong — that's the role of a `provider` block, not `output`.",
            "It imports an existing resource into state": "Wrong — that's done via the `terraform import` command, unrelated to output blocks.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "Which command reformats Terraform configuration files into a canonical style?",
        "options": ["terraform fmt", "terraform format", "terraform style", "terraform lint"],
        "correct_answer": "terraform fmt",
        "explanation_correct": "`terraform fmt` automatically rewrites configuration files to follow Terraform's standard formatting conventions.",
        "explanation_incorrect": {
            "terraform format": "Wrong — the actual command name is the shortened `fmt`, not `format`.",
            "terraform style": "Wrong — this is not a real Terraform command.",
            "terraform lint": "Wrong — this is not a real Terraform command (fmt handles formatting; validate handles correctness).",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "What is a 'provider' in Terraform?",
        "options": [
            "A plugin that allows Terraform to interact with an API, such as AWS or Azure",
            "A special type of input variable",
            "A remote backend for storing state",
            "A registry for sharing modules",
        ],
        "correct_answer": "A plugin that allows Terraform to interact with an API, such as AWS or Azure",
        "explanation_correct": "Providers are plugins that translate Terraform configuration into API calls against a specific platform (AWS, Azure, GCP, etc.).",
        "explanation_incorrect": {
            "A special type of input variable": "Wrong — providers configure how Terraform talks to a platform; they aren't a variable type.",
            "A remote backend for storing state": "Wrong — that describes a `backend` configuration, a separate concept from providers.",
            "A registry for sharing modules": "Wrong — that describes the Terraform Registry, not a provider itself.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "mcq",
        "prompt": "Which command checks whether a configuration is syntactically valid, without contacting any remote services?",
        "options": ["terraform validate", "terraform plan", "terraform init", "terraform check"],
        "correct_answer": "terraform validate",
        "explanation_correct": "`terraform validate` checks the configuration's internal consistency and syntax without accessing remote APIs or state.",
        "explanation_incorrect": {
            "terraform plan": "Wrong — plan typically contacts providers/remote state to compute an execution plan, unlike validate.",
            "terraform init": "Wrong — init sets up providers and backend, it doesn't perform syntax validation.",
            "terraform check": "Wrong — this is not a real Terraform command.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "To declare something Terraform should create and manage (like an S3 bucket or EC2 instance), use the ____ block.",
        "options": None,
        "correct_answer": "resource",
        "explanation_correct": "The `resource` block is the fundamental building block for declaring managed infrastructure objects.",
        "explanation_incorrect": "The blank should be filled with the block type used to declare managed infrastructure: resource.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ command applies the changes required to reach the desired state described in your configuration.",
        "options": None,
        "correct_answer": "apply",
        "explanation_correct": "`terraform apply` executes the actions proposed in a plan to reach the desired infrastructure state.",
        "explanation_incorrect": "The blank should be filled with the command that actually makes the proposed changes: apply.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "A Terraform ____ is a reusable, self-contained package of configuration that can be called from other configurations.",
        "options": None,
        "correct_answer": "module",
        "explanation_correct": "Modules let you package and reuse Terraform configuration across multiple projects or environments.",
        "explanation_incorrect": "The blank should be filled with the term for a reusable package of Terraform configuration: module.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Variable values can be supplied from a file with the extension .____.",
        "options": None,
        "correct_answer": "tfvars",
        "explanation_correct": ".tfvars files (like terraform.tfvars) let you assign values to declared variables without hardcoding them in the main configuration.",
        "explanation_incorrect": "The blank should be filled with the extension used for variable definition files: tfvars.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ block lets you define a named value that can be reused throughout a configuration, without exposing it as an input variable.",
        "options": None,
        "correct_answer": "locals",
        "explanation_correct": "The `locals` block defines local values, referenced elsewhere as local.<name>, useful for avoiding repeated expressions.",
        "explanation_incorrect": "The blank should be filled with the block type used for internal reusable values: locals.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "To reference the value of a declared variable named 'region' elsewhere in your configuration, you write var.____.",
        "options": None,
        "correct_answer": "region",
        "explanation_correct": "Variable references use the syntax var.<variable_name>, so a variable named 'region' is referenced as var.region.",
        "explanation_incorrect": "The blank should be filled with the variable's name as declared: region.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "Terraform's ____ file (terraform.lock.hcl) records the exact provider versions used, ensuring consistent installs across environments.",
        "options": None,
        "correct_answer": "lock",
        "explanation_correct": "The dependency lock file (terraform.lock.hcl) pins provider versions so everyone working on the configuration gets the same versions.",
        "explanation_incorrect": "The blank should describe the type of file that pins provider versions: lock.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The ____ argument inside a resource block can be used to create multiple similar resources from a single block, based on a number.",
        "options": None,
        "correct_answer": "count",
        "explanation_correct": "Setting `count = N` on a resource creates N instances of that resource, indexed via count.index.",
        "explanation_incorrect": "The blank should be filled with the numeric-based repetition argument: count.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "To hide a variable's value from CLI output (e.g. in plan/apply logs), set the ____ argument to true inside its variable block.",
        "options": None,
        "correct_answer": "sensitive",
        "explanation_correct": "Setting `sensitive = true` on a variable prevents Terraform from displaying its value in CLI output.",
        "explanation_incorrect": "The blank should be filled with the argument used to mark a variable as sensitive: sensitive.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "fill-in-blank",
        "prompt": "The terraform ____ command displays the current state of your managed infrastructure in a human-readable format.",
        "options": None,
        "correct_answer": "show",
        "explanation_correct": "`terraform show` prints a human-readable summary of the current state or a saved plan file.",
        "explanation_incorrect": "The blank should be filled with the command used to display current state: show.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these commands into the standard Terraform workflow order for creating infrastructure.",
        "options": ["terraform apply", "terraform init", "terraform plan"],
        "correct_answer": '["terraform init", "terraform plan", "terraform apply"]',
        "explanation_correct": "Correct — init sets up the working directory, plan previews the changes, and apply makes them — in that order.",
        "explanation_incorrect": "A directory must be initialized before Terraform can plan, and changes must be previewed with plan before you'd typically apply them.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a complete, correctly nested resource block for an EC2 instance.",
        "options": ["  ami = \"ami-12345\"", "resource \"aws_instance\" \"web\" {", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {", "  ami = \\"ami-12345\\"", "}"]',
        "explanation_correct": "Correct — the resource declaration opens the block, the argument sits inside it, and the closing brace ends the block.",
        "explanation_incorrect": "The opening brace must come first to start the block, and the closing brace must come last — an argument line can't appear before the block it belongs to is opened.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a complete, correctly nested variable block.",
        "options": ["}", "variable \"instance_type\" {", "  type = string"],
        "correct_answer": '["variable \\"instance_type\\" {", "  type = string", "}"]',
        "explanation_correct": "Correct — the variable declaration opens the block, the type argument sits inside it, and the closing brace ends the block.",
        "explanation_incorrect": "The block must be opened before its arguments appear, and the closing brace must come after them, not before.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a complete, correctly nested output block.",
        "options": ["  value = aws_s3_bucket.example.arn", "}", "output \"bucket_arn\" {"],
        "correct_answer": '["output \\"bucket_arn\\" {", "  value = aws_s3_bucket.example.arn", "}"]',
        "explanation_correct": "Correct — the output declaration opens the block, the value argument sits inside it, and the closing brace ends the block.",
        "explanation_incorrect": "The output block must be opened before its value argument, and closed only after that argument is defined.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a complete, correctly nested provider block.",
        "options": ["  region = \"us-east-1\"", "}", "provider \"aws\" {"],
        "correct_answer": '["provider \\"aws\\" {", "  region = \\"us-east-1\\"", "}"]',
        "explanation_correct": "Correct — the provider declaration opens the block, the region argument sits inside it, and the closing brace ends the block.",
        "explanation_incorrect": "The provider block must be opened before its arguments, and the closing brace must be the last line.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested required_providers block inside a terraform block (each item may span multiple lines).",
        "options": ["}", "terraform {", "  required_providers {\n    aws = {\n      source  = \"hashicorp/aws\"\n      version = \"~> 5.0\"\n    }\n  }"],
        "correct_answer": '["terraform {", "  required_providers {\\n    aws = {\\n      source  = \\"hashicorp/aws\\"\\n      version = \\"~> 5.0\\"\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the outer terraform block must open first, the nested required_providers content sits inside it, and the final closing brace matches the outer block.",
        "explanation_incorrect": "The outer terraform block must be opened before its nested content can appear, and the final closing brace must come last to properly close the outer block.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a complete, correctly nested data source block for looking up an AMI.",
        "options": ["  most_recent = true\n  owners      = [\"amazon\"]", "}", "data \"aws_ami\" \"example\" {"],
        "correct_answer": '["data \\"aws_ami\\" \\"example\\" {", "  most_recent = true\\n  owners      = [\\"amazon\\"]", "}"]',
        "explanation_correct": "Correct — the data block declaration opens the block, its filter arguments sit inside it, and the closing brace ends the block.",
        "explanation_incorrect": "The data block must be opened before its filter arguments appear, and closed only after they're defined.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a complete, correctly nested locals block.",
        "options": ["locals {", "  environment = \"production\"", "}"],
        "correct_answer": '["locals {", "  environment = \\"production\\"", "}"]',
        "explanation_correct": "Correct — the locals block opens first, the local value is defined inside it, and the closing brace ends the block.",
        "explanation_incorrect": "The locals block must be opened before any local values are defined inside it, and closed only after.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these blocks into the conventional top-to-bottom order they typically appear in a well-organized Terraform configuration file.",
        "options": ["resource \"aws_instance\" \"web\" { ... }", "terraform { required_providers { ... } }", "provider \"aws\" { ... }"],
        "correct_answer": '["terraform { required_providers { ... } }", "provider \\"aws\\" { ... }", "resource \\"aws_instance\\" \\"web\\" { ... }"]',
        "explanation_correct": "Correct — by convention, the terraform block (required providers/version) comes first, followed by provider configuration, followed by the resources that use that provider. Note Terraform itself doesn't require this order — its dependency graph resolves references regardless of file order — but this layout is the widely used convention for readability.",
        "explanation_incorrect": "While Terraform doesn't technically require a specific block order, the conventional and most readable layout declares required providers first, configures the provider next, and defines resources last.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the typical high-level order for standing up new infrastructure with Terraform, starting from nothing.",
        "options": ["Run terraform apply to create the resources", "Write .tf configuration files describing the desired resources", "Run terraform init to set up the working directory"],
        "correct_answer": '["Write .tf configuration files describing the desired resources", "Run terraform init to set up the working directory", "Run terraform apply to create the resources"]',
        "explanation_correct": "Correct — you need configuration written before there's anything to initialize against, the directory must be initialized before planning/applying, and apply is the step that actually creates the resources.",
        "explanation_incorrect": "Configuration files must exist before init has anything meaningful to work with, and the directory must be initialized before apply can run.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these commands into a typical pre-apply check sequence for a fresh Terraform project.",
        "options": ["terraform plan", "terraform init", "terraform validate"],
        "correct_answer": '["terraform init", "terraform validate", "terraform plan"]',
        "explanation_correct": "Correct — init must run first to set up providers, validate checks configuration correctness next, and plan previews the actual changes last.",
        "explanation_incorrect": "The directory must be initialized before validate or plan can run meaningfully, and validating basic syntax before generating a full plan is the more efficient order.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested backend configuration block.",
        "options": ["}", "terraform {", "  backend \"s3\" {\n    bucket = \"my-tf-state\"\n    key    = \"prod/terraform.tfstate\"\n    region = \"us-east-1\"\n  }"],
        "correct_answer": '["terraform {", "  backend \\"s3\\" {\\n    bucket = \\"my-tf-state\\"\\n    key    = \\"prod/terraform.tfstate\\"\\n    region = \\"us-east-1\\"\\n  }", "}"]',
        "explanation_correct": "Correct — the outer terraform block must open before the nested backend block, and the final closing brace closes the outer block after the backend configuration.",
        "explanation_incorrect": "The outer block must be opened before its nested backend configuration can appear, and the closing brace must come after that nested content, not before.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested resource block using count to create multiple instances.",
        "options": ["  ami   = \"ami-12345\"\n  count = 3", "resource \"aws_instance\" \"web\" {", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {", "  ami   = \\"ami-12345\\"\\n  count = 3", "}"]',
        "explanation_correct": "Correct — the resource block must be opened before its arguments (including count) are declared, and closed only after.",
        "explanation_incorrect": "The block must be opened before count or other arguments can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested resource block using for_each over a set of strings.",
        "options": ["resource \"aws_instance\" \"web\" {", "  ami      = \"ami-12345\"\n  for_each = toset([\"a\", \"b\", \"c\"])", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {", "  ami      = \\"ami-12345\\"\\n  for_each = toset([\\"a\\", \\"b\\", \\"c\\"])", "}"]',
        "explanation_correct": "Correct — the resource block must be opened before for_each and other arguments are declared, and closed only after.",
        "explanation_incorrect": "The block must be opened before for_each can be declared inside it, and closed only after all arguments are set.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested variable block that includes a validation rule.",
        "options": ["variable \"instance_count\" {", "  type = number\n  validation {\n    condition     = var.instance_count > 0\n    error_message = \"Must be greater than 0.\"\n  }", "}"],
        "correct_answer": '["variable \\"instance_count\\" {", "  type = number\\n  validation {\\n    condition     = var.instance_count > 0\\n    error_message = \\"Must be greater than 0.\\"\\n  }", "}"]',
        "explanation_correct": "Correct — the variable block must be opened before its type and nested validation block are declared, and closed only after.",
        "explanation_incorrect": "The variable block must be opened before the type and validation contents can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested module block that references a local module source.",
        "options": ["}", "module \"vpc\" {", "  source = \"./modules/vpc\"\n  cidr   = \"10.0.0.0/16\""],
        "correct_answer": '["module \\"vpc\\" {", "  source = \\"./modules/vpc\\"\\n  cidr   = \\"10.0.0.0/16\\"", "}"]',
        "explanation_correct": "Correct — the module block must be opened before its source and other arguments are declared, and closed only after.",
        "explanation_incorrect": "The module block must be opened before its arguments (like source) can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these commands into the correct order to create and switch to a new Terraform workspace, then apply changes in it.",
        "options": ["terraform apply", "terraform workspace select staging", "terraform workspace new staging"],
        "correct_answer": '["terraform workspace new staging", "terraform workspace select staging", "terraform apply"]',
        "explanation_correct": "Correct — the workspace must be created before it can be selected, and it must be selected as the active workspace before applying changes within it.",
        "explanation_incorrect": "A workspace must exist before you can select it, and it must be the active workspace before apply operates within its isolated state.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for using a terraform.tfvars file to supply variable values.",
        "options": ["Run terraform apply, which uses the previewed plan", "Create a terraform.tfvars file with variable values", "Run terraform plan, which automatically loads terraform.tfvars"],
        "correct_answer": '["Create a terraform.tfvars file with variable values", "Run terraform plan, which automatically loads terraform.tfvars", "Run terraform apply, which uses the previewed plan"]',
        "explanation_correct": "Correct — the tfvars file must exist before Terraform can load it during plan, and plan is typically reviewed before apply is run.",
        "explanation_incorrect": "The tfvars file must exist before it can be automatically loaded, and previewing with plan logically comes before applying the changes.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested resource block that uses depends_on to enforce ordering against another resource.",
        "options": ["}", "resource \"aws_instance\" \"web\" {", "  ami        = \"ami-12345\"\n  depends_on = [aws_s3_bucket.example]"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {", "  ami        = \\"ami-12345\\"\\n  depends_on = [aws_s3_bucket.example]", "}"]',
        "explanation_correct": "Correct — the resource block must be opened before its arguments (including depends_on) are declared, and closed only after.",
        "explanation_incorrect": "The block must be opened before depends_on and other arguments can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "easy", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these commands into a typical pre-commit check sequence for Terraform configuration changes.",
        "options": ["terraform plan", "terraform validate", "terraform fmt"],
        "correct_answer": '["terraform fmt", "terraform validate", "terraform plan"]',
        "explanation_correct": "Correct — formatting the files first, then validating their correctness, then previewing the actual plan is a sensible, commonly used check order before committing changes.",
        "explanation_incorrect": "Formatting is typically done first as a cheap cleanup step, validation checks correctness next, and plan (the most expensive check, often requiring provider calls) comes last.",
    },
]
