"""
Terraform - Hard batch, 50 questions total.
Distribution: even split — 10 coding, 10 mcq, 10 fill-in-blank, 10 drag-and-drop, 10 dropdown-order.

Schema matches python_easy_questions.py / terraform_easy_questions.py — see those files'
headers for full field notes. Hard content covers provider aliasing, preconditions/
postconditions, splat expressions, optional object attributes, check blocks, moved-into-
module patterns, explicit provider passing, config generation via import, and terraform test.
"""

TERRAFORM_HARD_QUESTIONS = [

    # ---------------- CODING (10) ----------------

    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a provider block that creates an aliased AWS provider configuration named 'west' pointing at region 'us-west-2', and a resource block for an aws_instance named 'web' that uses that aliased provider.",
        "correct_answer": "provider \"aws\" {\n  alias  = \"west\"\n  region = \"us-west-2\"\n}\n\nresource \"aws_instance\" \"web\" {\n  provider = aws.west\n  ami      = \"ami-12345\"\n}",
        "explanation_correct": "Correct — the alias argument creates a second named AWS provider configuration, and setting provider = aws.west on the resource directs it to use that specific configuration instead of the default.",
        "explanation_incorrect": "A correct solution must include an aliased provider block (alias = \"west\") and a resource that explicitly references it via provider = aws.west.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a resource block for an aws_instance named 'web' that includes a lifecycle block with a precondition ensuring var.instance_count is greater than 0, with an appropriate error_message.",
        "correct_answer": "resource \"aws_instance\" \"web\" {\n  ami           = \"ami-12345\"\n  instance_type = \"t2.micro\"\n\n  lifecycle {\n    precondition {\n      condition     = var.instance_count > 0\n      error_message = \"instance_count must be greater than 0.\"\n    }\n  }\n}",
        "explanation_correct": "Correct — the precondition inside the lifecycle block checks the condition before the resource is created or updated, and fails the apply with the given message if it's false.",
        "explanation_incorrect": "A correct solution must include a `precondition` block nested inside `lifecycle`, with a condition expression and an error_message.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a module block named 'app' (source './modules/app') that explicitly passes an aliased provider using the providers argument, mapping aws.west to the module's expected aws.west configuration alias.",
        "correct_answer": "module \"app\" {\n  source = \"./modules/app\"\n  providers = {\n    aws.west = aws.west\n  }\n}",
        "explanation_correct": "Correct — the providers argument explicitly maps the caller's aws.west provider configuration onto the alias the module expects internally.",
        "explanation_incorrect": "A correct solution must use the `providers` argument inside the module block, mapping a provider configuration (with alias) to the name the module expects.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a local value 'safe_value' that uses try() to safely evaluate var.config.optional_setting, falling back to null if that attribute doesn't exist.",
        "correct_answer": "locals {\n  safe_value = try(var.config.optional_setting, null)\n}",
        "explanation_correct": "Correct — try() attempts to evaluate the first expression and falls back to the next argument (null here) if evaluating it produces an error, such as a missing attribute.",
        "explanation_incorrect": "A correct solution must use the try() function with the potentially-missing expression as the first argument and a fallback value (null is acceptable) as a later argument.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write an output block named 'instance_ids' that uses a splat expression to return the id attribute from every instance created by a for_each-based aws_instance.web resource.",
        "correct_answer": "output \"instance_ids\" {\n  value = [for instance in aws_instance.web : instance.id]\n}",
        "explanation_correct": "Correct — since for_each-created resources are addressed as a map rather than a list, a for expression over aws_instance.web correctly extracts each instance's id into a list (a plain splat like aws_instance.web[*].id only works directly with count-based resources).",
        "explanation_incorrect": "A correct solution must produce a list of id values from every instance created by the resource — for a for_each-based resource, a for expression over the resource is the correct approach.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a moved block indicating that a resource previously at aws_instance.old has moved into a module, now living at module.app.aws_instance.new.",
        "correct_answer": "moved {\n  from = aws_instance.old\n  to   = module.app.aws_instance.new\n}",
        "explanation_correct": "Correct — this moved block tells Terraform to treat the resource at the old top-level address as now living at the new address inside the module, avoiding a destroy/recreate.",
        "explanation_incorrect": "A correct solution must use a `moved` block with `from` set to the original address and `to` set to the new address inside the module.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a variable block named 'settings' with an object type where the attribute 'timeout' is optional and defaults to 30, using the optional() function.",
        "correct_answer": "variable \"settings\" {\n  type = object({\n    timeout = optional(number, 30)\n  })\n}",
        "explanation_correct": "Correct — optional(number, 30) marks the timeout attribute as not required, defaulting to 30 if the caller doesn't provide it.",
        "explanation_incorrect": "A correct solution must use optional() inside the object type definition, with the attribute's type and a default value as arguments.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a check block named 'bucket_not_empty' that asserts output.bucket_name is not an empty string, with an appropriate error_message.",
        "correct_answer": "check \"bucket_not_empty\" {\n  assert {\n    condition     = output.bucket_name != \"\"\n    error_message = \"bucket_name output must not be empty.\"\n  }\n}",
        "explanation_correct": "Correct — the check block's nested assert validates the condition after apply, reporting the given error_message if it fails, without blocking the apply itself.",
        "explanation_incorrect": "A correct solution must use a `check` block with a nested `assert` block containing a condition and an error_message.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write the terraform command used to output a visual representation of the configuration's resource dependency graph.",
        "correct_answer": "terraform graph",
        "explanation_correct": "Correct — `terraform graph` outputs the dependency graph in DOT format, which can be piped into a tool like Graphviz to render it visually.",
        "explanation_incorrect": "A correct solution must be the `terraform graph` command specifically.",
        "options": None,
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "coding",
        "prompt": "Write a resource block for an aws_instance named 'web' that uses both for_each (over var.instances, a map) and, inside it, a dynamic block generating tag entries from each instance's 'extra_tags' attribute.",
        "correct_answer": "resource \"aws_instance\" \"web\" {\n  for_each = var.instances\n  ami      = each.value.ami\n\n  dynamic \"tag\" {\n    for_each = each.value.extra_tags\n    content {\n      key   = tag.key\n      value = tag.value\n    }\n  }\n}",
        "explanation_correct": "Correct — for_each creates one instance per map entry, and the nested dynamic block independently iterates over each instance's own extra_tags to generate its tag entries.",
        "explanation_incorrect": "A correct solution must combine for_each on the resource itself with a nested dynamic block that iterates over a per-instance collection (each.value.extra_tags), not a top-level variable.",
        "options": None,
    },

    # ---------------- MCQ (10) ----------------

    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of provider aliasing (e.g. `provider \"aws\" { alias = \"west\" }`)?",
        "options": [
            "It allows defining multiple distinct configurations of the same provider within one configuration",
            "It allows using entirely different, unrelated providers together",
            "It is required for every provider block regardless of use case",
            "It disables the default provider configuration",
        ],
        "correct_answer": "It allows defining multiple distinct configurations of the same provider within one configuration",
        "explanation_correct": "Aliasing lets you configure the same provider (e.g. aws) multiple times with different settings, such as different regions or accounts, and select which one a resource uses.",
        "explanation_incorrect": {
            "It allows using entirely different, unrelated providers together": "Wrong — using multiple different providers (aws and azurerm, for instance) doesn't require aliasing at all; aliasing is specifically for multiple configurations of the same provider.",
            "It is required for every provider block regardless of use case": "Wrong — aliasing is optional and only needed when you want more than one configuration of the same provider.",
            "It disables the default provider configuration": "Wrong — the default (unaliased) provider configuration remains active alongside any aliased ones.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What does a `precondition` block inside a resource's lifecycle block do?",
        "options": [
            "Validates an assumption before the resource is created or updated, failing the apply if the condition is false",
            "Deletes the resource if a condition becomes true",
            "Sets default values for missing attributes",
            "Silently ignores drift on the resource",
        ],
        "correct_answer": "Validates an assumption before the resource is created or updated, failing the apply if the condition is false",
        "explanation_correct": "Preconditions let you assert something must be true before Terraform proceeds with creating or updating a resource, surfacing a custom error message if it isn't.",
        "explanation_incorrect": {
            "Deletes the resource if a condition becomes true": "Wrong — preconditions block or allow an operation, they don't trigger deletion.",
            "Sets default values for missing attributes": "Wrong — that's unrelated to preconditions; defaults are handled via variable defaults or optional().",
            "Silently ignores drift on the resource": "Wrong — that describes ignore_changes, a different lifecycle argument.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What does the `try()` function do?",
        "options": [
            "Evaluates a sequence of expressions and returns the first one that succeeds without error",
            "Catches and suppresses provider-level API errors during apply",
            "Automatically retries a failed apply operation",
            "Validates a variable's value against a set of rules",
        ],
        "correct_answer": "Evaluates a sequence of expressions and returns the first one that succeeds without error",
        "explanation_correct": "try() attempts each given expression in order and returns the value of the first one that doesn't produce an error, commonly used to handle possibly-missing attributes gracefully.",
        "explanation_incorrect": {
            "Catches and suppresses provider-level API errors during apply": "Wrong — try() operates on expression evaluation within the configuration language, not on provider API failures during apply.",
            "Automatically retries a failed apply operation": "Wrong — retry behavior for applies isn't what try() does; it's a language-level expression fallback function.",
            "Validates a variable's value against a set of rules": "Wrong — that's the role of a variable's `validation` block, not try().",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What does a splat expression like `aws_instance.web[*].id` produce, for a resource created with `count`?",
        "options": [
            "A list of the id attribute from every instance created by that resource",
            "Only the id of the first created instance",
            "A single concatenated string of all ids",
            "An error, since splat expressions require for_each",
        ],
        "correct_answer": "A list of the id attribute from every instance created by that resource",
        "explanation_correct": "The `[*]` splat expression collects the given attribute from every instance of a count-based (or list-like) resource into a list.",
        "explanation_incorrect": {
            "Only the id of the first created instance": "Wrong — that would be `aws_instance.web[0].id`; the splat form collects from all instances, not just the first.",
            "A single concatenated string of all ids": "Wrong — the result is a list of individual id values, not a joined string.",
            "An error, since splat expressions require for_each": "Wrong — splat expressions work with count-based (list-like) resources; for_each-based resources are maps and typically use a for expression instead.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of the `optional()` function when used inside an object type definition for a variable?",
        "options": [
            "It marks a specific object attribute as optional, with an optional default value if omitted",
            "It makes the entire variable optional so the caller can skip it entirely",
            "It disables type checking for that variable",
            "It allows the object to accept any attribute names",
        ],
        "correct_answer": "It marks a specific object attribute as optional, with an optional default value if omitted",
        "explanation_correct": "optional(type, default) is used within an object() type constraint to mark one attribute as not required, optionally supplying a default value used when it's omitted.",
        "explanation_incorrect": {
            "It makes the entire variable optional so the caller can skip it entirely": "Wrong — optional() applies to individual attributes inside an object type, not to the variable as a whole (a variable default handles that case).",
            "It disables type checking for that variable": "Wrong — the attribute still has a declared type; optional() only affects whether it must be supplied.",
            "It allows the object to accept any attribute names": "Wrong — that would require a different type constraint (like `map(any)`); object() still requires a fixed, named attribute set.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What does setting the environment variable `TF_LOG=DEBUG` do when running Terraform commands?",
        "options": [
            "Enables verbose debug-level logging output, useful for troubleshooting",
            "Deletes any resources tagged as debug resources",
            "Disables state locking for the duration of the command",
            "Speeds up apply operations by skipping certain checks",
        ],
        "correct_answer": "Enables verbose debug-level logging output, useful for troubleshooting",
        "explanation_correct": "TF_LOG controls Terraform's internal logging verbosity (TRACE, DEBUG, INFO, WARN, ERROR); setting it to DEBUG surfaces detailed internal output for diagnosing issues.",
        "explanation_incorrect": {
            "Deletes any resources tagged as debug resources": "Wrong — TF_LOG is purely a logging verbosity setting; it has no effect on which resources exist.",
            "Disables state locking for the duration of the command": "Wrong — state locking behavior is unrelated to logging level.",
            "Speeds up apply operations by skipping certain checks": "Wrong — if anything, verbose logging adds overhead; it doesn't skip any validation or checks.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the purpose of a `check` block (introduced in Terraform 1.5)?",
        "options": [
            "Defines assertions that run after apply to validate infrastructure or outputs, without blocking the apply if they fail",
            "Blocks the apply immediately if any resource in the configuration fails",
            "Replaces variable validation blocks entirely",
            "Configures a provider's authentication method",
        ],
        "correct_answer": "Defines assertions that run after apply to validate infrastructure or outputs, without blocking the apply if they fail",
        "explanation_correct": "Check blocks run post-apply assertions and report failures as warnings, useful for ongoing monitoring-style validation without treating a failed check as a fatal apply error.",
        "explanation_incorrect": {
            "Blocks the apply immediately if any resource in the configuration fails": "Wrong — a failed check reports a warning rather than blocking the apply, which is the key distinction from preconditions/postconditions.",
            "Replaces variable validation blocks entirely": "Wrong — variable validation still exists separately and serves a different purpose (validating input before use, not post-apply state).",
            "Configures a provider's authentication method": "Wrong — check blocks are about assertions/validation, unrelated to provider authentication.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What is the primary purpose of files with the `.tftest.hcl` extension?",
        "options": [
            "Defining automated tests for Terraform modules and configurations",
            "Storing the current state of managed infrastructure",
            "Declaring default values for input variables",
            "Configuring the remote backend",
        ],
        "correct_answer": "Defining automated tests for Terraform modules and configurations",
        "explanation_correct": ".tftest.hcl files, used with `terraform test`, define test scenarios (run blocks with assertions) to automatically validate a configuration's behavior.",
        "explanation_incorrect": {
            "Storing the current state of managed infrastructure": "Wrong — that's the role of the state file (.tfstate), not test files.",
            "Declaring default values for input variables": "Wrong — that's the role of .tfvars files or variable defaults, not test files.",
            "Configuring the remote backend": "Wrong — backend configuration lives in a terraform block, unrelated to test files.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "When explicitly passing a provider into a module using the `providers` argument, what must the module itself declare to accept it?",
        "options": [
            "A configuration_aliases entry inside its required_providers block for that aliased provider",
            "Nothing — modules automatically accept any provider passed to them",
            "The module must be the root module of the configuration",
            "Providers cannot be passed into child modules at all",
        ],
        "correct_answer": "A configuration_aliases entry inside its required_providers block for that aliased provider",
        "explanation_correct": "A module must explicitly declare, via configuration_aliases in its required_providers block, which aliased provider configurations it expects the caller to supply.",
        "explanation_incorrect": {
            "Nothing — modules automatically accept any provider passed to them": "Wrong — modules must explicitly opt in to receiving aliased provider configurations via configuration_aliases.",
            "The module must be the root module of the configuration": "Wrong — explicit provider passing is specifically a child-module feature; the root module configures providers directly.",
            "Providers cannot be passed into child modules at all": "Wrong — passing providers explicitly into child modules is exactly what the providers argument and configuration_aliases enable.",
        },
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "mcq",
        "prompt": "What does the `terraform graph` command output?",
        "options": [
            "A representation of the resource dependency graph, typically in DOT format",
            "A list of every past apply operation with timestamps",
            "A cost estimate for the managed infrastructure",
            "A security vulnerability scan report",
        ],
        "correct_answer": "A representation of the resource dependency graph, typically in DOT format",
        "explanation_correct": "`terraform graph` produces a DOT-format description of how resources, modules, and providers depend on each other, which can be rendered visually with tools like Graphviz.",
        "explanation_incorrect": {
            "A list of every past apply operation with timestamps": "Wrong — Terraform doesn't maintain an apply history log accessible via this command; that's not what graph does.",
            "A cost estimate for the managed infrastructure": "Wrong — cost estimation is a separate concern (often handled by third-party or cloud-specific tooling), not something terraform graph provides.",
            "A security vulnerability scan report": "Wrong — security scanning is handled by separate tools (like tfsec or Checkov), not terraform graph.",
        },
    },

    # ---------------- FILL-IN-BLANK (10) ----------------

    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ argument on a provider block lets you define multiple named configurations of the same provider within one configuration.",
        "options": None,
        "correct_answer": "alias",
        "explanation_correct": "Setting `alias = \"name\"` on a provider block creates an additional named configuration, referenced elsewhere as provider.name.",
        "explanation_incorrect": "The blank should be filled with the argument used to name an additional provider configuration: alias.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A ____ block nested inside a resource's lifecycle block validates an assumption before that resource is created or updated, failing the apply if the condition is false.",
        "options": None,
        "correct_answer": "precondition",
        "explanation_correct": "A precondition block checks a condition before the associated resource action proceeds, surfacing a custom error message on failure.",
        "explanation_incorrect": "The blank should be filled with the block type used for pre-action validation: precondition.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____ function attempts to evaluate a sequence of expressions in order, returning the first one that succeeds without an error.",
        "options": None,
        "correct_answer": "try",
        "explanation_correct": "try(expr1, expr2, ...) is commonly used to gracefully handle expressions that might fail, such as accessing an attribute that may not exist.",
        "explanation_incorrect": "The blank should be filled with the function used for graceful expression fallback: try.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "An expression like `aws_instance.web[*].id`, which collects an attribute from every instance of a count-based resource into a list, is called a ____ expression.",
        "options": None,
        "correct_answer": "splat",
        "explanation_correct": "The `[*]` syntax is known as a splat expression, and it extracts a given attribute across all elements of a list-like resource.",
        "explanation_incorrect": "The blank should be filled with the term for this `[*]`-based syntax: splat.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The ____() function, used inside an object type definition, marks a specific attribute as not required and can specify a default value for it.",
        "options": None,
        "correct_answer": "optional",
        "explanation_correct": "optional(type, default) inside an object() constraint marks that attribute as optional for callers, with the given default used when it's omitted.",
        "explanation_incorrect": "The blank should be filled with the function used to mark an object attribute optional: optional.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Setting the environment variable TF_LOG to a level like DEBUG or TRACE enables verbose ____ output, useful for troubleshooting Terraform runs.",
        "options": None,
        "correct_answer": "logging",
        "explanation_correct": "TF_LOG controls the verbosity of Terraform's internal diagnostic logging output.",
        "explanation_incorrect": "The blank should describe what TF_LOG controls the verbosity of: logging.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "A ____ block (Terraform 1.5+) defines assertions that run after apply to validate infrastructure or outputs, reporting a warning rather than blocking the apply on failure.",
        "options": None,
        "correct_answer": "check",
        "explanation_correct": "check blocks provide ongoing, non-blocking validation of infrastructure state or output values after apply.",
        "explanation_incorrect": "The blank should be filled with the block type used for post-apply assertions: check.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "Automated tests for Terraform configurations are written in files ending in .____.hcl.",
        "options": None,
        "correct_answer": "tftest",
        "explanation_correct": "Test files use the .tftest.hcl extension and are run with the `terraform test` command.",
        "explanation_incorrect": "The blank should be filled with the middle portion of the test file extension: tftest.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "For a child module to accept an explicitly passed aliased provider, it must declare a ____ entry inside its required_providers block for that provider.",
        "options": None,
        "correct_answer": "configuration_aliases",
        "explanation_correct": "configuration_aliases lists the aliased provider configurations a module expects its caller to supply via the providers argument.",
        "explanation_incorrect": "The blank should be filled with the required_providers entry used to declare expected aliases: configuration_aliases.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "fill-in-blank",
        "prompt": "The `terraform ____` command outputs a visual representation of the resource dependency graph, typically in DOT format.",
        "options": None,
        "correct_answer": "graph",
        "explanation_correct": "`terraform graph` produces the DOT-format dependency graph of the configuration.",
        "explanation_incorrect": "The blank should be filled with the command that outputs the dependency graph: graph.",
    },

    # ---------------- DRAG-AND-DROP (10) ----------------

    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured aliased provider block followed by a resource that uses it.",
        "options": ["resource \"aws_instance\" \"web\" {\n  provider = aws.west\n  ami      = \"ami-12345\"\n}", "provider \"aws\" {", "  alias  = \"west\"\n  region = \"us-west-2\"\n}"],
        "correct_answer": '["provider \\"aws\\" {", "  alias  = \\"west\\"\\n  region = \\"us-west-2\\"\\n}", "resource \\"aws_instance\\" \\"web\\" {\\n  provider = aws.west\\n  ami      = \\"ami-12345\\"\\n}"]',
        "explanation_correct": "Correct — the aliased provider must be opened and its arguments declared (and the block closed) before a resource can reference it via provider = aws.west.",
        "explanation_incorrect": "The provider block (including its alias) must be fully defined before a resource can reference that alias.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested resource block containing a lifecycle precondition.",
        "options": ["  lifecycle {\n    precondition {\n      condition     = var.instance_count > 0\n      error_message = \"instance_count must be greater than 0.\"\n    }\n  }", "resource \"aws_instance\" \"web\" {\n  ami = \"ami-12345\"", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {\\n  ami = \\"ami-12345\\"", "  lifecycle {\\n    precondition {\\n      condition     = var.instance_count > 0\\n      error_message = \\"instance_count must be greater than 0.\\"\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block and its basic arguments come first, the nested lifecycle/precondition structure follows, and the outer closing brace comes last.",
        "explanation_incorrect": "The resource block must be opened before the lifecycle block can be nested inside it, and closed only after.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested module block that explicitly passes an aliased provider.",
        "options": ["module \"app\" {", "  source = \"./modules/app\"\n  providers = {\n    aws.west = aws.west\n  }", "}"],
        "correct_answer": '["module \\"app\\" {", "  source = \\"./modules/app\\"\\n  providers = {\\n    aws.west = aws.west\\n  }", "}"]',
        "explanation_correct": "Correct — the module block must be opened before its source and providers arguments are declared, and closed only after.",
        "explanation_incorrect": "The module block must be opened before its providers argument can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured moved block for a resource moving into a module.",
        "options": ["moved {", "  from = aws_instance.old\n  to   = module.app.aws_instance.new", "}"],
        "correct_answer": '["moved {", "  from = aws_instance.old\\n  to   = module.app.aws_instance.new", "}"]',
        "explanation_correct": "Correct — the moved block must be opened before its from/to arguments are declared, and closed only after.",
        "explanation_incorrect": "The moved block must be opened before its from and to arguments can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested variable declaration with an optional object attribute.",
        "options": ["}", "variable \"settings\" {", "  type = object({\n    timeout = optional(number, 30)\n  })"],
        "correct_answer": '["variable \\"settings\\" {", "  type = object({\\n    timeout = optional(number, 30)\\n  })", "}"]',
        "explanation_correct": "Correct — the variable block must be opened before its type expression is declared, and closed only after.",
        "explanation_incorrect": "The variable block must be opened before its type argument can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested check block asserting an output is not empty.",
        "options": ["check \"bucket_not_empty\" {", "  assert {\n    condition     = output.bucket_name != \"\"\n    error_message = \"bucket_name output must not be empty.\"\n  }", "}"],
        "correct_answer": '["check \\"bucket_not_empty\\" {", "  assert {\\n    condition     = output.bucket_name != \\"\\"\\n    error_message = \\"bucket_name output must not be empty.\\"\\n  }", "}"]',
        "explanation_correct": "Correct — the check block must be opened before the nested assert block, and closed only after that assert block is fully defined.",
        "explanation_incorrect": "The check block must be opened before the nested assert block can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for safely migrating Terraform state to a new backend.",
        "options": ["Run `terraform init -migrate-state` and confirm the prompt to copy existing state", "Update the backend configuration inside the terraform block", "Verify the migration with `terraform state list`"],
        "correct_answer": '["Update the backend configuration inside the terraform block", "Run `terraform init -migrate-state` and confirm the prompt to copy existing state", "Verify the migration with `terraform state list`"]',
        "explanation_correct": "Correct — the backend config must be changed before init can detect the difference and offer to migrate, and verifying afterward confirms the migration succeeded.",
        "explanation_incorrect": "Terraform only offers to migrate state once it detects a changed backend configuration, so the config change must happen first, and verification logically comes after the migration completes.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly structured pair of provider blocks — a default AWS provider followed by an aliased one — as conventionally ordered.",
        "options": ["provider \"aws\" {\n  region = \"us-east-1\"\n}", "provider \"aws\" {\n  alias  = \"west\"\n  region = \"us-west-2\"\n}"],
        "correct_answer": '["provider \\"aws\\" {\\n  region = \\"us-east-1\\"\\n}", "provider \\"aws\\" {\\n  alias  = \\"west\\"\\n  region = \\"us-west-2\\"\\n}"]',
        "explanation_correct": "Correct — by convention, the default (unaliased) provider configuration is listed first, followed by any aliased configurations, though Terraform itself doesn't require this ordering.",
        "explanation_incorrect": "While Terraform doesn't strictly require this order, the conventional and most readable layout lists the default provider configuration before any aliased ones.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these steps into the correct order for writing and running an automated Terraform test.",
        "options": ["Run `terraform test` from the configuration directory", "Write a .tftest.hcl file with one or more run blocks and assertions", "Review the pass/fail results for each run block"],
        "correct_answer": '["Write a .tftest.hcl file with one or more run blocks and assertions", "Run `terraform test` from the configuration directory", "Review the pass/fail results for each run block"]',
        "explanation_correct": "Correct — the test file must exist before it can be run, and reviewing results naturally happens after the test command finishes.",
        "explanation_incorrect": "A test file must be written before `terraform test` has anything to execute, and results can only be reviewed after the test run completes.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "drag-and-drop",
        "prompt": "Arrange these lines into a correctly nested resource block combining for_each with a nested dynamic block.",
        "options": ["resource \"aws_instance\" \"web\" {", "  for_each = var.instances\n  ami      = each.value.ami\n\n  dynamic \"tag\" {\n    for_each = each.value.extra_tags\n    content {\n      key   = tag.key\n      value = tag.value\n    }\n  }", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {", "  for_each = var.instances\\n  ami      = each.value.ami\\n\\n  dynamic \\"tag\\" {\\n    for_each = each.value.extra_tags\\n    content {\\n      key   = tag.key\\n      value = tag.value\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block must be opened before its for_each and nested dynamic block are declared, and closed only after.",
        "explanation_incorrect": "The resource block must be opened before for_each and the nested dynamic block can appear inside it.",
    },

    # ---------------- DROPDOWN-ORDER (10) ----------------

    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested local value using a nested for expression to build a map of maps.",
        "options": ["locals {", "  grouped = { for env in var.environments : env => { for r in var.regions : r => \"${env}-${r}\" } }", "}"],
        "correct_answer": '["locals {", "  grouped = { for env in var.environments : env => { for r in var.regions : r => \\"${env}-${r}\\" } }", "}"]',
        "explanation_correct": "Correct — the locals block must be opened before the nested for expression assignment appears, and closed only after.",
        "explanation_incorrect": "The locals block must be opened before a local value expression can be declared inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested resource block with two levels of dynamic block nesting.",
        "options": ["resource \"aws_security_group\" \"web\" {", "  dynamic \"ingress\" {\n    for_each = var.rules\n    content {\n      from_port = ingress.value.from\n      dynamic \"cidr_blocks\" {\n        for_each = ingress.value.cidrs\n        content {\n          cidr = cidr_blocks.value\n        }\n      }\n    }\n  }", "}"],
        "correct_answer": '["resource \\"aws_security_group\\" \\"web\\" {", "  dynamic \\"ingress\\" {\\n    for_each = var.rules\\n    content {\\n      from_port = ingress.value.from\\n      dynamic \\"cidr_blocks\\" {\\n        for_each = ingress.value.cidrs\\n        content {\\n          cidr = cidr_blocks.value\\n        }\\n      }\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block must open first, the outer dynamic block (and its nested inner dynamic block) follow, and the outer closing brace comes last.",
        "explanation_incorrect": "The resource block must be opened before the outer dynamic block can be nested inside it, and the inner dynamic block must be fully contained within the outer one.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for a blue-green style zero-downtime resource replacement using create_before_destroy.",
        "options": ["terraform apply to create the new resource alongside the old one", "add create_before_destroy = true to the resource's lifecycle block and change a triggering attribute", "the old resource is automatically destroyed once the new one is confirmed healthy and traffic is shifted"],
        "correct_answer": '["add create_before_destroy = true to the resource\'s lifecycle block and change a triggering attribute", "terraform apply to create the new resource alongside the old one", "the old resource is automatically destroyed once the new one is confirmed healthy and traffic is shifted"]',
        "explanation_correct": "Correct — the lifecycle setting and triggering change must be in place before apply runs, the new resource is created first because of create_before_destroy, and the old one is only removed afterward.",
        "explanation_incorrect": "create_before_destroy must be configured before the triggering apply, and by definition the new resource is created before the old one is torn down, not the other way around.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for safely moving a resource into a module using a moved block.",
        "options": ["run `terraform plan` and confirm it shows a move, not a destroy/create", "add a moved block with from/to addresses reflecting the new module location", "restructure the configuration so the resource is now declared inside the module"],
        "correct_answer": '["restructure the configuration so the resource is now declared inside the module", "add a moved block with from/to addresses reflecting the new module location", "run `terraform plan` and confirm it shows a move, not a destroy/create"]',
        "explanation_correct": "Correct — the resource's new location in configuration must exist before the moved block can reference it, and checking with plan afterward confirms the move was recognized correctly.",
        "explanation_incorrect": "The moved block's `to` address needs a real corresponding resource declaration to point to, and verifying via plan naturally comes last to confirm the intended outcome.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested null_resource with triggers and a local-exec provisioner.",
        "options": ["resource \"null_resource\" \"deploy\" {", "  triggers = {\n    always_run = timestamp()\n  }\n\n  provisioner \"local-exec\" {\n    command = \"echo deployed\"\n  }", "}"],
        "correct_answer": '["resource \\"null_resource\\" \\"deploy\\" {", "  triggers = {\\n    always_run = timestamp()\\n  }\\n\\n  provisioner \\"local-exec\\" {\\n    command = \\"echo deployed\\"\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block must be opened before its triggers map and nested provisioner block are declared, and closed only after.",
        "explanation_incorrect": "The resource block must be opened before triggers and the provisioner block can appear inside it.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for the modern config-generation import workflow (Terraform 1.5+).",
        "options": ["review and clean up the generated resource block, then remove the import block and -generate-config-out flag", "write an import block specifying the resource address and existing resource id", "run `terraform plan -generate-config-out=generated.tf` to produce a matching resource block"],
        "correct_answer": '["write an import block specifying the resource address and existing resource id", "run `terraform plan -generate-config-out=generated.tf` to produce a matching resource block", "review and clean up the generated resource block, then remove the import block and -generate-config-out flag"]',
        "explanation_correct": "Correct — the import block must exist before plan can generate matching configuration for it, and cleanup/adoption as a normal resource happens only after that configuration has been generated and reviewed.",
        "explanation_incorrect": "The import block declares intent and must come first, config generation depends on that import block being present, and cleanup naturally happens last once the generated config is available to review.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested resource block containing a postcondition validating its own result.",
        "options": ["resource \"aws_instance\" \"web\" {\n  ami = \"ami-12345\"", "  lifecycle {\n    postcondition {\n      condition     = self.public_ip != \"\"\n      error_message = \"Instance must have a public IP.\"\n    }\n  }", "}"],
        "correct_answer": '["resource \\"aws_instance\\" \\"web\\" {\\n  ami = \\"ami-12345\\"", "  lifecycle {\\n    postcondition {\\n      condition     = self.public_ip != \\"\\"\\n      error_message = \\"Instance must have a public IP.\\"\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the resource block and its basic arguments come first, the nested lifecycle/postcondition structure follows, and the outer closing brace comes last.",
        "explanation_incorrect": "The resource block must be opened before the lifecycle block (and its nested postcondition) can appear inside it, and closed only after.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested required_providers configuration_aliases declaration for a child module.",
        "options": ["terraform {", "  required_providers {\n    aws = {\n      source                = \"hashicorp/aws\"\n      configuration_aliases = [aws.west]\n    }\n  }", "}"],
        "correct_answer": '["terraform {", "  required_providers {\\n    aws = {\\n      source                = \\"hashicorp/aws\\"\\n      configuration_aliases = [aws.west]\\n    }\\n  }", "}"]',
        "explanation_correct": "Correct — the outer terraform block must open before the nested required_providers/configuration_aliases content, and the final closing brace closes the outer block after that content.",
        "explanation_incorrect": "The outer terraform block must be opened before its nested required_providers content can appear, and the closing brace must come after that content, not before.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these steps into the correct order for diagnosing a failed apply using debug logging.",
        "options": ["set TF_LOG=DEBUG (and optionally TF_LOG_PATH to save to a file)", "re-run the failing terraform command", "review the detailed debug output to identify the underlying error"],
        "correct_answer": '["set TF_LOG=DEBUG (and optionally TF_LOG_PATH to save to a file)", "re-run the failing terraform command", "review the detailed debug output to identify the underlying error"]',
        "explanation_correct": "Correct — the logging level must be set before the command runs in order to capture debug output, and reviewing that output is the final step once it's been produced.",
        "explanation_incorrect": "TF_LOG must be set before the command executes for debug output to be captured at all, and reviewing the output only makes sense after it's been generated.",
    },
    {
        "topic": "Terraform", "difficulty": "hard", "type": "dropdown-order",
        "prompt": "Use the dropdowns to arrange these lines into a correctly nested output using a for expression over a for_each-created resource, filtered to only instances tagged as 'public'.",
        "options": ["output \"public_instance_ids\" {", "  value = [for k, inst in aws_instance.web : inst.id if inst.tags[\"visibility\"] == \"public\"]", "}"],
        "correct_answer": '["output \\"public_instance_ids\\" {", "  value = [for k, inst in aws_instance.web : inst.id if inst.tags[\\"visibility\\"] == \\"public\\"]", "}"]',
        "explanation_correct": "Correct — the output block must be opened before the filtered for expression is declared as its value, and closed only after.",
        "explanation_incorrect": "The output block must be opened before its value expression can be declared inside it.",
    },
]
